UX fixed for date field
saeloun/miru-web pull request #1000
Opened 2023-02-06 12:24 UTC by Shruti-Apte

### **What :**
3rd task from this ticket:
(https://www.notion.so/saeloun/Invoice-page-UX-feedback-c94100068cbf41708986ccccfdb92f08)

- By clicking anywhere  on date field date picker is displayed.  
- By clicking outside, it is closing.

### **Why :**
- UX requirement.
(Earlier only on clicking pencil icon we were able to edit the date.)

### **Preview :**
**Code:**

```
<div
          className="hoverPencil cursor-pointer"
          onClick={() => setShowDueDatePicker(!showDueDatePicker)}
        >
          <p className="mt-4 flex text-xs font-normal text-miru-dark-purple-1000">
            <span>Due Date</span>
            <button className="invisible ml-2">
              <EditIcon color="#1D1A31" size={13} />
            </button>
          </p>
          {showDueDatePicker && (
            <CustomDatePicker
              date={dueDate}
              handleChange={handleDueDatePicker}
              setVisibility={setShowDueDatePicker}
            />
          )}
          <p className="text-base font-normal text-miru-dark-purple-1000">
            {getDueDate}
          </p>
        </div>
```

**Screenshots:**
<img width="155" alt="Screenshot 2023-02-06 at 5 22 15 PM" src="https://user-images.githubusercontent.com/72149587/216964734-3125b00e-548e-450c-b49d-423e758ea4ab.png">

<img width="413" alt="Screenshot 2023-02-06 at 5 22 27 PM" src="https://user-images.githubusercontent.com/72149587/216964702-1700be37-c7e9-4d26-8b09-a72b2473c741.png">

**Video:**

https://www.loom.com/share/9ece6ca38fab487ba3b39d4b0c2e724c

### **Todos** (testing):
- The user should be able to click on the date field itself to edit the date .
- A custom calendar should open and user should be able to select another year from the dropdown , select a date.
- After selecting a date the calendar should close and the date field should not be in edit UI mode.
- If the user opens calendar, it should close as soon as the user click anywhere outside the calendar.

2023-02-06 13:13 UTC, supriya3105 commented
@Shruti-Apte 
1. Whenever the calendar is open, the date field should be visible to the user. 
2 Also the calendar should open exactly below the date field. I think right now its open on the right side.

2023-02-07 05:14 UTC, apoorv1316 commented
@Shruti-Apte Please work on Supriya's comments and I will approve it then.

2023-02-07 07:19 UTC, supriya3105 commented
> @Shruti-Apte
> 
> 1. Whenever the calendar is open, the date field should be visible to the user.
>    2 Also the calendar should open exactly below the date field. I think right now its open on the right side.

For now keeping the calendar alignment to the right i.e. as it is now. The first part needs to be fixed.

2023-02-07 07:25 UTC, prasanthchaduvula requested changes

2023-02-07 07:25 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomDatePicker/index.tsx
> +import { useOutsideClick } from "../../helpers/outsideClick";
Here please change the import to `import { useOutsideClick } from "helpers";`

2023-02-07 08:03 UTC, Shruti-Apte commented
Also worked on 3rd task from the ticket as it was a very small change. 
listing out the changes (discussed with supriya on call): 
1. Order of the fields is changed. (date section is 3rd now ).
2. Added placeholder for invoice number and reference number.
3. Client selection dropdown issue fixed (pointed out by sonam on call).
cc: @supriya3105 @apoorv1316 
Updating the PR description as well.

2023-02-07 08:08 UTC, prasanthchaduvula approved these changes

2023-02-07 10:52 UTC, apoorv1316 requested changes
@Shruti-Apte Feedback for the PR https://www.loom.com/share/ee50d0d98feb40b6820380624701d424.

2023-02-07 13:38 UTC, Shruti-Apte commented
> @Shruti-Apte Feedback for the PR https://www.loom.com/share/ee50d0d98feb40b6820380624701d424.

Connected with akash for review, he is updating the designs. Will work on it.

2023-02-08 09:02 UTC, Shruti-Apte commented
> @Shruti-Apte Feedback for the PR https://www.loom.com/share/ee50d0d98feb40b6820380624701d424.
@apoorv1316 Updated the design and UX according to the discussion with akash and supriya! can you review it!
You can find the design specs here https://www.notion.so/saeloun/Invoice-page-UX-feedback-c94100068cbf41708986ccccfdb92f08

2023-02-08 09:39 UTC, apoorv1316 commented
@Shruti-Apte Please watch this loom video https://www.loom.com/share/75b79d5ce0d94fbb9793ea1ccbb63c2d

2023-02-08 10:07 UTC, apoorv1316 approved these changes

2023-02-08 11:58 UTC, merged