Mobile responsive personal details page
saeloun/miru-web pull request #1032
Opened 2023-02-14 05:01 UTC by onkar-saeloun

2023-02-17 05:00 UTC, prasanthchaduvula approved these changes

2023-02-20 12:39 UTC, onkar-saeloun commented on app/javascript/src/components/Team/Details/PersonalDetails/MobilePersonalDetails.tsx
> +  <div className="mt-12 px-4 py-2">
Done

2023-02-22 05:42 UTC, prasanthchaduvula requested changes

2023-02-22 05:42 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/Details/Layout/MobileNav.tsx
> +    const res: any = await teamsApi.get(memberId);
Move these to try-catch block and try to use promise life cycle methods if they are dependent API calls

2023-02-22 05:42 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/Details/Layout/MobileNav.tsx
> +const TeamUrl = ({ urlList }) => (
Extract TeamUrl and UserInformation into components. Import them here and use them.

2023-02-22 11:11 UTC, onkar-saeloun commented on app/javascript/src/components/Team/Details/Layout/MobileNav.tsx
> +    const res: any = await teamsApi.get(memberId);
done

2023-02-22 11:11 UTC, onkar-saeloun commented on app/javascript/src/components/Team/Details/Layout/MobileNav.tsx
> +const TeamUrl = ({ urlList }) => (
done

2023-02-23 12:31 UTC, vipulnsward commented
@onkar-saeloun Please rebase

2023-02-24 07:40 UTC, prasanthchaduvula approved these changes

2023-02-24 08:27 UTC, vipulnsward approved these changes

2023-02-24 08:27 UTC, vipulnsward commented on app/javascript/src/context/UserContext.tsx
> +/* eslint-disable no-unused-vars */
Is this needed still?

2023-02-24 08:27 UTC, merged

2023-02-24 08:28 UTC, vipulnsward commented
@supriya3105  to UX review on Staging
@apoorv1316  for staging functionality review