Added client logo key in the API response of reports and listing invoices.
saeloun/miru-web pull request #1048
Opened 2023-02-17 10:53 UTC by deepti-kakade

**Notion:** 

https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=ef0ff984508d41a289ea3f68ba3051ce&pm=s

https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=d6e1360130f34953b0a6ffe08f2c71b9&pm=s

**Description**:

- The Client logo should be visible on the invoice list and reports pages:

    - Recently updated section
    - The invoice list page
    - Accounts aging report
    - Time entry report
    - Revenue report
    - Invoices report
    
 **Screenshots**
<img width="1787" alt="Screenshot 2023-02-17 at 4 21 44 PM" src="https://user-images.githubusercontent.com/2971017/219626768-7c679dd6-0876-427b-8f72-2dbe51f41ab2.png">
<img width="1789" alt="Screenshot 2023-02-17 at 4 22 05 PM" src="https://user-images.githubusercontent.com/2971017/219626833-d074b7b7-4344-40c6-991e-bfef0ee2f66f.png">
<img width="1788" alt="Screenshot 2023-02-17 at 4 22 33 PM" src="https://user-images.githubusercontent.com/2971017/219626850-92e9c7c6-84c4-4b1d-b006-274ec805187e.png">

2023-02-21 09:29 UTC, supriya3105 commented
@deepti-kakade Same goes for this PR as well. Fix the issues and assign for review.

2023-02-27 07:06 UTC, supriya3105 commented
@shalapatil Please review. @apoorv1316 Please test as this will impact the invoice list page.

2023-02-27 07:51 UTC, apoorv1316 requested changes
@deepti-kakade Client logo front-end code for time entry seems missing. client logo is not visible on time entry reports.
<img width="1792" alt="Screenshot 2023-02-27 at 1 18 33 PM" src="https://user-images.githubusercontent.com/18750194/221504572-4dd4347c-b955-4b13-9a3c-aa05b344d540.png">

<img width="1792" alt="Screenshot 2023-02-27 at 1 16 35 PM" src="https://user-images.githubusercontent.com/18750194/221504554-323ae79d-2165-4928-8ab8-59f082240ac8.png">

2023-02-27 08:42 UTC, deepti-kakade commented
@apoorv1316 Fixed the above-mentioned issue and pushed the changes. You can review it again

2023-02-27 08:59 UTC, shalapatil requested changes

2023-02-27 08:59 UTC, shalapatil commented on app/views/internal_api/v1/partial/_invoice_item.json.jbuilder
> +      json.logo invoice.client.logo_url
we try to avoid more than a dot in the views. 
Refactor this so that you can get this in one dot instead.

2023-02-27 08:59 UTC, shalapatil commented on app/models/client.rb
>        name:,
Previously we needed only name and hence model was returning it. 
@vipulnsward Is it good idea to return all other required info from model? Purpose of model fn here is to get summarised data. IMO controller/presenter should take care of adding additional required info

2023-02-27 08:59 UTC, shalapatil commented on app/views/internal_api/v1/reports/time_entries/index.json.jbuilder
> +    json.client_logo report.client.logo_url
same. Don't use double dots

2023-02-27 08:59 UTC, shalapatil commented on spec/requests/internal_api/v1/invoices/index_spec.rb
>        describe "recently_updated_invoices return value" do
check for recently updated invoices as well

2023-02-27 08:59 UTC, shalapatil commented on spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
> +              logo: client1.logo_url, name: client1.name, paidAmount: @client1_paid_amount,
put name, paidAmount on new lines for readability

2023-02-27 08:59 UTC, shalapatil commented on app/javascript/src/components/Invoices/List/RecentlyUpdated/RecentlyUpdatedCard.tsx
> +        <Avatar url={invoice.client.logo} />
We should not use more than a dot to fetch data. 
Please try to destructure invoice to avoid this

2023-02-27 08:59 UTC, shalapatil commented on app/javascript/src/components/Invoices/List/Table/TableRow.tsx
> +          <Avatar url={invoice.client.logo} />
same, please do this wherever possible

2023-02-27 09:14 UTC, vipulnsward commented on app/models/client.rb
>        name:,
That is correct, @deepti-kakade please change accordingly

2023-02-27 09:34 UTC, deepti-kakade commented on app/views/internal_api/v1/partial/_invoice_item.json.jbuilder
> +      json.logo invoice.client.logo_url
Ok

2023-02-27 12:25 UTC, apoorv1316 commented
@deepti-kakade These entries will also have a client logo. refer to designs
<img width="1792" alt="Screenshot 2023-02-27 at 5 54 32 PM" src="https://user-images.githubusercontent.com/18750194/221563233-b97b821d-a145-4690-893f-80575d8f5a26.png">

2023-03-01 11:58 UTC, shalapatil reviewed
Please get frontend code reviewed from frontend dev

2023-03-01 11:58 UTC, shalapatil commented on app/models/invoice.rb
I am not sure about delegating logo url here as it's use case is not that much. 
@vipulnsward can help here?

2023-03-01 11:58 UTC, shalapatil commented on app/services/reports/client_revenues/index_service.rb
> +          client.payment_summary(duration_params).merge({ logo: client.logo_url })
add client name here instead of in model

2023-03-01 11:58 UTC, shalapatil commented on app/views/internal_api/v1/reports/time_entries/index.json.jbuilder
> +  json.client_logo grouped_report[:entries].first.client.logo_url
this is more than two dots here. 
Pass this data from respective service

2023-03-02 05:06 UTC, apoorv1316 approved these changes
@deepti-kakade Please add the logo to the timesheet report page in the mobile view
<img width="745" alt="Screenshot 2023-03-02 at 10 36 22 AM" src="https://user-images.githubusercontent.com/18750194/222336254-19a5122a-6dfe-403b-ac56-2063c0d081b3.png">

2023-03-02 08:27 UTC, prasanthchaduvula approved these changes
LGTM(frontend react code)

2023-03-02 08:58 UTC, shalapatil commented
@deepti-kakade  I can't see comments replied/implemented. Please reply to comments.

2023-03-02 09:23 UTC, shalapatil commented
@deepti-kakade There is only one comment, where I have asked @vipulnsward one doubt
Rest LGTM

2023-03-02 09:24 UTC, vipulnsward commented on app/models/invoice.rb
Its okay to do for now

2023-03-02 11:09 UTC, shalapatil approved these changes

2023-03-02 11:10 UTC, merged