Show only billable projects/clients should be displayed on the list.
saeloun/miru-web pull request #1050
Opened 2023-02-17 12:55 UTC by mayankagnihotri7

- Show only billable projects/clients that should be displayed on the list. Previously we used to show the clients whose projects are not billable and overdue.

https://user-images.githubusercontent.com/57438322/219658528-faf6874d-eaeb-4577-bc23-7fc14419663e.mp4

2023-02-22 05:02 UTC, shalapatil requested changes

2023-02-22 05:02 UTC, shalapatil commented on app/services/reports/accounts_aging/fetch_overdue_amount.rb
> +          projects: { billable: true }
Please add specs for the same.

2023-02-22 13:59 UTC, mayankagnihotri7 commented
@shalapatil I've added the specs as requested. Please review.

2023-02-23 05:42 UTC, shalapatil commented on spec/requests/internal_api/v1/reports/accounts_aging/index_spec.rb
> +      end
it should also have client2 also, right?
check for all the valid clients

2023-02-23 05:46 UTC, mayankagnihotri7 commented on spec/requests/internal_api/v1/reports/accounts_aging/index_spec.rb
> +      end
Right! I'll check for it as well.

2023-02-23 05:49 UTC, mayankagnihotri7 commented
@shalapatil I've made the requested changes. Please review.

2023-02-23 11:32 UTC, shalapatil commented on spec/requests/internal_api/v1/reports/accounts_aging/index_spec.rb
> +      end
expect(json_response["report"]["clients"].pluck("id")).to eq(client2.id, client1.id)

2023-02-23 11:33 UTC, shalapatil reviewed
One small suggestion, rest LGTM

2023-02-24 10:53 UTC, mayankagnihotri7 commented
@shalapatil I've made the requested changes. Please review.

2023-02-27 03:36 UTC, shalapatil approved these changes

2023-02-27 05:06 UTC, merged