Time entry report filter new design
saeloun/miru-web pull request #1053
Opened 2023-02-20 06:31 UTC by onkar-saeloun

Notion-
https://www.notion.so/saeloun/Time-Entry-Report-Desktop-Filter-Panel-design-update-c0a9d78c62584db496b861ad17c7d9d1?pvs=4

What-

1. Added new design with common components
2. Added new custom date select component
3. Added desktop view of filter panel with matching requirement

Why-

1. Common components will be reusable for other filters
2. new custom date select will be used as per new designs

Notes-

1. The logic of the custom date filter is not updated.
2. Tested on large and extra large devices for design and is working fine

Loom-
https://www.loom.com/share/14c7622dd9aa41119b64d714a3807edf

2023-02-20 09:34 UTC, AkashKale reviewed
- We have to remove 'All' option from Date Range
- Datepicker should close after user selects 'To' date

2023-02-21 06:14 UTC, onkar-saeloun commented
> * We have to remove 'All' option from Date Range
> * Datepicker should close after user selects 'To' date

@AkashKale I have removed all filter but can you please have a look at the closing calendar after selecting to filter? I have created a loom video. Previously we had done and reset button on the calendar thus it was readable.
https://www.loom.com/share/c72980ada1e8418b86f2ef060f505b7f

2023-02-21 08:21 UTC, AkashKale reviewed
After the user selects from and to dates and the datepicker is closed, the textboxes should be visible to show the dates which the user has selected so that the user can change the to or from date if they want
![image](https://user-images.githubusercontent.com/6756999/220287957-b73b8ab8-0893-477a-a92a-7308c62892c1.png)

2023-02-22 03:42 UTC, onkar-saeloun commented
@AkashKale please have a look on custom date picker functionality
https://www.loom.com/share/16bbffd5b5954ac691e02957edb7d6fd

2023-02-22 04:59 UTC, AkashKale approved these changes

2023-02-22 05:28 UTC, prasanthchaduvula requested changes

2023-02-22 05:28 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomDateRangeWIthInput/index.tsx
> +interface DateRange {
Please move the type props to the end of the file. It improves readability of the component.

2023-02-22 05:28 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/Filters/FilterSideBar.tsx
> +          // client.name.toLowerCase().includes(debouncedSearchQuery.toLowerCase())
If is it not used please remove this commented code

2023-02-22 05:28 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/Header/index.tsx
>                {/* <li className="flex items-center p-2 text-miru-dark-purple-400">
Please remove this commented code if it is not used

2023-02-22 12:11 UTC, onkar-saeloun commented on app/javascript/src/common/CustomDateRangeWIthInput/index.tsx
> +interface DateRange {
Done

2023-02-22 12:11 UTC, onkar-saeloun commented on app/javascript/src/components/Reports/Filters/FilterSideBar.tsx
> +          // client.name.toLowerCase().includes(debouncedSearchQuery.toLowerCase())
Done

2023-02-22 12:11 UTC, onkar-saeloun commented on app/javascript/src/components/Reports/Header/index.tsx
>                {/* <li className="flex items-center p-2 text-miru-dark-purple-400">
Done

2023-02-23 05:52 UTC, prasanthchaduvula approved these changes

2023-02-23 06:13 UTC, merged