Updated Organization settings API for Address changes.
saeloun/miru-web pull request #1057
Opened 2023-02-21 09:17 UTC by deepti-kakade

Notion:

https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=5578743881b44e108a04efb88153c00e&pm=s

Description:

After the developing the updated designs of organization settings page, backend changes are required for address fields on the organization settings page. 

- The address field is a text field which needs to be updated to different fields for Address line 1 , Address line 2 , Country, State, City & Zipcode. 

- We removed address column from the company table.
- We used Address association to save company's address.
- Updated create copmany API.

API Endpoint:
 
 http://localhost:3000/internal_api/v1/companies 

Input Params:
`
{
  "company": {
    "name": "Saeloun",
    "business_phone": "+918390108472",
    "country": "US",
    "base_currency": "USD",
    "standard_price": "200.00",
    "fiscal_year_end": "Dec",
    "date_format": "MM-DD-YYYY",
    "timezone": "(GMT-05:00) Eastern Time (US & Canada)"
  },
  "address": {
    "address_line_1": "Saeloun Inc",
    "address_line_2": "475 Clermont Ave",
    "state": "NY",
    "city": "Brooklyn",
    "country": "US",
    "pin": "12238"
  }
}
`

2023-02-23 08:35 UTC, shalapatil requested changes

2023-02-23 08:59 UTC, deepti-kakade commented on app/models/company.rb
> +  accepts_nested_attributes_for :addresses
`has_many` association is present in the Company model for addresses. Because of that referred to multiple addresses term.

Let me check with @supriya3105 regarding multiple addresses.

2023-02-23 09:02 UTC, deepti-kakade commented on app/views/internal_api/v1/companies/index.json.jbuilder
> +    json.address_line_1 address&.address_line_1
@shalapatil Address is not optional as per the current requirement, but addresses are missing for the few older records. To handle the null record we added the above check.

2023-02-23 09:51 UTC, deepti-kakade commented on scripts/update_company_addresses.rb
> +    end
@shalapatil Made the changes in the script.

2023-02-23 12:02 UTC, deepti-kakade commented on app/models/company.rb
> +  accepts_nested_attributes_for :addresses
Supriya said that we will only have a single address for the company and client. So I have changed the association to `has_one`.

2023-02-23 13:42 UTC, deepti-kakade commented on scripts/update_company_addresses.rb
> +    address_record = company.address
Need to change the association name of the address, because we have the same column in the client table. Or we can rename the address column and access the value. Working on this change.

2023-02-24 10:19 UTC, shalapatil commented on app/models/address.rb
> +    [address_line_1, address_line_2, city, state, pin, country].reject(&:blank?).join(", ")
shouldn't be order [...., country, pin]

2023-02-24 11:17 UTC, deepti-kakade commented on app/models/address.rb
> +    [address_line_1, address_line_2, city, state, pin, country].reject(&:blank?).join(", ")
@supriya3105  given the following format which we are currently using on the invoice page. 

i.e Address line 1, Address line 2 ( Since it is optional if the value is blank then don't display a blank line.), City, State
Zip code, Country 

So I referred to the given format.

2023-02-24 11:17 UTC, deepti-kakade commented on app/models/company.rb
> +  def attributes_blank?(attributes)
Ok

2023-02-24 11:21 UTC, deepti-kakade commented on db/seeds.rb
>      business_phone: "+1 9296207865",
We have renamed the address column and because of that replaced all occurrences.

2023-02-24 11:24 UTC, deepti-kakade commented on app/views/internal_api/v1/companies/index.json.jbuilder
> +    json.address_line_1 address&.address_line_1
While migrating I have added a blank value i.e `""` so I will remove this and will create a partial for the reusability.

2023-02-27 15:58 UTC, shalapatil commented on spec/requests/internal_api/v1/companies/create_spec.rb
> +            address_attributes: attributes_for(:address)
check if address is created successfully

2023-02-27 16:04 UTC, shalapatil reviewed
Please address all prev comments.

2023-02-27 16:04 UTC, shalapatil commented on app/policies/company_policy.rb
> +    [:name, :old_address, :business_phone, :country, :timezone, :base_currency, :standard_price, :fiscal_year_end,
why do we need old_address?

2023-02-27 16:04 UTC, shalapatil commented on app/policies/company_policy.rb
> -    [:name, :address, :business_phone, :country, :timezone, :base_currency, :standard_price, :fiscal_year_end,
Can you please clarify this?

2023-02-27 16:04 UTC, shalapatil commented on app/views/pdfs/invoices.html.erb
> +      <p><%=invoice.company.address&.formatted_address%></p>
Let's not keep optional part if address is not going to be optional.
make sure this gets handled in the migration

2023-02-27 16:04 UTC, shalapatil commented on db/seeds.rb
>      business_phone: "+1 9296207865",
No. old_address is required for migration purpose only. 
Remove all references from code until and unless something is breaking which I doubt will be the case. But please confirm.

2023-02-27 16:04 UTC, shalapatil commented on db/seeds.rb
>      business_phone: "+1 9296207865",
same goes for other PR as well

2023-02-28 10:13 UTC, deepti-kakade commented on app/policies/company_policy.rb
> -    [:name, :address, :business_phone, :country, :timezone, :base_currency, :standard_price, :fiscal_year_end,
We have renamed the address attribute to old_address because we have the same name relation.

2023-02-28 10:16 UTC, deepti-kakade commented on app/policies/company_policy.rb
> +    [:name, :old_address, :business_phone, :country, :timezone, :base_currency, :standard_price, :fiscal_year_end,
We have created a script that will copy address field data to the old_address field.  We will remove this attribute after the execution of the script. 

We will create a notion card to remove the old_address column.

2023-02-28 10:18 UTC, deepti-kakade commented on db/seeds.rb
>      business_phone: "+1 9296207865",
Ok

2023-03-01 12:43 UTC, shalapatil reviewed
Let's discuss about update on call. Not clear ro me. Also, as you are clear about update part, please add spec for the same
Rest LGTM

2023-03-02 09:02 UTC, deepti-kakade commented
> Let's discuss about update on call. Not clear ro me. Also, as you are clear about update part, please add spec for the same Rest LGTM

Sure. I have updated spec as per your comment. You can review it.

2023-03-02 09:05 UTC, deepti-kakade commented on app/policies/company_policy.rb
> -    [:name, :address, :business_phone, :country, :timezone, :base_currency, :standard_price, :fiscal_year_end,
I have added address attributes, we are considering address in update API as well.

2023-03-02 09:06 UTC, deepti-kakade commented on spec/requests/companies/update_spec.rb
> -              address: "updated address",
Updated a code to support address attributes.

2023-03-02 09:56 UTC, shalapatil commented
Script should be reviewed by @vipulnsward 
Rest is approved from my side.

2023-03-02 10:45 UTC, deepti-kakade commented on scripts/update_company_addresses.rb
> +    end
@vipulnsward Could you please review this script?

2023-03-02 13:40 UTC, closed without merging