Update add/edit client API for address field changes
saeloun/miru-web pull request #1068
Opened 2023-02-22 09:40 UTC by deepti-kakade

**Notion:**

https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=2587d88361084386a003bfee8c1f5029&pm=s

**Description:**

After developing the updated designs of the client creation page, backend changes are required for address fields on the new client page.

The address field is a text field that needs to be updated to different fields for Address line 1, Address line 2, Country, State, City & Zipcode.

- We removed the address column from the client table.

- We used Address association to save the client's address.

- Modified create/update client API.

- As well as list client API impacted, so made changes in that API as well.

- Migrating old addresses into the Address model. Created a script for the migration.

**Impacted API Endpoint:**

- GET - http://localhost:3000/internal_api/v1/clients?time_frame=week
- POST - http://localhost:3000/internal_api/v1/clients
- PATCH -http://localhost:3000/internal_api/v1/clients/<:client_id>
-  Generate Invoice API

2023-02-23 09:10 UTC, shalapatil requested changes

2023-02-23 09:10 UTC, shalapatil commented on scripts/update_client_addresses.rb
> +      client.addresses.create!(address_line_1: client.address)
will address creation work as we have lot of other validations in the address model?

2023-02-23 09:10 UTC, shalapatil commented on spec/requests/internal_api/v1/clients/create_spec.rb
> +            }]
just use ` attributes_for(:address)`

2023-02-23 09:10 UTC, shalapatil commented on spec/requests/internal_api/v1/clients/create_spec.rb
> +            }]
same here  attributes_for(:address) &  attributes_for(:client)

2023-02-23 09:10 UTC, shalapatil commented on spec/requests/internal_api/v1/clients/create_spec.rb
>        end
can we also add check to check created DB entry of client as well as address

2023-02-23 10:08 UTC, deepti-kakade commented on app/views/pdfs/invoices.html.erb
> +          <%=client.addresses&.last&.address_line_1%><br><%=client.phone%>
Got the address format from Supriya, updating it.

2023-02-23 11:24 UTC, shalapatil commented on app/views/pdfs/invoices.html.erb
> +          <%=client.addresses&.last&.address_line_1%><br><%=client.phone%>
@deepti-kakade This is same for all the places where you are returning address object directly. Please confirm how will it look on FE.

2023-02-23 13:14 UTC, deepti-kakade commented on app/controllers/internal_api/v1/clients_controller.rb
> +    end
The address is not optional as per the current requirement, but addresses are missing for the few older records.

2023-02-23 13:17 UTC, deepti-kakade commented on app/views/internal_api/v1/invoices/edit.json.jbuilder
> +  json.address client.addresses&.last
Currently, I have sent it as hash because, at the front end side, they need separate values. If required, we will change it as per the front-end requirement.

2023-02-23 13:18 UTC, deepti-kakade commented on app/views/pdfs/invoices.html.erb
> +          <%=client.addresses&.last&.address_line_1%><br><%=client.phone%>
I have modified this in my new commit.

2023-02-23 13:42 UTC, deepti-kakade commented on scripts/update_client_addresses.rb
> +    address_record = client.address
Need to change the association name of the address, because we have the same column in the client table. Or we can rename the address column and access the value. Working on this change.

2023-02-24 11:38 UTC, shalapatil commented on app/views/internal_api/v1/clients/_client.json.jbuilder
> +  json.logo client.logo
@deepti-kakade is frontend working fine with this? just check if UI is not breaking

2023-02-24 11:49 UTC, shalapatil commented on app/models/address.rb
> +  def formatted_address
use this in your other PR as well where you have defined the same method in the Company.

2023-02-24 11:49 UTC, shalapatil commented on app/models/client.rb
> +  def attributes_blank?(attributes)
rename this to address_attributes_blank?

2023-02-24 11:49 UTC, shalapatil commented on app/views/pdfs/invoices.html.erb
>          </p>
if address is not optional then do we need & ?

2023-02-24 11:49 UTC, shalapatil commented on scripts/update_client_addresses.rb
> +      address.save(validate: false)
we should use `save!`

2023-02-24 11:49 UTC, shalapatil commented on scripts/update_client_addresses.rb
> +      address.save(validate: false)
make same change in the other PR as well.

2023-02-24 11:49 UTC, shalapatil commented on spec/factories/clients.rb
>      phone { Faker::PhoneNumber.phone_number_with_country_code }
lets keep old_address for migration purpose only

2023-02-24 11:50 UTC, shalapatil commented on app/views/internal_api/v1/invoices/edit.json.jbuilder
> +  json.address client.addresses&.last
Okay

2023-02-24 11:51 UTC, shalapatil commented on scripts/update_client_addresses.rb
> +      client.addresses.create!(address_line_1: client.address)
Please get script reviewed from @vipulnsward

2023-02-24 12:18 UTC, deepti-kakade commented on app/views/internal_api/v1/clients/_client.json.jbuilder
> +  json.logo client.logo
The new UI is not yet created. We have just modified the API for address field changes. Once API is ready the front-end team will start the UI part. We will make changes in the response as per the UI requirements.

2023-02-27 15:53 UTC, shalapatil reviewed
Some comments are not replied/implemented. Please address them

2023-02-27 15:53 UTC, shalapatil commented on app/views/internal_api/v1/clients/_client.json.jbuilder
> +  json.logo client.logo
json.extract! client, :id, :name, :email, :phone, :logo

2023-02-27 15:53 UTC, shalapatil commented on app/views/internal_api/v1/clients/_client.json.jbuilder
> +    json.city address&.city
don't use & if address is not optional. Check if this is done at all the places.

2023-03-01 05:45 UTC, deepti-kakade commented on app/models/address.rb
> +  def formatted_address
Yes.

2023-03-01 06:24 UTC, deepti-kakade commented on app/views/internal_api/v1/partial/_client.json.jbuilder
> +json.address client.addresses&.last
I have changed it.

2023-03-01 12:49 UTC, shalapatil commented on app/views/internal_api/v1/clients/_client.json.jbuilder
> +    json.extract! address, :address_line_1, :address_line_2, :city, :state, :country, :pin
add address partial here as well and use that

2023-03-01 12:49 UTC, shalapatil commented on scripts/update_client_addresses.rb
> +      address = client.build_address(address_line_1: client&.old_address, city: "", state: "", country: "", pin: "")
if old address is not there, do we want to add empty address?

2023-03-02 05:35 UTC, deepti-kakade commented on app/views/internal_api/v1/clients/_client.json.jbuilder
> +    json.extract! address, :address_line_1, :address_line_2, :city, :state, :country, :pin
@shalapatil Yes we already created the address partial in my other PR https://github.com/saeloun/miru-web/pull/1057 but that is not yet merged. Because of that not created here otherwise, it will give conflict. I will change it as soon as that PR is merged.

2023-03-02 05:43 UTC, deepti-kakade commented on scripts/update_client_addresses.rb
> +      address = client.build_address(address_line_1: client&.old_address, city: "", state: "", country: "", pin: "")
Yes, otherwise address will not be created.

2023-03-02 09:07 UTC, deepti-kakade commented on spec/factories/clients.rb
>      phone { Faker::PhoneNumber.phone_number_with_country_code }
Yes, we have removed it from here.

2023-03-02 13:40 UTC, closed without merging