Add timesheet entry system spec
saeloun/miru-web pull request #1103
Opened 2023-03-02 14:41 UTC by mayankagnihotri7

2023-03-06 10:25 UTC, shalapatil commented on spec/system/time_tracking/time_tracking_spec.rb
> +      @company = create(:company)
can we please use let to define all this vars instead of using instance variables?

2023-03-06 10:25 UTC, shalapatil commented on spec/system/time_tracking/time_tracking_spec.rb
> +    end
Please create three types of users like this 
https://github.com/saeloun/miru-web/pull/970/files#diff-17585529c926d0f13fb1b1a6af591d8e982a1fc6d470cccf461eed1cd51b41a6

this is for good readability

2023-03-06 10:25 UTC, shalapatil commented on spec/system/time_tracking/time_tracking_spec.rb
> +    end
and add specs for all types of users

2023-03-06 10:25 UTC, shalapatil commented on spec/system/time_tracking/time_tracking_spec.rb
> +        fill_in "notes",	with: "Testing note!"
remove spacing

2023-03-06 10:25 UTC, shalapatil commented on spec/system/time_tracking/time_tracking_spec.rb
> +        expect(page).to have_content("Timesheet created", wait: 3)
can we also check if created timesheet is visible on the page

2023-03-06 10:25 UTC, shalapatil commented on spec/system/time_tracking/time_tracking_spec.rb
> +      end
can we also check if edited timesheet is visible on the page

2023-03-06 10:25 UTC, shalapatil commented on spec/system/time_tracking/time_tracking_spec.rb
> +      end
can we also check if deleted timesheet is not visible on the page

2023-03-06 10:25 UTC, shalapatil commented on spec/system/time_tracking/time_tracking_spec.rb
> +        within(".css-6j8wv5-Input") do
is there any better named element available?

2023-03-06 10:25 UTC, shalapatil commented on spec/system/time_tracking/time_tracking_spec.rb
> +      end
also add specs for bookeeper role

2023-03-06 11:39 UTC, mayankagnihotri7 commented on spec/system/time_tracking/time_tracking_spec.rb
> +        within(".css-6j8wv5-Input") do
No. All the elements for `react-select` have classes named like these.

2023-03-06 11:50 UTC, mayankagnihotri7 commented on spec/system/time_tracking/time_tracking_spec.rb
> +      end
Bookeeper cannot add time entries or view them, so there is no point of adding the specs for that role.

2023-03-06 12:07 UTC, mayankagnihotri7 commented on spec/system/time_tracking/time_tracking_spec.rb
> +    end
Bookeeper cannot add time entries or view them, so there is no point of adding the specs for that role.

2023-03-06 12:07 UTC, mayankagnihotri7 commented
@shalapatil I've made the requested changes. Please review.

2023-03-06 16:27 UTC, mayankagnihotri7 commented on spec/system/time_tracking/time_tracking_spec.rb
> +        within(".css-6j8wv5-Input") do
It is generated by `react-select` itself. We just use `Select` from the npm package.

2023-03-09 10:57 UTC, shalapatil requested changes

2023-03-09 10:57 UTC, shalapatil commented on spec/system/time_tracking/week_view_spec.rb
> +      employee.add_role :employee, company
same set of repeated specs can be avoided with shared_examples_for

2023-03-09 15:12 UTC, apoorv1316 reviewed
@mayankagnihotri7 I have added some comments. Also, let's add more tests here such as

- Checking/Unchecking billable checkbox on create and edit timesheet entry and then verifying it.
- Checking total hours for a row
- Editing the date after creating an entry and then verifying the entry has been moved to the edited date.
- Switching months on month view
- Checking for validations, currently, there is no validations test in this PR. For e.g, an employee can't edit and delete a billed entry, an employee can see only the clients and projects to which they are added to.

2023-03-09 15:12 UTC, apoorv1316 commented on spec/system/time_tracking/day_view_spec.rb
> +
This should be in before block

2023-03-09 15:12 UTC, apoorv1316 commented on spec/system/time_tracking/time_tracking_spec.rb
> +        el = find(:css, "#editIcon", visible: false).hover
Can you try visible: hidden here?

2023-03-13 09:41 UTC, mayankagnihotri7 commented
@apoorv1316 @shalapatil I've made the requested changes. Please review.

2023-03-13 10:15 UTC, vipulnsward commented on app/javascript/src/components/TimeTracking/WeeklyEntriesCard.tsx
> +    // if (isWeeklyEditing) return;
Is this not needed anymore? If yes please remove

2023-03-13 14:57 UTC, mohinid commented on spec/system/shared_examples/time_tracking.rb
> +shared_examples_for "Time tracking" do |obj|
Hey, can we use sub folders inside "shared_examples" to specify the spec. For eg. you can create "time_tracking" folder under "shared_examples" and then put all your examples there. In the same way, I will put all my specs under "shared_examples/invoices" folder. Will be good for organizing.

2023-03-14 10:00 UTC, shalapatil commented on spec/system/time_tracking/week_view_spec.rb
> +# require "./shared_examples/week_view"
not needed?

2023-03-17 10:38 UTC, mayankagnihotri7 commented on spec/system/shared_examples/time_tracking.rb
> +shared_examples_for "Time tracking" do |obj|
It makes the code look cleaner. Putting them together makes it look quite cluttered.

2023-03-20 04:55 UTC, shalapatil approved these changes

2023-03-21 07:30 UTC, merged