Fix time entry report
saeloun/miru-web pull request #1104
Opened 2023-03-03 04:12 UTC by shalapatil

2023-03-09 21:37 UTC, vipulnsward commented
@shalapatil can you check spec failures?

2023-03-13 12:05 UTC, supriya3105 commented
@shalapatil If the specs are now passing, please assign to Vipul for review. Let's try to get PR's approved faster.

2023-03-16 10:45 UTC, prasanthchaduvula commented on app/services/reports/time_entries/page_service.rb
> +    def users_query
```suggestion
    is it possible to build something similar to Invoices::IndexService
```

2023-03-16 10:46 UTC, prasanthchaduvula requested changes

2023-03-16 10:46 UTC, prasanthchaduvula commented on app/services/reports/time_entries/report_service.rb
> +class Reports::TimeEntries::ReportService
is it possible to build something similar to Invoices::IndexService

2023-03-17 11:20 UTC, supriya3105 commented
@mayankagnihotri7 Please finish the review comments from Prasanth on this PR and get it closed.

2023-03-20 10:24 UTC, shalapatil commented on app/services/duration_formatter.rb
> +    total_minutes = duration.to_i
this is working code which is just refactored into service from model

2023-03-20 10:30 UTC, shalapatil commented on app/services/reports/time_entries/report_service.rb
> +class Reports::TimeEntries::ReportService
didn't get it, can you please explain?

2023-03-22 01:26 UTC, shalapatil commented on app/models/client.rb
> +  scope :with_ids, -> (client_ids) { where(id: client_ids) if client_ids.present? }
IMO with_ids is clear name and conveying clearly that scope is to get for given ids.

2023-03-22 01:27 UTC, shalapatil commented on app/models/project.rb
> +  scope :with_ids, -> (project_ids) { where(id: project_ids) if project_ids.present? }
Not changing it as per the above comment.

2023-03-22 01:27 UTC, shalapatil commented on app/models/user.rb
> +  scope :with_ids, -> (user_ids) { where(id: user_ids) if user_ids.present? }
Not changing it as per the above comment

2023-03-22 06:08 UTC, mayankagnihotri7 commented on app/services/reports/time_entries/report_service.rb
> +class Reports::TimeEntries::ReportService
This is handling the filter as well.

2023-03-22 06:45 UTC, mayankagnihotri7 commented on app/services/reports/time_entries/page_service.rb
> +    def es_filter_for_pagination
Cannot currently do that due to rubocop warnings which come.

2023-03-23 11:15 UTC, prasanthchaduvula requested changes

2023-03-23 11:15 UTC, prasanthchaduvula commented on app/models/client.rb
> +  scope :with_specific_ids, -> (client_ids) { where(id: client_ids) if client_ids.present? }
@mayankagnihotri7 Revert it to `:with_ids`

2023-03-23 11:15 UTC, prasanthchaduvula commented on app/models/project.rb
> +  scope :with_specific_ids, -> (project_ids) { where(id: project_ids) if project_ids.present? }
@mayankagnihotri7 Revert it to :with_ids

2023-03-23 11:15 UTC, prasanthchaduvula commented on app/models/user.rb
> +  scope :with_specific_ids, -> (user_ids) { where(id: user_ids) if user_ids.present? }
@mayankagnihotri7 Revert it to :with_ids

2023-03-23 11:22 UTC, prasanthchaduvula approved these changes

2023-03-23 12:43 UTC, supriya3105 commented
@apoorv1316 Please test this functionality on local. If its working, please merge. Assigning it to you .

2023-03-24 04:47 UTC, apoorv1316 commented
@mayankagnihotri7 We are only displaying 3 client entries on a page but if we download the pdf I am also getting the entries for the client whose entries were not on the report page.  Please check loom: https://www.loom.com/share/e3c797352e9c4bf492e957d3c2ae926a

2023-03-24 12:08 UTC, mayankagnihotri7 commented
@apoorv1316 I've made the requested changes. Please review.
@prasanthchaduvula Can you please check the PR again as well? I've added frontend pagination.


https://user-images.githubusercontent.com/57438322/227517146-7564ee98-6354-415b-833d-84daef40e130.mp4

2023-03-27 06:26 UTC, merged