Generate Invoice - System Specs
saeloun/miru-web pull request #1107
Opened 2023-03-03 13:40 UTC by mohinid

**Notion**:
https://www.notion.so/saeloun/Add-RSpec-visual-tests-integration-along-with-UT-and-cypress-4ab4b3aa0e4840fcb771cfa46d67c055?d=574cd96410e645c0b09cc74903b25245#cc290ed5340d4d1f8deb44dde959352a

**Description**
Testing Invoice Generation with both Admin and Employee roles:
For Admin (Positive) - The user should be able to generate an invoice for an employee of his organization.
Employee (Negative)- The employee should not be able to see the menu option for Invoices.

**TODO:** 
-Refactor(Move xpaths to a separate locator file)
-Add more test cases.

2023-03-09 05:03 UTC, shalapatil requested changes

2023-03-09 05:03 UTC, shalapatil commented on spec/system/invoices/edit_invoice_spec.rb
> +  let(:user) { create :user, current_workspace_id: company.id }
create three users as admin, owner and employee here and use them directly
better for readability

2023-03-09 05:03 UTC, shalapatil commented on spec/system/invoices/edit_invoice_spec.rb
> +  let(:user) { create :user, current_workspace_id: company.id }
https://github.com/saeloun/miru-web/pull/970/files#diff-17585529c926d0f13fb1b1a6af591d8e982a1fc6d470cccf461eed1cd51b41a6

2023-03-09 05:16 UTC, shalapatil reviewed
Avoid repeated code.

2023-03-09 05:16 UTC, shalapatil commented on spec/system/invoices/generate_invoice_spec.rb
> +        find(:xpath, '//*[@id="client-list"]/div[2]/div').click()
will select option  work here like
https://github.com/saeloun/miru-web/pull/1103/files#diff-0c836bdf34c99660e3381ef7ea3c1b583801bc0ef0d0c5a2d59169eec53ce390

2023-03-09 05:16 UTC, shalapatil commented on spec/system/invoices/generate_invoice_spec.rb
> +        find(:xpath, '//*[@id="client-list"]/div[2]/div').click()
and same for other similar places

2023-03-09 05:16 UTC, shalapatil commented on spec/system/invoices/send_invoice_spec.rb
> +          #   expect(page).to have_content("Invoice will be sent!") - Need to verify.
why is this commented code?

2023-03-09 07:14 UTC, mohinid commented on spec/system/invoices/send_invoice_spec.rb
> +          #   expect(page).to have_content("Invoice will be sent!") - Need to verify.
This is failing on some runs. Thats why I have mentioned "- Need to verify." Checking this today.

2023-03-09 07:14 UTC, mohinid commented on spec/system/invoices/edit_invoice_spec.rb
> +  context "when logged-in user is Owner" do
Yes, checking :)

2023-03-09 14:52 UTC, apoorv1316 reviewed
@mohinid I have added some comments. Also, there are no validation tests here. Please add more tests. 

1. Generate invoice
 - All the validations
 - Adding entries from multiple entries modal
 - Adding manual entry
2. Send invoice
 - Checking for emails delivery
 - Validations on modal 
 - Making changes in send invoice modal and confirming it with the email received

2023-03-09 14:52 UTC, apoorv1316 commented on spec/system/invoices/generate_invoice_spec.rb
> +      sign_in user
Please use login_as(user). sign_in user will sign_in via UI every time the test is run and it will increase the runtime of tests. We already have test where we sign in via UI.

2023-03-09 14:52 UTC, apoorv1316 commented on spec/system/invoices/generate_invoice_spec.rb
> +       expect(page).to have_text "Invoices"
Add an empty line after visiting links.

2023-03-09 14:52 UTC, apoorv1316 commented on spec/system/invoices/generate_invoice_spec.rb
> +        find(:xpath, "//*[@id='entries-list']/span[contains(text(), '#{employee.first_name}')]").click()
this is hard to understand. Can we use id or class to target the element?

2023-03-09 14:52 UTC, apoorv1316 commented on spec/system/invoices/generate_invoice_spec.rb
> +        expect(page).to have_xpath "//h1[text()='All Invoices']"
If searching for text we can use have_content or if you want to match styles then we can use have_css. You can check more matches from here https://rubydoc.info/github/teamcapybara/capybara/master/Capybara/Node/Matchers

2023-03-09 14:52 UTC, apoorv1316 commented on spec/system/invoices/generate_invoice_spec.rb
> +        click_button("Create New Invoice")
Please add en empty line before assertions

2023-03-09 14:52 UTC, apoorv1316 commented on spec/system/invoices/send_invoice_spec.rb
> +      page.windows[0].maximize
what is the use case of this line?

2023-03-10 03:45 UTC, mohinid commented
> @mohinid I have added some comments. Also, there are no validation tests here. Please add more tests.
> 
> 1. Generate invoice
> 
> * All the validations
> * Adding entries from multiple entries modal
> * Adding manual entry
> 
> 2. Send invoice
> 
> * Checking for emails delivery
> * Validations on modal
> * Making changes in send invoice modal and confirming it with the email received

Hi these I will add in next PR as the code is getting really big here. Have to make a test case check list too. Will be best to refer the tracker for it.

2023-03-10 04:15 UTC, mohinid commented on spec/system/invoices/generate_invoice_spec.rb
> +        find(:xpath, '//*[@id="client-list"]/div[2]/div').click()
Hi, no this will not work because here On Invoices we are dealing with react-select and not HTML-select dropdown. Hence using XPath. On using the direct select option as you mentioned- we will get this error-  `"Unable to find select box "client-list" that is not disabled and Unable to find input box with datalist completion "client-list" that is not disabled"` Can discuss more in slack.

2023-03-10 04:19 UTC, mohinid commented on spec/system/invoices/generate_invoice_spec.rb
> +        expect(page).to have_xpath "//h1[text()='All Invoices']"
Hi This is not working with have_content or text as it throws this error- ```
Failure/Error: expect(page).to have_content "All Invoices"
       expected to find text "All Invoices" in "Time Tracking\nClients\nProjects\nTeam\nInvoices\nReports\nPayments\nSettings\nLogout\nSaeloun\nWesley Schuppe\nkendall@example.com\nInvoices\nNEW INVOICE\nLoading..."

Hence using XPath. Can discuss more on slack.
```

2023-03-13 05:22 UTC, mohinid commented
@shalapatil can you please review the changes.

2023-03-13 08:14 UTC, shalapatil commented on spec/system/invoices/edit_invoice_spec.rb
> +  let(:invoice) { create :invoice_with_invoice_line_items, status: :draft }
it it possible to move RSpec.describe section above shared example block?

2023-03-13 08:15 UTC, shalapatil reviewed
one comment, rest looks good to me

2023-03-13 08:16 UTC, mohinid commented
> one comment, rest looks good to me

Hi no, we cant do that. It throws as error as it cannot find shared_example.

2023-03-13 08:17 UTC, mohinid commented on spec/system/invoices/edit_invoice_spec.rb
> +  let(:invoice) { create :invoice_with_invoice_line_items, status: :draft }
https://github.com/saeloun/miru-web/pull/1107#issuecomment-1465691353

2023-03-13 09:54 UTC, mayankagnihotri7 reviewed
@mohinid I've added some comments. Please check.

2023-03-13 09:54 UTC, mayankagnihotri7 commented on app/javascript/src/components/Invoices/List/MoreOptions.tsx
> +            id="send-invoice-button"
Use camel casing in JS. Use camel casing in the files below as well where you have added IDs.

2023-03-13 09:54 UTC, mayankagnihotri7 commented on spec/system/invoices/send_invoice_spec.rb
> +RSpec.shared_examples "Send Invoice" do
Create a separate folder for `shared_examples`. Refer this PR - https://github.com/saeloun/miru-web/pull/1103/files

2023-03-13 14:53 UTC, mohinid commented on spec/system/invoices/send_invoice_spec.rb
> +RSpec.shared_examples "Send Invoice" do
thanks, checking

2023-03-14 11:16 UTC, mayankagnihotri7 commented on spec/system/invoices/edit_invoice_spec.rb
> +        login_as admin
This won't work anymore since we moved those pages from rails to react. Make changes to the session helpers file - https://github.com/saeloun/miru-web/blob/396e7611ea33fd53776d03ab0ea1d8762cb4c900/spec/support/session_helpers.rb
Replace the usage of `login_as` wherever you've used it in the specs.

2023-03-15 05:58 UTC, mohinid commented on spec/system/invoices/edit_invoice_spec.rb
> +        login_as admin
Done.

2023-03-20 13:51 UTC, prasanthchaduvula requested changes

2023-03-20 13:51 UTC, prasanthchaduvula commented on spec/factories/invoices.rb
> +    # amount { Faker::Number.decimal(r_digits: 2) }
@apoorv1316 Please run seed data in local check invoice are getting created properly or not

2023-03-20 15:13 UTC, prasanthchaduvula requested changes

2023-03-20 15:13 UTC, prasanthchaduvula commented on spec/system/shared_examples/invoices/edit_invoice.rb
> +      expect(page).to have_xpath "//h1[text()='All Invoices']"
Here target the text. Dont include elements like `h1 `here. Frontend styling can change any time

2023-03-20 15:13 UTC, prasanthchaduvula commented on spec/system/shared_examples/invoices/edit_invoice.rb
> +      expect(page).to have_css("h2", text: "Edit Invoice ##{invoice.invoice_number}")
ditto
Here target the text. Don't include elements like `h2 `here. Frontend styling can change at any time

2023-03-20 15:13 UTC, prasanthchaduvula commented on spec/system/shared_examples/invoices/generate_invoice.rb
> +      find("#BilledTo").click
ditto

2023-03-20 15:13 UTC, prasanthchaduvula commented on spec/system/shared_examples/invoices/send_invoice.rb
> +      expect(page).to have_xpath "//h1[text()='All Invoices']"
ditto
ditto
Here target the text. Don't include elements like `h1 `here. Frontend styling can change at any time

2023-03-21 05:44 UTC, apoorv1316 commented on spec/system/shared_examples/invoices/edit_invoice.rb
> +      expect(page).to have_xpath "//h1[text()='All Invoices']"
done

2023-03-21 05:44 UTC, apoorv1316 commented on spec/system/shared_examples/invoices/edit_invoice.rb
> +      expect(page).to have_css("h2", text: "Edit Invoice ##{invoice.invoice_number}")
done

2023-03-21 05:45 UTC, apoorv1316 commented on spec/system/shared_examples/invoices/edit_invoice.rb
> +      find_by_id("cancelEditInvoiceButton").click()
changed it to use click_on

2023-03-21 05:46 UTC, apoorv1316 commented on spec/system/shared_examples/invoices/generate_invoice.rb
> +      find("#BilledTo").click
This Billed to is in span and not in link or button so then we have to select it via selector which we want to avoid. So using id to target is a better approach here.

2023-03-21 05:46 UTC, apoorv1316 commented on spec/system/shared_examples/invoices/send_invoice.rb
> +      expect(page).to have_xpath "//h1[text()='All Invoices']"
done

2023-03-21 06:46 UTC, prasanthchaduvula approved these changes

2023-03-21 07:00 UTC, merged