Used Address model to store client address instead of address column.
saeloun/miru-web pull request #1118
Opened 2023-03-09 09:07 UTC by deepti-kakade

**Notion:**

https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=2587d88361084386a003bfee8c1f5029&pm=s

**Description:**

After developing the updated designs of the client creation page, backend changes are required for address fields on the new client page.

The address field is a text field that needs to be updated to different fields for Address line 1, Address line 2, Country, State, City & Zipcode.

- We used Address association to save the client's address.

- Modified create/update client API.

- As well as list client API impacted, so made changes in that API as well.

- Migrating old addresses into the Address model. Created a migration for the migration.

**Impacted API Endpoint:**

- GET - http://localhost:3000/internal_api/v1/clients?time_frame=week
- POST - http://localhost:3000/internal_api/v1/clients
- PATCH -http://localhost:3000/internal_api/v1/clients/<:client_id>
-  Generate Invoice API

2023-03-14 06:29 UTC, shalapatil requested changes

2023-03-14 06:29 UTC, shalapatil commented on spec/factories/addresses.rb
> +    trait :with_client do
this also needs to be fixed to use the created client

2023-03-14 11:25 UTC, deepti-kakade commented on app/models/company.rb
> +#  address         :text
@shalapatil 
The address was not null by default, so we changed the default value to null to allow null values.

2023-03-14 11:25 UTC, deepti-kakade commented on app/views/internal_api/v1/clients/_client.json.jbuilder
> +  json.address do
Okay

2023-03-14 11:36 UTC, deepti-kakade commented on db/seeds.rb
> +    address_line_1: "475 Clermont Ave", city: "Brooklyn", state: "NY", pin: "12238", country: "USA"
@shalapatil I think we can't use attributes_for method here because it is available with factory and Rspec.

2023-03-17 11:24 UTC, supriya3105 commented
@prasanthchaduvula Same for this PR. It is connected to the previous PR. Please review and make the required changes yourself to get it merged as soon as possible.

2023-03-17 11:26 UTC, prasanthchaduvula commented
@supriya3105 is it regarding the flaky system spec or regarding the PR review comments

2023-03-17 11:30 UTC, supriya3105 commented
> @supriya3105 is it regarding the flaky system spec or regarding the PR review comments

@prasanthchaduvula Review comments . If there are flaky specs that are failing , please fix them too. Anything that's required to get the PR merged.

2023-04-20 09:18 UTC, prasanthchaduvula commented
Closing this PR as these changes already got merged https://github.com/saeloun/miru-web/pull/1240

2023-04-20 09:18 UTC, closed without merging