Displaying only clients with billable projects on the revenue report.
saeloun/miru-web pull request #1121
Opened 2023-03-10 05:52 UTC by deepti-kakade

Notion:
https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=8d0f77eac98944b1a4bd4103a9ff403a&pm=s

Description:
Only billable clients should be displayed on the list. Previously we used to show the clients whose projects are not billable.
The same clients should not be listed on the filter panel as well.

2023-03-10 05:55 UTC, deepti-kakade commented
@vipulnsward 

On the Revenue Report page, we used an index API of the client to display client names in the filters.
But unnecessary data is also coming in the response which is not required on this page.
Also, we need only clients with billable projects.

And same API is consumed on the client page as well.

So I have created a new API for revenue reports to get only billable clients' names for the filters.

2023-03-10 10:56 UTC, supriya3105 commented
Same comment for this PR too. Please fix the checks and then assign for review.

2023-03-14 09:52 UTC, shalapatil requested changes
This is partially reviewed. 
Please update the route for billable_clients as per the suggestion. Will review after this change.

2023-03-14 09:52 UTC, shalapatil commented on app/controllers/internal_api/v1/clients_controller.rb
> +  def billable_clients
This is not following REST APIs
Instead of adding new route for client, add `new` route and `new` action  for client revenue report controller which will return all required filters for that page

2023-03-14 09:52 UTC, shalapatil commented on app/controllers/internal_api/v1/clients_controller.rb
> +  def billable_clients
and update js code accordingly

2023-03-14 09:52 UTC, shalapatil commented on app/models/company.rb
> +      ).kept.order(name: :asc)
More readable

 ```
clients
      .joins(:projects)
      .where(projects: { billable: true })
      .kept
      .order(name)
```

2023-03-14 09:52 UTC, shalapatil commented on app/models/company.rb
> +      ).kept.order(name: :asc)
Also, why do we need sorting in model? service can handle this

2023-03-15 05:33 UTC, shalapatil requested changes
Please get code reviewed from FE developers 
Also, upload the loom video for the feature

2023-03-15 05:33 UTC, shalapatil commented on app/controllers/internal_api/v1/clients_controller.rb
> +  def billable_clients
Remove this code

2023-03-15 05:33 UTC, shalapatil commented on spec/requests/internal_api/v1/clients/index_spec.rb
> +      create(:project, billable: true, client: client_2)
are this changes required?

2023-03-15 05:33 UTC, shalapatil commented on spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
> +      create(:project, billable: true, client: client1)
same here

2023-03-15 06:23 UTC, deepti-kakade commented on spec/requests/internal_api/v1/clients/index_spec.rb
> +      create(:project, billable: true, client: client_2)
Yes, it's required here.

2023-03-15 06:32 UTC, deepti-kakade commented on spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
> +      create(:project, billable: true, client: client1)
yes, we are displaying billable clients.

2023-03-15 06:32 UTC, deepti-kakade commented
@shalapatil Please review the changes.

2023-03-15 09:47 UTC, shalapatil commented on spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
> +      create(:project, billable: true, client: client1)
Okay, you can add non billable project as well and check if that is not listed

2023-03-15 09:48 UTC, shalapatil reviewed
also, loom video is missing

2023-03-17 11:29 UTC, supriya3105 commented
@prasanthchaduvula Please review and make the required changes yourself . merge PR once all required changes are done,

2023-03-17 15:58 UTC, prasanthchaduvula commented
@deepti-kakade Frontend changes LGTM
Please fix this one spec https://github.com/saeloun/miru-web/pull/1121#discussion_r1136788118
We can merge this PR

2023-03-17 16:09 UTC, prasanthchaduvula approved these changes

2023-03-17 17:44 UTC, prasanthchaduvula approved these changes

2023-03-18 04:03 UTC, deepti-kakade commented
> @deepti-kakade Frontend changes LGTM Please fix this one spec [#1121 (comment)](https://github.com/saeloun/miru-web/pull/1121#discussion_r1136788118) We can merge this PR

Yes, I have fixed it.

2023-03-21 05:45 UTC, shalapatil approved these changes

2023-03-21 06:13 UTC, merged