Bugfix- Add manual payment modal
saeloun/miru-web pull request #1132
Opened 2023-03-14 09:21 UTC by onkar-saeloun

What-
- PR includes fixing the font size and padding issue on add payment modal
- PR includes implementation of new design on add payment modal
- Fix - Outside click on calendar should close calendar
- add symbol in front of amount

why-
- The new UI textbox and select box needed to be implemented
- The invoice dropdown was having UI issues on large names
- Calendar was not closing clicking outside
- amount symbol was not present

Notion-
https://www.notion.so/saeloun/Fix-the-UI-issues-on-Add-manual-payment-entry-modal-on-web-f2f8e82bffed4e3f8cdba0472250fd9f?pvs=4

loom-
https://www.loom.com/share/598fb2d7246540ffa9caedb192768473

2023-03-14 09:22 UTC, onkar-saeloun commented on app/javascript/src/components/payments/Modals/AddManualEntry.tsx
> +                    <div
replaced old select and input fields by new common components for uniform UI appearance

2023-03-14 12:35 UTC, prasanthchaduvula commented on app/javascript/src/components/payments/Modals/AddManualEntry.tsx
> +                  name="transaction_date"
dito
name should be camelCase

2023-03-14 12:36 UTC, prasanthchaduvula commented on app/javascript/src/components/payments/Modals/AddManualEntry.tsx
> +                name="transaction-type"
dito
name should be camelCase

2023-03-14 12:36 UTC, prasanthchaduvula commented on app/javascript/src/components/payments/Modals/AddManualEntry.tsx
> +                name="payment_amount"
dito
name should be camelCase

2023-03-14 12:36 UTC, prasanthchaduvula commented on app/javascript/src/components/payments/Modals/AddManualEntry.tsx
> +                name="Notes-optional"
dito
name should be camelCase

2023-03-14 12:39 UTC, prasanthchaduvula requested changes

2023-03-15 05:52 UTC, onkar-saeloun commented on app/javascript/src/components/payments/Modals/AddManualEntry.tsx
> +                        name="invoice-search"
Done

2023-03-16 02:20 UTC, prasanthchaduvula approved these changes

2023-03-16 10:46 UTC, merged