revenue filter
saeloun/miru-web pull request #1138
Opened 2023-03-15 07:00 UTC by Ankita012

2023-03-17 07:44 UTC, onkar-saeloun requested changes
@Ankita012 few comments. Also can you please confirm you have tested it in your mobile screen.

in video its recorded

2023-03-17 07:44 UTC, onkar-saeloun commented on app/javascript/src/components/Reports/RevenueByClientReport/Filters/index.tsx
> +            <li className="relative cursor-pointer border-b border-miru-gray-200 pb-5 pt-6 text-miru-dark-purple-1000 hover:text-miru-han-purple-1000">
can we create separate component for each report item? refer `app/javascript/src/components/Reports/Filters/FilterSideBar.tsx`
It will become complex incase of any bug.

2023-03-17 07:44 UTC, onkar-saeloun commented on app/javascript/src/components/Reports/RevenueByClientReport/Filters/index.tsx
> +            <li className="cursor-pointer border-b border-miru-gray-200 pb-5 pt-6 text-miru-dark-purple-1000">
same as above we should create different component for each filter item. 
You can check whether you can reuse anything from the folder given below `app/javascript/src/components/Reports/Filters`

2023-03-17 11:25 UTC, supriya3105 commented
@onkar-saeloun Please make the required changes on this PR yourself and merge this PR as soon as possible.

2023-03-17 11:29 UTC, onkar-saeloun commented
> @onkar-saeloun Please make the required changes on this PR yourself and merge this PR as soon as possible.

Okay

2023-03-20 07:33 UTC, onkar-saeloun approved these changes

2023-03-20 07:33 UTC, merged