Updated the UI for Add Team members modal on project details page
saeloun/miru-web pull request #1139
Opened 2023-03-15 07:43 UTC by sanjibroy360

## Notion card
[https://www.notion.so/saeloun/Update-the-UI-for-Add-Team-members-modal-on-project-details-page-3964466aada34ef189fd8f4aac6881ee](https://www.notion.so/saeloun/Update-the-UI-for-Add-Team-members-modal-on-project-details-page-3964466aada34ef189fd8f4aac6881ee)

## Figma
[https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?node-id=11779%3A166708&t=LBTOw1VtpHn4eABe-0](https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?node-id=11779%3A166708&t=LBTOw1VtpHn4eABe-0)

## Summary
- Updated the UI for Add Team members modal on the project details page.
- Added validations for the rate input field.
- Although the project details page is not responsive, I've ensured that this modal will be mobile responsive.

## Preview
[https://www.loom.com/share/953f4d0e4ca745fca6fed37528f31c88](https://www.loom.com/share/953f4d0e4ca745fca6fed37528f31c88)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2023-03-15 08:05 UTC, onkar-saeloun requested changes
Please go through the comments

2023-03-15 08:05 UTC, onkar-saeloun commented on app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
> +export const customStyles = (isDesktopView, hideDropdownIndicator = false) => ({
do we need to assign false value?
we have provided default prop for this `hideDropdownIndicator: false`

2023-03-15 08:05 UTC, onkar-saeloun commented on app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
> +        : "15%",
Have you tested its implications on other components? Other components should not break.

2023-03-15 08:05 UTC, onkar-saeloun commented on app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
> +    "absolute top-0.5 right-1 h-6 z-1 origin-0 bg-white p-2 text-base font-medium duration-300";
move this outside `EditMembersListForm` component

2023-03-15 08:05 UTC, onkar-saeloun commented on app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
> +  const handleHourlyRateInput = (e, idx) => {
any specific reason to use a variable name as `idx`? we should use common names as it won't create confusion to other developers. Let me know if it has any reason.

2023-03-15 08:46 UTC, sanjibroy360 commented on app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
> +  const handleHourlyRateInput = (e, idx) => {
In many places, we already use the variable name `idx` to represent the index of any array. That's why I used the same so that it won't create any confusion.

2023-03-15 09:31 UTC, onkar-saeloun commented on app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
> +  const handleHourlyRateInput = (e, idx) => {
okay

2023-03-15 09:47 UTC, sanjibroy360 commented on app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
> +        : "15%",
Yes, I checked It will not break other components.
[https://www.loom.com/share/62ce80ddd275459a9fd65fcc123c28f0](https://www.loom.com/share/62ce80ddd275459a9fd65fcc123c28f0)

2023-03-15 10:05 UTC, sanjibroy360 commented on app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
> +export const customStyles = (isDesktopView, hideDropdownIndicator = false) => ({
Given that the component CustomAsyncSelect also uses the same styles and there we don't need to hide the indicator. If the default value of false for hideDropdownIndicator is removed from the `customStyles`, passing the hideDropdownIndicator value will become mandatory every time the customStyles is used. Otherwise, it'll throw an error.

2023-03-15 10:23 UTC, sanjibroy360 commented on app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
> +  const handleHourlyRateInput = (e, idx) => {
I have updated the variable name in the components related to adding a team member.

2023-03-15 10:31 UTC, sanjibroy360 commented on app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
> +    "absolute top-0.5 right-1 h-6 z-1 origin-0 bg-white p-2 text-base font-medium duration-300";
I think we don't need a separate variable as we are using these variables only once. I'll directly use the value.

2023-03-15 10:37 UTC, onkar-saeloun commented on app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
> +export const customStyles = (isDesktopView, hideDropdownIndicator = false) => ({
Please keep it no need to remove default value.

2023-03-15 10:39 UTC, onkar-saeloun commented on app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
> +    "absolute top-0.5 right-1 h-6 z-1 origin-0 bg-white p-2 text-base font-medium duration-300";
Please try to keep component free. Its okay if you want to assign them to variables and then use it but if it is not getting impacted by lifecycle then keep it outside.

2023-03-15 10:40 UTC, onkar-saeloun commented on app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
> +  const handleHourlyRateInput = (e, idx) => {
okay

2023-03-15 10:44 UTC, sanjibroy360 commented on app/javascript/src/components/Projects/Details/EditMembersListForm.tsx
> +    "absolute top-0.5 right-1 h-6 z-1 origin-0 bg-white p-2 text-base font-medium duration-300";
Okay Onkar.

2023-03-16 07:17 UTC, sanjibroy360 commented on app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
> +export const customStyles = (isDesktopView, hideDropdownIndicator = false) => ({
Done

2023-03-16 12:32 UTC, Shruti-Apte approved these changes
LGTM !!

2023-03-17 07:36 UTC, onkar-saeloun commented on app/javascript/src/common/CustomReactSelectStyle/Styles/index.ts
> +<<<<<<< HEAD
Please check this line/ try to run your project once. The comparison line of Head is there.

2023-03-17 07:37 UTC, onkar-saeloun requested changes
Please just remove the Github header line

2023-03-17 08:49 UTC, onkar-saeloun approved these changes
LGTM

2023-03-17 09:33 UTC, merged