Fix/sign in and sign up page UI issues
saeloun/miru-web pull request #1155
Opened 2023-03-20 11:11 UTC by sanjibroy360

## Notion card
[https://www.notion.so/saeloun/Signin-Signup-UI-Review-f6ec879d28824cbfb0868a83524ac685](https://www.notion.so/saeloun/Signin-Signup-UI-Review-f6ec879d28824cbfb0868a83524ac685)

## Summary
- Ensured that the gap between elements should be consistent.
- Update the UI of all error screens.
- Show validation errors only when the user tries to submit the form, not on blur.
- In mobile and iPad view we were not showing the Miru logo anywhere on the Sign-up and Sign-in page. I've added that as well.
- Ensured that the label and input-box's text should be aligned correctly.

## Preview
[https://www.loom.com/share/a702c7d2417f40ffaeaa52494cb91f7e](https://www.loom.com/share/a702c7d2417f40ffaeaa52494cb91f7e)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2023-03-20 12:59 UTC, prasanthchaduvula requested changes

2023-03-20 13:32 UTC, sanjibroy360 commented on app/javascript/src/components/Authentication/ForgotPassword/index.tsx
> +                        inputBoxClassName={`p-3.75 ${
Okay @prasanthchaduvula , I'll move the `inputBoxClassName` logic to `<InputField/>`. 

We are implementing the onChange function to clear validation errors as the user types. 
So now validation error messages will only be displayed when the user tries to submit the form(`onSubmit`) with invalid data and we'll clear those errors as the user types(`onChange`).

2023-03-20 14:01 UTC, prasanthchaduvula commented on app/javascript/src/components/Authentication/ForgotPassword/index.tsx
> +                        inputBoxClassName={`p-3.75 ${
Can you try adding this logic of `onChange` to `<InputField/>` itself?

2023-03-20 16:28 UTC, sanjibroy360 commented on app/javascript/src/components/Authentication/ForgotPassword/index.tsx
> +                        inputBoxClassName={`p-3.75 ${
Okay

2023-03-21 06:45 UTC, supriya3105 commented
@prasanthchaduvula Please review. Would like the fixes to be part of release 0.16.0.

2023-03-21 06:48 UTC, prasanthchaduvula commented
@sanjibroy360 all the changes completed?

2023-03-21 06:51 UTC, sanjibroy360 commented on app/javascript/src/components/Authentication/ForgotPassword/index.tsx
> +                        inputBoxClassName={`p-3.75 ${
Done

2023-03-21 06:57 UTC, sanjibroy360 commented
@prasanthchaduvula Two tasks remaining: update signup system specs and fix regex issue.

2023-03-21 07:00 UTC, prasanthchaduvula requested changes

2023-03-21 07:00 UTC, prasanthchaduvula commented on app/javascript/src/components/Authentication/ForgotPassword/index.tsx
> +                        hasError={errors.email && touched.email}
Please add 
`resetErrorOnChange`,
`hasError`,
`setFieldError={setFieldError}`
`setFieldValue={setFieldValue}`
as a default value to `<InputField/>`

2023-03-21 09:51 UTC, sanjibroy360 commented on app/javascript/src/components/Authentication/ForgotPassword/index.tsx
> +                        hasError={errors.email && touched.email}
@prasanthchaduvula , I'll set a default value of `true` for `resetErrorOnChange`. But we have to pass the following three props: `hasError, setFieldError, and setFieldValue`. 

Here `setFieldError` and `setFieldValue` are optional props and only need to be passed if we want to clear validation errors upon input change(when `resetErrorOnChange` is true).

2023-03-21 10:39 UTC, sanjibroy360 commented on app/javascript/src/components/Authentication/ForgotPassword/index.tsx
> +                        hasError={errors.email && touched.email}
Done

2023-03-21 11:02 UTC, prasanthchaduvula approved these changes

2023-03-21 12:20 UTC, apoorv1316 commented
@sanjibroy360 We are getting 2 toasts in case of an invalid email/password. And all errors are shown below their respective fields but if we add an invalid name then the error message for it is shown via toaster and the same for invalid email/password. We should handle it in a consistent manner. cc @supriya3105 . Also, get the UI reviewed by Akash once.
Loom: https://www.loom.com/share/c8ff9b331239479685341683089834b3

2023-03-21 14:29 UTC, sanjibroy360 commented
> @sanjibroy360 We are getting 2 toasts in case of an invalid email/password. And all errors are shown below their respective fields but if we add an invalid name then the error message for it is shown via toaster and the same for invalid email/password. We should handle it in a consistent manner. cc @supriya3105 . Also, get the UI reviewed by Akash once. Loom: https://www.loom.com/share/c8ff9b331239479685341683089834b3

@apoorv1316 I've resolved these 2 issues.

## Preview
[https://youtu.be/frGQmxIFS5w](https://youtu.be/frGQmxIFS5w)

2023-03-22 04:38 UTC, apoorv1316 commented
@sanjibroy360 We are getting 2 toasts on entering an email that doesn't exist in DB on forgot password page. Please fix it too.

2023-03-22 07:34 UTC, supriya3105 commented
@sanjibroy360 Please check why the tests are failing . 

@prasanthchaduvula Lets review again after Sanjib fixes the tests.

2023-03-22 08:14 UTC, sanjibroy360 commented
> @sanjibroy360 We are getting 2 toasts on entering an email that doesn't exist in DB on forgot password page. Please fix it too.

@apoorv1316 

> @sanjibroy360 We are getting 2 toasts on entering an email that doesn't exist in DB on forgot password page. Please fix it too.

Done 
cc: @apoorv1316

2023-03-22 10:55 UTC, sanjibroy360 commented
@prasanthchaduvula now all tests are passing here.

2023-03-22 11:02 UTC, prasanthchaduvula approved these changes

2023-03-22 11:10 UTC, merged