Fix: Bookeeper role bugs
saeloun/miru-web pull request #1159
Opened 2023-03-21 05:57 UTC by mayankagnihotri7

## Notion
[Notion Card](https://www.notion.so/saeloun/Backend-Bookeeper-role-bugs-e4d7cca09dd94036890b5e912f5e77af)

## Description
- Fixed the bug where the reports tab was not accessible to the user with the bookkeeper role.
- Fixed the bug which caused alert `toastr` to pop up on accessing the payments page.
- Removed the time tracking tab from the bookkeeper's navigation tab.
- Added payments and reports tab.

## Preview

https://user-images.githubusercontent.com/57438322/226528801-965a6a34-a089-4ec5-a49e-62ad61532791.mp4

2023-03-21 07:28 UTC, prasanthchaduvula requested changes

2023-03-21 07:28 UTC, prasanthchaduvula commented on spec/requests/internal_api/v1/payments/create_spec.rb
> -  context "when user is a book keeper" do
Why these specs got removed

2023-03-21 07:28 UTC, prasanthchaduvula commented on spec/requests/internal_api/v1/payments/new_spec.rb
> -  context "when user is a book keeper" do
ditto
Why these specs got removed

2023-03-21 07:28 UTC, prasanthchaduvula commented on spec/requests/internal_api/v1/reports/accounts_aging/index_spec.rb
> -  context "when user is a book keeper" do
Why these specs got removed

2023-03-21 07:28 UTC, prasanthchaduvula commented on spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
> -  context "when user is a book keeper" do
Why these specs got removed

2023-03-21 07:28 UTC, prasanthchaduvula commented on spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
> -    before do
Why these specs got removed

2023-03-21 07:28 UTC, prasanthchaduvula commented on spec/requests/internal_api/v1/reports/time_entry/index_spec.rb
> -      create(:employment, company:, user:)
ditto
Why did these specs got removed

2023-03-21 07:28 UTC, prasanthchaduvula commented on spec/requests/internal_api/v1/reports/time_entry/download_spec.rb
> -    before { sign_in book_keeper }
ditto
Why did these specs got removed

2023-03-21 07:28 UTC, prasanthchaduvula commented on app/javascript/src/components/Navbar/utils.tsx
> +const navBookKeeperOptions = [
instead of having different options array for different user roles, can't we keep the single array and add some key kind of role to the options object so that its easy to maintain instead of adding the same option object to all the arrays

2023-03-21 07:47 UTC, mayankagnihotri7 commented on spec/requests/internal_api/v1/payments/new_spec.rb
> -  context "when user is a book keeper" do
They were failing and it was rendered obsolete after the recent changes made according to the notion card. I'll add them back and modify the tests.

2023-03-21 07:47 UTC, mayankagnihotri7 commented on spec/requests/internal_api/v1/reports/accounts_aging/index_spec.rb
> -  context "when user is a book keeper" do
They were failing and it was rendered obsolete after the recent changes made according to the notion card. I'll add them back and modify the tests.

2023-03-21 07:47 UTC, mayankagnihotri7 commented on spec/requests/internal_api/v1/reports/client_revenue/index_spec.rb
> -  context "when user is a book keeper" do
They were failing and it was rendered obsolete after the recent changes made according to the notion card. I'll add them back and modify the tests.

2023-03-21 07:47 UTC, mayankagnihotri7 commented on spec/requests/internal_api/v1/reports/outstanding_overdue_invoices/index_spec.rb
> -    before do
They were failing and it was rendered obsolete after the recent changes made according to the notion card. I'll add them back and modify the tests.

2023-03-21 07:47 UTC, mayankagnihotri7 commented on spec/requests/internal_api/v1/reports/time_entry/index_spec.rb
> -      create(:employment, company:, user:)
They were failing and it was rendered obsolete after the recent changes made according to the notion card. I'll add them back and modify the tests.

2023-03-21 07:47 UTC, mayankagnihotri7 commented on spec/requests/internal_api/v1/reports/time_entry/download_spec.rb
> -    before { sign_in book_keeper }
They were failing and it was rendered obsolete after the recent changes made according to the notion card. I'll add them back and modify the tests.

2023-03-22 11:16 UTC, prasanthchaduvula approved these changes

2023-03-22 11:17 UTC, prasanthchaduvula commented
@apoorv1316 Please test this PR before merging as it handles the user roles and naviagtions

2023-03-24 14:45 UTC, supriya3105 commented
@apoorv1316 Please test .

2023-03-27 06:43 UTC, apoorv1316 commented
@mayankagnihotri7 Book-keeper is not able to access settings. I think he should be able to access his personal settings page. Also, he is able to access the invoices index page. If he is allowed to access the invoice index page then we should show the invoice tab for him. If not then we need to update the policy.
Loom: https://www.loom.com/share/04a390582b7e41bba54bd41556fee8e0
cc @supriya3105

2023-03-28 09:05 UTC, prasanthchaduvula commented
@mayankagnihotri7 Please fix the tests

2023-03-28 10:08 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've fixed the test cases. Please review.

2023-03-29 17:21 UTC, prasanthchaduvula approved these changes

2023-03-30 02:20 UTC, merged