Generate Invoice Page Mobile : section 2
saeloun/miru-web pull request #1170
Opened 2023-03-22 12:50 UTC by Shruti-Apte

### **Notion :**
Section 2
https://www.notion.so/saeloun/Mobile-Responsive-Generate-Invoice-Page-Invoice-Details-section-359a7ae203be40a1b8123bf8cedb37ec?pvs=4 
### **What :**
 - Line Items section of generate invoice page mobile view.
 - User can add line entry.
 - User can edit line entry.
 -  - User can delete line entry.
 - User can add multiple line entries. 
 
### **Why :**
- Requirement & Enhancement 
### **Preview :**
**Screenshots:**
<img width="545" alt="Screenshot 2023-03-22 at 6 18 06 PM" src="https://user-images.githubusercontent.com/72149587/226909591-9f2e6ccb-6c08-4314-8798-c5f66b633568.png">

<img width="663" alt="Screenshot 2023-03-21 at 5 51 38 PM" src="https://user-images.githubusercontent.com/72149587/226909051-b8eb44a2-6a8c-44f6-8e5e-9688d950a506.png">

<img width="547" alt="Screenshot 2023-03-21 at 5 51 55 PM" src="https://user-images.githubusercontent.com/72149587/226908951-5361a91b-2a65-4e32-9d60-f25fd368aeb1.png">

**Video:**
https://www.loom.com/share/bb1b8d98c4d842b08749ab1b4aff1ade
### **Todos** (for testing):
- Tested all basic workflows.
- Need to look into some validations once again (after merging with develop some validations are not working).

2023-03-23 11:36 UTC, prasanthchaduvula requested changes

2023-03-23 11:36 UTC, prasanthchaduvula commented on app/javascript/src/common/FormikFields/InputErrors/index.tsx
> +  ) : null;
Why do we want to return `null`

2023-03-23 11:36 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/InvoiceDetails.tsx
> +                readOnly={false}
You already `readOnly={false}` default value right

2023-03-23 11:39 UTC, prasanthchaduvula commented
@Shruti-Apte Record video and share it here - Please add more description to timesheet entries and add them in lint items

2023-03-30 14:29 UTC, Shruti-Apte commented
Closing this PR as section 3  PR (1193) has all the changes from this PR.

2023-03-30 14:29 UTC, closed without merging