Client email changes
saeloun/miru-web pull request #1183
Opened 2023-03-27 14:49 UTC by deepti-kakade

**Notion:**

https://www.notion.so/saeloun/Backend-Add-new-client-form-should-support-multiple-emails-d30681a5f0e94742a249de1950ada1f8

**Description:**

- Backend is allowing multiple emails for a client. 
- Saving emails as an array in the database.
- Replaced Ransack with Searchkick for the Client.
- Added Searchkick in the client model.
- Updated test cases.

**Screenshots:**

**Note:** Frontend changes are required. In this PR we handled backend changes.

2023-03-29 16:40 UTC, prasanthchaduvula requested changes

2023-03-29 16:40 UTC, prasanthchaduvula commented on app/services/clients/index_service.rb
> +        if params[:q].present?
Please make it into a query for more readability `params[:query]`

2023-03-31 08:42 UTC, prasanthchaduvula reviewed
Backend changes LGTM

2023-05-25 13:04 UTC, supriya3105 commented
@mayankagnihotri7 Copy the file changes in another PR and raise the PR assign to Shruti so that she can work on the front end changes.

2023-05-26 07:09 UTC, mayankagnihotri7 commented
Closing this PR. Raised a new one which includes the latest changes from the develop branch.

2023-05-26 07:09 UTC, closed without merging