Organisation settings profile
saeloun/miru-web pull request #1185
Opened 2023-03-28 05:27 UTC by onkar-saeloun

What- 
PR includes the design and integration of the organization settings profile page.

Why-
The new APIs and design needs to be integrated as new signup flow is completed

2023-03-29 16:15 UTC, prasanthchaduvula requested changes

2023-03-29 16:15 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +            dataCy="company-name"
not required any more as we are not using cypress any more

2023-03-29 16:15 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +            dataCy="company-name"
Remove `dataCy` key from all the inputs and buttons from this PR file changes

2023-03-30 05:17 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +            dataCy="company-name"
Okay removing it

2023-03-30 06:37 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +import PhoneInput from "react-phone-number-input";
Done

2023-03-30 06:38 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +            dataCy="company-name"
Done

2023-03-30 06:41 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +import PhoneInput from "react-phone-number-input";
@prasanthchaduvula getting formatting issue if declared below the react-phone-input

2023-03-31 08:55 UTC, prasanthchaduvula requested changes

2023-03-31 08:55 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Layout.tsx
> +                firstName={settingsStates.profileSettings?.firstName}
Please destructure these values

2023-03-31 08:55 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Layout.tsx
> +                lastName={settingsStates.profileSettings?.lastName}
ditto
Please destructure these values

2023-03-31 08:55 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +            value={orgDetails.companyAddr.addressLine1}
can we destructure these values and store them

2023-03-31 08:55 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +            value={orgDetails.companyAddr.addressLine2}
ditto
can we destructure these values and store them

2023-03-31 08:55 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +              value={orgDetails.companyAddr.country}
can we destructure these values and store them

2023-03-31 08:55 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +                      label: orgDetails.companyAddr.state.label,
ditto
can we destructure these values and store them
Please make this change across file

2023-04-03 08:47 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Layout.tsx
> +                firstName={settingsStates.profileSettings?.firstName}
done

2023-04-03 08:47 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Layout.tsx
> +                lastName={settingsStates.profileSettings?.lastName}
Done

2023-04-03 08:47 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +            value={orgDetails.companyAddr.addressLine1}
Done

2023-04-03 08:47 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +            value={orgDetails.companyAddr.addressLine2}
Done

2023-04-03 08:47 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/Edit/StaticPage.tsx
> +              value={orgDetails.companyAddr.country}
Done

2023-04-04 03:17 UTC, prasanthchaduvula approved these changes

2023-04-04 10:48 UTC, merged