added image requirement
saeloun/miru-web pull request #1186
Opened 2023-03-28 09:37 UTC by Ankita012

**Notion link** 
https://www.notion.so/Add-image-requirements-to-the-add-edit-client-window-for-client-logo-26a5746060764e639aea31f590db4b26

**Summary** 
Added image requirement while uploading client logo image in add/edit client modal

**Preview** 
<img width="1792" alt="Screenshot 2023-03-28 at 3 11 05 PM" src="https://user-images.githubusercontent.com/22776061/228196301-5968bfb3-07c9-49fc-aeb2-4edccec20cd4.png">
<img width="1792" alt="Screenshot 2023-03-28 at 3 09 24 PM" src="https://user-images.githubusercontent.com/22776061/228196249-7e30c80d-01f3-4016-9f25-940352017ee9.png">

2023-03-29 08:07 UTC, apoorv1316 commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +const deleteImage = require("../../../../../assets/images/redDelete.svg");
@Ankita012 Please add the svg to miruIcons and then import from there. Refactor the required svgs also in the same way.

2023-03-29 11:31 UTC, apoorv1316 commented on app/javascript/src/miruIcons/index.ts
>  const edit_image_button = require("../../../assets/images/edit_image_button.svg");
@Ankita012 edit button is already added in this file. Please remove your variable and use that is already defined.

2023-03-29 17:04 UTC, prasanthchaduvula requested changes

2023-03-29 17:04 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
>  import { i18n } from "../../../i18n";
Add `i18n` to alias and import it

2023-04-04 03:21 UTC, prasanthchaduvula approved these changes

2023-04-04 09:29 UTC, merged