Team member modal bugs
saeloun/miru-web pull request #1201
Opened 2023-03-30 10:49 UTC by Shruti-Apte

### **Notion :**
https://www.notion.so/saeloun/Update-the-UI-for-Add-Team-members-modal-on-project-details-page-3964466aada34ef189fd8f4aac6881ee?pvs=4
### **What :**
- Added usekeyPress hook to handle all key events.
- The modal is now closing on hitting the ‘esc’ key. 
- After adding a team member the now cursor is moving automatically to the rate field.
- Disabled add team member button if no members are remaining to add.
 
### **Why :**
- Added useKeyPress hook as a helper to save time, now we just need to pass event name and actions to perform.
- Bug fixes
  
### **Preview :**

Before:
https://www.loom.com/share/315f83ea1355489594a220cac00942ba

After:
https://www.loom.com/share/ac3846e37f5c4e8b94d9b1de39e5e92a

### **Todos** (for testing):
- Checked add/remove team member flow.
- Checked if modal is closing on esc key.
- Checked if after adding a team member the now cursor is moving automatically to the rate field.

2023-03-30 11:00 UTC, apoorv1316 commented
@Shruti-Apte Isn't it better to hide/remove "add another team member" button instead of disabling it? cc @supriya3105

2023-03-30 11:03 UTC, apoorv1316 approved these changes

2023-03-30 11:55 UTC, prasanthchaduvula requested changes

2023-03-31 11:38 UTC, prasanthchaduvula approved these changes

2023-03-31 11:39 UTC, merged