Send email to owner and admin once payment is successful
saeloun/miru-web pull request #1204
Opened 2023-03-31 15:24 UTC by mayankagnihotri7

## Notion Card
[Notion Card](https://www.notion.so/saeloun/Backend-Once-payment-is-received-from-client-through-Stripe-send-email-notification-to-admin-and-o-052ee4b6b68d4615914ca09122dafda3)

## Description
Send an email to the owner and admin of the company once the payment is successful.

2023-04-05 05:49 UTC, prasanthchaduvula requested changes

2023-04-05 05:49 UTC, prasanthchaduvula commented on app/controllers/invoices/payments_controller.rb
> +      if @invoice.paid?
Move this logic to a presenter and user render json instead of flash messages

2023-04-05 11:40 UTC, vipulnsward commented on app/controllers/invoices/payments_controller.rb
> +    def email_message
This should not be here, it can be built in mailer

2023-04-05 11:40 UTC, vipulnsward commented on app/controllers/invoices/payments_controller.rb
> +          recipients: invoice_company.users.with_role([:admin, :owner], invoice_company).pluck(:email)
This too can be done in mailer

2023-04-07 07:38 UTC, mayankagnihotri7 commented
@vipulnsward @prasanthchaduvula I've made the requested changes. Please review.

2023-04-11 16:47 UTC, vipulnsward commented
@apoorv1316 please verify

2023-04-12 10:37 UTC, apoorv1316 requested changes
@mayankagnihotri7 I am not able to get to pyamnets success page.Please check loom https://www.loom.com/share/e00f8e5f284846478b5a46df3da84f2e

2023-04-12 11:35 UTC, mayankagnihotri7 commented
@apoorv1316 The reason for that is that the payment intent is not present when you directly access the page. For testing the payment success mail you need to comment out the code checking the payment intent from the payments controller in the internal API folder.

2023-04-12 12:03 UTC, apoorv1316 approved these changes

2023-04-14 13:18 UTC, prasanthchaduvula requested changes

2023-04-14 13:18 UTC, prasanthchaduvula commented on app/javascript/src/components/payments/Success/index.tsx
> +      setError(e.response.data.error);
use try-catch here

2023-04-14 14:32 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2023-04-14 15:27 UTC, prasanthchaduvula approved these changes

2023-04-14 15:27 UTC, merged