New address changes with client
saeloun/miru-web pull request #1218
Opened 2023-04-05 05:50 UTC by onkar-saeloun

What-
PR includes new address field changes on adding a new client and updating a client.

Why-
The backend implementation of new address fields was breaking the UI.

Loom-
https://www.loom.com/share/8f5f4e63870a42809c6fcfffd01911a0

2023-04-06 14:42 UTC, prasanthchaduvula requested changes

2023-04-06 14:42 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +  phone: Yup.string()
Move the client validation schema to another file

2023-04-06 14:42 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +  address1: client?.address?.address_line_1 || "",
Move this initial values to the schema file
kind of utils

2023-04-10 10:10 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +  address1: client?.address?.address_line_1 || "",
Done

2023-04-10 10:10 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +  phone: Yup.string()
Done

2023-04-10 10:34 UTC, prasanthchaduvula requested changes

2023-04-10 10:34 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/NewClient.tsx
> +
@onkar-saeloun Please extract the common code of `EditClient` and `NewClient`components like form and submit methods to `ClientForm`

2023-04-11 04:46 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Modals/NewClient.tsx
> +
ok

2023-04-11 09:16 UTC, prasanthchaduvula requested changes

2023-04-11 09:16 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/EditClient.tsx
>    const [clientLogoUrl, setClientLogoUrl] = useState<string>(client.logo);
If possible please move the logo related common codebase to client form from edit client and new client components

2023-04-11 09:16 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/schema.ts
> +import { Country } from "country-state-city";
Rename this to `formValidationSchema`

2023-04-11 09:27 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Modals/schema.ts
> +import { Country } from "country-state-city";
Okay

2023-04-11 09:28 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Modals/utils.ts
> +export const formatFormData = (
same as above. If we need to reuse the same form anywhere else then we can make use of client form, keeping the form submission step in it will make it work for only in this component

2023-04-11 09:31 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Modals/schema.ts
> +import { Country } from "country-state-city";
Done

2023-04-11 12:15 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/utils.ts
> +export const formatFormData = (
We won't use the same form anywhere. Please move it to the client form so that it's easy to maintain.

2023-04-13 05:15 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Modals/utils.ts
> +export const formatFormData = (
@prasanthchaduvula comment resolved please have a look

2023-04-13 06:46 UTC, prasanthchaduvula requested changes

2023-04-13 06:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +        document.location.reload();
Fetching the updated list of clients from the API after creating a new client is generally a better approach than reloading the page using document.location.reload(). Reloading the page causes the entire page to refresh, which can be disruptive to the user experience and cause unnecessary load times.

On the other hand, fetching the updated list of clients from the API is faster and more efficient because it only retrieves the data that has changed. Additionally, fetching the updated data allows for a more seamless user experience, as the user does not need to wait for the page to reload to see the new client in the list.

**otherwise**

You can simply update the client list by using the response from create mclient or edit the client and appending it to the list state.

2023-04-13 06:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/utils.ts
> +  formData.append("client[name]", values.name);
Please make this change
https://github.com/saeloun/miru-web/pull/1218/files#r1162730052

2023-04-13 08:35 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Modals/utils.ts
> +  formData.append("client[name]", values.name);
@prasanthchaduvula didn't get what's the issue? keeping it in different file is good thing right? Otherwise component will become complex

2023-04-13 08:38 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/utils.ts
> +  formData.append("client[name]", values.name);
The formData is used in client form for both create and edit. It's better to move the logic to the same component. It's easy for the developers to read, maintain and debug.

2023-04-13 08:44 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/utils.ts
> +  formData.append("client[name]", values.name);
Lets keep it. In future if we feel its hard to debug we will make the change

2023-04-13 08:47 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +        document.location.reload();
Yah removed document.location.reload(). Managed the API with state change

2023-04-13 08:48 UTC, onkar-saeloun commented
@prasanthchaduvula Done with the change.

2023-04-13 08:56 UTC, prasanthchaduvula approved these changes

2023-04-17 12:59 UTC, merged