Add mobile responsive clients list page
saeloun/miru-web pull request #1234
Opened 2023-04-10 13:45 UTC by mayankagnihotri7

## Notion Card
[Notion Card](https://www.notion.so/saeloun/Mobile-Responsive-Clients-list-page-aad6ea8bdf474861a14a537b88a5ede6)

## Description
- Added responsive design for the clients' list page.

## Preview
<img width="432" alt="Screenshot 2023-04-10 at 7 14 59 PM" src="https://user-images.githubusercontent.com/57438322/230913210-958a414d-864d-43db-adc8-2c3399c414f9.png">

2023-04-11 07:03 UTC, onkar-saeloun approved these changes

2023-04-11 09:24 UTC, prasanthchaduvula requested changes

2023-04-11 09:24 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/List/index.tsx
> +import { DotsThreeVertical } from "phosphor-react";
Use it from `MiruIcons`

2023-04-13 02:01 UTC, prasanthchaduvula approved these changes

2023-04-13 02:02 UTC, merged