mobile view project list page
saeloun/miru-web pull request #1235
Opened 2023-04-10 15:02 UTC by Shruti-Apte

### **Notion :**
https://www.notion.so/saeloun/Mobile-Responsive-Projects-List-page-bc3f85d80a2c48368d3862a89e095bb6?pvs=4
### **What :**
- Responsive project list page
### **Why :**
- Enhancement and requirement.
### **Preview :**
<img width="532" alt="Screenshot 2023-04-10 at 8 29 18 PM" src="https://user-images.githubusercontent.com/72149587/230927803-6f7852fe-8bdb-4250-ba4a-9e7e9efebf82.png">

<img width="531" alt="Screenshot 2023-04-10 at 8 29 29 PM" src="https://user-images.githubusercontent.com/72149587/230927833-d261c536-525e-48ea-a7dc-ac68fc95914c.png">

### **Todos** (for testing):
- Need to test with multiple clients and projects.

2023-04-11 08:41 UTC, prasanthchaduvula requested changes

2023-04-11 08:41 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/List/Mobile/AddEditProjectMobile.tsx
> +const AddEditProjectMobile = ({
Can we rename it to `ProjectMobileForm`

2023-04-11 08:41 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/List/Mobile/AddEditProjectMobile.tsx
> +      Logger.error(error);
Don't use Logger

2023-04-11 08:41 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/List/Mobile/AddEditProjectMobile.tsx
> +        Logger.error(error);
Ditto
Don't use Logger

2023-04-11 08:41 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/List/Mobile/AddEditProjectMobile.tsx
> +    window.location.reload();
Fetching the updated list of projects from the API after creating a new project is generally a better approach than reloading the page using window.location.reload(). Reloading the page causes the entire page to refresh, which can be disruptive to the user experience and cause unnecessary load times.

On the other hand, fetching the updated list of projects from the API is faster and more efficient because it only retrieves the data that has changed. Additionally, fetching the updated data allows for a more seamless user experience, as the user does not need to wait for the page to reload to see the new project in the list.

You can simply updated the project list by using response from create project or by fetching the project list again

2023-04-11 08:59 UTC, Shruti-Apte commented on app/javascript/src/components/Projects/List/Mobile/AddEditProjectMobile.tsx
> +const AddEditProjectMobile = ({
`ProjectMobileForm ` doesn’t define what this form does, It is confusing. 
We have multiple pages like the list page, the details page(future scope).
How about `AddEditProjectMobileForm`?

2023-04-12 01:51 UTC, prasanthchaduvula requested changes

2023-04-12 01:51 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/List/Mobile/AddEditProjectMobileForm.tsx
> +import React, { useState, useEffect } from "react";
Please rename the component to `ProjectForm`

2023-04-12 01:51 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/List/Mobile/AddEditProjectMobileForm.tsx
> +      // error logic already handled in api.ts
This is wrong. If there is nothing to handle in a catch block then using a try-catch block doesn't make any sense. I think already api.ts already handles errors. Please verify and move away from try-catch as they are empty.

2023-04-12 01:51 UTC, prasanthchaduvula commented
As provided review comments earlier please resolve all the comments and reassign.

2023-04-13 01:56 UTC, prasanthchaduvula approved these changes

2023-04-13 01:57 UTC, merged