Search filter enhancement on invoice list page.
saeloun/miru-web pull request #1237
Opened 2023-04-11 14:08 UTC by Shruti-Apte

### **Notion :**
NA
### **What :**
- Apply the search filter, navigate to any invoice come back to the invoice list page. Now the search filter is still applied to the list of invoices.
 
### **Why :**
- Earlier we removed the search string if we navigated to the other page.
### **Preview :**
https://www.loom.com/share/1eb389a69a2b42c5a3d824bad8b09602

### **Todos** (for testing):
- Tested if the search filter is still intact after coming back.

2023-04-11 14:17 UTC, prasanthchaduvula requested changes

2023-04-12 04:50 UTC, Shruti-Apte commented on app/javascript/src/components/Invoices/Invoice/Header.tsx
> +      <BackButton href="javascript:history.back()" />
No need we are using `Link ` tag in backButton component.

2023-04-13 02:00 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/Header.tsx
> +      <BackButton href="javascript:history.back()" />
what if the admin clicks on the edit button and returns back to invoices and still using react method is better

2023-04-18 12:31 UTC, prasanthchaduvula approved these changes

2023-04-18 12:32 UTC, merged