Responsive page for client details
saeloun/miru-web pull request #1238
Opened 2023-04-12 05:48 UTC by mayankagnihotri7

2023-04-12 10:33 UTC, supriya3105 commented
@mayankagnihotri7 The screenshots of client details page do not match with the designs in Figma. In the actual designs there is just the table and it does not have the top section with the total hours. 
Please check 
https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?node-id=13279-201455&t=ppTgTuA0R871PFFt-4

2023-04-12 11:09 UTC, mayankagnihotri7 commented
@supriya3105 If I make the table then the amount section will also be done in this PR. I did not do it because you had mentioned in the ticket that the amount section is out of scope for this one. Shall I remove it or add the table.?

2023-04-13 02:07 UTC, prasanthchaduvula requested changes

2023-04-13 02:07 UTC, prasanthchaduvula commented on package.json
> +    "react-html-parser": "^2.0.2",
Can you check for an alternate package? This package is not maintained

2023-04-13 05:28 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've replaced the usage of that package. Please review.

2023-04-13 06:17 UTC, prasanthchaduvula requested changes

2023-04-13 06:17 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/MobileMenu.tsx
> +interface IProps {
Move Iprops towards the end of file. So that developers can focus on component codebase

2023-04-13 07:53 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2023-04-13 08:18 UTC, prasanthchaduvula approved these changes

2023-04-13 08:24 UTC, merged