Add client responsive form
saeloun/miru-web pull request #1245
Opened 2023-04-14 08:57 UTC by mayankagnihotri7

2023-04-20 07:27 UTC, prasanthchaduvula approved these changes

2023-04-20 11:59 UTC, apoorv1316 requested changes
@mayankagnihotri7 Remove the "drag logo" text from the image upload. We don't have functionality for it. Also, change the accepted formats text and size supported. I have attached the screenshot from the web. Make the same changes here
<img width="372" alt="Screenshot 2023-04-20 at 5 28 16 PM" src="https://user-images.githubusercontent.com/18750194/233359218-4d9742ec-5f41-45d7-919d-32ee05363895.png">

2023-04-21 05:55 UTC, mayankagnihotri7 commented
@apoorv1316 I've made the requested changes. Please review.

2023-04-21 10:05 UTC, apoorv1316 approved these changes

2023-04-21 12:34 UTC, merged