Add & edit project bug fix : mobile view
saeloun/miru-web pull request #1255
Opened 2023-04-19 09:51 UTC by Shruti-Apte

### **Notion :**
https://www.notion.so/saeloun/Mobile-view-Fix-add-edit-project-9810a29a4efd43e6b62c8215ec2a1879?pvs=4
### **What :**
- Fixed add and edit project on the project list page mobile view.
### **Why :**
-  Add and edit project was broken on the project list page mobile view.
### **Preview :**
https://www.loom.com/share/46287f6292484ede88f5866b1123e808
### **Todos** (for testing):
- Tested all workflows on the project module.

2023-04-19 12:22 UTC, apoorv1316 commented
@Shruti-Apte Remove the option to edit and delete project from mobile view for employees and book_keeeper role
<img width="405" alt="Screenshot 2023-04-19 at 5 52 24 PM" src="https://user-images.githubusercontent.com/18750194/233073470-9b0ed5dd-978c-4c2c-8282-c50e6a018b03.png">

2023-04-19 13:13 UTC, prasanthchaduvula requested changes

2023-04-19 13:13 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/List/Mobile/ProjectForm.tsx
> +      data.project.client_id &&
instead of writing `data.project.client_id &&` we can directly use `client_id`, `name` and `billable` from project itself.

2023-04-19 13:13 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/List/Mobile/ProjectForm.tsx
> +      data.project.client_id &&
ditto
instead of writing data.project.client_id && we can directly use client_id, name and billable from project itself.

2023-04-19 13:13 UTC, prasanthchaduvula commented on app/javascript/src/helpers/hhmmParser.ts
> +export const minToHHMM = duration => {
Any reason the type checking got removed

2023-04-20 06:03 UTC, Shruti-Apte commented on app/javascript/src/helpers/hhmmParser.ts
> +export const minToHHMM = duration => {
so that we can use the parseInt() function, 
but will update parseInt() func with Number().

2023-04-20 06:06 UTC, Shruti-Apte commented on app/javascript/src/components/Projects/List/Mobile/ProjectForm.tsx
> +      data.project.client_id &&
These are the updated values, can not use from the project.

2023-04-20 11:51 UTC, apoorv1316 approved these changes

2023-04-21 04:16 UTC, prasanthchaduvula approved these changes

2023-04-21 05:37 UTC, merged