invoice list more options Bugs
saeloun/miru-web pull request #1259
Opened 2023-04-21 12:17 UTC by Shruti-Apte

### **Notion :**
NA
### **What :**
- More options updated on the invoice list page mobile view.
### **Why :**
- Previously it was linked to desktop modals.
### **Preview :**
<img width="485" alt="Screenshot 2023-04-21 at 5 43 24 PM" src="https://user-images.githubusercontent.com/72149587/233632974-506c0bc3-d5a5-42c4-94ef-386fb3fafd05.png">

### **Todos** (for testing):
- Needs to be tested thoroughly.

2023-04-21 12:41 UTC, prasanthchaduvula requested changes

2023-04-21 12:41 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Edit/index.tsx
> +              clientList={invoiceDetails.companyClientList}
destructure `invoiceDetails`

2023-04-21 12:41 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Generate/MobileView/Container/InvoicePreview/index.tsx
> +      currency={currency || invoiceDetails.companyDetails.currency}
destructure `invoiceDetails`

2023-04-21 12:41 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/InvoiceDetails.tsx
> +                      invoiceDetails.clientList
destructure `invoiceDetails`

2023-04-21 12:41 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Generate/MobileView/Header.tsx
> +      navigate(-1);
I hope the user wont navigate to any other screen from edit. If not then this back button wont work properly

2023-04-24 05:57 UTC, Shruti-Apte commented on app/javascript/src/components/Invoices/Edit/index.tsx
> +              clientList={invoiceDetails.companyClientList}
cannot destructure `invoicedetails ` on this page, as the state names and field names from `invoicedetails` objects are the same.

2023-04-24 05:58 UTC, Shruti-Apte commented on app/javascript/src/components/Invoices/Generate/MobileView/Header.tsx
> +      navigate(-1);
Handled the other conditions.

2023-04-24 06:39 UTC, prasanthchaduvula approved these changes

2023-04-24 07:28 UTC, merged