Once payment is received from client and invoice is marked as paid on Miru, send a payment receipt to the client
saeloun/miru-web pull request #1289
Opened 2023-05-05 08:49 UTC by mayankagnihotri7

2023-05-09 10:26 UTC, prasanthchaduvula requested changes

2023-05-09 10:26 UTC, prasanthchaduvula commented on app/controllers/internal_api/v1/invoices/payments_controller.rb
> +      PaymentMailer.with(
Here we are sending the without even checking whether the invoice is paid. what if the `InvoicePayment::StripePaymentInten` process fails? We have to send the mail to the client if the invoice is paid or marked as paid right?

2023-05-10 08:16 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2023-05-10 10:59 UTC, prasanthchaduvula approved these changes

2023-05-10 11:00 UTC, merged