Design client list page amount section and resolve horizontal scrolling issue in client list table
saeloun/miru-web pull request #1291
Opened 2023-05-05 11:19 UTC by sanjibroy360

2023-05-05 12:04 UTC, prasanthchaduvula requested changes

2023-05-05 12:04 UTC, prasanthchaduvula commented on app/javascript/src/common/AmountBox/MobileAmountBox.tsx
> +import { minToHHMM } from "../../helpers/hhmmParser";
Directly import from helpers `import { minToHHMM } from "helpers";`

2023-05-05 12:04 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/List/index.tsx
> +  const formattedOverdueAmount =
destructure `overdueOutstandingAmount` with nullish operator

2023-05-05 12:32 UTC, sanjibroy360 commented on app/javascript/src/common/AmountBox/MobileAmountBox.tsx
> +import { minToHHMM } from "../../helpers/hhmmParser";
Done ✅

2023-05-05 12:32 UTC, sanjibroy360 commented on app/javascript/src/components/Clients/List/index.tsx
> +  const formattedOverdueAmount =
Done ✅ 

cc: @prasanthchaduvula

2023-05-08 05:17 UTC, prasanthchaduvula approved these changes

2023-05-08 05:17 UTC, merged