Sign up password field criteria
saeloun/miru-web pull request #1307
Opened 2023-05-11 07:36 UTC by Shruti-Apte

### **Notion :**
- https://www.notion.so/saeloun/Signin-Signup-review-mobile-fc999aac28374cb0921d200822fdf718?pvs=4
- https://www.notion.so/saeloun/Mobile-Fix-the-spacing-b-w-logo-and-text-on-sign-in-page-d8dda2a6aa3543c7931dd5d517199f33?pvs=4
### **What :**
- Password field criteria added and conditions added for error field.
- Sign In mobile view page spacing fixed between logo and welcome back text.
### **Why :**
- User should know the password criteria beforehand
- We were showing same error for password and confirm password field (bad UI/UX)  
- Too much space between logo and welcome back text.
### **Preview :**
Sign In page before:
<img width="432" alt="Screenshot 2023-05-11 at 1 04 03 PM" src="https://github.com/saeloun/miru-web/assets/72149587/c6939543-9572-4e3d-90d1-86cf3d64f124">

Sign In page After:
<img width="463" alt="Screenshot 2023-05-11 at 12 37 50 PM" src="https://github.com/saeloun/miru-web/assets/72149587/1c8ba007-8327-4300-b301-3c010c3cfc4e">

Signup page:
Desktop:
<img width="761" alt="Screenshot 2023-05-11 at 12 50 19 PM" src="https://github.com/saeloun/miru-web/assets/72149587/eedc3f30-ec5c-40ae-826c-fbe96de9a8a9">

<img width="853" alt="Screenshot 2023-05-11 at 1 05 43 PM" src="https://github.com/saeloun/miru-web/assets/72149587/e4a31ff8-d32a-44af-a8ad-43ee0954c4dd">

Mobile:
<img width="468" alt="Screenshot 2023-05-11 at 12 38 17 PM" src="https://github.com/saeloun/miru-web/assets/72149587/974f4ff2-31b4-4afe-8d35-701e06a0cfff">

<img width="399" alt="Screenshot 2023-05-11 at 12 49 42 PM" src="https://github.com/saeloun/miru-web/assets/72149587/e9cb94ae-3c75-4108-ab0d-d4e35f8c3d91">

### **Todos** (for testing):

2023-05-12 11:12 UTC, prasanthchaduvula requested changes

2023-05-12 11:12 UTC, prasanthchaduvula commented on app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
> +                      marginBottom="mb-2"
Use classnames and provide the tailwind classes to override the inpux styles

2023-05-12 12:15 UTC, Shruti-Apte commented on app/javascript/src/components/Authentication/SignUp/SignUpForm.tsx
> +                      marginBottom="mb-2"
If the new value that we provide to override the default value is smaller than default value, then it won’t work even with the `classnames`
e.g: If the default value is `mb-6` and we want to override it with `mb-2`, then it won’t work.

That’s why I added different `marginBottom`

2023-05-13 02:28 UTC, prasanthchaduvula commented
@Shruti-Apte Always the end class names will override the previous ones

2023-05-15 04:19 UTC, Shruti-Apte commented
> @Shruti-Apte Always the end class names will override the previous ones

Not in case of smaller values.

2023-05-15 06:11 UTC, prasanthchaduvula commented
@Shruti-Apte we can resolve the classNames in another PR

2023-05-15 06:11 UTC, prasanthchaduvula approved these changes

2023-05-15 06:11 UTC, merged