Fix: Application breaking when pay button was clicked
saeloun/miru-web pull request #1325
Opened 2023-05-17 10:02 UTC by mayankagnihotri7

2023-06-16 11:04 UTC, prasanthchaduvula requested changes

2023-06-16 11:04 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Edit/index.tsx
> +      !showConnectPaymentDialog
can' we write like this `selectedClient && invoiceNumber && !showConnectPaymentDialog`

2023-06-16 11:04 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Generate/index.tsx
> +      Logger.log("ERROR!");
ditto

2023-06-16 11:04 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/InvoiceActions.tsx
> +          if (!isStripeEnabled) {
it's the reverse of ternary. Please use proper ternary with true and false conditions instead of false and true

2023-06-16 11:04 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/MobileView/index.tsx
> +                if (!isStripeEnabled) {
ditto

2023-06-16 11:04 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/MoreOptions.tsx
> +              if (!isStripeEnabled) {
ditto

2023-06-19 09:44 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2023-06-20 05:42 UTC, prasanthchaduvula commented on app/javascript/src/components/InvoiceEmail/Header.tsx
> +              if (invoice.status != "paid" && !isStripeConnected) {
```
if (invoice.status != "paid") {
    if (isStripeConnected) {
       window.location.href = stripeUrl;
        } else {
        setIsInvoiceEmail(true);
        setShowConnectPaymentDialog(true);
    }
 }
```

2023-06-20 12:07 UTC, prasanthchaduvula requested changes

2023-06-20 12:07 UTC, prasanthchaduvula commented on app/javascript/src/components/InvoiceEmail/Header.tsx
> +Header.propTypes = {
use typescript interface

2023-06-20 12:07 UTC, prasanthchaduvula commented on app/javascript/src/components/InvoiceEmail/index.tsx
> +import Toastr from "common/Toastr";
use toastr from `StyledComponents`

2023-06-20 12:07 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/index.tsx
> +      Logger.log("ERROR!");
Please don't use` logger`. Implement this in all the file changes in this PR

2023-06-20 12:07 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/MoreOptions.tsx
> +              if (!isStripeEnabled) {
if should check for truthy value.

2023-06-20 12:07 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/index.tsx
> +      Logger.log("ERROR!");
ditto

2023-06-20 12:07 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/common/InvoiceForm/Header/index.tsx
> +            if (!isStripeEnabled) {
ditto

2023-06-20 12:07 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/popups/ConnectPaymentGateway.tsx
> +      Logger.log(error);
ditto

2023-06-21 09:42 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2023-06-21 12:18 UTC, prasanthchaduvula requested changes

2023-06-21 12:24 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2023-06-22 06:30 UTC, apoorv1316 requested changes
@mayankagnihotri7 Please fix this.
https://www.loom.com/share/029b76aae81b4a1b8ef79c950f973300

2023-06-23 08:40 UTC, mayankagnihotri7 commented
@apoorv1316 I've made the requested changes. Please review.

2023-06-26 04:48 UTC, apoorv1316 approved these changes

2023-06-26 04:49 UTC, merged