Multiple emails on add client
saeloun/miru-web pull request #1347
Opened 2023-05-30 05:01 UTC by Shruti-Apte

### **Notion :**
https://www.notion.so/saeloun/Frontend-Integration-Add-new-client-form-should-support-multiple-emails-a174bc5f85644ed5b0195e30028c752a?pvs=4

### **What :**
- Add new client and edit new client modals are now supporting multiple client emails.
- This PR contains backend changes from mayank's PR as well as frontend changes
.### **Why :**
- Requirement 
- It is very possible that user might want to add multiple emails when adding a new client
### **Preview :**
<img width="1440" alt="Screenshot 2023-05-30 at 10 10 08 AM" src="https://github.com/saeloun/miru-web/assets/72149587/ac49ecca-d07e-4fdb-be8b-7955929bed82">

<img width="912" alt="Screenshot 2023-05-30 at 10 26 10 AM" src="https://github.com/saeloun/miru-web/assets/72149587/711fd30e-b972-485c-9cc5-862a3de5e730">//github.com/saeloun/miru-web/assets/72149587/9ad2496d-e8b5-4bb2-a8a9-d7259513590d">

<img width="953" alt="Screenshot 2023-05-30 at 10 28 23 AM" src="https://github.com/saeloun/miru-web/assets/72149587/fba2c6e5-75dc-42ba-9098-a7ebebc4ac69">
<img width="813" alt="Screenshot 2023-05-30 at 10 28 37 AM" src="https://github.com/saeloun/miru-web/assets/72149587/13b6829b-8232-4034-84a6-c09bae48f3cc">

### **Todos** (for testing):

2023-06-02 08:40 UTC, prasanthchaduvula requested changes

2023-06-02 08:40 UTC, prasanthchaduvula commented on db/migrate/20230526061908_remove_client_email.rb
> +    safety_assured { remove_column :clients, :email }
@mayankagnihotri7 let's keep this column for some days. OWe can remove this column once we have working functionality for multiple client emails on the production app

2023-06-02 08:40 UTC, prasanthchaduvula commented on db/migrate/20230526062007_rename_client_emails_to_email.rb
> +    safety_assured { rename_column :clients, :emails, :email }
@mayankagnihotri7  No need for this migration, client emails as column name good enough

2023-06-02 08:43 UTC, prasanthchaduvula requested changes

2023-06-02 08:43 UTC, prasanthchaduvula commented on db/migrate/20230526061821_copy_client_email_to_emails_column.rb
> +      client.update(emails: client.email) if client.email.present?
Instead of update, use the update_column

2023-06-06 08:32 UTC, mayankagnihotri7 commented on db/migrate/20230526061821_copy_client_email_to_emails_column.rb
> +      client.update(emails: client.email) if client.email.present?
Causes error while updating if `update_column` is used.

2023-06-06 17:11 UTC, apoorv1316 commented
@Shruti-Apte Please add system specs for it.

2023-06-09 11:40 UTC, prasanthchaduvula commented on db/migrate/20230526061821_copy_client_email_to_emails_column.rb
> +      client.update(emails: client.email) if client.email.present?
what is the error

2023-06-12 08:15 UTC, prasanthchaduvula commented
until we implement client authentication flow, this PR is on hold

2023-07-25 05:23 UTC, prasanthchaduvula commented
Changes got implemented #1429, #1412 and #1378

2023-07-25 05:23 UTC, closed without merging