Cities not loading bug fixed
saeloun/miru-web pull request #1353
Opened 2023-05-31 09:49 UTC by Shruti-Apte

### **Notion :**
https://www.notion.so/saeloun/The-cities-list-loading-only-when-the-user-starts-typing-ccd736741ce741fbb3a0b6682694d7e0?pvs=4

### **What :**
- Cities not loading bug fixed
### **Why :**
- When we click on city dropdown the city list should be displayed
### **Preview :**
Before:
<img width="980" alt="Screenshot 2023-05-31 at 3 18 58 PM" src="https://github.com/saeloun/miru-web/assets/72149587/b23e9e32-47cd-4aff-8b00-da695a1c3285">

After:
<img width="855" alt="Screenshot 2023-05-31 at 3 18 05 PM" src="https://github.com/saeloun/miru-web/assets/72149587/429fd239-f84f-4826-b5fb-44bf1848db83">

### **Todos** (for testing):
Tested if cities are loading on selecting the city field, or changing the state field.

2023-05-31 11:13 UTC, apoorv1316 commented
@Shruti-Apte The same fix needs to be done on the team details page, while creating a new company and editing it.

2023-06-02 04:49 UTC, apoorv1316 commented
> @Shruti-Apte The same fix needs to be done on the team details page, while creating a new company and editing it.

@Shruti-Apte Gentle reminder

2023-06-05 12:05 UTC, apoorv1316 requested changes
@Shruti-Apte If a city is already selected then its not showing cities list. We have to change state or country first to change the city.
<img width="715" alt="Screenshot 2023-06-05 at 5 34 21 PM" src="https://github.com/saeloun/miru-web/assets/18750194/86d970ed-2044-4d1a-a2d8-d55f53302fac">

2023-06-06 10:19 UTC, Shruti-Apte commented
> @Shruti-Apte If a city is already selected then its not showing cities list. We have to change state or country first to change the city. <img alt="Screenshot 2023-06-05 at 5 34 21 PM" width="715" src="https://user-images.githubusercontent.com/18750194/243347183-86d970ed-2044-4d1a-a2d8-d55f53302fac.png">

There are no cities present for central district state, If you select different country and state it's working properly.

2023-06-08 07:48 UTC, apoorv1316 commented
@Shruti-Apte Can't access edit org. page. Please check all the pages once where we can create/edit address.
<img width="1792" alt="Screenshot 2023-06-08 at 1 17 20 PM" src="https://github.com/saeloun/miru-web/assets/18750194/560cff0c-cff5-414d-bf3b-0cb1e0901a3d">

2023-06-09 13:06 UTC, apoorv1316 commented
@Shruti-Apte Have you updated the seed data and tested the timezone and fiscal year that we discussed yesterday?

2023-06-12 08:24 UTC, Shruti-Apte commented
> @Shruti-Apte Have you updated the seed data and tested the timezone and fiscal year that we discussed yesterday?

Yes, In seed data fiscal year is stored as` jan-dec`  but in code we are accepting only single month value like `Dec`,  `Nov` we need to update it from seed data

2023-06-12 08:34 UTC, Shruti-Apte commented
@prasanthchaduvula Please review this PR.
The bug:
Earlier  the cities list on the “Setup org”, “Edit Org” & “Edit Personal Details” were loading only when the user starts typing on the field.  Also the city value was not updating if user changes the state or country.  

Bug Fix:
Now the list of cities  is populating on click of city dropdown. also if user changes the country or state the City value will be removed.

 we can connect for demo.

2023-06-12 08:39 UTC, prasanthchaduvula commented
@Shruti-Apte Please update the seed data to support cities

2023-06-12 08:45 UTC, prasanthchaduvula requested changes

2023-06-12 08:45 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Edit/index.tsx
> +        orgDetails.companyAddr.state.code ?? orgDetails.companyAddr.state.value
use optional chaining

2023-06-12 12:32 UTC, prasanthchaduvula approved these changes

2023-06-14 12:18 UTC, apoorv1316 approved these changes

2023-06-14 12:19 UTC, merged