Feat: View change logs of invoices
saeloun/miru-web pull request #1357
Opened 2023-06-05 11:50 UTC by apoorv1316

Notion: https://www.notion.so/saeloun/Backend-Admin-owner-user-should-be-able-to-view-the-change-log-for-an-invoice-844e71c756be4ffca24e192d65a7e039

What
- Added backend code to view changelog of invoice events (create, view, send, update, destroy and download)

2023-06-08 13:06 UTC, gowsik-ragunath requested changes
Added few minor comments

2023-06-09 12:36 UTC, apoorv1316 commented
@gowsik-ragunath Committed your suggestions. Please review

2023-06-12 08:13 UTC, prasanthchaduvula requested changes

2023-06-12 08:13 UTC, prasanthchaduvula commented on config/routes.rb
> +        ActiveSupport::SecurityUtils.secure_compare(
this indenetation changes is wrong and no code changes in this.

2023-06-12 08:22 UTC, prasanthchaduvula approved these changes

2023-06-12 09:16 UTC, gowsik-ragunath approved these changes
LGTM

2023-06-12 09:31 UTC, merged