Fix: Send reminder modal ui and options UI
saeloun/miru-web pull request #1410
Opened 2023-07-06 10:20 UTC by mayankagnihotri7

## Designs
- [Send Reminder Modal](https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?type=design&node-id=14889%3A208433&mode=design&t=3AaVPFSt6iL2nPbU-1)
- [Options on invoice details page](https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?type=design&node-id=12636%3A207136&mode=design&t=3AaVPFSt6iL2nPbU-1)

## Description
- Fixed send reminder modal UI for the labels.
- Fixed the overlapping issue where when the options were opened it had text overlapping it.

## Preview
Before -
<img width="1490" alt="Screenshot 2023-07-06 at 3 45 27 PM" src="https://github.com/saeloun/miru-web/assets/57438322/8e57100e-5e30-4e1f-987e-1a297b528f67">

<img width="1492" alt="Screenshot 2023-07-06 at 3 46 02 PM" src="https://github.com/saeloun/miru-web/assets/57438322/fc665825-a0b3-41bb-a84c-fd8a35ab4032">

After -
<img width="1495" alt="Screenshot 2023-07-06 at 3 43 53 PM" src="https://github.com/saeloun/miru-web/assets/57438322/cc8c9944-a087-44a2-829e-b9ef9f5171a7">

<img width="1492" alt="Screenshot 2023-07-06 at 3 44 18 PM" src="https://github.com/saeloun/miru-web/assets/57438322/2723e2ed-a218-4944-b0e0-b78aeeaaa9bd">

2023-07-06 11:11 UTC, apoorv1316 commented
@mayankagnihotri7 Few fixes are required here
1. Remove the '{}' from the "Send Invoice" heading.
2. Email  & Message label is not similar to designs.
3. Email value background should have more margin from the bottom of the box
4. Subject label text is small
<img width="1792" alt="Screenshot 2023-07-06 at 4 36 42 PM" src="https://github.com/saeloun/miru-web/assets/18750194/e7d380b7-3c5a-48ac-92e0-412713acb2af">

2023-07-07 03:28 UTC, prasanthchaduvula requested changes

2023-07-07 03:28 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/SendInvoice/index.tsx
> +                    ref={input}
Why is this code commented out? If it's not used anymore please remove it.

2023-07-07 03:28 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/popups/SendInvoice/index.tsx
>                      style={{ width }}
ditto

2023-07-07 04:51 UTC, mayankagnihotri7 commented on app/javascript/src/components/Invoices/List/SendInvoice/index.tsx
> +                    ref={input}
It was commented out before I even used modal.

2023-07-07 04:51 UTC, mayankagnihotri7 commented on app/javascript/src/components/Invoices/popups/SendInvoice/index.tsx
>                      style={{ width }}
It was commented out before I even used modal.

2023-07-07 04:52 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/SendInvoice/index.tsx
> +                    ref={input}
Please remove it if it not used

2023-07-07 04:52 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/popups/SendInvoice/index.tsx
>                      style={{ width }}
Please remove it if it not used

2023-07-07 10:55 UTC, apoorv1316 commented
@mayankagnihotri7 Can we close the menu after the modal is opened?
<img width="1369" alt="Screenshot 2023-07-07 at 4 23 46 PM" src="https://github.com/saeloun/miru-web/assets/18750194/53843bbb-6a23-47aa-8dc2-52788656d78a">

2023-07-07 10:55 UTC, apoorv1316 approved these changes

2023-07-07 12:04 UTC, mayankagnihotri7 commented
@apoorv1316 Yes. We can close the modal using the esc key.

2023-07-07 12:49 UTC, apoorv1316 commented
<img width="985" alt="Screenshot 2023-07-07 at 6 17 42 PM" src="https://github.com/saeloun/miru-web/assets/18750194/90a938df-2927-4586-b786-ca8e7bded8bd">
@mayankagnihotri7 We are able to type in the email field and add other emails. I don't think we are now allowing that. Please fix it

2023-07-07 13:37 UTC, mayankagnihotri7 commented
@apoorv1316 I've made the requested changes. Please review.

2023-07-07 13:41 UTC, apoorv1316 commented
@mayankagnihotri7 We can still type emails on the mobile screens. Please fix it

2023-07-07 14:53 UTC, mayankagnihotri7 commented
@apoorv1316 I've made the requested changes. Please review.

2023-07-10 06:19 UTC, apoorv1316 approved these changes

2023-07-10 06:20 UTC, apoorv1316 commented
@prasanthchaduvula Please review.

2023-07-13 06:09 UTC, prasanthchaduvula approved these changes

2023-07-13 09:17 UTC, merged