Add pagination for teams page
saeloun/miru-web pull request #1414
Opened 2023-07-11 08:12 UTC by mayankagnihotri7

## Notion Card
[Notion Card](https://www.notion.so/saeloun/Implement-pagination-on-teams-page-2d6167ca653a42b3bc240c415f05f89d)

## Description
- Added pagination for the teams page.

2023-07-13 06:38 UTC, prasanthchaduvula requested changes

2023-07-13 06:38 UTC, prasanthchaduvula commented on app/controllers/internal_api/v1/team_controller.rb
> +    presenter_data = TeamPresenter.new(teams, invitations, current_user, current_company).index_data
Add an empty line before between `invitations` and `presenter_data`

2023-07-13 06:38 UTC, prasanthchaduvula commented on app/controllers/internal_api/v1/team_controller.rb
> +    render :index, locals: {
Add an empty line before `render`

2023-07-13 06:38 UTC, prasanthchaduvula commented on app/javascript/src/common/Pagination/Pagination.tsx
> +              if (isTeamPage) {
move this logic to a function

2023-07-17 07:03 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2023-07-18 10:21 UTC, prasanthchaduvula approved these changes

2023-07-18 12:43 UTC, apoorv1316 commented
@mayankagnihotri7 Please watch loom video and fix the bugs mentioned in video https://www.loom.com/share/63d6d3c3ae2a472b823795b4843bd721?focus_title=1&muted=1&from_recorder=1

2023-07-19 11:43 UTC, mayankagnihotri7 commented
@prasanthchaduvula Can you please review the code again? I've made some changes.

@apoorv1316 I've made the requested changes. Please review.

2023-07-24 05:43 UTC, apoorv1316 approved these changes

2023-07-24 05:44 UTC, apoorv1316 commented
@mayankagnihotri7 Please add system specs for it.

2023-07-25 06:03 UTC, merged