Refactored clients index action by moving away from ransack to searchkick
saeloun/miru-web pull request #1429
Opened 2023-07-25 05:17 UTC by prasanthchaduvula

### What
- We are using `Ransack` to search clients by name/email. With this PR, we will be using `Searchkick` to search clients by name/email. We are using `Searchkick ` in other places.

2023-07-27 10:15 UTC, gowsik-ragunath requested changes
Added one minor comment

2023-07-27 10:15 UTC, gowsik-ragunath commented on app/services/clients/index_service.rb
> +      @params = params
Instead of passing the entire params, can you pass only the `query` and `time_frame` values as argument to service? or pass a sanitized params as argument.

2023-07-31 06:41 UTC, gowsik-ragunath approved these changes
LGTM

2023-08-01 06:26 UTC, apoorv1316 approved these changes

2023-08-01 06:26 UTC, merged