PTO module updated
saeloun/miru-web pull request #1448
Opened 2023-08-23 10:43 UTC by Shruti-Apte

Notion:
https://www.notion.so/saeloun/Update-the-designs-for-PTO-module-Admin-settings-084f3e014cb74b7a87b232e73ac732f9?pvs=4

##What:
- Separated Leaves and Holidays design.
- Updated code quality
- Fixed UI issues.

##Why
- Requirement

2023-09-08 05:12 UTC, prasanthchaduvula requested changes

2023-09-08 05:12 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Holidays/Details/index.tsx
> +              {holidaysList.map((holiday, index) => (
what if `holidaysList` is empty []

2023-09-08 05:12 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Holidays/EditHolidays.tsx
> +          {holidayList.map((holiday, index) => (
what if `holidaysList` is empty []

2023-09-08 05:12 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Holidays/Details/index.tsx
> +              {optionalHolidayList.map((holiday, index) => (
what if `optionalHolidayList` is empty []

2023-09-08 05:12 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Leaves/Details/index.tsx
> +          {leavesList.map((leave, index) => (
what if `leavesList` is empty []

2023-09-08 05:12 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Leaves/EditLeaves.tsx
> +const customStyles = {
Move `iconStyles `and `customStyles` to a separate file inside `EditLeaves`

2023-09-08 05:12 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Holidays/EditHolidays.tsx
> +const customStyles = {
Move `customStyles` to a separate file inside `EditHolidays`

2023-09-08 05:12 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/Leaves/EditLeaves.tsx
> +const ColorOption = props => (
Move` IconOption` and `ColorOption` to a separate file inside EditLeaves

2023-09-08 05:12 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/RouteConfig.tsx
>  import Import from "./Organization/Import";
Please change the name of Import component to OrganizationImport

2023-09-08 10:52 UTC, Shruti-Apte commented on app/javascript/src/components/Profile/Organization/Holidays/Details/TableRow.tsx
> +        {dayjs(date).format(dateFormat)}
No, need to fetch organisation date format from API. 
Currently using predefined date format.

2023-09-12 07:14 UTC, prasanthchaduvula approved these changes

2023-09-12 09:00 UTC, merged