Frontend for the meetings page
saeloun/miru-web pull request #1487
Opened 2023-09-26 15:09 UTC by mayankagnihotri7

## Notion Card
[Notion Card](https://www.notion.so/saeloun/Frontend-As-a-Miru-user-I-should-be-able-to-view-the-meetings-page-as-per-my-google-calendar-inte-75d30aa6c17d4538ada0b3f3a0463af1)

## Description
- This is a part of Google Calendar integration into Miru.
- This PR adds a frontend design for the meetings page.
- Add multiple meetings at once or one by one to the time entries.
- Fixed `Google::Apis::AuthorizationError` which was caused due to token expiring every hour.

## Preview
<img width="1791" alt="Screenshot 2023-09-27 at 12 59 20 PM" src="https://github.com/saeloun/miru-web/assets/57438322/461f6b3c-9129-4863-866e-96996a49195a">

<img width="1792" alt="Screenshot 2023-09-27 at 1 06 29 PM" src="https://github.com/saeloun/miru-web/assets/57438322/fc221051-0a73-4801-b25a-d1786081edef">

<img width="1792" alt="Screenshot 2023-09-27 at 1 06 52 PM" src="https://github.com/saeloun/miru-web/assets/57438322/d77c83aa-f04f-41fe-9052-b1805c038a97">

<img width="1792" alt="Screenshot 2023-09-27 at 1 09 15 PM" src="https://github.com/saeloun/miru-web/assets/57438322/24a6bd29-9013-4943-be0a-71946637f5b0">

2023-10-26 06:48 UTC, supriya3105 commented
@mayankagnihotri7 Can we close this PR ?

2023-10-26 07:01 UTC, mayankagnihotri7 commented
@supriya3105 This PR is being worked on currently.

2023-10-26 16:17 UTC, prasanthchaduvula requested changes

2023-10-26 16:17 UTC, prasanthchaduvula commented on app/controllers/internal_api/v1/timesheet_entry/bulk_action_controller.rb
> +
Extract this logic to a service. Make controllers slim

2023-10-26 16:17 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/AddAllMeetingsModal.tsx
> +  <Modal
return from this component so that it will be easy to debug

2023-10-26 16:17 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/Header.tsx
> +  <>
return from this component so that it will be easy to debug

2023-10-26 16:17 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/Meeting.tsx
> +import Button from "../../StyledComponents/Button";
`Import { Button, TimeInput } from "StyledComponents"`

2023-10-26 16:17 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/Meeting.tsx
> +                "dd MMM, yyyy"
Please check the date format is in sync with the organizational date format on the client side.

2023-10-26 16:17 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/MeetingList.tsx
> +import Logger from "js-logger";
No need to use Js logger

2023-10-26 16:17 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/index.tsx
> +import Button from "../../StyledComponents/Button";
import it from `StyledComponents`

2023-10-26 16:17 UTC, prasanthchaduvula commented on app/javascript/src/constants/routes.ts
> +    authorisedRoles: [ADMIN, OWNER, EMPLOYEE, BOOK_KEEPER, CLIENT],
Why `CLIENT` will have the access to meetings

2023-10-27 10:34 UTC, mayankagnihotri7 commented on app/javascript/src/components/Meetings/AddAllMeetingsModal.tsx
> +  <Modal
Doing that gives me this eslint warning - `Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`.` which prevents me from committing the code.

2023-10-27 10:34 UTC, mayankagnihotri7 commented on app/javascript/src/components/Meetings/Header.tsx
> +  <>
Doing that gives me this eslint warning - `Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`.` which prevents me from committing the code.

2023-10-27 10:48 UTC, mayankagnihotri7 commented on app/javascript/src/components/Meetings/MeetingList.tsx
> +import Logger from "js-logger";
How am I supposed to log the error I catch using the `try...catch` block then?

2023-10-27 12:12 UTC, mayankagnihotri7 commented on app/javascript/src/components/Meetings/Meeting.tsx
> +                "dd MMM, yyyy"
It's the same as what we are doing for time tracking as well. If I make use of organizational date format from the client side it does not work properly.

2023-10-30 01:43 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/AddAllMeetingsModal.tsx
> +  <Modal
Please share the screenshot of the component

2023-10-30 01:43 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/MeetingList.tsx
> +import Logger from "js-logger";
`api.ts` file already handles the response thrown from backend

2023-10-30 01:44 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/Header.tsx
> +  <>
Please share the screenshot of the component

2023-10-30 01:45 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/Meeting.tsx
> +                "dd MMM, yyyy"
Lets create another ticket for it

2023-10-30 09:41 UTC, mayankagnihotri7 commented on app/javascript/src/components/Meetings/Header.tsx
> +  <>
<img width="1250" alt="Screenshot 2023-10-30 at 3 11 36 PM" src="https://github.com/saeloun/miru-web/assets/57438322/a7800fca-c96a-4092-8c86-d5646d9a58f5">

2023-10-31 11:27 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/AddAllMeetingsModal.tsx
> +  <Modal
I pushed the change

2023-10-31 11:28 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/Header.tsx
> +  <>
I pushed the change

2023-10-31 16:23 UTC, prasanthchaduvula requested changes

2023-10-31 16:23 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/MeetingList.tsx
> +  const [projects, setProjects] = useState<any>({});
here projects is an array or object

2023-10-31 16:23 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/MeetingList.tsx
> +    let timeTrackingFormat;
rename it to `timeSheetEntries` or `timeSheetEntriesData`

2023-10-31 16:23 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/index.tsx
> +    JSON.parse(localStorage.getItem("calendarEvents"))
use `getValueFromLocalStorage` from `storage.ts`

2023-10-31 16:23 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/index.tsx
> +    localStorage.setItem("calendarEvents", JSON.stringify(meetings));
use `setToLocalStorage` from storage.ts

2023-10-31 16:23 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/index.tsx
> +      localStorage.setItem("calendarEvents", JSON.stringify(data));
ditto

2023-10-31 16:23 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/index.tsx
> +      Logger.log(error);
Dont use logger

2023-10-31 16:23 UTC, prasanthchaduvula commented on app/services/create_bulk_time_entries_service.rb
> +      entries_data.each do |entry_data|
Move it to a method and return if `entries_data.blank?`

2023-10-31 16:23 UTC, prasanthchaduvula commented on app/services/create_bulk_time_entries_service.rb
> +          render json: { error: "An error occurred while trying to add meetings. Please try again." },
instead rescue it

2023-11-01 09:43 UTC, mayankagnihotri7 commented on app/javascript/src/components/Meetings/MeetingList.tsx
> +  const [projects, setProjects] = useState<any>({});
Object with it's keys having an array of objects.

2023-11-01 13:16 UTC, prasanthchaduvula commented on app/javascript/src/components/Meetings/index.tsx
> +    JSON.parse(getValueFromLocalStorage("calendarEvents") || "[]")
Please test this once, as `getValueFromLocalStorage` parses the value

2023-11-01 13:16 UTC, prasanthchaduvula commented on app/services/create_bulk_time_entries_service.rb
> +          render json: { error: "An error occurred while trying to add meetings. Please try again." },
please test it whether it's throwing a proper error message when we try to add an invalid timesheet entry otherwise rescue it with a proper message

2023-11-01 14:07 UTC, mayankagnihotri7 commented on app/javascript/src/components/Meetings/index.tsx
> +    JSON.parse(getValueFromLocalStorage("calendarEvents") || "[]")
That function returns a string if not present so it won't be possible to assign it due to type defined as - `any[]`.

2023-11-07 09:59 UTC, prasanthchaduvula approved these changes
@apoorv1316 Please test this PR

2023-11-09 05:32 UTC, apoorv1316 requested changes
@mayankagnihotri7 Please see the loom video and work on the requested changes
cc @supriya3105 
https://www.loom.com/share/66c48b29d0a84853bcb1d82049d9db1c
https://www.loom.com/share/654b1494e15841d8baceba970485ab21

2023-11-09 09:24 UTC, mayankagnihotri7 commented
@apoorv1316 I've made the requested changes. Please review.

2023-11-15 07:50 UTC, apoorv1316 requested changes
@mayankagnihotri7 
1. Close the calendar on outside click
2. Billable checkbox should get disabled if the selected project is non-billable.
3. "Connect Meeting Apps" should be the text for button on empty sate design 
4. When adding all meetings the text for the dialog box is "Delete project". Fix it

2023-11-15 11:32 UTC, mayankagnihotri7 commented
@apoorv1316 I've made the requested changes. Please review. Here are the explanations for some changes I could not make:
- Billable checkbox cannot be disabled because we use an image for it and even in the time entries we do the same.

2023-11-17 05:47 UTC, apoorv1316 commented
@mayankagnihotri7 If admin disables the Google integration and then if employee logs in then the request is sent to fetch events and which results in error
<img width="1792" alt="Screenshot 2023-11-17 at 11 16 43 AM" src="https://github.com/saeloun/miru-web/assets/18750194/a7de86ab-ff6f-496a-883b-2a2c11fd0d66">

2023-11-17 11:01 UTC, mayankagnihotri7 commented
@apoorv1316 I've fixed the error you were facing. Please review.

2023-11-21 06:05 UTC, apoorv1316 commented
@supriya3105 @prasanthchaduvula @mayankagnihotri7 Demo video
https://www.loom.com/share/6cd853a684bb452d81b07a47b1b77a45

2023-11-21 06:07 UTC, apoorv1316 commented
@mayankagnihotri7 The code for integations route and link is commented out. Why is it so? Also, The  google_client_id and secret, how can we get them for prod. and staging acc. and whose account's should be used for it. cc @prasanthchaduvula

2023-11-21 06:23 UTC, mayankagnihotri7 commented
@apoorv1316 I don't know why the code for the integrations was commented out on the frontend. It was done by Prasanth.

2023-11-21 10:26 UTC, prasanthchaduvula commented
@mayankagnihotri7 you mean client-side routing along with the navigation menu on side nav
cc; @apoorv1316

2023-11-21 10:27 UTC, apoorv1316 commented
@mayankagnihotri7 What about the secrets and key and account to be used for staging and prod?

2023-11-21 11:29 UTC, mayankagnihotri7 commented
@prasanthchaduvula Yes. Apoorv means that I guess.
@apoorv1316 For the secrets and key to be used I think the existing ones should work but make sure to enable the Google Calendar API and enable the read-only scopes i.e, only for fetching the calendars and events.

2023-11-21 11:36 UTC, prasanthchaduvula commented
@mayankagnihotri7 I commented out because those features are not complete on the develop branch
Please uncomment them if things are complete

2023-11-21 13:04 UTC, mayankagnihotri7 commented
@prasanthchaduvula Let's do that in another PR?

2023-11-21 13:05 UTC, apoorv1316 commented
@mayankagnihotri7 We just need to uncomment the route right? Lets do in this PR itself.

2023-11-21 13:21 UTC, prasanthchaduvula commented
> @prasanthchaduvula Let's do that in another PR?

Please do that in this PR if the feature of calendar integration is completed

2023-11-22 10:56 UTC, prasanthchaduvula commented
@apoorv1316 Please test it once

2024-03-14 21:30 UTC, closed without merging