[Feature][UI] Allocated devices tab read only view
saeloun/miru-web pull request #1514
Opened 2023-10-03 07:40 UTC by reettikgoswami

2023-10-04 04:46 UTC, prasanthchaduvula requested changes

2023-10-04 04:46 UTC, prasanthchaduvula commented on app/javascript/src/apis/devices.ts
> +const getPath = user_id => `/users/${user_id}/devices`;
Use camelcase here. `userId` and currently, `getPath` is not reusable, please change the const get function to return the whole path instead of using `getPath`.

Remove the `getPath` function from this file which is not required any more.

2023-10-04 04:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/SubNav.tsx
> +      {personalSettingsList.map((selectOption, index) => (
Rename `selectOption` to `setting`

2023-10-04 04:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/SubNav.tsx
>  const SideNav = ({ isAdmin, firstName, company, lastName }) => {
Can you rename the component from `SideNav` to `SubNav` to match the file and component convention

2023-10-04 04:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +  <Fragment>
Consider adding a `return` statement to explicitly indicate the component's output. This can improve code readability and make it easier for future debugging. For example:

```javascript
const StaticPage = ({ devices }) => {
  return (
    <Fragment>
      {/* Your component content here */}
    </Fragment>
  );
}

2023-10-04 04:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +      devices.map((device, index) => (
Use  optional chaining here
```javascript
devices?.map()

2023-10-04 04:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +                    {device.device_type}
Consider destructuring values from the `device` object to improve code readability. Instead of accessing individual properties like `{device.device_type}`, you can destructure them at the beginning of the component to make the code cleaner and more maintainable.

2023-10-04 04:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/index.tsx
> +  // const handleEditClick = () => {};
Remove this commented code

2023-10-04 04:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/index.tsx
> +        // editAction={() => handleEditClick(devices)}
Remove this commented prop

2023-10-04 05:40 UTC, reettikgoswami commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +  <Fragment>
Project ESlint prevents me from doing that.

2023-10-04 09:50 UTC, supriya3105 commented
@prasanthchaduvula Please review the feedback incorporated today .

2023-10-04 10:32 UTC, prasanthchaduvula requested changes

2023-10-04 10:32 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +  <Fragment>
move the below code towards the end of the component and `DeviceDetails`  before the return so that it won't throw the error
otherwise, render the component directly instead of extracting to `DeviceDetails`
```javascript
<Fragment>
 {devices?.map((device, index) => (
      <DeviceDetails device={device} key={index} />
    ))}
  </Fragment>

2023-10-04 10:32 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/SubNav.tsx
> +const SubNav = ({ isAdmin, firstName, company, lastName }) => {
Please update the import statement in `profile/layout`

`import SideNav from "./SubNav";`

2023-10-05 04:09 UTC, prasanthchaduvula requested changes

2023-10-05 04:09 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +  <Fragment>
Please add the return statement to make it easier for future debugging. 
Make `StaticPage`.

We can also move the `DeviceDetails` Inside the `StaticPage`

2023-10-05 04:09 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +                {specifications?.ram}
destructure the `specification ` object while destructuring the `device `object itself.

2023-10-05 04:54 UTC, reettikgoswami commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +  <Fragment>
@prasanthchaduvula, Eslint prevent me from adding a return statement, If I do pre-commit hook revert back.

2023-10-05 05:09 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +  <Fragment>
```
const StaticPage = ({ devices = [] }) => {
  const DeviceDetails = ({ device }) => {
    const { device_type, name, serial_number, specifications } = device;

    return (
      <div className="mt-4 h-full bg-miru-gray-100 px-10">
        <div className="flex border-b border-b-miru-gray-400 py-10">
          <div className="flex w-1/5 pr-4">
            <MobileIcon
              className="mr-4 mt-1 text-miru-dark-purple-1000"
              size={16}
              weight="bold"
            />
            <span className="text-sm font-medium text-miru-dark-purple-1000">
              Devices
            </span>
          </div>
          <div className="w-4/5">
            <div className="flex">
              <div className="w-6/12">
                <span className="text-xs text-miru-dark-purple-1000">
                  Device Type
                </span>
                <p className="text-miru-dark-purple-1000">{device_type}</p>
              </div>
              <div className="w-6/12">
                <span className="text-xs text-miru-dark-purple-1000">
                  Model
                </span>
                <p className="text-miru-dark-purple-1000">{name}</p>
              </div>
            </div>
            <div className="mt-4 flex">
              <div className="w-6/12">
                <span className="text-xs text-miru-dark-purple-1000">
                  Serial Number
                </span>
                <p className="text-miru-dark-purple-1000">{serial_number}</p>
              </div>
              <div className="w-6/12">
                <span className="text-xs text-miru-dark-purple-1000">
                  Memory
                </span>
                <p className="text-miru-dark-purple-1000">
                  {specifications?.ram}
                </p>
              </div>
            </div>
            <div className="mt-4 flex">
              <div className="w-6/12">
                <span className="text-xs text-miru-dark-purple-1000">
                  Graphics
                </span>
                <p className="text-miru-dark-purple-1000">
                  {specifications?.graphics}
                </p>
              </div>
              <div className="w-6/12">
                <span className="text-xs text-miru-dark-purple-1000">
                  Processor
                </span>
                <p className="text-miru-dark-purple-1000">
                  {specifications?.processor}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  };

  return (
    <Fragment>
      {devices?.map((device, index) => (
        <DeviceDetails device={device} key={index} />
      ))}
    </Fragment>
  );
};

export default StaticPage;

```

2023-10-05 05:10 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +  <Fragment>
@reettikgoswami please check the above suggested code which won't throw any error with the eslint recommit hook. 

destructure the specification  object while destructuring the device object itself.

2023-10-05 06:28 UTC, prasanthchaduvula requested changes

2023-10-05 06:28 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/StaticPage.tsx
> +      specifications: { ram, graphics, processor },
`specifications: { ram, graphics, processor } = {},`

use = {} to provide a default empty object in case specifications is null or undefined. This ensures that destructuring` ram `, `graphics`  and `processor` won't throw errors even if specifications is not defined.

2023-10-05 08:35 UTC, prasanthchaduvula approved these changes

2023-10-05 09:06 UTC, merged