Upgrade Rails to 7.1
saeloun/miru-web pull request #1540
Opened 2023-10-11 07:07 UTC by akhilgkrishnan

- This PR upgrades the rails version to 7.1

2023-10-11 07:11 UTC, akhilgkrishnan commented on config/initializers/new_framework_defaults_7_1.rb
> +# frozen_string_literal: true
We can uncomment the changes, that we required.

2024-03-30 11:32 UTC, vipulnsward commented
@akhilgkrishnan can you rebase this?

2024-03-31 02:33 UTC, akhilgkrishnan commented
> @akhilgkrishnan can you rebase this?

Rebased the PR

2024-04-01 20:43 UTC, vipulnsward commented
Specs are failing, @apoorv1316 can you take a look?

2024-04-14 11:17 UTC, apoorv1316 commented on Gemfile
> +gem "sidekiq", "~> 7.2"
Upgraded sidekiq to fix the following error on running sidekiq
`super: no superclass method `broadcast' for ActiveSupport::Logger:Class`

2024-04-14 11:18 UTC, apoorv1316 commented
Removed search_service and its specs because we are not using ransack for search. It was old code which was not being used.

2024-04-15 08:15 UTC, apoorv1316 commented
@gowsik-ragunath @prasanthchaduvula @akhilgkrishnan Please review

2024-04-15 08:49 UTC, nisusam requested changes

2024-04-15 08:49 UTC, nisusam commented on Gemfile.lock
> +  arm64-darwin-23
Either get all the relative platforms or remove this

2024-04-15 08:49 UTC, nisusam commented on db/schema.rb
> +ActiveRecord::Schema[7.1].define(version: 2024_03_31_034308) do
Only single-line change? please check whether the above migrations ran or not.

2024-04-15 10:17 UTC, apoorv1316 commented on Gemfile.lock
> +  arm64-darwin-23
done

2024-04-15 10:17 UTC, apoorv1316 commented on db/schema.rb
> +ActiveRecord::Schema[7.1].define(version: 2024_03_31_034308) do
Yes it is up

2024-04-15 10:18 UTC, nisusam approved these changes

2024-04-23 15:01 UTC, apoorv1316 commented
> @apoorv1316 @nisusam Are we good to merge this PR?

will merge tomorrow

2024-04-24 04:27 UTC, merged