auto save timesheet entry
saeloun/miru-web pull request #1553
Opened 2023-10-18 09:17 UTC by apoorv1316

Closes #1495

2023-10-19 08:07 UTC, supriya3105 commented
@prasanthchaduvula Please review the PR.

2023-10-19 10:18 UTC, prasanthchaduvula requested changes

2023-10-19 10:18 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/EntryForm.tsx
> +    localStorage.setItem("note", note);
Move this to a function and call it inside the useEffect

2023-10-19 10:18 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/EntryForm.tsx
> +    localStorage.getItem("billable") === "true"
Move the setting of the state values to a method and call them inside the useEffect and use `setToLocalStorage` and `getValueFromLocalStorage` method from `utils/storage`

2023-10-20 07:39 UTC, apoorv1316 commented on app/javascript/src/components/TimeTracking/EntryForm.tsx
> +    localStorage.setItem("note", note);
Done

2023-10-20 07:39 UTC, apoorv1316 commented on app/javascript/src/components/TimeTracking/EntryForm.tsx
> +    localStorage.getItem("billable") === "true"
Done

2023-10-20 10:58 UTC, prasanthchaduvula commented
@apoorv1316 I have tested this PR. When we click on New time entry and add the description. After that If we refresh or visit clients and come back to a time-tracking page and click on a new timesheet entry the previous details are not preloaded

2023-10-23 06:19 UTC, apoorv1316 commented
@prasanthchaduvula It is working. Please check again.

2023-10-23 15:01 UTC, prasanthchaduvula approved these changes

2023-10-23 15:01 UTC, merged