Added designation under profile picture when designation field is populated
saeloun/miru-web pull request #1564
Opened 2023-10-25 14:03 UTC by sainikhil1605

Issue #1484 
Populate the designation under the profile photo, if the designation field is populated on the employment details tab

Steps:

Login as any user in Miru
Click on settings on the left navigation bar
Go to employment details tab
if the designation field is populated, the value should be populated under the profile photo
Desktop
<img width="959" alt="desktop" src="https://github.com/saeloun/miru-web/assets/35322884/982d1a96-dc31-434f-856d-f3515f95f09f">
Mobile
<img width="448" alt="mobile" src="https://github.com/saeloun/miru-web/assets/35322884/4d1112ab-f2a5-4056-93e9-778936402a29">

2023-10-26 06:50 UTC, supriya3105 commented
@apoorv1316 Please test the feature and update here.

2023-10-26 16:02 UTC, prasanthchaduvula requested changes

2023-10-27 05:42 UTC, prasanthchaduvula approved these changes

2023-10-27 05:42 UTC, prasanthchaduvula commented
@apoorv1316 Please test this PR

2023-10-27 06:37 UTC, apoorv1316 requested changes
@sainikhil1605 Getting this error toast on a mobile device
<img width="1792" alt="Screenshot 2023-10-27 at 12 07 08 PM" src="https://github.com/saeloun/miru-web/assets/18750194/c2cfa5de-33c1-4ada-ad1c-7f02be82330c">

2023-10-27 06:37 UTC, apoorv1316 commented on app/javascript/src/components/Profile/CommonComponents/UserInformation/index.tsx
>              wrapperClassName="relative block max-w-full "
@sainikhil1605 We don't need to show the designation on the tooltip.

2023-10-27 06:37 UTC, apoorv1316 commented on app/javascript/src/components/Profile/CommonComponents/UserInformation/index.tsx
> +                {designation}
Add some margin b/w name and designation. It looks cluttered

2023-10-27 17:56 UTC, sainikhil1605 commented
Fixed Issue in mobile screens

https://github.com/saeloun/miru-web/assets/35322884/c8bc00fb-53e1-4f62-a925-ba815ff10401

2023-10-30 01:40 UTC, prasanthchaduvula approved these changes

2023-10-30 06:10 UTC, supriya3105 commented
@sainikhil1605 1 check is failing, please check and fix.

2023-10-31 05:12 UTC, apoorv1316 commented on app/javascript/src/components/Profile/Layout/UserDetails.tsx
> +
@sainikhil1605 Users with a `client` role are not authorized for any action related to  Employment and PreviousEmployments. So, this will throw an error when a client user logs in and visits the profile page.
We need to add a condition and skip this API call and the designation if the role is `client`
You can use these creds for testing client role.
`email: oliver@example.com
password: welcome`

2023-10-31 05:13 UTC, apoorv1316 requested changes
@sainikhil1605 Please work on the requested change

2023-11-06 11:06 UTC, apoorv1316 commented
@sainikhil1605 Can you please confirm if you can work on the requested changes?

2023-11-07 17:18 UTC, sainikhil1605 commented
> @sainikhil1605 Please work on the requested change

Fixed this in client account

2023-11-15 05:08 UTC, apoorv1316 commented
@prasanthchaduvula Please review

2023-11-15 06:46 UTC, prasanthchaduvula requested changes

2023-11-15 06:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Layout/UserDetails.tsx
> +  const { avatarUrl, setCurrentAvatarUrl, companyRole } = useUserContext();
Above, we are importing `user` from `useUserContext()` and here we are importing other values.
Import `user` with these values itself in this single import statement

2023-11-15 06:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Layout/UserDetails.tsx
> +          const res: any = await teamsApi.getEmploymentDetails(
rename `res` to `employmentData` as we have multiple requests in this function.

And rename the above `const data = await profileApi.index();` to rename it `const userData = await profileApi.index();`

2023-11-15 06:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Layout/UserDetails.tsx
> +          const res1 = await teamsApi.getPreviousEmployments(data.data.user.id);
rename `res1` to `previouseEmploymentData`

2023-11-15 06:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/UserDetailsView/index.tsx
> +        const res1: any = await teamsApi.getPreviousEmployments(
rename `res1` to `previouseEmploymentData`

2023-11-15 06:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/UserDetailsView/index.tsx
> +        const res: any = await teamsApi.getEmploymentDetails(
rename `res` to `employmentData` as we have multiple requests in this function.

2023-11-15 06:48 UTC, prasanthchaduvula commented
@apoorv1316 Please create a ticket to update the profile API to send the response which includes the user details, address details and employment details instead of sending multiple requests to render the same component to load the values.

2023-11-20 13:35 UTC, supriya3105 commented
@apoorv1316 Can you please work on the review comments from Prasanth on this PR.

2023-11-23 13:31 UTC, closed without merging