Invoice download access enabled for client
saeloun/miru-web pull request #1577
Opened 2023-11-01 07:51 UTC by Shruti-Apte

### **Notion :**
https://www.notion.so/saeloun/a-client-should-be-able-to-download-an-invoice-from-the-client-portal-after-they-have-logged-in-280076985fc94d69b72c528c431858e5?pvs=4
### **What :**
- Added more options button on view Invoice page client role
- Enabled access for clients to download a invoice 
### **Why :**
- Enhancement 
- Client should be able to download a invoice 

### **Todos** (for testing):
- Tested for oliver smith account

2023-11-01 08:03 UTC, apoorv1316 commented
@Shruti-Apte Add policy_spec for the client able to download the invoice

2023-11-01 13:06 UTC, prasanthchaduvula requested changes

2023-11-01 13:06 UTC, prasanthchaduvula commented on app/javascript/src/components/ClientInvoices/Details/Header.tsx
> +import { handleDownloadInvoice } from "../../Invoices/common/utils";
import it from `components/Invoices/common/utils`

2023-11-01 13:06 UTC, prasanthchaduvula commented on app/javascript/src/components/ClientInvoices/Details/Header.tsx
> +            Invoice #{invoice.invoice_number}
destructure values from invoice

2023-11-01 13:06 UTC, prasanthchaduvula commented on app/javascript/src/components/ClientInvoices/Details/Header.tsx
> +            className="ml-2 rounded border border-miru-han-purple-1000 bg-miru-gray-1000 p-2.5 text-miru-han-purple-1000 opacity-50"
If possible, try to use `Button` component from `StyledComponents`

2023-11-06 11:44 UTC, apoorv1316 requested changes
@Shruti-Apte Please work on requested changes

2023-11-06 11:44 UTC, apoorv1316 commented on spec/policies/invoice_policy_spec.rb
@Shruti-Apte Here you are trying to add_role to a client which is not valid. Roles can be added to a user only.
 Create a user and then add a role to it.
 It will look like

```
  let(:client_member) { create(:user, current_workspace_id: company.id) }
  client_member.add_role :client, company

```

2023-11-06 11:44 UTC, apoorv1316 commented on app/policies/invoice_policy.rb
>    end
Do the same for show? method too

2023-11-06 11:44 UTC, apoorv1316 commented on app/javascript/src/components/ClientInvoices/Details/Header.tsx
> +                onClick={() => handleDownloadInvoice(invoice)}
set isMoreOptionsVisible to false so that the menu can be closed when clicked on download link

2023-11-07 05:06 UTC, apoorv1316 approved these changes

2023-11-07 05:07 UTC, apoorv1316 commented
@prasanthchaduvula Please approve

2023-11-07 05:26 UTC, prasanthchaduvula approved these changes

2023-11-07 05:37 UTC, merged