Fix pagination and group by filters
saeloun/miru-web pull request #1582
Opened 2023-11-06 09:10 UTC by apoorv1316

Notion: https://www.notion.so/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=e558285a6d77425f809e005101775580&pm=s

Loom: https://www.loom.com/share/f94e593debcb4250abf2a0cf52c86466

2023-11-06 13:37 UTC, prasanthchaduvula requested changes

2023-11-06 13:37 UTC, prasanthchaduvula commented on app/services/reports/time_entries/report_service.rb
> +      order_field = case params[:group_by]
```suggestion
     order_fields = {
        "project" => :project_name,
        "client" => :client_name,
        "team_member" => :user_name,
        "default" => :client_name
      }

      order_field = order_fields[params[:group_by]] || order_fields["default"]

      TimesheetEntry.search(
        where: where_clause,
        order: [order_field => :asc, work_date: :desc],
        per_page: 50,
        page: params[:page],
        load: false,
      )
    end
```

2023-11-07 04:48 UTC, apoorv1316 commented on app/services/reports/time_entries/report_service.rb
> +      order_field = case params[:group_by]
@prasanthchaduvula Done

2023-11-07 04:49 UTC, prasanthchaduvula approved these changes

2023-11-07 05:07 UTC, merged