UI: Edit page allocated devices
saeloun/miru-web pull request #1588
Opened 2023-11-08 10:52 UTC by Shruti-Apte

Closess issue #1533

2023-11-17 04:28 UTC, apoorv1316 commented
@Shruti-Apte Is it ready for review?

2023-11-21 10:09 UTC, prasanthchaduvula requested changes

2023-11-21 10:09 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Button.tsx
> +  style,
why the `primary` value is removed?

2023-11-21 10:09 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/Edit/EditPage.tsx
> +  <div className="mt-4 h-full bg-miru-gray-100 px-10">
return from this component for future debugging

2023-11-21 10:09 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/Edit/EditPage.tsx
> +              // handleOnChange={}
why these actions are commented out?

2023-11-22 04:16 UTC, Shruti-Apte commented on app/javascript/src/StyledComponents/Button.tsx
> +  style,
Because it was applying primary style to the buttons where it is not needed. 
for example in some places we are using `<Button>` component with it's own modified CSS but if we pass primary as a default value, it's combing the primary css style with modified css.

2023-11-22 10:52 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Button.tsx
> +  style,
By default, the primary style is needed. Update the Button component to overwrite the primary styles with the modified css from the importing component. Please check the Miru docs of the Button component https://docs.miru.so/contributing-guide/component-library/button
What I mean is whenever someone imports the Button component, then by default primary style should be loaded without passing any style prop

2023-11-22 10:55 UTC, prasanthchaduvula requested changes

2023-11-22 10:55 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/Edit/EditPage.tsx
> +            </React.Fragment>
`Fragment`. import it at the top

2023-11-22 10:55 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/Edit/EditPage.tsx
> +            <React.Fragment key={device.id}>
Import the Fragment but the ideal one is `<div> `

2023-11-22 10:55 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/UserDetail/AllocatedDevicesDetails/Edit/EditPage.tsx
> +          {devices.map(device => (
Destructure the values of devise

2023-11-24 10:24 UTC, prasanthchaduvula approved these changes

2023-11-24 10:25 UTC, merged