Add more invoice history actions
saeloun/miru-web pull request #1594
Opened 2023-11-17 06:52 UTC by apoorv1316

Notion
https://www.notion.so/saeloun/More-details-needs-to-be-displayed-in-the-view-history-panel-d005aac54b3040c697c092a224a1d3fb?d=1cfd0ea5f022496c9a3118c62ced62e7

What
- Show the email addresses of users for all actions
- Capture manual payment event
- Capture stripe payment event
- Add email addresses of all recipients on send_invoice action

2023-11-17 09:22 UTC, prasanthchaduvula requested changes

2023-11-17 09:22 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/ViewHistory/utils.ts
> +        if (Array.isArray(data.emails) && data.emails.length > 0) {
Move this logic to a function and call it here.

2023-11-17 09:22 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/ViewHistory/utils.ts
>          const time = calculateTime(
each case has the same return logic. Move the common logic to function and call it inside the each case

2023-11-20 07:37 UTC, apoorv1316 commented
@prasanthchaduvula Please review

2023-11-21 10:21 UTC, prasanthchaduvula requested changes

2023-11-21 10:21 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/ViewHistory/utils.ts
> +        Data.push({ message: partialPaymentMessage, time: partialPaymentTime });
Can't we use `processInvoiceEvent` here

2023-11-21 10:21 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/ViewHistory/utils.ts
> +        Data.push({ message: cancellationMessage, time: cancellationTime });
ditto

2023-11-21 10:21 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/ViewHistory/utils.ts
> +        Data.push({ message: failedPaymentMessage, time: failedPaymentTime });
ditto

2023-11-21 14:57 UTC, supriya3105 approved these changes
The requested functionality is implemented. However, will require testing to confirm the behaviour .

2023-11-23 06:53 UTC, prasanthchaduvula approved these changes

2023-11-23 07:02 UTC, merged