autogenerate invoice number & bugfixes
saeloun/miru-web pull request #1600
Opened 2023-12-06 09:12 UTC by apoorv1316

What
- Implemented autogenerate invoice number for mobile
- Bugfixes in clientSelction on both web & mobile
- Refactored the client_list partial

2023-12-06 12:09 UTC, prasanthchaduvula requested changes
Please delete `companies/_client_list.json.jbuilder`

2023-12-06 12:09 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/InvoiceDetails.tsx
> +  const list = companyClientList || clientList;
can you renames list to something with client

2023-12-07 04:34 UTC, apoorv1316 commented on app/javascript/src/components/Invoices/Generate/MobileView/Container/MenuContainer/InvoiceDetails.tsx
> +  const list = companyClientList || clientList;
done.

2023-12-07 09:33 UTC, apoorv1316 commented
@prasanthchaduvula I've fixed it. Please check.

2023-12-12 02:06 UTC, prasanthchaduvula approved these changes

2023-12-12 02:06 UTC, merged