Additional details for invitation email
saeloun/miru-web pull request #1609
Opened 2023-12-20 09:49 UTC by apoorv1316

Notion:

https://www.notion.so/saeloun/Backend-changes-Send-the-information-used-in-the-new-I-from-formatted-Invitation-email-39302fb836854979b7a200817de89167

2024-01-08 05:11 UTC, prasanthchaduvula requested changes

2024-01-08 05:11 UTC, prasanthchaduvula commented on app/models/invitation.rb
> +      company.users.where.not(id: users_with_client_role_ids)
Do we have to check all the users without client including the discarded ones or only kept records
`company.users..keptwhere.not`

2024-01-08 07:45 UTC, apoorv1316 commented on app/models/invitation.rb
> +      company.users.where.not(id: users_with_client_role_ids)
we want to display the count of employees in the org. Clients are included in employments but we don't want to count them.

2024-01-08 08:13 UTC, apoorv1316 commented on app/javascript/src/components/Authentication/ResetPassword/index.tsx
> +      setToLocalStorage("authEmail", res.data.user.email);
Added redirect

2024-01-08 12:03 UTC, prasanthchaduvula commented on app/models/invitation.rb
> +      company.users.where.not(id: users_with_client_role_ids)
I mean here we have to check kept users or all the users`company.users.kept`

2024-01-10 07:46 UTC, apoorv1316 commented on app/models/invitation.rb
> +      company.users.where.not(id: users_with_client_role_ids)
I found out the query was wrong. It was counting the invitations along with deleted ones. But we only want to show the employees. So the following query works and `kept`  is not required because we use `destroy` when deleting team members.
`company.employments.joins(user: :roles).where.not(roles: { name: "client" })`

2024-01-10 07:47 UTC, apoorv1316 commented
@prasanthchaduvula Please review again

2024-01-11 10:51 UTC, prasanthchaduvula commented on app/models/invitation.rb
> +      company.users.where.not(id: users_with_client_role_ids)
But I think it should be discarded.

2024-01-11 10:51 UTC, prasanthchaduvula approved these changes

2024-01-11 10:53 UTC, prasanthchaduvula commented on app/models/invitation.rb
> +      company.users.where.not(id: users_with_client_role_ids)
Please check the team members controller destroy action as its discard the employee

2024-01-11 12:32 UTC, merged