Add mark as paid
saeloun/miru-web pull request #1611
Opened 2023-12-27 04:45 UTC by adititipnis

<img width="302" alt="image" src="https://github.com/saeloun/miru-web/assets/10024684/b55ca37e-a0bf-4f31-a21d-97d119f8af30">

2023-12-27 06:09 UTC, apoorv1316 requested changes
@adititipnis Please fix the bugs
1. When trying to change the year or month for transaction date this is how the dropdown looks right now. Please fix the positioning and font sizes
<img width="1792" alt="Screenshot 2023-12-27 at 11 38 34 AM" src="https://github.com/saeloun/miru-web/assets/18750194/4cd1b0a3-e859-4cd6-8b2b-37efd8a474a2">
![Screenshot 2023-12-27 at 11 38 34 AM (2)](https://github.com/saeloun/miru-web/assets/18750194/9329ad93-1652-4829-a1ee-2eb5e3f52734)

2. Not able to change the transaction type

2024-01-04 12:33 UTC, JijoBose requested changes

2024-01-04 12:33 UTC, JijoBose commented on app/javascript/src/components/Invoices/Invoice/MarkInvoicePaidModal.tsx
> +                if (!transactionType) {
You can fix the transaction type in mobile view by replacing  isDisabled={showTransactionTypes} with 

```
<CustomReactSelect
              isDisabled
```

2024-01-05 09:35 UTC, adititipnis commented
> @adititipnis Please fix the bugs
> 
> 1. When trying to change the year or month for transaction date this is how the dropdown looks right now. Please fix the positioning and font sizes
> 
> <img alt="Screenshot 2023-12-27 at 11 38 34 AM" width="1792" src="https://private-user-images.githubusercontent.com/18750194/292968962-4cd1b0a3-e859-4cd6-8b2b-37efd8a474a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDY1OTUsIm5iZiI6MTcwNDQ0NjI5NSwicGF0aCI6Ii8xODc1MDE5NC8yOTI5Njg5NjItNGNkMWIwYTMtZTg1OS00Y2Q2LThiMmItMzdlZmQ4YTQ3NGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA5MTgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlYWI5ZWQzYmZjY2Q2MmZhYjAwNDExOTI1ZjMwMjMzNTcxOGNkMGNkYjA0NjZhMjQ3ZGZiNTNiNDcwM2ZiMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.29KhNtcDPKqGRbVa-rrg2DkmO-B0mC1QblDO-c-x0mU"> ![Screenshot 2023-12-27 at 11 38 34 AM (2)](https://github.com/saeloun/miru-web/assets/18750194/9329ad93-1652-4829-a1ee-2eb5e3f52734)
> 2. Not able to change the transaction type

Since the datepicker issue is present throughout the application for mobile, taking it up separately here https://www.notion.so/Fix-datepicker-month-and-year-dropdown-issue-on-mobile-devices-47fa4edc718c4c98a33011ecf9c8ae16

2024-01-05 09:35 UTC, JijoBose approved these changes

2024-01-05 10:49 UTC, apoorv1316 approved these changes

2024-01-05 10:50 UTC, merged