Refactor Payment entry forms
saeloun/miru-web pull request #1613
Opened 2023-12-27 13:26 UTC by JijoBose

Notion Link:
https://www.notion.so/Refactor-Components-dc63e7c61b9e47aa9b909f0b17166d69

**What**
  - Added Formik to Payment entry form
  - Removed state variables used for Form

2024-01-02 08:00 UTC, apoorv1316 requested changes
@JijoBose Not able to select transaction type option for mobile screens. Please check

2024-01-02 08:02 UTC, apoorv1316 commented
Also, the heading title of the modal is incorrect for mobile screens. @JijoBose 
![Screenshot 2024-01-02 at 1 31 39 PM](https://github.com/saeloun/miru-web/assets/18750194/dcc34956-10ff-4f8d-80f3-a78e7421dba7)

2024-01-03 10:47 UTC, JijoBose commented
@apoorv1316 I've fixed the mobile view issue

https://github.com/saeloun/miru-web/assets/13100108/57034bfa-2166-4742-8119-7ab6cdd68e6e

2024-01-05 06:56 UTC, apoorv1316 approved these changes

2024-01-05 06:57 UTC, merged