Refactor Time tracking page components
saeloun/miru-web pull request #1621
Opened 2024-01-05 11:08 UTC by sanjibroy360

2024-01-05 16:02 UTC, JijoBose requested changes

2024-01-05 16:02 UTC, JijoBose commented on app/javascript/src/components/TimesheetEntries/EntryCard.tsx
> +              text="unbilled"
Let's move this to a method

```
const UnBilledBadge = () => (
  <Badge
     bgColor="bg-miru-alert-yellow-400"
     className="uppercase"
     color="text-miru-alert-green-1000"
     text="unbilled"
   />
)



```

2024-01-05 16:02 UTC, JijoBose commented on app/javascript/src/components/TimesheetEntries/EntryCard.tsx
> +          {bill_status === "unbilled" ? (
Instead of ternary let's use 

```
{bill_status === "unbilled" && <UnbilledBadge />}
```

2024-01-05 16:04 UTC, JijoBose commented on app/javascript/src/components/TimesheetEntries/Header/index.tsx
> +        />
Can we remove unused props

2024-01-06 23:46 UTC, prasanthchaduvula requested changes

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/EntryCard.tsx
> +              text="unbilled"
```
import getStatusCssClass from "utils/getBadgeStatus";

<Badge
  className={`${getStatusCssClass(status)} uppercase`}
  text={status}
/>
```

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomDatePicker/index.tsx
> +  visibility?: boolean;
Move these prop types towards the end of the file for better Readability and consistency and keep the focus on the component's core functionality first.

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/DatesInWeek.tsx
> +            <button
if possible use the `<Button>` from `StyledComponents` in all the file changes wherever possible. Mostly we can do as the `Button` component accepts the custom styles

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/EmptyStatesMobileView.tsx
> +    <button
ditto
if possible use the <Button> from StyledComponents.

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/EntryCard.tsx
> +interface props {
ditto

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/EntryCard.tsx
> +      <button
ditto

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/EntryCard.tsx
> +const EntryCard: React.FC<props> = ({
Define the prop types at the end of the file and use them here.

```
const EntryCard = ({
  id,
  client,
  project,
  note,
  duration,
  handleDeleteEntry,
  setEditEntryId,
  bill_status,
  currentUserRole,
  setNewEntryView,
  handleDuplicate,
  wrapperClassName,
}: Iprops) => {
```

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/Header/CalendarNavigator/NavArrowBtn.tsx
> +const NavArrowBtn = ({ id, icon, handleClick }) => (
Design a style component for `NavBackButton` which will take a few props like icon, className and handleClick. Use it in these file changes wherever there is NavArrowBtn

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/MonthCalendar/index.tsx
> +import { useTimesheetEntries } from "../context/TimesheetEntriesContext";
`import { useTimesheetEntries } from "components/context/TimesheetEntriesContext";`

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/MonthCalendar/index.tsx
> +          {DAYS.map((d, index) => (
instead of `d` make it into `day`

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/SelectProject.tsx
> +      <button
ditto

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/SelectProject.tsx
> +      <button
ditto

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/TimeEntryForm/DesktopTimeEntryForm.tsx
> +import { BUTTON_STYLES } from "../../../StyledComponents/Button";
import { BUTTON_STYLES } from "StyledComponents/Button";

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/TimeEntryForm/DesktopTimeEntryForm.tsx
> +import { useTimesheetEntries } from "../context/TimesheetEntriesContext";
import { useTimesheetEntries } from "components/context/TimesheetEntriesContext";

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/TimeEntryForm/MobileEntryForm.tsx
> +import { useTimesheetEntries } from "../context/TimesheetEntriesContext";
ditto

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/TimeEntryForm/MobileEntryForm.tsx
> +import { useTimeEntryForm } from "./context/TimeEntryFormContext";
ditto
If possible keep all the contexts related to timesheet entries in one folder

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/TimeEntryForm/MobileEntryForm.tsx
> +import DeleteEntryModal from "../MobileView/DeleteEntryModal";
import DeleteEntryModal from "components/MobileView/DeleteEntryModal";

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/WeeklyEntriesCard.tsx
> +      Logger.error(error.message);
Dont use logger

2024-01-06 23:46 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/WeeklyEntriesCard.tsx
> +      Logger.error(error.message);
ditto

2024-01-09 07:23 UTC, JijoBose commented on app/javascript/src/components/TimesheetEntries/WeeklyEntries.tsx
> +    return ids;
Can we replace these ForEach loops with Map


```
const getIds = () => {
  return currentEntries
    .map(entry => entry && entry["id"])
    .filter(Boolean);
};
```

2024-01-09 07:37 UTC, sanjibroy360 commented on app/javascript/src/components/TimesheetEntries/WeeklyEntries.tsx
> +    return ids;
Yes Jijo, we can directly use `reduce` here instead of `forEach`.

```js
const getIds = () => {
    let ids = [];

    if (currentEntries?.length > 0) {
      ids = currentEntries.reduce((acc, entry) => {
        if (entry) acc.push(entry["id"]);
        return acc;
      }, []);
    }
    return ids;
  };
```

2024-01-09 07:54 UTC, JijoBose commented on app/javascript/src/components/TimesheetEntries/WeeklyEntries.tsx
> +    return ids;
I was trying to avoid using an additional variable to`push` array elements.

Instead we can also use something like this

```
const getIds = () => currentEntries.map(entry => entry && entry?.id);
```

2024-01-09 07:55 UTC, JijoBose commented on app/javascript/src/components/TimesheetEntries/WeeklyEntries.tsx
> +    return ids;
It returns an array of ID's

2024-01-09 08:17 UTC, sanjibroy360 commented on app/javascript/src/components/TimesheetEntries/WeeklyEntries.tsx
> +    return ids;
Done ✅

2024-01-09 08:52 UTC, JijoBose approved these changes

2024-01-09 09:51 UTC, prasanthchaduvula requested changes

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/NavArrowBtn.tsx
> +const NavArrowBtn = ({
If it is only for calendar navigation then keep it under that folder. it should not be part of component library

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/WeeklyEntriesCard.tsx
> +      Toastr.error(error.message);
Check this as it may render two toaster as we have one in api.ts

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/index.tsx
> +// /* eslint-disable no-unexpected-multiline */
uncomment it as we are not rendering it anymore.

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/EntryCard/index.tsx
> +}) => {
```
const EntryCard = ({
  id,
  client,
  project,
  note,
  duration,
  handleDeleteEntry,
  setEditEntryId,
  bill_status,
  currentUserRole,
  setNewEntryView,
  handleDuplicate,
}: Iprops) => {
```

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/EntryCard/utils.tsx
> +import { Roles } from "../../../constants";
import { Roles } from "constants/index";

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/EntryCard/utils.tsx
> +      <button
If possible use Button component from styled-components library

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/EntryCard/utils.tsx
> +      <button
ditto

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/WeeklyEntriesCard.tsx
> +          if (newState[res.data.entry.work_date]) {
destrcture work_date from res.

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/WeeklyEntriesCard.tsx
> +              <button
If possible use Button from styled components

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/WeeklyEntriesCard.tsx
> +                  UPDATE
ditto

2024-01-09 09:51 UTC, prasanthchaduvula commented on app/javascript/src/components/TimesheetEntries/WeeklyEntriesCard.tsx
> +                <button
ditto

2024-01-09 17:26 UTC, prasanthchaduvula approved these changes

2024-01-09 17:26 UTC, merged