Frontend: Time tracking page of PTO module
saeloun/miru-web pull request #1623
Opened 2024-01-08 10:33 UTC by sanjibroy360

2024-01-11 14:11 UTC, JijoBose requested changes

2024-01-11 14:11 UTC, JijoBose commented on app/javascript/src/components/TimeoffEntries/EntryCard/utils.tsx
> +  billStatus != "billed" || role == Roles["OWNER"] || role == Roles["ADMIN"];
- Let's move the "billed" to  "constants/index"
- There are many billStatus in the app, so let's import it from a constant.
- Please use !== and === for comparing

2024-01-11 16:01 UTC, sanjibroy360 commented on app/javascript/src/components/TimeoffEntries/EntryCard/utils.tsx
> +  billStatus != "billed" || role == Roles["OWNER"] || role == Roles["ADMIN"];
Done ✅

2024-01-12 07:02 UTC, apoorv1316 commented
@sanjibroy360 This is not looking good. We don't have second dropdown so its looking odd.
<img width="1400" alt="Screenshot 2024-01-12 at 12 31 12 PM" src="https://github.com/saeloun/miru-web/assets/18750194/17d49b13-739b-4d0a-8764-ad62a5bae669">

2024-01-12 08:33 UTC, JijoBose commented on app/javascript/src/components/TimeoffEntries/constants.ts
> +};
Can we move it to "constants/index"

2024-01-12 10:11 UTC, sanjibroy360 commented on app/javascript/src/components/TimeoffEntries/constants.ts
> +};
Done ✅

2024-01-12 10:19 UTC, JijoBose commented on app/javascript/src/constants/index.tsx
> +export const BILL_STATUS = {
Let's make it an `export enum`

2024-01-12 10:33 UTC, sanjibroy360 commented on app/javascript/src/constants/index.tsx
> +export const BILL_STATUS = {
Done ✅

2024-01-12 10:37 UTC, sanjibroy360 commented
> @sanjibroy360 This is not looking good. We don't have second dropdown so its looking odd. <img alt="Screenshot 2024-01-12 at 12 31 12 PM" width="1400" src="https://private-user-images.githubusercontent.com/18750194/296154436-17d49b13-739b-4d0a-8764-ad62a5bae669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTQ4MTEsIm5iZiI6MTcwNTA1NDUxMSwicGF0aCI6Ii8xODc1MDE5NC8yOTYxNTQ0MzYtMTdkNDliMTMtNzM5Yi00ZDBhLTg3NjQtYWQ2MmE1YmFlNjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEwMTUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NzNjMTVjNDZiNGFmZTI1MzgwOTYyNzI5NjZhMzRlOTE4ZGZiMDkwYTAyMDQ3NjJkYWQyZGRhOWZkNjI3ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ahLf3IN-SfT4zQWL5iAOsBkZIY27BxOBekZOOoil0sA">

Done ✅ 
Preview:  [https://youtu.be/IwV49S-JnOg](https://youtu.be/IwV49S-JnOg)

cc: @apoorv1316

2024-01-12 11:19 UTC, prasanthchaduvula commented
@apoorv1316 Please test the changes now

2024-01-15 04:00 UTC, apoorv1316 approved these changes

2024-01-15 09:00 UTC, merged