Expense module: UI and Integration
saeloun/miru-web pull request #1625
Opened 2024-01-09 10:57 UTC by Shruti-Apte

### What 
1. UI for all pages.
2. Expense list, add expense modal Integration
3. Mobile responsive pages.

Preview:
<img width="1478" alt="Screenshot 2024-01-09 at 4 23 12 PM" src="https://github.com/saeloun/miru-web/assets/72149587/79dcbc98-944e-461b-9f79-7d6f7f993d28">

<img width="567" alt="Screenshot 2024-01-09 at 4 22 42 PM" src="https://github.com/saeloun/miru-web/assets/72149587/b5550049-8a35-48b1-bc3a-28aedd1f16ae">

<img width="570" alt="Screenshot 2024-01-09 at 4 22 50 PM" src="https://github.com/saeloun/miru-web/assets/72149587/752b0616-e86c-4847-8387-0dd3b47af7f9">

<img width="852" alt="Screenshot 2024-01-09 at 4 23 26 PM" src="https://github.com/saeloun/miru-web/assets/72149587/8d515d95-5aa6-444f-80e3-3ac2512e6fcb">

<img width="1486" alt="Screenshot 2024-01-09 at 4 23 36 PM" src="https://github.com/saeloun/miru-web/assets/72149587/039d9263-5d57-42fd-b055-9f93b5dff9b8">

### What's Remaining
- Edit and delete functionality
- Expense summary API and integration
- PieChart

2024-01-11 05:43 UTC, apoorv1316 requested changes

2024-01-11 05:43 UTC, apoorv1316 commented on app/controllers/internal_api/v1/expenses_controller.rb
> +
Use the bang method ( update!)

2024-01-11 05:43 UTC, apoorv1316 commented on app/controllers/internal_api/v1/expenses_controller.rb
> +    render json: { notice: "Expense updated successfully" }, status: :ok
Use locales.

Example:     `render json: { notice: I18n.t("invitation.update.success.message") }, status: :ok`

2024-01-11 05:43 UTC, apoorv1316 commented on app/controllers/internal_api/v1/expenses_controller.rb
> +    @expense.destroy
Use bang method for destroy

2024-01-11 05:43 UTC, apoorv1316 commented on app/controllers/internal_api/v1/expenses_controller.rb
> +    render json: { notice: "Expense deleted successfully" }, status: :ok
Use locales

2024-01-12 08:08 UTC, JijoBose requested changes
<img width="554" alt="Screenshot 2024-01-12 at 1 38 08 PM" src="https://github.com/saeloun/miru-web/assets/13100108/982ac9a3-b465-40aa-bfc2-846df5abadcb">

2024-01-12 08:08 UTC, JijoBose commented on package.json
> +    "chart.js": "^4.1.2",
please push the changes added to `yarn.lock`

2024-01-16 06:19 UTC, JijoBose commented
@Shruti-Apte Filter button has no functionality, 
Should we remove it if it's not part of this Ticket?

2024-01-16 09:21 UTC, apoorv1316 commented
@Shruti-Apte Please work on changes discussed on call

2024-03-01 02:39 UTC, apoorv1316 requested changes
@Shruti-Apte Please fix the requested changes

2024-03-01 02:39 UTC, apoorv1316 commented on app/controllers/internal_api/v1/expenses_controller.rb
> +
this is incorrect. We have to authorize Expense here and not the private method

2024-03-01 02:39 UTC, apoorv1316 commented on app/controllers/internal_api/v1/expenses_controller.rb
> +    authorize set_expense
ditto

2024-03-01 11:00 UTC, nisusam requested changes

2024-03-01 11:00 UTC, nisusam commented on app/javascript/src/components/Expenses/Details/index.tsx
> +      {showEditExpenseModal && !isDesktop && (
Move this above `DeleteExpenseModal`

2024-03-01 11:00 UTC, nisusam commented on app/javascript/src/components/Expenses/List/Container/Table/MoreOptions.tsx
> +          onClick={e => {
If the button is disabled, do we need to add `onClick`?

2024-03-01 11:00 UTC, nisusam commented on app/javascript/src/components/Expenses/Modals/ExpenseForm.tsx
> +          <span>{Math.ceil(receipt.size / 1000)}kb</span>
This should be 1024.

2024-03-06 08:06 UTC, Shruti-Apte commented on app/javascript/src/components/Expenses/List/Container/Table/TableRow.tsx
> +          {isDesktop && (
No, It cannot be refactored into Ternary

2024-03-08 02:36 UTC, apoorv1316 approved these changes
Some requirements are yet to be implemented. Let's do it in upcoming PR.

2024-03-08 06:43 UTC, nisusam approved these changes

2024-03-08 06:46 UTC, merged