Mails styling reset password
saeloun/miru-web pull request #1651
Opened 2024-01-16 08:00 UTC by adititipnis

<img width="1786" alt="image" src="https://github.com/saeloun/miru-web/assets/10024684/94074fbc-9a74-48f0-926b-d63a8ba2a259">

2024-01-19 08:43 UTC, JijoBose requested changes
Lock icon missing from the mailer,

<img width="598" alt="Screenshot 2024-01-19 at 2 12 16 PM" src="https://github.com/saeloun/miru-web/assets/13100108/00d199ae-2ddd-44c7-9e68-900527d37c67">

2024-01-19 08:50 UTC, JijoBose submitted a review, later dismissed
<img width="599" alt="Screenshot 2024-01-19 at 2 19 12 PM" src="https://github.com/saeloun/miru-web/assets/13100108/79aae66f-cb12-46cc-91b1-7363e462ce8c">

2024-02-16 06:22 UTC, nisusam commented on app/assets/stylesheets/mailers.css
> +    text-align: center;
Duplicate.
Fix Indentation.

2024-02-16 06:24 UTC, nisusam commented on app/javascript/images/Banner Animation.svg
Remove this file if unused

2024-02-16 06:29 UTC, nisusam requested changes

2024-02-16 06:29 UTC, nisusam commented on app/javascript/images/Miru Logo With Text.svg
Remove this file if unused. Also please use filenames without spaces.

2024-03-01 02:31 UTC, apoorv1316 commented
@adititipnis Please work on review comments

2024-03-01 10:32 UTC, nisusam commented on app/assets/stylesheets/mailers.css
> +  text-align: center;
This is duplicate.

2024-03-01 10:33 UTC, nisusam commented on app/assets/stylesheets/mailers.css
> +      display: flex;
`display` property used couple of times

2024-03-01 10:33 UTC, nisusam approved these changes
Fix the comments. Rest LGTM!

2024-03-05 08:48 UTC, merged