Show total on accounts aging report base on filter
saeloun/miru-web pull request #1669
Opened 2024-02-26 07:21 UTC by apoorv1316

What
- Show the total on the bottom for selected clients only.

Before
<img width="1450" alt="Screenshot 2024-02-26 at 12 51 14 PM" src="https://github.com/saeloun/miru-web/assets/18750194/c85dfd4e-dbcb-4f5f-a94f-2ff1dac0b612">

After

<img width="1472" alt="Screenshot 2024-02-26 at 12 50 06 PM" src="https://github.com/saeloun/miru-web/assets/18750194/5967972a-bfd6-4d45-a843-39d2a3e7882b">

2024-02-26 07:37 UTC, nisusam reviewed
`Audit Gems` step is failing in CI

2024-02-27 06:03 UTC, apoorv1316 commented
@nisusam Please review

2024-02-27 06:25 UTC, nisusam requested changes

2024-02-27 06:25 UTC, nisusam commented on app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableTotal.tsx
> +      zero_to_thirty_days: 0,
Please update these values to float `0.0`

2024-02-27 07:15 UTC, apoorv1316 commented on app/javascript/src/components/Reports/AccountsAgingReport/Container/Table/TableTotal.tsx
> +      zero_to_thirty_days: 0,
done

2024-02-27 08:16 UTC, nisusam approved these changes

2024-02-27 08:17 UTC, merged