Redesign team list page
saeloun/miru-web pull request #1673
Opened 2024-02-27 06:31 UTC by Shruti-Apte

### What:
Redesign team list page

Preview:
<img width="1790" alt="Screenshot 2024-02-27 at 12 00 15 PM" src="https://github.com/saeloun/miru-web/assets/72149587/43860ba9-17c0-425a-ab1a-812cd8510c21">

2024-02-28 16:04 UTC, nisusam reviewed
Please rebase and also fix rubocop offense

2024-03-04 05:48 UTC, apoorv1316 requested changes
Please work on the requested changes

2024-03-04 05:48 UTC, apoorv1316 commented on app/javascript/src/components/Team/List/Table/TableRow.tsx
> +            {email}
Email should be in downcase like "supriya@example.com"

2024-03-04 05:48 UTC, apoorv1316 commented on app/javascript/src/components/Team/List/Table/TableRow.tsx
> +    return duration;
Please check if this can be done with date-fns

2024-03-04 05:48 UTC, apoorv1316 commented on app/javascript/src/components/Team/List/Header.tsx
> +        <button
Use common component

2024-03-04 05:48 UTC, apoorv1316 commented on app/javascript/src/components/Team/List/Table/MoreOptions.tsx
> +  item: any;
Avoid using any type

2024-03-04 05:48 UTC, apoorv1316 commented on app/javascript/src/components/Team/List/Table/MoreOptions.tsx
> +      <Button
Tooltip missing for delete

2024-03-06 04:46 UTC, apoorv1316 approved these changes

2024-03-06 06:11 UTC, nisusam requested changes

2024-03-06 06:11 UTC, nisusam commented on app/javascript/src/components/Team/List/Table/TableRow.tsx
> +    const daysDifference = differenceInCalendarDays(today, start);
Can you please use `intervalToDuration` instead of `differenceInCalendarDays`?
https://date-fns.org/v2.16.1/docs/intervalToDuration

2024-03-06 06:30 UTC, nisusam approved these changes
Fix & Ship!

2024-03-06 06:30 UTC, nisusam commented on app/javascript/src/components/Team/List/Table/TableRow.tsx
> +    const dur = intervalToDuration({ start, end: today });
Use `end: new Date()` over here, instead of creating a variable

2024-03-06 06:37 UTC, Shruti-Apte commented on app/javascript/src/components/Team/List/Table/TableRow.tsx
> +    const dur = intervalToDuration({ start, end: today });
I kept it for better readability

2024-03-06 06:37 UTC, merged