Add validation for non-billable projects
saeloun/miru-web pull request #1689
Opened 2024-03-06 13:51 UTC by apoorv1316

Notion
https://www.notion.so/saeloun/Bug-in-time-tracking-API-276920f24771433bb71695600d8aec2a

2024-03-12 05:58 UTC, nisusam requested changes

2024-03-12 05:58 UTC, nisusam commented on spec/models/timesheet_entry_spec.rb
> +    end
Also, add test cases for valid timesheet entries.

2024-03-20 06:06 UTC, apoorv1316 commented
@nisusam Please review

2024-03-20 06:25 UTC, nisusam approved these changes
Please rebase

2024-03-20 06:45 UTC, merged