Devices API
saeloun/miru-web pull request #1699
Opened 2024-03-12 07:47 UTC by apoorv1316

What
- Add insurance details to devices
- Add support for bulk operations

2024-06-10 06:18 UTC, nisusam requested changes

2024-06-10 06:18 UTC, nisusam commented on app/controllers/internal_api/v1/users/devices_controller.rb
> +        add_devices: [:device_type, :name, :serial_number, :is_insured, :insurance_bought_date, :insurance_expiry_date,
```RUBY
expected_attributes = [:device_type, :name, :serial_number, :is_insured, :insurance_bought_date, :insurance_expiry_date, specifications: [:processor, :ram, :graphics]]

add_devices: expected_attributes,
update_devices: expected_attributes + [:id]
remove_devices: []
```

2024-06-10 06:18 UTC, nisusam commented on app/models/device.rb
> +#  insurance_bought_date :date
Is `insurance_bought_date == insurance_start_date`?

2024-06-26 04:45 UTC, apoorv1316 commented on app/models/device.rb
> +#  insurance_bought_date :date
using insurance_activation_date now

2024-06-26 04:45 UTC, apoorv1316 commented on app/controllers/internal_api/v1/users/devices_controller.rb
> +        add_devices: [:device_type, :name, :serial_number, :is_insured, :insurance_bought_date, :insurance_expiry_date,
done

2024-06-26 05:12 UTC, nisusam approved these changes
Are we maintaining histories of insurance? Anyways, We can tackle it in a new PR.

Rest LGTM!

2024-06-26 05:19 UTC, merged