Leave types validations
saeloun/miru-web pull request #1702
Opened 2024-03-12 14:06 UTC by apoorv1316

Fixes #1700

2024-03-12 14:31 UTC, nisusam requested changes

2024-03-12 14:31 UTC, nisusam commented on app/models/leave_type.rb
> +        ["days", "per_year"] => 365,
`366` for leap year

2024-03-12 14:31 UTC, nisusam commented on app/models/leave_type.rb
> +        ["days", "per_quarter"] => 93,
`92`

2024-03-14 02:35 UTC, prasanthchaduvula commented on app/models/leave_type.rb
> +    def valid_allocation_combination
If possible move these validations to concerns

2024-03-14 13:57 UTC, nisusam commented on app/models/concerns/leave_type_validatable.rb
> +        ["weeks", "per_quarter"] => 13,
92 / 7 = 13.14

2024-03-14 13:57 UTC, nisusam commented on app/models/concerns/leave_type_validatable.rb
> +        ["weeks", "per_year"] => 52,
366 / 7 = 52.28

2024-03-14 13:58 UTC, nisusam approved these changes
Just rebase with `develop`

2024-03-14 14:18 UTC, merged