Leave balance issue days per month
saeloun/miru-web pull request #1703
Opened 2024-03-13 06:49 UTC by SiddharthShringi

Fixes #1693 
- Fixed the issue with days per month case.
- Now we are calculating the leave balance based on the user joining date as the start time and the present time as the end time for the current year.
- If the user joining date is the previous year, then we are showing the leave balance based on year start time till present time

https://www.loom.com/share/7bcc76797b7740eea5c674cf81f72ffe?sid=5e4cd9bf-c2c0-4fa9-9363-2283b2da59da

2024-03-13 10:23 UTC, apoorv1316 commented
@SiddharthShringi Can you please add loom video for this?

2024-03-14 02:54 UTC, prasanthchaduvula reviewed
Please check the formatting once as mentioned in the comment

2024-03-14 03:14 UTC, apoorv1316 approved these changes

2024-03-14 09:17 UTC, SiddharthShringi commented
@prasanthchaduvula, yes the organization date format would not affect the leave balance date format.

2024-03-14 10:22 UTC, nisusam requested changes

2024-03-14 10:22 UTC, nisusam commented on app/javascript/src/components/LeaveManagement/index.tsx
> +    const getLeaveBlanaceDateText = () => {
`Balance`

2024-03-14 10:22 UTC, nisusam commented on app/javascript/src/components/LeaveManagement/index.tsx
> +        date = new Date();
In which case, the current year not match with present year?

2024-03-14 10:22 UTC, nisusam commented on spec/services/timeoff_entries/index_service_spec.rb.rb
> +      service = service = TimeoffEntries::IndexService.new(user, company, params[:user_id], params[:year])
Redundant.

Also rename filename to single `.rb`

2024-03-14 10:40 UTC, SiddharthShringi commented on app/javascript/src/components/LeaveManagement/index.tsx
> +        date = new Date();
The `currentYear` variable is responsible for current year shown on the leave management page, it will change when we go to previous year leave balance.
And the presentYear is simply present year.

2024-03-14 11:40 UTC, nisusam approved these changes

2024-03-14 11:41 UTC, merged