Expense module remaining work
saeloun/miru-web pull request #1706
Opened 2024-03-13 07:57 UTC by Shruti-Apte

### Notion:
- https://www.notion.so/saeloun/Expense-module-remaining-work-126e0655da3f4e0fb54449a41850893b?pvs=4

### What: 
- Search expense
- Upload and Download multiple receipts
- Create vendor functionality 
- Removed static expense summary component
- Small UI changes

2024-03-14 03:30 UTC, prasanthchaduvula requested changes

2024-03-14 03:30 UTC, prasanthchaduvula commented on app/javascript/src/components/Expenses/Details/index.tsx
> +      {isLoading ? (
move this to if condition

2024-03-14 03:30 UTC, prasanthchaduvula commented on app/javascript/src/components/Expenses/Details/index.tsx
> +          {!isDesktop && showEditExpenseModal ? null : (
use && and remove null by altering condition

2024-03-14 03:30 UTC, prasanthchaduvula commented on Gemfile.lock
> +  x86_64-darwin-23
don't commit this change

2024-03-14 13:56 UTC, Shruti-Apte commented on app/javascript/src/components/Expenses/Details/index.tsx
> +          {!isDesktop && showEditExpenseModal ? null : (
No, this can not be refactored, If we use the altering condition, it breaks on mobile view. 
Returning null is necessary here.

2024-03-14 14:45 UTC, nisusam approved these changes
Fix the failing spec

2024-06-19 06:38 UTC, apoorv1316 approved these changes

2024-06-19 06:49 UTC, merged