Mark time off responsive
saeloun/miru-web pull request #1710
Opened 2024-03-13 15:00 UTC by prasanthchaduvula

### What
- Added mark time off feature on mobile with add, update, delete and duplicate operations.
- Fixed the leave date error on duplication of time off entry on the web.
- Fixed the work date error on duplication of timesheet entry on the web and mobile.
- Created EntryButton components and refactored the timesheet codebase.
- Updated the button component size styles so that we can override them with classnames.
- Refactored the maritime off forms and moved the complete logic into one component and only rendered forms in other components.

### Figma
https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?type=design&node-id=18953-141908&mode=design&t=RGTox1yJchcY1siY-0

### Demo
https://youtu.be/chHU2C-WTP8?feature=shared

2024-03-14 13:37 UTC, nisusam requested changes

2024-03-14 13:37 UTC, nisusam commented on app/javascript/src/components/TimeoffEntries/TimeoffForm/index.tsx
> +      const substraction = minToHHMM(minFromHHMM(hhmm));
Can we simplify this logic? Since the same code is used in both `handleDecreaseTime` and `handleIncreaseTime`.

Fix the typo `subtraction`.

2024-03-14 13:37 UTC, nisusam commented on app/javascript/src/components/TimeoffEntries/TimeoffForm/index.tsx
> +      const mint = minFromHHMM(duration);
use `minutes` instead

2024-03-15 05:37 UTC, nisusam requested changes

2024-03-15 05:37 UTC, nisusam commented on app/javascript/src/components/TimeoffEntries/TimeoffForm/index.tsx
> +  const incrementOrDecrementTime = (increment = true) => {
The function name and parameters passed are not in sync / confusing.

You can use `updateTime('increment')` or `updateTime('decrement')`

2024-03-15 06:07 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeoffEntries/TimeoffForm/index.tsx
> +  const incrementOrDecrementTime = (increment = true) => {
There is already a timeinput change method. Let's keep with iincrementOrDecrementTime time itself. will move them to the styled-components.

2024-03-15 06:25 UTC, nisusam approved these changes

2024-03-15 06:32 UTC, merged