Optional holiday lapses
saeloun/miru-web pull request #1727
Opened 2024-03-19 08:21 UTC by prasanthchaduvula

### What
- We can't apply for optional holiday more than the defined optional holidays. It will throw the following error message "You have exceeded the maximum number of permitted optional holidays". For example, if the admin defined one optional holiday for one quarter then the employee can apply for more than one optional holiday in the same quarter.

-  We can't apply for two holidays on the same day. It will throw the following error message "You are adding two holidays on the same day, please recheck".

2024-03-19 12:27 UTC, nisusam requested changes

2024-03-19 12:27 UTC, nisusam commented on app/models/timeoff_entry.rb
> +        total_optional_entries = optional_timeoff_entries.where(user:).count
`leave_date` should be filtered based on year

2024-03-20 05:50 UTC, prasanthchaduvula commented on app/models/timeoff_entry.rb
> +        total_optional_entries = optional_timeoff_entries.where(user:).count
We are filtering optional_timeoff_entries from holidays and holidays are unique for each year. The entries are getting filtered based on the holiday year.

2024-03-20 06:21 UTC, apoorv1316 approved these changes

2024-03-20 06:22 UTC, nisusam requested changes

2024-03-20 06:22 UTC, nisusam commented on app/models/timeoff_entry.rb
> +      no_of_allowed_optional_holidays = holiday_info&.holiday.no_of_allowed_optional_holidays
DRY `holiday_info&.holiday`

2024-03-20 06:22 UTC, nisusam commented on spec/models/timeoff_entry_spec.rb
> +      existing_timeoff_entry = create(
Use `before` block

2024-03-20 07:19 UTC, nisusam approved these changes

2024-03-20 07:25 UTC, merged