Refresh page after adding/editing team member
saeloun/miru-web pull request #1750
Opened 2024-03-22 04:15 UTC by Shruti-Apte

Closes issue #1741 

### What 
- Page refresh after add/edit/delete
- Compensation tab hidden from profile and team details
- Employment and devices tab added on team details

2024-03-26 13:09 UTC, prasanthchaduvula requested changes

2024-03-26 13:09 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/modals/AddEditMember.tsx
> +          setRefreshList(true);
ditto

2024-03-26 13:09 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/modals/DeleteMember.tsx
> +        setRefreshList(true);
ditto

2024-04-09 07:10 UTC, apoorv1316 commented
@prasanthchaduvula Please review again

2024-04-10 01:46 UTC, prasanthchaduvula requested changes

2024-04-10 01:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/modals/AddEditMember.tsx
> +          const updatedUser = res.data.invitation;
Create `updatedTeamList` function. Extract the below logic and call it inside the above if and this else conditions and pass the` res.data.user `or `res.data.invitation` as param.
```
teamList.map(member => {
            if (member.id === updatedUser.id) {
              return updatedUser;
            }

            return member;
          });
          setTeamList(updatedTeamList);
```

2024-04-10 01:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/modals/DeleteMember.tsx
> +        const updatedTeamList = teamList.filter(
create one function named `updatedTeamListAferDelete` with below code and pass `res.data.user.id` or `res.data.id` and call it inside the if and else conditions

```
teamList.filter(
          member => member.id !== id
        );
        setTeamList(updatedTeamList);
```

2024-04-10 05:14 UTC, prasanthchaduvula approved these changes

2024-04-10 05:19 UTC, merged