create invitation presenter
saeloun/miru-web pull request #1772
Opened 2024-03-28 05:14 UTC by apoorv1316

Why
- To send the created invitation in JSON response while adding team members.
- To resolve https://github.com/saeloun/miru-web/pull/1750#discussion_r1539194438

2024-03-28 06:34 UTC, prasanthchaduvula requested changes

2024-03-28 06:34 UTC, prasanthchaduvula commented on app/presenters/invitation_presenter.rb
> +      status: "INVITATION PENDING",
Instead of status value sending from the backend, let frontend use the whatever message they want to display. Its better to send the key   `accepted_at `

2024-03-28 06:36 UTC, apoorv1316 commented on app/presenters/invitation_presenter.rb
> +      status: "INVITATION PENDING",
Shruti asked me to send the same keys that are use in GET requests for teams. LMK if we have to change

2024-03-28 06:38 UTC, prasanthchaduvula commented on app/presenters/invitation_presenter.rb
> +      status: "INVITATION PENDING",
For status, we have to use `accepted_at `. On the frontend, they can display any message as the messages keep on changing.

2024-04-08 08:36 UTC, prasanthchaduvula requested changes

2024-04-08 08:36 UTC, prasanthchaduvula commented on app/presenters/team_presenter.rb
> +      user_employed_at_current_company && member.accepted_at
Use `accepted_at?` return boolean

2024-04-08 08:36 UTC, prasanthchaduvula commented on app/views/internal_api/v1/invitations/_invitation.json.jbuilder
> +  json.status invitation.accepted_at
Use `accepted_at? ` returns boolean

2024-04-08 08:49 UTC, prasanthchaduvula approved these changes

2024-04-08 09:06 UTC, merged