Fix address payload
saeloun/miru-web pull request #1820
Opened 2024-04-25 03:25 UTC by apoorv1316

Fixes 
https://saeloun-inc.sentry.io/issues/5250931858/?project=4504649746087936&query=is%3Aunresolved&referrer=issue-stream&stream_index=1

2024-04-25 06:34 UTC, nisusam commented on app/javascript/src/components/Clients/ClientForm/utils.ts
> -    errors.phone ||
Is this relevant to this PR?

2024-04-25 06:35 UTC, nisusam approved these changes

2024-04-25 06:37 UTC, nisusam reviewed
This is still pointing to ruby 3.2.2.
Please rebase with develop once

2024-04-25 06:51 UTC, apoorv1316 commented on app/javascript/src/components/Clients/ClientForm/utils.ts
> -    errors.phone ||
Not related to this bug

2024-04-25 13:46 UTC, prasanthchaduvula requested changes
LGTM.
Small suggestions

2024-04-25 13:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/ClientForm/utils.ts
> +    ? 0
`const addressIndex = isNewForm ? 0 : client.address?.id ?? 0;`

2024-04-25 13:46 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/ClientForm/utils.ts
> +  if (!isNewForm && client.address && client.address.id) {
```
if (!isNewForm && client?.address?.id) {
    formData.append(`${addressPrefix}[id]`, client.address.id);
}
```

2024-05-02 05:24 UTC, prasanthchaduvula approved these changes

2024-05-02 05:35 UTC, merged