UI: custom leaves
saeloun/miru-web pull request #1833
Opened 2024-05-09 06:34 UTC by Shruti-Apte

### 
closes #1795 

### Preview:
<img width="953" alt="Screenshot 2024-05-09 at 11 50 13 AM" src="https://github.com/saeloun/miru-web/assets/72149587/5ae68959-7f4a-43e1-834b-627942c236b8">

<img width="1065" alt="Screenshot 2024-05-09 at 12 01 40 PM" src="https://github.com/saeloun/miru-web/assets/72149587/7ec741aa-e5b3-4676-80e6-005d00d250da">

2024-05-16 07:48 UTC, nisusam commented
@Shruti-Apte Please resolve conflicts

2024-05-21 05:08 UTC, apoorv1316 commented
@nisusam I've resolved conflicts. Please have another look. @Shruti-Apte Backend code was updated. Please check if everything working as expected.

2024-05-27 06:22 UTC, nisusam requested changes

2024-05-27 06:22 UTC, nisusam commented on app/javascript/src/components/Profile/Organization/Leaves/Details/CustomTableRow.tsx
> +            <span>{emp.label}</span>{" "}
Remove `{" "}`

2024-05-31 10:54 UTC, nisusam approved these changes

2024-06-05 05:45 UTC, merged