Fix audit gems failure
saeloun/miru-web pull request #1921
Opened 2024-10-21 13:00 UTC by apoorv1316

2024-10-21 13:34 UTC, keshavbiswa approved these changes

2024-10-21 14:28 UTC, keshavbiswa requested changes

2024-10-21 14:28 UTC, keshavbiswa commented on Gemfile
> +gem "rails", "~> 7.1.3.4"
```suggestion
gem "rails", "~> 7.1.4"
```

2024-11-04 08:38 UTC, keshavbiswa commented
Tests are failing

2024-11-04 09:17 UTC, apoorv1316 commented
@keshavbiswa Please approve. I have fixed tests

2024-11-04 10:53 UTC, keshavbiswa approved these changes
LGTM!

2024-11-04 12:37 UTC, merged