Use react router for invoice page
saeloun/miru-web pull request #333
Opened 2022-04-26 08:36 UTC by apoorv-mishra

## Notion card
NA
## Summary

This PR moves implements routing for invoice page on FE
## Preview

![Screenshot 2022-04-22 at 8 01 38 PM](https://user-images.githubusercontent.com/15694566/165258333-4b684d84-a4f6-42d5-8742-a9a7b08193fc.png)

Fixes ☝️ 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have added automated tests for my code

2022-04-29 17:14 UTC, apoorv-mishra commented on app/controllers/internal_api/v1/invoices_controller.rb
> +        })
Removed altogether and handled in the view layer.

2022-05-02 08:43 UTC, supriya3105 approved these changes

2022-05-02 08:45 UTC, mohd-anas-ansari approved these changes

2022-05-03 03:33 UTC, shivamsinghchahar requested changes
@apoorv-mishra Please look at the comments below

2022-05-03 03:33 UTC, shivamsinghchahar commented on app/views/internal_api/v1/invoices/show.json.jbuilder
> +json.company do
Move client, company and invoice_line_items to partials

2022-05-03 03:33 UTC, shivamsinghchahar commented on app/views/internal_api/v1/invoices/show.json.jbuilder
> +  json.id invoice_line_item.id
`N+1` queries here, need to `includes(:invoice_line_items)` while fetching invoice from DB in `invoice` method.

2022-05-03 06:52 UTC, apoorv-mishra commented on app/views/internal_api/v1/invoices/show.json.jbuilder
> +json.company do
Fixed.

2022-05-03 06:52 UTC, apoorv-mishra commented on app/views/internal_api/v1/invoices/show.json.jbuilder
> +  json.id invoice_line_item.id
Fixed.

2022-05-03 08:06 UTC, supriya3105 commented
@shivamsinghchahar Apoorv has incorporated the feedback comments. Have a look and approve if the PR is good to be merged.

2022-05-03 08:12 UTC, shivamsinghchahar approved these changes
Just one small change, rest LGTM 🚀

2022-05-03 08:12 UTC, shivamsinghchahar commented on app/javascript/src/components/Invoices/Invoice/index.tsx
> +  const [invoice, setInvoice] = useState<any>();
Just one tiny change, the initial value should be `null`.
```suggestion
  const [invoice, setInvoice] = useState<any>(null);
```

2022-05-03 08:31 UTC, apoorv-mishra commented on app/javascript/src/components/Invoices/Invoice/index.tsx
> +  const [invoice, setInvoice] = useState<any>();
Fixed.

2022-05-03 08:43 UTC, merged