Project filter search
saeloun/miru-web pull request #345
Opened 2022-04-27 16:32 UTC by aniket-k-kaushik

## Notion card

API : http://127.0.0.1:3000/internal_api/v1/projects?search=Project_1_Client_1_saeloun_India&user_filter[]=1&client_filter[]=1

````json
{
    "projects": [
        {
            "id": 1,
            "name": "Project_1_Client_1_saeloun_India",
            "clientName": "client_1_saeloun_India",
            "isBillable": false,
            "minutesSpent": 2640.0,
            "teamMember": [
                "Vipul A M"
            ]
        }
    ],
    "clients": [
        {
            "id": 1,
            "name": "client_1_saeloun_India"
        },
        {
            "id": 2,
            "name": "client_2_saeloun_India"
        },
        {
            "id": 5,
            "name": "mMicrosoft"
        }
    ],
    "teamMembers": [
        {
            "id": 1,
            "userName": "Vipul A M"
        },
        {
            "id": 3,
            "userName": "Akhil G Krishnan"
        },
        {
            "id": 4,
            "userName": "Keshav Biswa"
        },
        {
            "id": 5,
            "userName": "Rohit Joshi"
        },
        {
            "id": 2,
            "userName": "Supriya Agarwal"
        }
    ]
}
````

TODO : Test are renaming, Approach discussion with senior developer remaining   

Added Search for projects
Added Client filter for projects 
Added User filter for projects

## Type of change

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-05-11 04:23 UTC, sudeeptarlekar requested changes

2022-05-11 04:23 UTC, sudeeptarlekar commented on app/controllers/internal_api/v1/projects_controller.rb
> +    # def projects
nit: remove if not being used anywhere

2022-05-11 04:23 UTC, sudeeptarlekar commented on app/models/company.rb
> +        if id == project.id
I see that we are using only first element from these arrays, check if we can stop further processing if we find project.

Please add `TODO: Optimize` for this operation, will check later when we have a time

2022-05-11 04:23 UTC, sudeeptarlekar commented on spec/models/company_spec.rb
> +      def project_detail_list(client_id = nil, user_id = nil, billable = nil, search)
Why have we written same method again? Can't we access `company.project_list`

2022-05-11 04:23 UTC, sudeeptarlekar commented on spec/models/company_spec.rb
> +          user_id, client_id, billable, search = nil
Please use `let` for these assignments, you can then tweak single value in context based on requirement.
e.g. you can only tweak `search` in next context. This way it will become much more cleaner.
Thoughts?

Please follow same comments for another method added

2022-05-16 05:21 UTC, aniket-k-kaushik commented on app/models/company.rb
> +        if id == project.id
I, akhil and keshav have already tried it, we couldn't find another way to optimise it. I will added TODO for now

2022-05-16 05:21 UTC, aniket-k-kaushik commented on app/controllers/internal_api/v1/projects_controller.rb
> +    # def projects
yes

2022-05-16 05:24 UTC, aniket-k-kaushik commented on spec/models/company_spec.rb
> +          user_id, client_id, billable, search = nil
yes, but in one of the examples, we have all the filters, which means we will have 11 lets, which rubocop doesn't allows, so keshav suggested this way.

2022-05-17 10:00 UTC, sudeeptarlekar commented on app/models/company.rb
> +        if id == project.id
Log the ticket in Notion as well for same.

2022-05-18 13:10 UTC, aniket-k-kaushik commented on spec/models/company_spec.rb
> +      def project_detail_list(client_id = nil, user_id = nil, billable = nil, search)
It's the model spec and we are testing project_list method only.

2022-05-18 16:39 UTC, sudeeptarlekar commented on spec/models/company_spec.rb
> +      def project_detail_list(client_id = nil, user_id = nil, billable = nil, search)
But why have we written duplicate method logic, if method is returning something, hardcode response and check if in spec

2022-05-19 08:29 UTC, aniket-k-kaushik commented on spec/models/company_spec.rb
> +      def project_detail_list(client_id = nil, user_id = nil, billable = nil, search)
we are using factory bot and faker gem,

2022-05-23 06:01 UTC, sudeeptarlekar commented on app/controllers/internal_api/v1/projects_controller.rb
> +    # def projects
?

2022-05-23 06:05 UTC, aniket-k-kaushik commented on app/controllers/internal_api/v1/projects_controller.rb
> +    # def projects
done

2022-05-23 17:36 UTC, merged