Adds ability to generate and send InvoicePDF as an attachment.
saeloun/miru-web pull request #346
Opened 2022-04-27 21:17 UTC by anasansari157

## Notion card

## Summary
Added generation of PDF AS attachment while mailing invoices.

## Preview

<img width="1728" alt="Screenshot 2022-04-28 at 2 46 04 AM" src="https://user-images.githubusercontent.com/25636554/165632640-bd720651-ca33-4662-9b76-9cf0f0b443d0.png">

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-04-28 05:48 UTC, apoorv1316 commented
@anasansari157 CI check failed.

2022-04-28 08:23 UTC, akhilgkrishnan reviewed
@anasansari157  Added some suggestions, also Can you add test for helpers and mailers.

2022-04-28 08:23 UTC, akhilgkrishnan commented on package.json
> +    "puppeteer": "^13.6.0",
why do we need puppeteer

2022-04-28 08:23 UTC, akhilgkrishnan commented on app/mailers/invoice_mailer.rb
>      mail(to: recipients, subject:)
add a reply to, with company email id

2022-04-28 08:36 UTC, anasansari157 commented on package.json
> +    "puppeteer": "^13.6.0",
It is a dependency for Grover`. We are using `Grover` for PDFs

2022-04-28 08:41 UTC, akhilgkrishnan commented on app/views/invoices/pdf.html.erb
> +          <th class="text-miru-dark-purple-600 font-normal text-xs text-right tracking-widest">L. TOTAL</th>
typo?

2022-04-28 09:30 UTC, anasansari157 commented on app/mailers/invoice_mailer.rb
>      mail(to: recipients, subject:)
We don't have email for companies.

2022-04-28 10:05 UTC, akhilgkrishnan commented on app/mailers/invoice_mailer.rb
>      mail(to: recipients, subject:)
We have

2022-04-28 10:09 UTC, akhilgkrishnan commented on app/mailers/invoice_mailer.rb
>      mail(to: recipients, subject:)
Ohh yes, we don't have. Can we add no-reply email id

2022-04-28 13:20 UTC, rohitjoshixyz commented on app/views/invoices/pdf.html.erb
> +            <%="#{invoice.client.company.base_currency} #{(sub_total + invoice["tax"].to_i - invoice["discount"].to_i)}"%>
Extract this calculation into a private method in the mailer

2022-05-04 06:57 UTC, apoorv1316 commented
@mohd-anas-ansari Have you fixed all the review comments on this PR?

2022-05-04 07:17 UTC, mohd-anas-ansari commented
@apoorv1316 Yes, all reviews have been addressed.

2022-05-04 07:32 UTC, rohitjoshixyz approved these changes
Some non-blocking comments, LGTM 🎉

2022-05-04 07:32 UTC, rohitjoshixyz commented on app/helpers/invoices_helper.rb
> +  def serializer(invoice_line_items)
Why is this method called serializer? It is returning a hash if I am not mistaken

2022-05-04 07:32 UTC, rohitjoshixyz commented on app/mailers/invoice_mailer.rb
> +                        "",
Move to a private method, difficult to read here

2022-05-04 07:32 UTC, rohitjoshixyz commented on app/mailers/invoice_mailer.rb
> +        company_logo: @invoice.client.company.logo.attached? ?
You have added association for invoice and company in this same PR, please use that `@invoice.company`

2022-05-04 07:41 UTC, shivamsinghchahar requested changes

2022-05-04 07:41 UTC, shivamsinghchahar commented on app/mailers/invoice_mailer.rb
> +        company_logo: @invoice.client.company.logo.attached? ?
Invoice generation is not the responsibility of the mailer. We should have a separate service for this.

2022-05-06 06:42 UTC, supriya3105 commented
@apoorv1316 Please test this .

2022-05-06 09:19 UTC, apoorv1316 commented
@shivamsinghchahar Please approve it so it can be merged.

2022-05-09 11:48 UTC, shivamsinghchahar approved these changes
LGTM🚀

2022-05-09 11:50 UTC, merged