Fixes unit_amount for zero_decimal_currencies
saeloun/miru-web pull request #353
Opened 2022-04-30 12:11 UTC by anasansari157

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-05-04 06:55 UTC, apoorv1316 commented
@shivamsinghchahar Can you please review this?

2022-05-04 07:20 UTC, rohitjoshixyz approved these changes
The code looks good, add a service spec for both scenarios zero decimal and normal currency

2022-05-04 07:23 UTC, rohitjoshixyz commented on app/services/invoice_payment/checkout.rb
> +      def calculate_amount
We can keep the method name as `unit_amount`

2022-05-04 07:37 UTC, shivamsinghchahar requested changes

2022-05-04 07:37 UTC, shivamsinghchahar commented on app/services/invoice_payment/checkout.rb
> +        end
We are using `money` gem, could you explore if there's a better way to handle it with that? If there is then we should have a method on the invoice model and use that, since this will be used at a lot of places, not just this particular service.

2022-05-05 09:19 UTC, shivamsinghchahar approved these changes
LGTM🚀

2022-05-05 09:21 UTC, merged