Deleted project visible bug
saeloun/miru-web pull request #361
Opened 2022-05-06 09:17 UTC by abinashpa

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-05-06 09:42 UTC, supriya3105 commented
@abinashpa The CI Checks are failing for this .

2022-05-09 15:08 UTC, supriya3105 approved these changes

2022-05-09 15:08 UTC, supriya3105 commented
@apoorv1316 Please test this @sudeeptarlekar Please review .

2022-05-10 06:23 UTC, apoorv1316 approved these changes

2022-05-10 08:45 UTC, sudeeptarlekar requested changes

2022-05-10 08:45 UTC, sudeeptarlekar commented on spec/models/client_spec.rb
> +            expect(client.project_details(time_frame)).to include(result)
Check if we can use `match_array` from rspec here.

2022-05-10 12:07 UTC, supriya3105 commented
@abinashpa Lets work on the review comments on priority and close this PR.

2022-05-10 15:29 UTC, sudeeptarlekar approved these changes
LGTM

2022-05-10 16:00 UTC, merged