Invoice settings added
saeloun/miru-web pull request #369
Opened 2022-05-10 07:31 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Payment-settings-on-New-Invoice-ade2b260124d48ff95bd0bed687a5b5c
## Summary

Invoice settings added on new invoice
## Preview

https://www.loom.com/share/9d4eb5931ea442c498c8a0abe5165be1
## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-05-10 07:45 UTC, onkar-saeloun requested changes

2022-05-10 07:45 UTC, onkar-saeloun commented on app/javascript/src/common/CustomToggle.tsx
> +        <div></div>
Why do we require an empty div ?

2022-05-10 07:45 UTC, onkar-saeloun commented on app/javascript/src/components/Invoices/Generate/Invoice_settings.tsx
> +                handleCheck={() => {}} // eslint-disable-line
do we need an empty function?

2022-05-10 07:45 UTC, onkar-saeloun commented on app/javascript/src/components/Invoices/Generate/Invoice_settings.tsx
> +                handleCheck={() => {}} // eslint-disable-line
same as above.

2022-05-10 07:45 UTC, onkar-saeloun commented on app/javascript/stylesheets/application.scss
> +	  -webkit-transform: translate3d( -50%, -50%, 0 );
I can see in most of the cases code is not indented/formatted properly if you are using VS Code you can indent selected content by using `cmd+k, cmd+f`. It will help others to visualize your code.

2022-05-10 07:53 UTC, Shruti-Apte commented on app/javascript/src/common/CustomToggle.tsx
> +        <div></div>
Yes, This div is required for converting checkbox into toggle button. added some css for this div

2022-05-10 07:55 UTC, Shruti-Apte commented on app/javascript/src/components/Invoices/Generate/Invoice_settings.tsx
> +                handleCheck={() => {}} // eslint-disable-line
Imported a common component .. will add some handling function once backed is ready.

2022-05-10 10:05 UTC, onkar-saeloun approved these changes

2022-05-11 07:08 UTC, ajinkyaa commented on app/javascript/stylesheets/application.scss
> +input[type="checkbox"].toggle  {
why not create a common class for `input[type="checbox"]`

you can create a `custom-checkbox` class

also do use SCSS `&` for self selection then add pseudo classes

2022-05-11 07:14 UTC, ajinkyaa commented on app/javascript/stylesheets/application.scss
> +  &_Container{
keep double underscore and it should be small letters

2022-05-12 06:59 UTC, apoorv1316 commented
@Shruti-Apte Please take latest pull from develop and re-run ci jobs again.

2022-05-12 08:08 UTC, supriya3105 commented
@apoorv1316 Please test this locally and merge if working properly.

2022-05-12 10:04 UTC, merged