Send button functionality invoice
saeloun/miru-web pull request #375
Opened 2022-05-12 07:22 UTC by ajinkyaa

Save and send the invoice on the generate-invoice page.

- Code review pending.
- Will have a call with Apoorv regarding the QA PR review before the merge.

2022-05-12 07:23 UTC, apoorv1316 commented
@ajinkyaa Please take the latest pull from develop and re-run ci jobs

2022-05-12 12:54 UTC, JijoBose commented on app/javascript/src/components/Invoices/Generate/Header.tsx
Do fix these linting errors

2022-05-12 12:54 UTC, JijoBose commented on app/javascript/src/components/Invoices/Generate/index.tsx
>  import Invoice_settings from "./Invoice_settings";
`./Invoice_settings` import should occur before import of `../../../mapper/generateInvoice.mapper`

2022-05-12 12:56 UTC, JijoBose requested changes
Do fix the `warnings` and `errors` from es-lint

2022-05-12 13:03 UTC, ajinkyaa commented
@JijoBose Yeah sorry came in after conflicts, resolved.

2022-05-12 13:22 UTC, JijoBose approved these changes

2022-05-13 09:06 UTC, apoorv1316 commented
@ajinkyaa As discussed please send another pr for sending the invoice after saving it as a draft.

2022-05-13 09:07 UTC, merged