Edit invoice
saeloun/miru-web pull request #381
Opened 2022-05-16 13:11 UTC by sudeeptarlekar

## Notion card
https://www.notion.so/saeloun/Edit-Invoice-05b8cca4cf234559a51c3d49f7c39573

## Summary
Added Edit invoice page

## Preview
![Edit Invoice](https://user-images.githubusercontent.com/23317691/168772331-68d22baa-d658-4c5f-adc4-5c15febf2409.png)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Test cases for APIs were already in place.

### Checklist:
- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-05-17 10:32 UTC, supriya3105 commented
@apoorv1316 Please test this PR.

2022-05-19 03:33 UTC, apoorv1316 requested changes
@onkar-saeloun Few concerns
1. The amount is showing wrong after clicking on the edit invoice button. You can see in the video the amount was 5000 but it's showing 10,000.
2. Even after changing the due date of an invoice it's showing I guess the default due date on the invoice edit page. Also, I was not able to change the due date on the edit invoice.
https://www.loom.com/share/41e0d39a7a604c3db0054940ebd8a747

2022-05-19 11:13 UTC, sudeeptarlekar commented
@apoorv1316 Fixed bugs, let me know if I am missing something.

2022-05-20 08:01 UTC, apoorv-mishra commented on app/views/internal_api/v1/invoices/edit.json.jbuilder
> +  json.partial! "internal_api/v1/partial/company", locals: { company: invoice.client.company }
Can we use url helpers here instead of hardcoding a string? `internal_api_v1_partial_company_path`?

2022-05-20 08:02 UTC, apoorv-mishra commented on app/views/internal_api/v1/invoices/edit.json.jbuilder
> +  json.partial! "internal_api/v1/partial/invoice_line_item", locals: { invoice_line_item: }
ditto!

2022-05-20 08:02 UTC, apoorv-mishra commented on app/views/internal_api/v1/invoices/edit.json.jbuilder
> +  json.partial! "internal_api/v1/partial/client_list", locals: { client: }
ditto!

2022-05-20 08:03 UTC, apoorv-mishra commented on app/views/internal_api/v1/invoices/edit.json.jbuilder
> +json.partial! "internal_api/v1/partial/invoice", locals: { invoice: }
Can we use url helpers here instead of hardcoding a string? `internal_api_v1_partial_company_path`?

2022-05-20 10:05 UTC, sudeeptarlekar commented on app/views/internal_api/v1/invoices/edit.json.jbuilder
> +json.partial! "internal_api/v1/partial/invoice", locals: { invoice: }
It's a file path and not an URL, I'm not sure how helper can be used here? Will check though

2022-05-20 11:12 UTC, apoorv-mishra commented on app/views/internal_api/v1/invoices/edit.json.jbuilder
> +  json.partial! "internal_api/v1/partial/company", locals: { company: invoice.client.company }
Oops! My bad. Ignore then.

2022-05-20 11:13 UTC, apoorv-mishra approved these changes
LGTM after resolving conflicts.

2022-05-23 09:14 UTC, supriya3105 commented
@sudeeptarlekar Please resolve the conflicts on this PR.

2022-05-23 09:50 UTC, apoorv1316 commented
@sudeeptarlekar This still has bugs on editing discount. Please see the loom video https://www.loom.com/share/006958646bdf4a6eb3e1e980baadd316

2022-05-23 17:37 UTC, merged