Invoice email design
saeloun/miru-web pull request #384
Opened 2022-05-17 10:36 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Clients-should-be-able-to-view-invoices-from-email-Frontend-01b4088de4cf4f3bac5524802a65782d
## Summary

Designed Invoice Email page

## Preview

![emailInvoice](https://user-images.githubusercontent.com/72149587/168787858-273c8d9c-8856-40a4-a390-930bcddb3038.png)
## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-05-17 11:55 UTC, akhilgkrishnan commented on app/views/layouts/mailer.html.erb
> +
Are we planning to use the same design for all the emails from Miru. If not please remove the uncommon styles to invoice.html.erb itself

2022-05-17 12:25 UTC, Shruti-Apte commented on app/views/layouts/mailer.html.erb
> +
Not sure if we are using this for all email designs

2022-05-17 12:30 UTC, shivamsinghchahar commented on app/views/layouts/mailer.html.erb
> +
This layout file should contain only the common styles which can be used by other mailers e.g. color classes, container classes, etc.,

The specific styles like amount, details_title, etc., belong to the `../invoice_mailer/invoice.html.erb` file.

2022-05-27 05:05 UTC, apoorv1316 commented
@Shruti-Apte Few concerns
1. Any idea why I can't see Saeloun and Miru logo in my local. You can see there is no logo in the image.
2. Also, why the currency symbol is not being displayed with the amount.
3. On the view invoice page the footer is not fixed to the bottom and it looks odd at my screen resolution.
<img width="1792" alt="Screenshot 2022-05-27 at 10 17 56 AM" src="https://user-images.githubusercontent.com/18750194/170631370-d8547a10-7468-4bc4-b0a8-1084e87a6d31.png">
<img width="1792" alt="Screenshot 2022-05-27 at 10 26 49 AM" src="https://user-images.githubusercontent.com/18750194/170632116-5f82141c-20af-4273-9bf2-3afb17cda1ba.png">

2022-05-27 08:08 UTC, Shruti-Apte commented
> Why are there so many commits and file changes? You may want to cherry-pick your changes or raise the PR on another base branch

Yes Actually my laptop was crashing continuously ..was facing issues like "bad object head" with git so used few commands to fix it like  " git reset --hard head" and had to rebase it with develop ! That may have been caused this issue according to me!

I will raise a PR on another base branch, and will make sure this doesn't happen next time !

2022-05-30 07:10 UTC, supriya3105 requested changes
Change the date format to dd-mm-yyyy at all the places
Logo and company name should be dynamic on invoice email
Remove print and download from client invoice view
Remove pay via paypal
The stripe payment link is not working.

2022-05-30 11:53 UTC, supriya3105 commented
@apoorv1316 Please test your review comments. I have tested it on Shruti's local and except for the currency symbol everything is working. Added the currency symbol to another Notion card.

2022-05-30 11:55 UTC, apoorv1316 commented
@supriya3105 We can merge it then. I'll approve it.

2022-05-30 11:55 UTC, apoorv1316 approved these changes

2022-05-30 13:45 UTC, supriya3105 commented
Closing this as new PR has been raised.

2022-05-30 13:45 UTC, closed without merging