client search enhancements
saeloun/miru-web pull request #387
Opened 2022-05-18 09:02 UTC by ajinkyaa

development screenshot:
<img width="1236" alt="Screenshot 2022-05-18 at 2 31 01 PM" src="https://user-images.githubusercontent.com/6236169/169001018-eaacb724-7517-47e7-be0d-80c5159a32d7.png">

figma:
https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?node-id=1839%3A32953

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-05-18 09:14 UTC, JijoBose commented on app/javascript/src/components/Clients/List/AutoComplete.tsx
> +            return <div></div>
can we use `return null` instead of empty <div> ?

2022-05-18 09:19 UTC, JijoBose commented on app/javascript/src/components/Clients/List/AutoComplete.tsx
> +            <h5 style={{ padding: "8px", textAlign: "center", color: '#A5A3AD', fontSize: '20px', fontWeight: '600' }}>
<h5> won't be required if we are changing the font size, maybe we could use a paragraph  tag or  React Fragment

2022-05-18 09:20 UTC, JijoBose requested changes
Please fix the ES-Lint warnings

2022-05-18 14:36 UTC, JijoBose approved these changes

2022-05-18 14:38 UTC, JijoBose requested changes
Please fix the failing tests

2022-05-19 04:17 UTC, ajinkyaa commented
@JijoBose resolved.

2022-05-19 07:49 UTC, merged