An external user should not be able to modify invoice URL to view any invoice in Miru.
saeloun/miru-web pull request #422
Opened 2022-05-30 07:35 UTC by aniket-k-kaushik

## Notion card
https://saeloun.notion.site/An-external-user-should-not-be-able-to-modify-invoice-URL-to-view-any-invoice-in-Miru-940481f83c804debbc448855a759a673

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have added automated tests for my code

2022-05-30 09:57 UTC, akhilgkrishnan commented on app/controllers/internal_api/v1/invoices_controller.rb
> +    external_view_key = "#{[*'a'..'z', *0..9, *'A'..'Z'].shuffle.join}_#{Time.now.to_i}_#{current_user.id}"
use Securerandom for generating the keys

2022-06-01 06:01 UTC, supriya3105 commented
@aniket-k-kaushik Please resolve the conflicts . @apoorv-mishra @akhilgkrishnan Please review the PR.

2022-06-02 11:55 UTC, apoorv-mishra requested changes

2022-06-02 11:55 UTC, apoorv-mishra commented on app/controllers/internal_api/v1/invoices_controller.rb
> +      invoice: @client.invoices.create!(invoice_params.merge(external_view_key:)),
Use [callbacks](https://guides.rubyonrails.org/active_record_callbacks.html#available-callbacks)(`before_create` in this case) to set `external_view_key` in your model instead of controller. Refer [this](https://github.com/saeloun/miru-web/blob/15548ff5d1809fec64bffd7d9a98177d12222f66/app/models/stripe_connected_account.rb#L26-L28) for help.

2022-06-02 11:55 UTC, apoorv-mishra commented on db/migrate/20220530064957_add_external_view_key_to_inovice.rb
> +class AddExternalViewKeyToInovice < ActiveRecord::Migration[7.0]
Fix the typo `AddExternalViewKeyToInovice` -> `AddExternalViewKeyToInvoice`.

2022-06-02 11:55 UTC, apoorv-mishra commented on spec/requests/internal_api/v1/invoices/create_spec.rb
> +require "securerandom"
Is this `require` needed? If not, you may get rid of it.

2022-06-02 11:55 UTC, apoorv-mishra commented on spec/requests/invoices/view_spec.rb
> +require "securerandom"
Ditto!

2022-06-02 11:55 UTC, apoorv-mishra commented on app/controllers/internal_api/v1/invoices_controller.rb
> +require "securerandom"
Is this needed? If not, you may get rid of it.

2022-06-02 13:36 UTC, aniket-k-kaushik commented on app/controllers/internal_api/v1/invoices_controller.rb
> +      invoice: @client.invoices.create!(invoice_params.merge(external_view_key:)),
OK

2022-06-02 13:36 UTC, aniket-k-kaushik commented on db/migrate/20220530064957_add_external_view_key_to_inovice.rb
> +class AddExternalViewKeyToInovice < ActiveRecord::Migration[7.0]
OK

2022-06-03 05:25 UTC, apoorv-mishra requested changes

2022-06-03 05:25 UTC, apoorv-mishra commented on db/migrate/20220530064957_add_external_view_key_to_invoice.rb
> +    add_column :invoices, :external_view_key, :string
Better to add a `unique` constraint here. Refer [this](https://github.com/saeloun/miru-web/blob/a7addd4025433074fb35fd55737ce33c809b0df3/db/migrate/20220309073708_create_invoices.rb#L23)

2022-06-03 08:44 UTC, apoorv-mishra requested changes

2022-06-03 08:44 UTC, apoorv-mishra commented on app/models/invoice.rb
> +  validates :external_view_key, uniqueness: true
Not in the model. It needs to be added in migration.

2022-06-03 08:54 UTC, aniket-k-kaushik commented on app/models/invoice.rb
> +  validates :external_view_key, uniqueness: true
ok

2022-06-03 10:57 UTC, apoorv-mishra approved these changes
LGTM!

2022-06-09 05:37 UTC, supriya3105 commented
@apoorv1316 Can you get this tested on someone else's system today.

2022-06-13 09:35 UTC, rohitjoshixyz reviewed
This looks good but we could potentially use UUID which is more conventional way of achieving the same https://pawelurbanek.com/uuid-order-rails @aniket-k-kaushik @apoorv-mishra @akhilgkrishnan @sudeeptarlekar

2022-06-14 11:11 UTC, apoorv1316 approved these changes

2022-06-14 11:12 UTC, apoorv1316 commented
@supriya3105 I have approved it.

2022-06-14 11:58 UTC, merged