Add Book Keeper Role
saeloun/miru-web pull request #465
Opened 2022-06-11 19:16 UTC by aniket-k-kaushik

## Notion card

https://www.notion.so/saeloun/Add-Book-keeper-role-2202d380771845bfbf23fb781afc29ae

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have added automated tests for my code

2022-06-14 07:46 UTC, rohitjoshixyz requested changes
Nice work @aniket-k-kaushik with the spec coverage. Added few comments

2022-06-14 07:46 UTC, rohitjoshixyz commented on app/controllers/users/sessions_controller.rb
> +    end
Convert to switch case

2022-06-14 07:46 UTC, rohitjoshixyz commented on app/controllers/users/sessions_controller.rb
>      # end
Remove this

2022-06-14 07:46 UTC, rohitjoshixyz commented on app/models/user.rb
> +  end
We have created separate methods to check role, I don't think creating new methods for all combinations is a good idea.
Add one method for employee role and we can then use
`has_owner_or_admin_role? || has_employee_role?` in the policy which is equivalent to the above method

2022-06-14 07:46 UTC, rohitjoshixyz commented on app/policies/application_policy.rb
> +  end
Adding so many methods for combinations is confusing, reuse individual methods as mentioned in above comment

2022-06-14 07:46 UTC, rohitjoshixyz commented on app/views/partial/_navbar.html.erb
> +        <% if policy(:timesheet_entry).index? %>
This is too much repetition. Let's use a helper method to render the navbar. It will return a hash with the title and path of the authorized nav links and then we can iterate it here cc @apoorv-mishra @akhilgkrishnan @keshavbiswa

2022-06-14 07:46 UTC, rohitjoshixyz commented on spec/requests/internal_api/v1/clients_controller_spec.rb
> +    context "when user is an book keeper" do
```suggestion
    context "when user is a book keeper" do
```
Check for grammar in all spec descriptions. I see the B of book keeper is unnecessarily capitalized at some places

2022-06-14 07:49 UTC, akhilgkrishnan commented on app/controllers/root_controller.rb
> +    # end
Why this commented? And what happen if the user is admin or owner

2022-06-14 07:49 UTC, akhilgkrishnan commented on app/controllers/users/sessions_controller.rb
>      # end
why these all are commented?

2022-06-14 07:49 UTC, akhilgkrishnan commented on app/models/user.rb
> +
can we move all these methods to a concern?

2022-06-14 07:53 UTC, akhilgkrishnan commented on app/policies/timesheet_entry_policy.rb
> +    user_owner_or_admin_or_employee?
why we are not allowing the bookkeeper from timesheet?

2022-06-14 07:54 UTC, apoorv-mishra commented on app/views/partial/_navbar.html.erb
> +        <% if policy(:timesheet_entry).index? %>
Makes sense, but in a separate PR IMO.

2022-06-14 08:05 UTC, keshavbiswa reviewed
Reviewed most of the codes except the tests and added few comments

2022-06-14 08:05 UTC, keshavbiswa commented on app/controllers/users/sessions_controller.rb
> +    end
Also we can DRY this bit of code out.

2022-06-14 08:09 UTC, apoorv-mishra commented on app/models/user.rb
> +  end
Agree. This creates confusion. [KISS](https://en.wikipedia.org/wiki/KISS_principle) please! `is_owner_or_admin?`, `is_employee?` & `is_bookkeeper?` is fine.

2022-06-14 08:09 UTC, apoorv-mishra commented on app/controllers/root_controller.rb
> +
Why comments?

2022-06-14 08:23 UTC, aniket-k-kaushik commented on app/controllers/users/sessions_controller.rb
>      # end
@supriya3105  Suggest to redirect all users to time-sheet page temporally as we don't have dashboard yet so, once the dashboard is done, we can comment these lines and remove the current conditions. 
```
if resource.has_book_keeper_role?(current_company)
      payments_path
    else
      time_tracking_index_path
    end
```

2022-06-14 08:24 UTC, aniket-k-kaushik commented on app/controllers/users/sessions_controller.rb
> +    end
OK

2022-06-14 08:25 UTC, aniket-k-kaushik commented on app/models/user.rb
> +  end
OK, will look into it.

2022-06-14 08:26 UTC, aniket-k-kaushik commented on app/policies/application_policy.rb
> +  end
ok

2022-06-14 08:26 UTC, rohitjoshixyz commented on app/controllers/users/sessions_controller.rb
>      # end
We can add the commented code later if needed, it's simple enough but having unused commented code is bad practice

2022-06-14 08:27 UTC, aniket-k-kaushik commented on app/views/partial/_navbar.html.erb
> +        <% if policy(:timesheet_entry).index? %>
OK

2022-06-14 08:28 UTC, aniket-k-kaushik commented on app/controllers/users/sessions_controller.rb
>      # end
Supriya Suggested to redirect all users to time-sheet page temporally as we don't have dashboard yet so, once the dashboard is done, we can uncomment these lines and remove the current conditions.

2022-06-14 08:28 UTC, aniket-k-kaushik commented on app/models/user.rb
> +
ok

2022-06-14 08:29 UTC, aniket-k-kaushik commented on app/policies/timesheet_entry_policy.rb
> +    user_owner_or_admin_or_employee?
Not sure about this, but as requirement, book keeper only has the access to invoice and payment index page

2022-06-14 08:30 UTC, aniket-k-kaushik commented on app/controllers/root_controller.rb
> +
ok

2022-06-14 08:34 UTC, aniket-k-kaushik commented on app/controllers/root_controller.rb
> +
will remove it

2022-06-14 11:54 UTC, aniket-k-kaushik commented on app/controllers/users/sessions_controller.rb
>      # end
ok, I will remove it

2022-06-14 19:50 UTC, aniket-k-kaushik commented
> Nice work @aniket-k-kaushik with the spec coverage. Added few comments

thanks

2022-06-15 06:27 UTC, rohitjoshixyz approved these changes
LGTM 🎉  perform a self-review of the code before merging. There are many minor changes in the specs similar to the ones I have commented.

2022-06-15 06:27 UTC, rohitjoshixyz commented on spec/requests/internal_api/v1/timesheet_entries/update_spec.rb
> +
Remove this

2022-06-15 06:27 UTC, rohitjoshixyz commented on spec/requests/payment_settings/refresh_stripe_connect_spec.rb
> +  context "when the user is an book keeper" do
Check grammar
```suggestion
  context "when the user is a book keeper" do
```

2022-06-15 06:40 UTC, aniket-k-kaushik commented on spec/policies/payments/provider_policy_spec.rb
>      it "denies permission to employee" do
I choose the one, which are used for admin, owner and employee in the same specs

2022-06-15 06:40 UTC, aniket-k-kaushik commented on spec/policies/invoice_policy_spec.rb
> +    it "grants permission to an admin and employee" do
will fix it

2022-06-15 06:41 UTC, aniket-k-kaushik commented on spec/policies/project_policy_spec.rb
> +  end
ok

2022-06-15 06:59 UTC, keshavbiswa commented on app/models/concerns/user_roles.rb
> +      self.has_cached_role?("#{role}".to_sym, company)
```suggestion
      self.has_cached_role?(role.to_sym, company)
```

2022-06-15 07:11 UTC, aniket-k-kaushik commented on spec/requests/clients/destroy_spec.rb
> +        send_request(:delete, "/internal_api/v1/clients/#{client.id}")
ok

2022-06-15 07:12 UTC, aniket-k-kaushik commented on spec/requests/payment_settings/refresh_stripe_connect_spec.rb
> +  context "when the user is an book keeper" do
they are at so many places

2022-06-15 07:26 UTC, aniket-k-kaushik commented on app/models/concerns/user_roles.rb
> +      self.has_cached_role?("#{role}".to_sym, company)
removing the user_roles concerns

2022-06-15 07:26 UTC, aniket-k-kaushik commented on spec/requests/internal_api/v1/timesheet_entries/update_spec.rb
> +
ok

2022-06-15 07:38 UTC, apoorv-mishra commented on app/policies/application_policy.rb
> +      user.has_cached_role?("#{role}".to_sym, resource)
```suggestion
      user.has_cached_role?(role.to_sym, resource)
```

2022-06-15 07:38 UTC, apoorv-mishra commented on app/controllers/users/sessions_controller.rb
> +    resource.has_book_keeper_role?(current_company) ? payments_path : time_tracking_index_path
Could you refactor as follows?
```rb
def after_sign_in_path_for(user)
  if user.has_role?(:owner) && user.companies.empty
    new_company_path
  elsif user.has_book_keeper_role?(current_company)
    payments_path
  else
    time_tracking_index_path
  end
end
```
It's generally better to optimize for readability instead of number of lines.

2022-06-15 07:46 UTC, aniket-k-kaushik commented on app/policies/application_policy.rb
> +      user.has_cached_role?("#{role}".to_sym, resource)
done

2022-06-15 08:50 UTC, keshavbiswa commented on app/models/concerns/user_roles.rb
> +      self.has_cached_role?("#{role}".to_sym, company)
What exactly didn't work?

2022-06-15 08:57 UTC, aniket-k-kaushik commented on app/controllers/users/sessions_controller.rb
> +    resource.has_book_keeper_role?(current_company) ? payments_path : time_tracking_index_path
done

2022-06-15 09:15 UTC, aniket-k-kaushik commented on app/models/concerns/user_roles.rb
> +      self.has_cached_role?("#{role}".to_sym, company)
has_admin_role? in the session_controller.rb gave an error, when I removed the user_roles.rb concern

2022-06-15 09:16 UTC, aniket-k-kaushik commented on app/models/concerns/user_roles.rb
> +      self.has_cached_role?("#{role}".to_sym, company)
undefined method `has_book_keeper_role?

2022-06-15 09:37 UTC, keshavbiswa commented on app/models/concerns/user_roles.rb
> +      self.has_cached_role?("#{role}".to_sym, company)
Yes obviously, you will need to use the function `rolify` provides.

2022-06-15 10:14 UTC, aniket-k-kaushik commented on app/models/concerns/user_roles.rb
> +      self.has_cached_role?("#{role}".to_sym, company)
done with the changes

2022-06-15 10:29 UTC, keshavbiswa approved these changes
LGTM!

2022-06-15 10:40 UTC, merged