Buy plan page
saeloun/miru-web pull request #466
Opened 2022-06-13 04:47 UTC by Shruti-Apte

## Notion card

https://www.notion.so/saeloun/Develop-the-Plan-details-page-5dae88a09c1f48b0a9d22707161ac81a

## Summary

- Designed Buy plan page 
- Functions for calculating amount added

## Preview

https://www.loom.com/share/43341e2b03b64265a6a469053847759d

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-06-13 17:38 UTC, onkar-saeloun requested changes
@Shruti-Apte Please let me know in case of any issue.

2022-06-13 17:38 UTC, onkar-saeloun commented on app/javascript/src/components/PlanDetails/index.tsx
> +                type="text"
Why we are taking input type as text and not as number. If we use input type number you don't need to write logic for parsing the text as well you can set min property too.

2022-06-13 17:38 UTC, onkar-saeloun commented on app/javascript/src/components/PlanDetails/index.tsx
> +        Toastr.error("Please enter valid data");
Ideally toaster should be displayed when you need to show some notifications or after an API call to show response status. We shouldn't use toaster on onChange method here you can handle error state like 
`const [error, setError] = useState<string>("")` 
and show it in `p` tag with danger colour below your inputbox to show error.

2022-06-13 17:38 UTC, onkar-saeloun commented on app/javascript/src/components/PlanDetails/index.tsx
> +        Toastr.error("Number of team members can not be zero");
You can use Yup validation here or simply use min property if feasible.

2022-06-13 17:38 UTC, onkar-saeloun commented on app/javascript/src/components/PlanDetails/index.tsx
> +        setPlanTotal(count * 5 + 10);
Please don't hardcode the amount lets say your basic_plan_charge = 10 and team_member_charge = 5 then make a file in constant folder and keep it over there. Your initial state value should be also come from the calculation 
`const [planTotal, setPlanTotal] = useState<number>(basic_plan_charge + team_member_charge);`
If the values will come from database then please ignore the comment.

2022-06-14 05:30 UTC, Shruti-Apte commented on app/javascript/src/components/PlanDetails/index.tsx
> +                type="text"
Yes.. But if I use type=number down and up arrows are also getting displayed which are not there in our designs. 
Is there any other way to remove those default css other than webkits.

2022-06-14 05:31 UTC, Shruti-Apte commented on app/javascript/src/components/PlanDetails/index.tsx
> +        Toastr.error("Please enter valid data");
Okay

2022-06-14 08:34 UTC, onkar-saeloun commented on app/javascript/src/components/PlanDetails/index.tsx
> +                type="text"
Ohh then you can simply use Yup validations its simple to use you can add validations over there also.

2022-06-15 11:50 UTC, Shruti-Apte commented
Becasue of multiple files changed (rebasing issue) creating a new PR.

2022-06-15 11:50 UTC, closed without merging