Billing Page UI design
saeloun/miru-web pull request #467
Opened 2022-06-13 10:56 UTC by onkar-saeloun

## Notion card
https://www.notion.so/saeloun/Front-end-create-the-billings-page-3ad957f851b44ca7a189377cd9282d02

## Summary

- Added Design for Billing Page

## Preview

https://user-images.githubusercontent.com/104751221/173338600-7deba1e2-2956-4466-9475-cc64c01782a7.mp4

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- Tested Manually

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-06-13 10:58 UTC, JijoBose commented on app/javascript/src/components/Profile/Billing/index.tsx
> +      // saveAction={}
let's remove commented code

2022-06-13 10:58 UTC, JijoBose approved these changes

2022-06-13 11:06 UTC, supriya3105 commented
@onkar-saeloun Please check the CI tests that are failing.

2022-06-13 14:18 UTC, JijoBose requested changes

2022-06-13 14:41 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Billing/Table/index.tsx
> +      {data.map((data) => (
@JijoBose currently we are not rendering any data on the page. We are planning to do API integration afterwords. We will pass data while doing API integration.

2022-06-13 14:41 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Billing/index.tsx
> +      // saveAction={}
Okay.

2022-06-14 07:49 UTC, JijoBose approved these changes

2022-06-14 07:54 UTC, merged