Project edit issue
saeloun/miru-web pull request #469
Opened 2022-06-13 18:59 UTC by abinashpa

## Notion card
https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=f1810139870444259ef38b4bee169b34&p=2e3337478aec42818dbaca5f4ba3c1f5

## Summary
The page is breaking after clicking on edit project details

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-06-14 14:10 UTC, ajinkyaa commented on app/javascript/src/components/Projects/Modals/AddEditProject.tsx
> +      const client = clientList.filter(clientItem => clientItem["name"] == editProjectData["client"]["name"]);
why not use `search`

2022-06-15 07:30 UTC, akhilgkrishnan commented on app/javascript/src/components/Projects/Modals/AddEditProject.tsx
> +                    onChange={(e) => setClient(+ e.target.value)}>
What's the use of + here?

2022-06-15 08:28 UTC, abinashpa commented on app/javascript/src/components/Projects/Modals/AddEditProject.tsx
> +    if (! editProjectData) return;
No, It's just more elegant than nested if condition.

2022-06-15 08:28 UTC, abinashpa commented on app/javascript/src/components/Projects/Modals/AddEditProject.tsx
> +                    onChange={(e) => setClient(+ e.target.value)}>
Converting string to a number.

2022-06-15 12:44 UTC, supriya3105 commented
@ajinkyaa @akhilgkrishnan Please review this PR. Abinash has responded to your questions. 
@apoorv1316 Please test this.

2022-06-16 07:46 UTC, abinashpa commented on app/javascript/src/components/Projects/Modals/AddEditProject.tsx
> +      const client = clientList.filter(clientItem => clientItem["name"] == editProjectData["client"]["name"]);
Do you mean `Array.find`?

2022-06-17 03:59 UTC, apoorv1316 requested changes
@abinashpa <img width="1792" alt="Screenshot 2022-06-17 at 9 29 14 AM" src="https://user-images.githubusercontent.com/18750194/174222189-d1f9721e-c8f5-4357-b020-39dfa7fd6789.png">
 Getting this error on the projects page. Please fix it.

2022-06-17 04:55 UTC, akhilgkrishnan reviewed
@abinashpa what's the use of helix file?

2022-06-17 04:55 UTC, akhilgkrishnan commented on app/javascript/src/components/Projects/Modals/AddEditProject.tsx
>                        clientList.map((e, index) => <option key={index} value={e.id} selected={e.id == client}>{e.name}</option>)}
user proper naming instead of e

2022-06-20 05:01 UTC, abinashpa commented on app/javascript/src/components/Projects/Modals/AddEditProject.tsx
>                        clientList.map((e, index) => <option key={index} value={e.id} selected={e.id == client}>{e.name}</option>)}
Changed to event.

2022-06-20 05:17 UTC, ajinkyaa commented on app/javascript/src/components/Projects/Modals/AddEditProject.tsx
> +    if (clientList.length) {
what if clientList.length is `0`. What will happen?

2022-06-20 05:19 UTC, ajinkyaa approved these changes

2022-06-20 07:33 UTC, supriya3105 commented
@apoorv1316 Please test this and merge if the functionality is working.

2022-06-20 07:34 UTC, apoorv1316 commented
@supriya3105 2-3 things need to be fixed. I have talked and conveyed it to Abhinash already and he is working on it.

2022-06-20 07:58 UTC, supriya3105 commented
> @supriya3105 2-3 things need to be fixed. I have talked and conveyed it to Abhinash already and he is working on it.

Please add the feedback your have provided to the PR.

2022-06-21 03:54 UTC, akhilgkrishnan approved these changes
LGTM

2022-06-22 05:11 UTC, apoorv1316 approved these changes

2022-06-22 05:11 UTC, merged