Add API to get team members
saeloun/miru-web pull request #471
Opened 2022-06-14 05:54 UTC by shalapatil

## Notion card

## Summary
https://www.notion.so/API-to-fetch-team-members-details-on-team-page-2104bddb4caa447bb2f91c1268493102

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-06-14 06:50 UTC, rohitjoshixyz requested changes
Some changes needed

2022-06-14 06:50 UTC, rohitjoshixyz commented on spec/requests/internal_api/v1/team/index_spec.rb
> +      })
Create the user using factory instead of making a `POST` request

2022-06-14 06:50 UTC, rohitjoshixyz commented on spec/requests/internal_api/v1/team/index_spec.rb
> +        })
Create the user needed using factory

2022-06-14 06:50 UTC, rohitjoshixyz commented on spec/requests/internal_api/v1/team/index_spec.rb
> +      expect(actual_members_data).to eq(expected_members_data)
We can simplify this spec, there is a lot of repetition of keys.

2022-06-14 06:50 UTC, rohitjoshixyz commented on spec/requests/internal_api/v1/team/index_spec.rb
> +    it "is not permitted to view teamt" do
Typo
```suggestion
    it "is not permitted to view team members" do
```

2022-06-14 06:50 UTC, rohitjoshixyz commented on spec/requests/internal_api/v1/team/index_spec.rb
> +      expect(json_response["team"].pluck("profilePicture")).not_to include(nil)
Assert with actual value instead of asserting not nil. You can create one user with an explicitly set avatar, and another with no avatar which will render the default `avatar.png`

2022-06-14 06:50 UTC, rohitjoshixyz commented on app/views/internal_api/v1/team/index.json.jbuilder
> +end
Use I18n. Check for `t('team.reconfirmation')` and reuse it for statuses

2022-06-14 06:50 UTC, rohitjoshixyz commented on app/views/internal_api/v1/team/index.json.jbuilder
> +end
Ideally, this method should go in a presenter class. cc @keshavbiswa 
We have not added any presenters so we could keep this in the user model to keep this JBuilder file clean

2022-06-14 07:56 UTC, keshavbiswa reviewed
Added some comments.

2022-06-15 05:10 UTC, shalapatil commented on app/policies/team_policy.rb
> +    true
to current user we show members of his team. We want to show it to employee type of users also. That's how this is done at other places too.

2022-06-15 05:11 UTC, shalapatil commented on app/controllers/internal_api/v1/team_controller.rb
> +  helper :all
because we need access to`user_avatar` helper method in jbuilder

2022-06-16 08:09 UTC, keshavbiswa commented on app/controllers/internal_api/v1/team_controller.rb
> +  helper :all
Could you try `helper :application_helper` as `helper :all` will include All helpers.

2022-06-16 09:51 UTC, keshavbiswa approved these changes
LGTM! Thanks for making the changes.

2022-06-17 04:00 UTC, apoorv1316 approved these changes

2022-06-17 07:23 UTC, supriya3105 commented
@rohitjoshixyz Please review this PR.

2022-06-17 08:19 UTC, rohitjoshixyz approved these changes
LGTM

2022-06-17 08:19 UTC, rohitjoshixyz commented on spec/factories/users.rb
> +    end
Nice

2022-06-17 08:20 UTC, supriya3105 commented
@ajinkyaa @shalapatil The same is applicable for this PR too. Please do not merge this on develop branch.

2022-06-17 08:24 UTC, ajinkyaa commented
@supriya3105 we can merge this PR on the develop, UI we are not merging.

2022-06-17 08:32 UTC, merged