Invite user api
saeloun/miru-web pull request #474
Opened 2022-06-14 18:15 UTC by shalapatil

## Notion card

## Summary
https://www.notion.so/saeloun/Develop-API-to-add-new-team-member-69a4e28d55ea4f39918d6b6e124c16dd

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have added automated tests for my code

2022-06-15 02:01 UTC, rohitjoshixyz approved these changes
LGTM 🎉

2022-06-15 07:27 UTC, akhilgkrishnan commented on app/controllers/internal_api/v1/users_controller.rb
> +    super do |resource|
@shalapatil can you please confirm whether the invitation emails are sending or not?

2022-06-16 05:16 UTC, shalapatil commented on app/controllers/internal_api/v1/users_controller.rb
> +    super do |resource|
@akhilgkrishnan Yes, emails are being sent!

2022-06-17 08:14 UTC, supriya3105 commented
@akhilgkrishnan @rohitjoshixyz Please review and approve if no further review comments.

2022-06-17 08:15 UTC, akhilgkrishnan approved these changes

2022-06-17 08:17 UTC, akhilgkrishnan commented
> @akhilgkrishnan @rohitjoshixyz Please review and approve if no further review comments.

@supriya3105 Do not merge this PR without testing the entire user invite flow.

2022-06-17 08:19 UTC, supriya3105 commented
@akhilgkrishnan We need to merge this on the feature branch created by @ajinkyaa for the teams page refactoring. @shalapatil @ajinkyaa This PR needs to be merged into feature branch. Please coordinate among yourselves. Do not merge this on develop branch

2022-06-17 08:22 UTC, rohitjoshixyz approved these changes
LGTM

2022-06-21 04:17 UTC, apoorv-mishra requested changes

2022-06-21 04:17 UTC, apoorv-mishra commented on app/controllers/internal_api/v1/users_controller.rb
> -          invited_user.companies.exists?(id: current_company.id)
Why were these checks removed @shalapatil ? Can you test the flow where a user is invited to same workspace multiple times @apoorv1316 for this PR? It shouldn't happen.

2022-06-22 05:16 UTC, apoorv1316 commented on app/controllers/internal_api/v1/users_controller.rb
> -          invited_user.companies.exists?(id: current_company.id)
@apoorv-mishra I invited a user as an employee and without accepting the invitation I invited him again in the same workspace and it sent the invitation again. cc @shalapatil @supriya3105 @akhilgkrishnan

2022-07-05 08:41 UTC, closed without merging