Search dropdown added in time-tracking
saeloun/miru-web pull request #477
Opened 2022-06-15 07:57 UTC by abinashpa

## Notion card
[Link](https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=f1810139870444259ef38b4bee169b34&p=c353d267a48f4cfeb06d0cfde4fe2977)

## Summary
Replaced the select elements with react-select.

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-06-15 08:00 UTC, ajinkyaa approved these changes
I see lot of duplication of code, can you please create common component out of this?

2022-06-15 08:40 UTC, onkar-saeloun requested changes

2022-06-15 08:40 UTC, onkar-saeloun commented on app/javascript/src/components/time-tracking/SelectProject.tsx
> +  const clientList = clients.map(client => ({ value: client.name, label: client.name }));
These maps will be looped each time you update the component. Better to keep it in useEffect along with specific conditions or wrapping it by a function..

2022-06-15 12:46 UTC, supriya3105 commented
@abinashpa Why is the title suggesting that search is added to time tracking. The Notion card linked to this PR is for search on projects list page.

2022-07-01 03:11 UTC, onkar-saeloun requested changes
@abinashpa few small comments please have a look

2022-07-01 03:11 UTC, onkar-saeloun commented on app/javascript/src/common/SyncAutoComplete.tsx
> +          setValue(event.target.value);
please declare a function and add your logic over there just initiate the function here.
for example,
const handleOnChange = (e) => {
setValue(e.target.value)
}
<Autocomplete
  onChange={handleOnChange}
  ...
 />

2022-07-01 03:11 UTC, onkar-saeloun commented on app/javascript/src/common/SyncAutoComplete.tsx
> +        onSelect={(value) => {
same as above

2022-07-01 03:11 UTC, onkar-saeloun commented on app/javascript/src/common/SyncAutoComplete.tsx
> +              return <></>;
why do we need fragment over here `<></>`? Actually do we need this if condition?

2022-07-01 03:11 UTC, onkar-saeloun commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +          {isDataFilled &&<SyncAutoComplete
please format over here

2022-07-01 03:11 UTC, onkar-saeloun commented on app/controllers/time_tracking_controller.rb
> +    full_name = current_user.first_name + " " + current_user.last_name
You can use template literals over here,
full_name = `${current_user.first_name} ${current_user.last_name}`

2022-07-01 07:10 UTC, ajinkyaa commented on app/javascript/src/common/SyncAutoComplete.tsx
> +import * as React from "react";
no need to import *, use `import React from "react"`

2022-07-01 07:10 UTC, ajinkyaa commented on app/javascript/src/common/SyncAutoComplete.tsx
> +import * as React from "react";
Add comment at the first line, that this file is for synchronous auto complete.

2022-07-01 07:10 UTC, ajinkyaa commented on app/javascript/src/components/Invoices/MultipleEntriesModal/index.tsx
> +      <div className="bg-white rounded-lg w-full h-160 flex flex-col justify-between">
why do we need height? can we just keep the height as per the content?
what if we remove height from the modal?

2022-07-01 08:11 UTC, abinashpa commented on app/javascript/src/common/SyncAutoComplete.tsx
> +              return <></>;
This code is inherited from AutoComplete.tsx.

2022-07-01 10:14 UTC, onkar-saeloun approved these changes

2022-07-04 08:30 UTC, ajinkyaa approved these changes

2022-07-04 11:55 UTC, apoorv1316 commented
@abinashpa Please add a notion card and the loom video.

2022-07-04 13:09 UTC, abinashpa commented
> @abinashpa Please add a notion card and the loom video.

Notion card and Loom video has been added @apoorv1316.

2022-07-05 04:59 UTC, apoorv1316 requested changes
@abinashpa I cannot see projects just by clicking on the project field. Refer to loom: https://www.loom.com/share/1eb059b564e84c328262e6b3e7b6fe6d
 Also, can we add a placeholder text for the project & client text field?

2022-07-06 11:56 UTC, apoorv1316 commented
@abinashpa Can we show the current logged-in admin/owner's name when the time tracking page loads for the first time? The empty space doesn't look so good. Also, the workspace switcher is showing under the search bar. Can you fix it?
<img width="1792" alt="Screenshot 2022-07-06 at 5 22 23 PM" src="https://user-images.githubusercontent.com/18750194/177544081-8c5cec20-b569-44db-9477-4fd7c1fe8a1f.png">
<img width="1792" alt="Screenshot 2022-07-06 at 5 24 35 PM" src="https://user-images.githubusercontent.com/18750194/177544655-c688244c-3789-4d36-aa7f-a2593bca45b5.png">

2022-07-07 17:10 UTC, abinashpa commented
@apoorv1316 Fixes have been added

2022-07-08 07:50 UTC, apoorv1316 commented
@supriya3105 @abinashpa LGTM from functional perspective. Just wanted to confirm that this search box and results are as per the designs. Coz the search box in the middle looks a bit odd to me.
<img width="1792" alt="Screenshot 2022-07-08 at 1 18 51 PM" src="https://user-images.githubusercontent.com/18750194/177944233-f2e3e8f9-04c1-496d-aae0-51e22f11f64b.png">

2022-07-08 07:51 UTC, apoorv1316 approved these changes

2022-07-08 08:25 UTC, abinashpa commented
> @supriya3105 @abinashpa LGTM from functional perspective. Just wanted to confirm that this search box and results are as per the designs. Coz the search box in the middle looks a bit odd to me.
> <img width="1792" alt="Screenshot 2022-07-08 at 1 18 51 PM" src="https://user-images.githubusercontent.com/18750194/177944233-f2e3e8f9-04c1-496d-aae0-51e22f11f64b.png">
> 

On figma designs search box has been moved to center.

2022-07-08 09:11 UTC, supriya3105 commented
@abinashpa  @apoorv1316 As per the designs it has been moved to centre. However we will need to make some changes to the search dropdown . Will add that as a separate ticket.  
Merging this PR for now.

2022-07-08 09:11 UTC, merged