Team page updates
saeloun/miru-web pull request #482
Opened 2022-06-15 10:54 UTC by ajinkyaa

Team page updates
<img width="1358" alt="Screenshot 2022-06-15 at 4 23 38 PM" src="https://user-images.githubusercontent.com/6236169/173810783-669a8a69-e89d-464e-8864-dc2754634455.png">
<img width="1311" alt="Screenshot 2022-06-15 at 4 23 23 PM" src="https://user-images.githubusercontent.com/6236169/173810765-e8ff6039-ace0-4483-9772-29eeb2812546.png">

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-06-15 12:48 UTC, supriya3105 commented
@ajinkyaa Please check the CI tests that are failing for this PR.

2022-06-16 05:45 UTC, ajinkyaa commented
@supriya3105 I think someone from ror side to work on this. Those are failing because new routes addition for teams page.

2022-06-16 05:49 UTC, JijoBose commented on app/javascript/src/components/Team/List/Header.tsx
> +  console.log("isAdminUser ---> ", isAdminUser);
Let's remove console logs

2022-06-16 05:52 UTC, JijoBose commented on app/javascript/src/components/Team/modals/Modals.tsx
> +      return <></>;
Can we add `null` here?

2022-06-16 05:54 UTC, JijoBose approved these changes

2022-06-16 06:12 UTC, JijoBose requested changes
tests are failing

2022-06-16 06:37 UTC, JijoBose approved these changes

2022-06-16 06:41 UTC, merged