Redirect to email verification window
saeloun/miru-web pull request #484
Opened 2022-06-16 06:28 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Once-the-user-signs-up-email-verification-window-should-be-displayed-as-per-the-design-aeef4cccf92042c4bca82023aa68e9c9
## Summary

- Email verification window design 
- Redirecting to email verification window after sign up
## Preview

https://www.loom.com/share/e3043ed8e72a41649d53f83da7fa2c92
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-06-16 07:55 UTC, harshaanNihal requested changes

2022-06-16 07:55 UTC, harshaanNihal commented on app/javascript/src/components/EmailVerification/index.tsx
> +  });
This will add a listener everytime the component is mount.

Move the eventListener inside a useEffect Hook and remove the listener in a cleanup function 

for ref: https://stackoverflow.com/a/55566585

2022-06-17 12:17 UTC, harshaanNihal approved these changes
LGTM ✨

2022-06-20 07:59 UTC, supriya3105 commented
@apoorv1316 Please test this flow and merge if working as expected. Its known that the toast message is still getting displayed after the verification which needs to be fixed by @harshaanNihal

2022-06-20 11:27 UTC, apoorv1316 approved these changes

2022-06-20 12:04 UTC, merged