React Context in settings app
saeloun/miru-web pull request #497
Opened 2022-06-20 07:18 UTC by onkar-saeloun

## Notion card
https://www.notion.so/saeloun/Implementation-of-Context-for-settings-pages-94b4f7c80908450fa6e647cb1b49727f

## Summary

- This feature will introduce the context state management from settings pages.

## Preview

https://user-images.githubusercontent.com/104751221/174546024-7bf8b331-6e4f-4989-8fec-88b522cc9997.mp4

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested Manually on my local machine.

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-06-20 07:21 UTC, JijoBose approved these changes

2022-06-21 06:01 UTC, ajinkyaa requested changes

2022-06-21 06:01 UTC, ajinkyaa commented on app/javascript/src/components/Profile/context/EntryContext.tsx
> +export const useEntry = () => useContext(EntryContext);
change the name, it's not the entry page. 
keep it `useProfile` something.

2022-06-21 09:11 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/UserDetail/index.tsx
> +      setUserState("profileSettings", {
@ajinkyaa I have wrapped this API call with try catch block so it will take care of API failure.

2022-06-22 05:34 UTC, ajinkyaa approved these changes

2022-06-22 06:25 UTC, merged