Create API to view & update user's personal details
saeloun/miru-web pull request #543
Opened 2022-07-05 13:33 UTC by mohinid

## Notion card
https://www.notion.so/saeloun/Create-APIs-to-add-and-view-personal-details-for-a-user-e312e4f0ceb849fda5f14eb05f8b2cf3

## Summary
1. Create an API for updating and viewing users' personal details from users table.

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
Used Postman on local & RSpecs.

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have added automated tests for my code

2022-07-05 13:34 UTC, mohinid commented
Postman response for User Details API
<img width="1569" alt="Screenshot 2022-07-05 at 7 03 52 PM" src="https://user-images.githubusercontent.com/5313625/177340305-7382049d-803a-40d8-9f69-aabcb809d9b7.png">

2022-07-05 14:17 UTC, keshavbiswa requested changes

2022-07-05 14:17 UTC, keshavbiswa commented on app/controllers/internal_api/v1/team_members/details_controller.rb
> +    authorize current_user, policy_class: TeamMembers::DetailPolicy
You need to authorize the resource, not the current_user. In this action the resource would be the user.

2022-07-05 14:17 UTC, keshavbiswa commented on app/views/internal_api/v1/team_members/details/show.json.jbuilder
> +  json.linkedin_url user.social_accounts["linkedin_url"]
You can make use of the `extract` method.

2022-07-05 14:17 UTC, keshavbiswa commented on app/policies/team_members/detail_policy.rb
> +    user_owner_role? || user_admin_role? || user_employee_role?
Take a look at `.has_any_role?` from the `pundit` gem documentation.

2022-07-06 15:10 UTC, mohinid commented on app/controllers/internal_api/v1/team_members/details_controller.rb
> +    if user.update!(detail_params)
removed if condition

2022-07-07 09:42 UTC, mohinid commented
> Should someone with admin or employee role, be able to update any team member's personal details?

If from the same company- yes. @supriya3105  please confirm.

2022-07-07 13:45 UTC, supriya3105 commented
> > Should someone with admin or employee role, be able to update any team member's personal details?
> 
> If from the same company, then yes. @supriya3105 please confirm.

Yes. I agree . Admin and owner should be able to update personal details of any employee

2022-07-08 05:52 UTC, akhilgkrishnan reviewed
Added couple of comments.

2022-07-08 05:52 UTC, akhilgkrishnan commented on app/controllers/internal_api/v1/team_members/details_controller.rb
> +
You can use memoization for find the employement record.
def employment
 @employment ||= Employment.find(params[:team_id])
end

2022-07-08 05:52 UTC, akhilgkrishnan commented on app/controllers/internal_api/v1/team_members/details_controller.rb
> +    render :show, locals: { user: employment.user }, status: :ok
include proper message to the response

2022-07-08 06:15 UTC, akhilgkrishnan commented on app/policies/team_members/detail_policy.rb
> +      { name: :employee, resource: record.company }) || user == record.user
```suggestion
      { name: :owner, resource: record.company }) || user == record.user
```

2022-07-08 06:16 UTC, mohinid commented on app/policies/team_members/detail_policy.rb
> +      { name: :employee, resource: record.company }) || user == record.user
my bad! :/

2022-07-08 08:27 UTC, akhilgkrishnan approved these changes
LGTM 🎉

2022-07-11 08:41 UTC, keshavbiswa commented on spec/factories/users.rb
> +    date_of_birth { Date.today }
```suggestion
    date_of_birth { Date.current }
```

2022-07-11 08:41 UTC, keshavbiswa commented on spec/requests/internal_api/v1/team_members/details/show_spec.rb
> +      get "/internal_api/v1/team/#{employment.id}/details"
You can make use of the `send_request` method.

2022-07-11 10:53 UTC, mohinid commented
@keshavbiswa integrated suggested changes. Ci is failing for some other test. Will merge it once resolved.

2022-07-12 04:20 UTC, keshavbiswa commented on spec/requests/internal_api/v1/team_members/details/show_spec.rb
> +      expect(response).to have_http_status(:ok)
Could you also assert if we're getting the correct response data?

2022-07-12 04:20 UTC, keshavbiswa commented on spec/requests/internal_api/v1/team_members/details/show_spec.rb
> +      expect(response).to have_http_status(:ok)
Could you also assert if we're getting the correct response data?

2022-07-12 04:20 UTC, keshavbiswa commented on spec/requests/internal_api/v1/team_members/details/show_spec.rb
> +      expect(response).to have_http_status(:ok)
Could you also assert if we're getting the correct response data?

2022-07-12 04:20 UTC, keshavbiswa commented on spec/requests/internal_api/v1/team_members/details/update_spec.rb
> +      expect(response).to have_http_status(:ok)
Could you also assert if we're getting the correct response data?

2022-07-12 04:20 UTC, keshavbiswa commented on spec/requests/internal_api/v1/team_members/details/update_spec.rb
> +      expect(response).to have_http_status(:ok)
Could you also assert if we're getting the correct response data?

2022-07-12 07:38 UTC, keshavbiswa requested changes

2022-07-12 07:38 UTC, keshavbiswa commented on spec/requests/internal_api/v1/team_members/details/show_spec.rb
> +      response.body == user.to_json
This is not a correct way to write tests.

2022-07-12 07:44 UTC, mohinid commented on spec/requests/internal_api/v1/team_members/details/show_spec.rb
> +      response.body == user.to_json
please check now.

2022-07-12 07:46 UTC, keshavbiswa commented on spec/requests/internal_api/v1/team_members/details/show_spec.rb
> +      expect(json_response["social_accounts"]).to eq(JSON.parse(user.social_accounts.to_json))
expect(json_response).to eq(user.to_json) this could also work.

2022-07-12 07:47 UTC, mohinid commented on spec/requests/internal_api/v1/team_members/details/show_spec.rb
> +      expect(json_response["social_accounts"]).to eq(JSON.parse(user.social_accounts.to_json))
its not working because we have checks on specific fields.

2022-07-12 07:49 UTC, mohinid commented on spec/requests/internal_api/v1/team_members/details/show_spec.rb
> +      expect(json_response["social_accounts"]).to eq(JSON.parse(user.social_accounts.to_json))
Here is the error SS- 
<img width="1792" alt="Screenshot 2022-07-12 at 1 18 50 PM" src="https://user-images.githubusercontent.com/5313625/178437736-3843af76-5dea-46af-a3c4-356f99e0e73a.png">

2022-07-12 14:32 UTC, merged