Invoice status will be updated based on stripe response
saeloun/miru-web pull request #547
Opened 2022-07-06 13:31 UTC by gowsik-ragunath

## Notion card

https://www.notion.so/saeloun/Fix-the-critical-issue-on-stripe-payments-267d5635c20844ab8ef4c4184021527c

## Summary

This PR adds a validation that will check if the payment for an invoice is recorded in Stripe, if the payment is recorded then invoice status will be updated to `Paid` if not, then an error message will be displayed.

## Preview

If the payment is recorded in Stripe:

<img width="1792" alt="Screenshot 2022-07-06 at 6 52 30 PM" src="https://user-images.githubusercontent.com/52308930/177561478-0aa446c7-f284-44c5-877d-3e2acc26ad3d.png">

If payment is not recorded in Stripe or user manually tries to visit payment success page:

<img width="1780" alt="Screenshot 2022-07-06 at 6 53 19 PM" src="https://user-images.githubusercontent.com/52308930/177561502-d95c5204-d368-40fc-8276-f4894c050838.png">

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [X] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-07-08 05:04 UTC, apoorv1316 approved these changes
LGTM 🚀

2022-07-08 07:07 UTC, supriya3105 commented
@akhilgkrishnan Please review this PR.

2022-07-08 11:21 UTC, gowsik-ragunath commented on app/models/invoice.rb
> +#  stripe_payment_intent :string
@akhilgkrishnan As discussed in the call, I have removed `stripe_payment_intent` and replaced it with `payment info` jsonb field (store_accessor).

2022-07-11 06:23 UTC, supriya3105 commented
@akhilgkrishnan Please review the PR again and approve if it looks good.

2022-07-11 06:27 UTC, akhilgkrishnan approved these changes
LGTM

2022-07-11 07:05 UTC, keshavbiswa requested changes

2022-07-11 07:05 UTC, keshavbiswa commented on db/schema.rb
> +  end
This is not part of this PR.

2022-07-11 07:14 UTC, gowsik-ragunath commented on app/models/invoice.rb
> +#  payment_infos      :jsonb
Akhil suggested that we can use this JSON field to store checkout payment reference data from different payment processors like stripe, wise, and Razorpay. Can we rename this field name to `checkout_info`, `payment_details` or `payment_references`?

2022-07-11 07:24 UTC, keshavbiswa commented on app/models/invoice.rb
> +#  payment_infos      :jsonb
Ideally all invoice should have an associated payment/order record. Storing these important data in a jsonb column doesn't sound quite right to me.

2022-07-11 07:33 UTC, gowsik-ragunath commented on app/models/invoice.rb
> +#  payment_infos      :jsonb
Yeah, but this payment record will be created only after confirming that the payment is successful but we need to store these checkout id, and payment intent id while creating a Stripe checkout session, once the payment is successful and users are redirected to our site we will use these ids to check if payment is successful or not by making API calls to Stripe.

2022-07-11 09:23 UTC, gowsik-ragunath commented on db/schema.rb
> +  end
Removed invitations related database schemas.

I used `rails db:schema:load` while switching between the invitation branch and this branch to get the old devise inevitable column back in DB, not sure if this invitation data schema was added into schema.rb file while running this command.

2022-07-12 04:57 UTC, gowsik-ragunath commented on app/models/invoice.rb
> +#  payment_infos      :jsonb
@keshavbiswa soft ping.

2022-07-12 12:15 UTC, supriya3105 commented
@keshavbiswa Reminder to review this PR.

2022-07-14 07:00 UTC, keshavbiswa approved these changes

2022-07-14 07:15 UTC, merged