Feature/routes cleanup
saeloun/miru-web pull request #556
Opened 2022-07-12 00:50 UTC by harshaanNihal

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-07-12 09:49 UTC, akhilgkrishnan commented on app/javascript/src/apis/time-tracking.ts
> +
can you rename the fine to timeTracking.ts

2022-07-12 09:49 UTC, akhilgkrishnan commented on app/javascript/src/components/Main.tsx
> +    const url = role === "book_keeper" ? "/payments" : "/time-tracking";
can we create a URL constant file, for stroring all the urls

2022-07-12 09:49 UTC, akhilgkrishnan commented on app/javascript/src/components/time-tracking/Index.tsx
> +import timeTrackingApi from "apis/time-tracking";
add an empty line above

2022-07-12 09:49 UTC, akhilgkrishnan commented on app/javascript/src/components/time-tracking/Index.tsx
>      setAuthHeaders();
We can remove `setAuthHeaders(); registerIntercepts();` thats is already calling in app.tsx

2022-07-12 09:49 UTC, akhilgkrishnan commented on app/javascript/src/components/routes.tsx
> +import ErrorPage from "common/Error";
can you move this file to helper or constant folder? Route is not a component

2022-07-12 10:08 UTC, gowsik-ragunath commented on app/controllers/users/sessions_controller.rb
> +      root_path + "payments"
Instead of appending "payments" to root_url, you can use `payments_url`.

2022-07-12 10:11 UTC, gowsik-ragunath commented on app/helpers/navigation_helper.rb
> +          url: "#{root_path}time-tracking",
Same, you can use url instead of path (time_tracking_index_url).

2022-07-12 10:14 UTC, gowsik-ragunath commented on app/helpers/navigation_helper.rb
> +          url: "#{root_url}projects",
Same, replace this with url (projects_url).

2022-07-12 10:15 UTC, gowsik-ragunath commented on app/helpers/navigation_helper.rb
> +          url: "#{root_url}reports",
Same, replace this with url (reports_url).

2022-07-12 10:15 UTC, gowsik-ragunath commented on app/helpers/navigation_helper.rb
> +          url: "#{root_url}invoices",
Same, replace this with url (invoices_url).

2022-07-12 10:15 UTC, gowsik-ragunath commented on app/helpers/navigation_helper.rb
> +          url: "#{root_url}payments",
Same, replace this with url (payments_url).

2022-07-12 10:23 UTC, gowsik-ragunath commented on app/views/mailers/send_weekly_reminder_to_user_mailer/notify_user_about_missed_entries.text.erb
> +  Your logged hours for the week <%= @starting_date %> to <%= @ending_date %> is less than 40 hours. Please visit <%= root_url + "time-tracking" %> to update your timesheet.
Same concern.

2022-07-12 14:45 UTC, harshaanNihal commented on app/controllers/users/sessions_controller.rb
> +      root_path + "payments"
`payments_url/payments_path` is no longer present as we have removed the controller and and moved the routing to React

2022-07-12 14:47 UTC, harshaanNihal commented on app/controllers/users/sessions_controller.rb
> +      root_path + "time-tracking"
same for `time_tracking_index_url/time_tracking_index_path`. these paths have been removed from router.rb

2022-07-12 14:51 UTC, harshaanNihal commented on app/helpers/navigation_helper.rb
> +          url: "#{root_path}time-tracking",
same as above the routes they have been removed from route.rb file.
We will extract the erb Navbar to react component in this [ticket](https://www.notion.so/saeloun/Change-the-navigation-on-Home-page-0af62fe9d5ac460fb9e1152618f3b21a)

2022-07-12 14:54 UTC, harshaanNihal commented on app/views/mailers/send_weekly_reminder_to_user_mailer/notify_user_about_missed_entries.html.erb
> +  Please click <%= link_to "here", root_url + "time-tracking" , target: "_blank" %> to update your timesheet. </p>
the controller have been removed along with the routes
Now all the unhandeled request will be moved to homeController#index which will render React entry component `App.jsx`

2022-07-12 14:55 UTC, harshaanNihal commented on app/views/mailers/send_weekly_reminder_to_user_mailer/notify_user_about_missed_entries.text.erb
> +  Your logged hours for the week <%= @starting_date %> to <%= @ending_date %> is less than 40 hours. Please visit <%= root_url + "time-tracking" %> to update your timesheet.
https://github.com/saeloun/miru-web/pull/556#discussion_r919073482

2022-07-12 14:56 UTC, harshaanNihal commented on app/helpers/navigation_helper.rb
> +          url: "#{root_url}clients",
https://github.com/saeloun/miru-web/pull/556#discussion_r919070517

2022-07-12 14:56 UTC, harshaanNihal commented on app/helpers/navigation_helper.rb
> +          url: "#{root_url}projects",
https://github.com/saeloun/miru-web/pull/556#discussion_r919070517

2022-07-12 15:35 UTC, harshaanNihal commented on app/javascript/src/apis/time-tracking.ts
> +
Renamed file

2022-07-12 15:54 UTC, harshaanNihal commented on app/javascript/src/components/Main.tsx
> +    const url = role === "book_keeper" ? "/payments" : "/time-tracking";
I missed this one 
Since the paths `payments & `time-tracking` is present as react-routes we can Navigate to these routes

Added a Paths enum in constants file.

2022-07-12 15:58 UTC, harshaanNihal commented on app/javascript/src/components/time-tracking/Index.tsx
> +import timeTrackingApi from "apis/time-tracking";
Fix imports order

2022-07-12 15:59 UTC, harshaanNihal commented on app/javascript/src/components/routes.tsx
> +import ErrorPage from "common/Error";
file moved to constant folder

2022-07-12 16:20 UTC, harshaanNihal commented on app/javascript/src/components/time-tracking/Index.tsx
> +import timeTrackingApi from "apis/time-tracking";
I tried arranging them in external and internal import order but ES-Lint consider aliases as external packages and arrange them alphabatically

2022-07-13 04:01 UTC, akhilgkrishnan commented on app/helpers/application_helper.rb
> +      company_role: current_user.roles.find_by(resource: current_company)&.name
can you also pass the current company

2022-07-13 07:03 UTC, harshaanNihal commented on app/helpers/application_helper.rb
> +      company_role: current_user.roles.find_by(resource: current_company)&.name
Added

2022-07-13 07:11 UTC, harshaanNihal commented on app/controllers/internal_api/v1/time_tracking_controller.rb
> +    render json: { clients:, projects:, entries:, employees: }
Added Status code.

The controller has been moved from `app/controllers/time_tracking_controller.rb` → `conrtoller/internal_api/v1/time_tracking_controller.rb` previously it was rendering a template with these values as params ported it to api controller hence passing JSON response directly.

2022-07-13 13:05 UTC, harshaanNihal commented on app/controllers/home_controller.rb
> +    render
In the PR we are porting ruby routes to react routes.
The Controller renders the main react App component. Instead of keeping the Implementation blank, I added the `render` statement as mentioned [here](https://www.notion.so/Do-not-leave-action-implementation-blank-a3080e80b9c74bc49459bb5f07afc59a)

2022-07-13 13:11 UTC, harshaanNihal commented on app/controllers/root_controller.rb
> +    redirect_to root_path + path
`payments_path` & `time_tracking_index_path` are no longer present in rails routes as we have removed both controller and their respective routes.

Once the team_controller also got ported to react we can move this whole logic to react and will redirect all request to react root_path

2022-07-13 13:27 UTC, harshaanNihal commented on app/helpers/navigation_helper.rb
> +          url: "#{root_path}time-tracking",
Fixed

2022-07-13 14:14 UTC, harshaanNihal commented
@keshavbiswa fixed the routes on navigation_helpers.

2022-07-13 14:23 UTC, harshaanNihal commented on app/controllers/root_controller.rb
> +    redirect_to root_path + path
Done

2022-07-13 16:58 UTC, supriya3105 commented
@harshaanNihal Please do not merge this in to develop. Merge into the feature branch .

2022-07-14 04:32 UTC, gowsik-ragunath commented on app/controllers/users/sessions_controller.rb
> +      root_path + "payments"
Oh got it, I will mark all the URL related PR as resolved.

2022-07-14 04:33 UTC, gowsik-ragunath approved these changes

2022-07-14 10:09 UTC, supriya3105 commented
This page is not looking correct. We cannot merge it until we fix the page. @harshaanNihal @apoorv1316 

This is how it looks in staging 
<img width="1440" alt="Screenshot 2022-07-14 at 3 38 32 PM" src="https://user-images.githubusercontent.com/91338424/178958603-cc70be8f-08db-40be-bc94-5dc0c211774f.png">

2022-07-14 10:09 UTC, supriya3105 requested changes
Need to fix the time tracking page

2022-07-14 11:18 UTC, apoorv1316 commented
@harshaanNihal Let me know when it's ready to test the time-tracking page.

2022-07-14 11:23 UTC, harshaanNihal commented
@apoorv1316 @supriya3105  I have removed the additional padding Please check.

Demo: https://www.loom.com/share/8e3a2caa2ce3440cb77fd2208d917811
There is still a max-width constraint present on  time tracking page hence it appear slight different from Production.
If we need it exactly same as production (without the max-width constraint) please let me know.

2022-07-14 11:34 UTC, apoorv1316 commented
> @apoorv1316 @supriya3105 I have removed the additional padding Please check.
> 
> Demo: https://www.loom.com/share/8e3a2caa2ce3440cb77fd2208d917811 There is still a max-width constraint present on time tracking page hence it appear slight different from Production. If we need it exactly same as production (without the max-width constraint) please let me know.
<img width="1792" alt="Screenshot 2022-07-14 at 4 58 21 PM" src="https://user-images.githubusercontent.com/18750194/178972539-b36f9b64-efda-4585-92fc-f439cdd4f0f4.png">


@supriya3105 Can you confirm does it looks okay to you. Because I agree with Harshaan. On staging and prod. the time tracking page is not aligned with the headers while all others are. So do we want to keep this change?

2022-07-14 12:58 UTC, supriya3105 approved these changes

2022-07-14 12:59 UTC, supriya3105 commented
@harshaanNihal Approved for now. will test it on production and will get it fixed in case of any bad user experience.

2022-07-15 06:34 UTC, merged