Fix: Unable to add member to project
saeloun/miru-web pull request #566
Opened 2022-07-13 13:05 UTC by mayankagnihotri7

## Notion card
https://www.notion.so/Can-t-add-a-add-a-team-members-to-a-project-96026c5e630e45f3b33b84c48e4fe3ed

## Summary
- User was not able to add members to a project.

## Preview
[Video](https://www.loom.com/share/ce3be9df351a48dcbf4c98232d7a4a6d)

## Type of change
- Bug fix.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Tested locally.

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-07-13 13:48 UTC, keshavbiswa commented on app/controllers/internal_api/v1/project_members_controller.rb
> +        next unless m.key?("hourlyRate")
Why are we doing this?

2022-07-14 07:00 UTC, supriya3105 commented
@apoorv1316 Please test this bug fix.

2022-07-15 06:53 UTC, apoorv1316 requested changes
@mayankagnihotri7 I am still not able to add team members to some projects. You can see this behavior in the video. Also, the rates are not being fetched in add team member dropdown for already added users.

2022-07-15 12:39 UTC, mayankagnihotri7 commented
@apoorv1316 If you have attached any video it is not there in the comment. In my video as far as I can see it is adding the member and fetching the cost when viewing.

2022-07-18 08:28 UTC, supriya3105 commented
@mayankagnihotri7 Please check the tests that are failing. @apoorv1316 Please retest this functionality and share results

2022-07-20 06:04 UTC, supriya3105 commented
@mayankagnihotri7 Please resolve conflicts @gowsik-ragunath Can you review this PR today.

2022-07-20 06:43 UTC, gowsik-ragunath approved these changes
LGTM!

2022-07-25 18:13 UTC, apoorv1316 requested changes
@mayankagnihotri7 the rates are not being fetched in add team member modal. https://www.loom.com/share/17927c46afaf40608df0216076bc183b 
Also, can you change the heading of the modal from 'Add new client" to "Add team member". cc @supriya3105

2022-08-05 13:51 UTC, supriya3105 commented
@akhilgkrishnan CI tests are failing. Please check

2022-08-05 14:45 UTC, akhilgkrishnan commented
@apoorv1316 and @supriya3105 this PR is ready for testing

2022-08-08 08:42 UTC, apoorv1316 approved these changes
@supriya3105 Verified. Can be merged.

2022-08-08 10:16 UTC, merged