Add API for invoice payment download for admin
saeloun/miru-web pull request #595
Opened 2022-07-27 05:00 UTC by shalapatil

## Notion card
https://www.notion.so/saeloun/As-an-admin-I-should-be-able-to-download-an-invoice-0d03772e47954476959226bc18279f0b

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-07-27 05:59 UTC, keshavbiswa commented on app/policies/invoice_policy.rb
> +  end
Could you add a policy spec for invoice policy as well. Noticed there are couple of problems with our policies which we weren't catching since there were no tests for policies.

2022-08-01 08:34 UTC, shalapatil commented on app/policies/invoice_policy.rb
> +  end
done

2022-08-01 09:17 UTC, keshavbiswa commented on spec/requests/internal_api/v1/invoices/download_spec.rb
> +    context "when request is made to download the Invoice" do
We don't need to add this context.

2022-09-29 09:41 UTC, swaathi requested changes

2022-09-29 09:41 UTC, swaathi commented on app/controllers/internal_api/v1/invoices_controller.rb
> +    send_data InvoicePayment::PdfGeneration.process(invoice, current_company.company_logo || "")
Can you handle the logo or empty string inside the service? This does not need to here.

2022-10-04 12:38 UTC, sudeeptarlekar approved these changes
Looks good.

2022-10-04 12:38 UTC, sudeeptarlekar commented on config/routes/internal_api.rb
> +      get :download, on: :member
nit-picky suggestion

```suggestion
      member do
        post :send_invoice
        get :download
      end
```

2022-10-04 12:38 UTC, sudeeptarlekar commented on spec/requests/internal_api/v1/invoices/download_spec.rb
> +  context "when user is an admin" do
nit: I think by adding `authenticated` context we can DRY out before block. Thoughts?

2022-10-05 04:25 UTC, swaathi approved these changes

2022-10-05 05:21 UTC, shalapatil commented on spec/requests/internal_api/v1/invoices/download_spec.rb
> +  context "when user is an admin" do
I didn't get this, can you please explain bit more on this?

2022-10-05 08:19 UTC, sudeeptarlekar commented on spec/requests/internal_api/v1/invoices/download_spec.rb
> +  context "when user is an admin" do
```
subject { send_request :get, download_internal_api_v1_invoice_path(id: invoice.id) }

context 'authenticated' do
  before do
    create(...)
    user.add_role role, company
    sign_in user
  end

  context 'when user is admin' do
    let(:role) { :admin }
    ...
  end
end
```

2022-10-06 09:56 UTC, swaathi approved these changes

2022-10-07 03:54 UTC, akhilgkrishnan approved these changes
LGTM

2022-10-07 09:31 UTC, merged