Navbar restyle
saeloun/miru-web pull request #597
Opened 2022-07-27 13:04 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Change-the-navigation-on-Home-page-0af62fe9d5ac460fb9e1152618f3b21a
## Summary

- Navbar updated according to new designs
## Preview

<img width="1792" alt="Screenshot 2022-07-27 at 6 32 42 PM" src="https://user-images.githubusercontent.com/72149587/181253601-0830ff37-d895-40d8-a294-9cd3a4a54269.png">

## Type of change

- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-07-27 13:45 UTC, onkar-saeloun commented
@Shruti-Apte checks are failing

2022-07-27 14:04 UTC, onkar-saeloun commented on app/javascript/src/components/Navbar/index.tsx
> +    navAdminOptions.map((option) => (
same as above

2022-07-27 14:07 UTC, onkar-saeloun commented on app/javascript/src/components/Navbar/index.tsx
> +
no extra space

2022-07-27 14:07 UTC, onkar-saeloun commented on app/javascript/src/components/Navbar/index.tsx
> +          <img src={avatar} className="mr-2" />
while using <img> tag, it is good practice to use alt attribute

2022-07-28 08:29 UTC, apoorv1316 requested changes
@Shruti-Apte Can you remove the dashboard tab? We don't have any route for the dashboard tag. It throws an error when you click on the dashboard. Also, the navbar is open all the time. Do we want it open all the time or a button to open and close the navbar @supriya3105

2022-08-01 04:17 UTC, onkar-saeloun approved these changes

2022-08-01 04:55 UTC, AkashKale reviewed
Discussed following changes with Shruti :

- Font weight for selected section should be 800 (Extrabold)
- Spacing between bottommost section (logout) and profile section should be 24px (1.5rem)
- Update miru logo and profile image to 2x because currently it is looking blurred
- Update hover effect
- Update text : 'Setting' to 'Settings'

2022-08-02 08:44 UTC, apoorv1316 approved these changes

2022-08-02 15:19 UTC, merged