Specs for generate invoice
saeloun/miru-web pull request #602
Opened 2022-08-02 07:40 UTC by apoorv1316

## Notion card

## Summary
Cypress generate invoice specs

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-08-09 07:19 UTC, supriya3105 commented
@apoorv1316 Please rebase with develop as the test that is failing with this PR has been fixed. 

@mohinid Please review

2022-08-16 08:12 UTC, mohinid requested changes
[data-cy='new-invoice-button'] not found hence tests are failing. Please add it.

2022-08-17 04:29 UTC, apoorv1316 commented
@mohinid It's fixed now.
<img width="1792" alt="Screenshot 2022-08-17 at 9 59 42 AM" src="https://user-images.githubusercontent.com/18750194/185034935-b19c1251-0880-4c88-9c96-5021c0546df0.png">

2022-08-17 17:37 UTC, mohinid commented on cypress/support/commands.js
> +  cy.contains("Flipkart").click()
Why do we have Flipkart as hardcoded value here?

2022-08-18 05:52 UTC, apoorv1316 commented on cypress/support/commands.js
> +  cy.contains("Flipkart").click()
Just for the sake of simplicity. Flipkart has seed data in which we also have time entries.

2022-08-18 16:47 UTC, mohinid approved these changes
LGTM!

2022-08-19 10:54 UTC, merged