Timezones not showing bug
saeloun/miru-web pull request #604
Opened 2022-08-02 08:12 UTC by abinashpa

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-08-03 07:53 UTC, apoorv1316 commented
@abinashpa Is it ready for review?

2022-08-03 07:54 UTC, abinashpa commented
> @abinashpa Is it ready for review?

Yes

2022-08-04 04:52 UTC, apoorv1316 requested changes
@abinashpa 'company/new' page is broken. Please check it. 
<img width="1792" alt="Screenshot 2022-08-04 at 10 21 18 AM" src="https://user-images.githubusercontent.com/18750194/182765743-505007cc-7c47-4b4d-a612-23905057081d.png">

2022-08-09 05:36 UTC, abinashpa commented
<img width="1187" alt="Screenshot 2022-08-09 at 11 05 19 AM" src="https://user-images.githubusercontent.com/33005890/183572303-84a51bc2-9f28-4f2e-a6ad-200db20b47f5.png">
Working fine.

2022-08-09 07:20 UTC, supriya3105 commented
@abinashpa Please rebase with develop as the test that is failing with this PR has been been fixed by Gowsik earlier.

2022-08-09 08:09 UTC, apoorv1316 approved these changes

2022-08-09 10:48 UTC, gowsik-ragunath approved these changes
LGTM!

2022-08-09 10:49 UTC, gowsik-ragunath commented
@akhilgkrishnan It seems we are adding alot of JS code in action view can we integrate stimulus js in the app?

2022-08-09 13:12 UTC, akhilgkrishnan commented on app/assets/js/org_timezones.js
> +document.addEventListener("DOMContentLoaded", function () {
@abinashpa cant we move this to pack folder instead of assets?

2022-08-16 13:35 UTC, akhilgkrishnan approved these changes
LGTM

2022-08-18 06:59 UTC, supriya3105 commented
@abinashpa Please fix the tests that are failing

2022-08-23 06:36 UTC, merged