Project page redirect bug
saeloun/miru-web pull request #612
Opened 2022-08-10 07:23 UTC by abinashpa

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-08-10 10:00 UTC, supriya3105 commented
@abinashpa Can you add the link to the related notion ticket as well as add a loom video of the fix.

2022-08-17 07:08 UTC, apoorv1316 commented
@abinashpa In the notion, it's mentioned that after deleting a project it should be redirected to the client's details page but here in the PR description, it's mentioned that after deleting the project it should be redirected to the client's page. So what is the actually expected behavior here? And please update the description on the notion or GitHub wherever it is required.

2022-08-19 06:57 UTC, abinashpa commented
@apoorv1316 Fixes have been added for redirect back to the same client page.

2022-08-19 10:58 UTC, apoorv1316 approved these changes
@abinashpa LGTM!

2022-08-22 15:55 UTC, ajinkyaa commented on app/javascript/src/components/Projects/Modals/DeleteProject.tsx
> +          if (window.location.pathname.includes("/clients")) {
why using `window.location`? 
Using routes there right?

2022-08-23 04:09 UTC, akhilgkrishnan commented on app/javascript/src/components/Projects/Modals/DeleteProject.tsx
> +          }
Why do we need a redirection?

2022-08-23 04:16 UTC, akhilgkrishnan commented on app/javascript/src/components/Projects/Modals/DeleteProject.tsx
>            setShowDeleteDialog(false);
If we are redirecting the page. Then there is no point of having this method.

2022-08-23 04:28 UTC, akhilgkrishnan approved these changes
`If we are using window.location that actually redirect the page and sent all requests to the backend. This is against the SPA`

I'm approving this, but we should consider for a refactor ASAP.

2022-08-23 06:33 UTC, supriya3105 commented
@abinashpa we should be using the same method that we have implemented for clients page. 

@ajinkyaa Can you confirm which method should be used here.

2022-08-23 06:57 UTC, ajinkyaa commented
@akhilgkrishnan I had the same question when I was reviewing this last night.
it's needed because Abinash is redirecting it from the client page and routes are not set up on the project level. 

@supriya3105 if teams page is converted in react, can we have a call regarding setting up the routes on the project level?
that way we don't have to reload the application every time.

2022-08-23 06:58 UTC, ajinkyaa approved these changes

2022-08-23 07:07 UTC, ajinkyaa requested changes
Please wait I am discussing react-router with Onkar.

2022-08-23 07:19 UTC, ajinkyaa commented
@abinashpa had a discussion with Harshaan. 
you will need to use react-router methods instead of window methods. 
We already have a route setup for both client and project.

2022-08-24 07:59 UTC, abinashpa commented
@ajinkyaa On /project and /clients/:id page uses different data formats so it's impossible to set data from DELETE /projects/:id so I have implemented it in the previous way you suggested.

2022-08-24 08:00 UTC, abinashpa commented
@apoorv1316 Please test /client and /project page.

2022-08-25 08:13 UTC, supriya3105 commented
@ajinkyaa Can you review this PR is its implemented as per you discussion with Abinash.

2022-08-26 08:38 UTC, ajinkyaa commented
Closing this PR, @abinashpa will be raising PR with new branch.

2022-08-26 08:38 UTC, closed without merging