Fix: Client not selected when generating invoice from project details page
saeloun/miru-web pull request #643
Opened 2022-09-08 10:43 UTC by mayankagnihotri7

## Notion card
[Notion Card](https://www.notion.so/saeloun/Client-not-getting-selected-automatically-when-generating-an-invoice-from-the-project-details-page-95a331a293ed4031946ce5bcbb09d49b)

## Summary

Project names that were more than one word like `Dell Technologies` was appended to URL as query params and was only getting split using `?` operator whereas for multiple word names there were special characters being inserted by the browser and because of that the name was not matching when filtering to get the data.

## Preview

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-09-09 05:46 UTC, apoorv1316 approved these changes
@mayankagnihotri7 Please rebase

2022-09-09 09:31 UTC, mayankagnihotri7 commented
@apoorv1316 I have rebased it with the develop.

2022-09-09 11:03 UTC, JijoBose approved these changes

2022-09-12 09:48 UTC, keshavbiswa commented on app/javascript/src/components/Invoices/Generate/ClientSelection.tsx
> +          client.label.split(" ").join("").split(",").join("") ==
```suggestion
          client.label.replace(/\s|,/g, '')
```
Can you check if this works?

2022-09-12 13:05 UTC, mayankagnihotri7 commented on app/javascript/src/components/Invoices/Generate/ClientSelection.tsx
> +          client.label.split(" ").join("").split(",").join("") ==
It is working.

2022-09-12 13:16 UTC, keshavbiswa approved these changes
LGTM!

2022-09-13 06:02 UTC, apoorv1316 requested changes
@mayankagnihotri7 This is not working if a client name has a "." or "_" or "-".  It will not work if a client name is "cf.",  "coca-cola" or "coca_cola". Also, see the loom for more scenarios https://www.loom.com/share/acc5c15ceb124608b97690848142f3c8

2022-09-13 13:02 UTC, mayankagnihotri7 commented
@apoorv1316 I have made the requested changes and handled all those scenarios. Please review.

2022-09-13 13:35 UTC, keshavbiswa commented on app/javascript/src/components/Invoices/Generate/ClientSelection.tsx
>        );
Could you explain what are we trying to do with this bit of code?

2022-09-13 13:45 UTC, mayankagnihotri7 commented on app/javascript/src/components/Invoices/Generate/ClientSelection.tsx
>        );
I am replacing spaces which is encoded into the query string by the browser in the form of `%20` and replacing it with the space itself. And for the line `#38` I just reverted the code back to as it was before i.e; comparing the label coming from the backend with the query string we just got after removing the spaces from the url.

2022-09-19 04:22 UTC, apoorv1316 approved these changes

2022-09-19 04:22 UTC, merged