Added vendor folder to .gitignore
saeloun/miru-web pull request #644
Opened 2022-09-08 15:47 UTC by prasanthchaduvula

## Notion card
https://www.notion.so/6afc9500b2cc42af86be55f37894fb09?v=b4528f26f4424af7beaf036262796cb3&p=c78c618d68cc450290fd7980d39695f3&pm=s

## Summary

Added /vendor/* folder to .gitignore as it creates a lot of untracked files when we do bundle install —path vendor/bundle.
Even for assets, it's better to use the javascript folder where by default assets will be loaded to the application.js file. With the vendor, if we want to add assets we have to manually require them in the application.js file. Please refer https://stackoverflow.com/a/24169365

## Type of change
- Added /vendor/* and !/vendor/.keep to .gitignore
- Ran git rm -r --cached .
- Updated the files that were meant to be added to .gitignore file

### Checklist:
- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-09-08 16:16 UTC, prasanthchaduvula commented
@keshavbiswa Please test it locally. As checks, CI checks are passing here but in local I am facing the below issue. Maybe my setup is wrong but still please test it before you merge it. In the above summary, I added my thoughts on the vendor folder as well.

```
Companies#new when user is an employee renders Company#new page
      Failure/Error: <%= javascript_pack_tag "org_timezones", "data-turbo-track": "reload", defer: true %>
      
      ActionView::Template::Error:
        Webpacker can't find org_timezones.js in /Users/prasanthchaduvula/Documents/saeloun/miru-web/public/packs-test/manifest.json. Possible causes:
        1. You want to set webpacker.yml value of compile to true for your environment
           unless you are using the `webpack -w` or the webpack-dev-server.
        2. webpack has not yet re-run to reflect updates.
        3. You have misconfigured Webpacker's config/webpacker.yml file.
        4. Your webpack configuration is not creating a manifest.
        Your manifest contains:
        {
        }
  ```

2022-09-09 06:25 UTC, keshavbiswa requested changes

2022-09-09 06:25 UTC, keshavbiswa commented on .gitignore
> +/vendor/*
Like I mentioned I would like the vendor folder to exists. Since this can be used to store vendor assets.

2022-09-09 06:31 UTC, prasanthchaduvula commented on .gitignore
> +/vendor/*
@keshavbiswa Vendor folder along with the .keep file exists here with the above changes. Please check the file changes where vendor folder files didn't change even after running `git rm -r --cached .`
```
vendor
  javascript
    .keep
  .keep
```

2022-09-09 06:33 UTC, keshavbiswa commented on .gitignore
> +/vendor/*
Yes but future additions in vendor folder will remain ignored which we don't want. For this PR we only want to ignore vendor/bundle part.

2022-09-09 06:36 UTC, prasanthchaduvula commented on .gitignore
> +/vendor/*
@keshavbiswa got it but please give it a thought for future sustainable development https://stackoverflow.com/a/24169365
I will make the requested changes

2022-09-09 06:49 UTC, keshavbiswa commented on .gitignore
> +/vendor/*
Yeah, I'm not saying we're going to add our assets to vendor folder, but there is a reason why Rails include a vendor folder, if we're going to ignore it in our gitignore file entirely, then it just won't make sense.

2022-09-09 06:50 UTC, keshavbiswa approved these changes
LGTM!

2022-09-09 07:00 UTC, merged