Multiline select, search and filter on generate invoice
saeloun/miru-web pull request #645
Opened 2022-09-09 05:26 UTC by mohinid

## Notion card
https://www.notion.so/saeloun/Filter-and-search-for-Multiple-line-entries-on-invoice-553f5607f1f64eedbd3c3a57119d6e37?d=dc26a6ee88104a4e94b4196df99ed9a6

## Summary
1. Add multiline select feature on generate invoice form.
2. Add search on Name and Description.
3. Add Team member filter.
4. Add Date filter with options- 
- All
- Last week
- This week
- Last Month
- This Month
- Custom - Custom date picker should open with To and From fields.

## Preview

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-09-11 16:41 UTC, mohinid commented
@shalapatil can you please review this? I will add unit tests after your first review.

2022-09-12 10:54 UTC, shalapatil requested changes

2022-09-12 10:54 UTC, shalapatil commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +        fields: [:note, :user_name],
what's the use of fields if data is being fetched from pg only

2022-09-12 10:54 UTC, shalapatil commented on app/views/internal_api/v1/generate_invoice/show.json.jbuilder
> +  json.team_member User.find(line_item.user_id).full_name
include user while doing search query so that it won't fire separate query for finding each user

2022-09-12 10:54 UTC, shalapatil commented on app/views/internal_api/v1/generate_invoice/show.json.jbuilder
> +  json.client_id Project.find(line_item.project_id).client_id
same. include project, client  while doing search query so that it won't fire separate query for finding each project/client

2022-09-12 10:54 UTC, shalapatil commented on config/routes/internal_api.rb
> +      get :fetch_new_line_item_entries, on: :member
is this being used or not?

2022-09-12 10:54 UTC, shalapatil commented on lib/utility_functions.rb
> +      "*"
this is a generic function. why are we returning * ?

2022-09-12 10:54 UTC, shalapatil commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +      where_clause = default_filter.merge(Reports::TimeEntries::Filters.process(params))
rename as in it should be common to both, reports and generate invoice

2022-09-12 10:54 UTC, shalapatil commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +    render :show, locals: { new_line_item_entries:, filter_options: }, status: :ok
dont we need pagination now?

2022-09-12 11:16 UTC, mohinid commented on config/routes/internal_api.rb
> +      get :fetch_new_line_item_entries, on: :member
this will be removed

2022-09-12 11:20 UTC, mohinid commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +      where_clause = default_filter.merge(Reports::TimeEntries::Filters.process(params))
sure will rename

2022-09-12 11:20 UTC, mohinid commented on lib/utility_functions.rb
> +      "*"
using * for fetching all data if nothing is passed in date range

2022-09-12 11:20 UTC, mohinid commented on app/views/internal_api/v1/generate_invoice/show.json.jbuilder
> +  json.client_id Project.find(line_item.project_id).client_id
Yes this file is updated now. You can check in next commit

2022-09-12 11:21 UTC, mohinid commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +        fields: [:note, :user_name],
Hi, this is to search data only inside these 2 fields and nowhere else.

2022-09-13 15:31 UTC, mohinid commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +      end
fixed

2022-09-14 06:56 UTC, keshavbiswa commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +    render :show, locals: { new_line_item_entries:, filter_options: }, status: :ok
@mohinid Are we removing pagination here?

2022-09-14 06:56 UTC, keshavbiswa commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +      project = Project.find_by(client_id: params[:id])
As mentioned earlier it will be great if you could add `includes` here to avoid n+1 queries.

2022-09-14 06:56 UTC, keshavbiswa commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +      { project_id: Project.find_by(client_id: params[:id]).id }
Can we extract Project.find_by(client_id: params[:id]) elsewhere so that we don't need to query more than once as discussed earlier?

2022-09-14 06:56 UTC, keshavbiswa commented on app/views/internal_api/v1/generate_invoice/show.json.jbuilder
> +  json.client_id Project.find(line_item.project_id).client_id
`Project.find(line_item.project_id).client_id` => `line_item.project.client_id` ? 

If the above code works, then don't forget to add `:inverse_of` association to timesheet_entry relationship.

2022-09-14 07:27 UTC, mohinid commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +    render :show, locals: { new_line_item_entries:, filter_options: }, status: :ok
hi I have added to the query. @keshavbiswa  I couldn't accommodate it in the earlier way.

2022-09-15 06:29 UTC, mohinid commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +    render :show, locals: { new_line_item_entries:, filter_options: }, status: :ok
no, i have added to the searchkick query.

2022-09-15 07:24 UTC, prasanthchaduvula commented on app/models/client.rb
> +         timesheet_entries.duration as qty",
@mohinid Please rebase the current branch with develop branch. In develop recently we changed qty to quantity for consistency   `timesheet_entries.duration as quantity"`
https://github.com/saeloun/miru-web/blob/develop/app/models/client.rb#L61

2022-09-15 07:38 UTC, mohinid commented on app/models/client.rb
> +         timesheet_entries.duration as qty",
done. although i am not using this query for my pr.

2022-09-15 11:24 UTC, prasanthchaduvula commented
I tested this PR API changes in local. @mohinid As discussed in the call, update the resourceful routing on `companies controller` if we are going to use it to fetch the company along with the clients data on the invoice generation page instead of using the existing index action of `generate_invoice_controller` then make the route and action of companies controller to resourceful  like and also please update the auth policy for it. 

Otherwise keep the index action of `generate_invoice_controller` instead of removing it. Regarding the `generate_invoice_controller` show action please update `new_line_item_entries` generated from searchkiq to support the props and values we need on frontend. 
```
users.first_name as first_name,
users.last_name as last_name,
timesheet_entries.work_date as date,
timesheet_entries.note as description,
project_members.hourly_rate as rate,
timesheet_entries.duration as quantity"
```

2022-09-15 11:27 UTC, prasanthchaduvula commented
I tested this PR API changes in local. @mohinid As discussed in the call, update the resourceful routing on `companies controller` if we are going to use it to fetch the company along with the clients data on the invoice generation page instead of using the existing index action of `generate_invoice_controller` then make the route and action of companies controller to resourceful  like and also please update the auth policy for it. 

Otherwise keep the index action of `generate_invoice_controller` instead of removing it. Regarding the `generate_invoice_controller` show action please update `new_line_item_entries` generated from searchkiq to support the props and values we need on frontend. 
```
users.first_name as first_name,
users.last_name as last_name,
timesheet_entries.work_date as date,
timesheet_entries.note as description,
project_members.hourly_rate as rate,
timesheet_entries.duration as quantity"
```

cc: @supriya3105

2022-09-19 05:49 UTC, mohinid commented
@prasanthchaduvula I have updated the company show method and generate invoice index methods as discussed. Tested via
<img width="1792" alt="Screenshot 2022-09-19 at 11 18 37 AM" src="https://user-images.githubusercontent.com/5313625/190956464-529106f0-5706-4fff-afde-04954f162e34.png">
 postman. Working on unit tests.
<img width="1792" alt="Screenshot 2022-09-19 at 11 18 34 AM" src="https://user-images.githubusercontent.com/5313625/190956452-b562bcc3-a95b-4a83-b9fc-444399b6faeb.png">

2022-09-21 06:18 UTC, shalapatil commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
> +        fields: [:note, :user_name],
Okay

2022-09-21 16:32 UTC, mohinid commented
@shalapatil  the tests are failing only in Ci although passing when I trigger from the specific file location on local. Have you faced this in the reports tests?

2022-09-22 06:50 UTC, mohinid commented
> @shalapatil the tests are failing only in Ci although passing when I trigger from the specific file location on local. Have you faced this in the reports tests?

Hey, it's fixed. please ignore. :)

2022-09-26 09:48 UTC, mohinid commented
@shalapatil  @keshavbiswa  can you pls review this pr.

2022-09-28 06:56 UTC, mohinid commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
>      end
sure

2022-09-29 05:37 UTC, mohinid commented
@apoorv1316 
 the issue is with creation of the projectMember entry. Currently there is no entry created for a user if his hourly_rate is set as '0' for that project. Will fix it in separate issue.
For now please try and test with users who have 'non-zero' hourly rate set for project that you are selecting in time-entry.

Raised bug here- https://www.notion.so/saeloun/Create-an-entry-in-project_members-table-for-users-having-0-00-as-hourly_rate-9a9bb6636b0d4283a666181327c4a523
Shalaka will be taking it.

2022-10-03 11:56 UTC, mohinid commented on app/controllers/internal_api/v1/generate_invoice_controller.rb
>      end
Will integrate this change in issue- https://www.notion.so/saeloun/Create-service-to-get-new_line_item_entries-0b664c85c44a4752a10b990f6015706e

2022-10-03 16:25 UTC, prasanthchaduvula approved these changes

2022-10-03 16:41 UTC, merged