Date picker edit timesheet entry
saeloun/miru-web pull request #651
Opened 2022-09-12 06:30 UTC by abinashpa

## Notion card
https://www.notion.so/saeloun/User-should-be-able-to-edit-the-date-for-a-time-tracking-entry-On-clicking-the-date-field-a-custom--1b82e058bbb64d91b4aee68a870f6cb7
## Summary
- The date picker should pop up on clicking the date while editing the timesheet entry.
- After choosing a date it should update the timesheet entry and change the date on that entry.

## Preview
<img width="1436" alt="Screenshot 2022-09-12 at 11 59 54 AM" src="https://user-images.githubusercontent.com/33005890/189587562-8c638d57-644d-4954-8a57-1124ef8fd24e.png">

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-09-12 06:47 UTC, JijoBose requested changes

2022-09-12 06:47 UTC, JijoBose commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +    return `${getNumberWithOrdinal(Number(day))} ${month}, ${year}`;
Since we are already using date-fns , we can write this code as

```javascript
import { format } from 'date-fns';

format(new Date, 'do MMM, yyyy')
// "12th Sep, 2022"
```

Ref: https://date-fns.org/v2.29.2/docs/format

2022-09-13 06:32 UTC, apoorv1316 commented
@supriya3105 Before I review this PR Can we Ask Akash for the design? Because in the image attached I can see the calendar's height much more than the card's height and it hides the hours logged field also.

2022-09-13 08:10 UTC, abinashpa commented
@apoorv1316 There are some UI issues occurring.
- Day, week and month have different sizes.
- Clicking on a date with a timesheet entry makes the calendar bigger.
- Edit and delete button disappeared

2022-09-15 05:39 UTC, JijoBose approved these changes

2022-09-16 04:57 UTC, apoorv1316 commented
@abinashpa FIx failing tests also refer to the design for calendar positioning https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?node-id=8207%3A77554
cc @supriya3105

2022-09-19 04:25 UTC, apoorv1316 commented
@abinashpa Something is breaking on this PR. Please check
<img width="1792" alt="Screenshot 2022-09-19 at 9 55 19 AM" src="https://user-images.githubusercontent.com/18750194/190949662-83fe2024-f4e8-4258-88c2-d0126cac0369.png">

2022-09-19 04:28 UTC, abinashpa commented
> @abinashpa Something is breaking on this PR. Please check
> <img width="1792" alt="Screenshot 2022-09-19 at 9 55 19 AM" src="https://user-images.githubusercontent.com/18750194/190949662-83fe2024-f4e8-4258-88c2-d0126cac0369.png">
> 

On it.

2022-09-19 07:34 UTC, abinashpa commented
<img width="1440" alt="Screenshot 2022-09-19 at 1 00 36 PM" src="https://user-images.githubusercontent.com/33005890/190969759-26e58789-17eb-43bd-b887-6bd64599311d.png">
New UI.

2022-09-22 05:04 UTC, apoorv1316 commented
@abinashpa I changed the props in the custom date picker to be more generic. Make changes in your PR accordingly

2022-09-28 10:47 UTC, akhilgkrishnan reviewed
@abinashpa Added couple of comments

2022-09-28 10:47 UTC, akhilgkrishnan commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +      }
can't we handle this in interceptors

2022-09-28 10:47 UTC, akhilgkrishnan commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +  const [selectedDate, setSelectedDate] = useState(selectedFullDate);
type checking missing for the useState

2022-09-28 10:47 UTC, akhilgkrishnan commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +    const textArea = document.querySelector("textarea");
Can't we use the useRef

2022-09-28 10:47 UTC, akhilgkrishnan commented on app/javascript/src/components/time-tracking/Index.tsx
> +        const ns = { ...allEmployeesEntries, [selectedEmployeeId]: res.data.entries };
can you name the variables properly

2022-09-29 07:18 UTC, abinashpa commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +      }
We can but then we can't use the interceptor as DRY.

2022-09-29 07:35 UTC, abinashpa commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +    const textArea = document.querySelector("textarea");
We might but this piece of code wasn't added in this PR.

2022-10-03 06:33 UTC, apoorv1316 commented
@abinashpa Please check this
<img width="1792" alt="Screenshot 2022-10-03 at 12 03 06 PM" src="https://user-images.githubusercontent.com/18750194/193514472-76d1b1c3-b1c8-44ee-9610-1b7f076e1bf8.png">

2022-10-03 07:28 UTC, abinashpa commented
@apoorv1316 Everything is working fine, Can't reproduce the error.

2022-10-03 11:52 UTC, apoorv1316 requested changes
@abinashpa As per the ticket description, the date picker should close when clicked anywhere outside it.  I wasn't able to do it. Have you implemented this functionality?

2022-10-05 07:54 UTC, apoorv1316 commented
@abinashpa resolve conflicts

2022-10-05 08:38 UTC, prasanthchaduvula requested changes

2022-10-05 08:38 UTC, prasanthchaduvula commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +  useEffect(() => {
@abinashpa Please use existing `useOutsideClick` helper function insteed of using this custom code.

2022-10-05 13:32 UTC, prasanthchaduvula commented
@abinashpa I resolved the conflicts & also Fixed the Updating time entry based on date change. Please make the requested changes like `useOutsideClick` helper to close the date picker instead of custom code. Please test the app before you make any changes.

2022-10-05 13:39 UTC, prasanthchaduvula requested changes

2022-10-05 13:39 UTC, prasanthchaduvula commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +    const clickHandler = (e: MouseEvent) => {
@abinashpa Please use existing useOutsideClick helper function instead of using this custom code for closing calendar by clicking outside.

2022-10-07 04:15 UTC, apoorv1316 requested changes
@abinashpa In your pr when we create a non-billable entry and click on the update button, the billable checkbox is checked(for non-billable too). So if we update the data then the entry is billed. https://www.loom.com/share/33771d65de474107b083249f0660b0c1

2022-10-07 05:49 UTC, prasanthchaduvula commented
@abinashpa This is already fixed on the develop. Ref: #654 Please have a look and change your PR accordingly. 
cc: @apoorv1316

2022-10-07 08:06 UTC, abinashpa commented
@apoorv1316 I have fixed the billable issue, please do a test again.

2022-10-10 05:04 UTC, apoorv1316 approved these changes

2022-10-10 05:04 UTC, apoorv1316 commented
@prasanthchaduvula Can you review it one more time, please?

2022-10-11 04:06 UTC, prasanthchaduvula requested changes

2022-10-11 04:06 UTC, prasanthchaduvula commented on app/javascript/src/components/time-tracking/EntryCard.tsx
> +import { Badge } from "../../StyledComponents";
@abinashpa  Please do`import { Badge } from "StyledComponents"`

2022-10-11 04:08 UTC, prasanthchaduvula commented
@apoorv1316 I don't think this PR properly got rebased with develop branch. Please test all the functionality this PR handles along with the complete time sheet entry page functionality as well

2022-10-12 08:01 UTC, prasanthchaduvula approved these changes

2022-10-13 07:06 UTC, apoorv1316 approved these changes

2022-10-13 08:15 UTC, apoorv1316 commented
@abinashpa Please resolve conflicts. We just merged a hackotberfest PR in develop.

2022-10-14 07:44 UTC, merged