Updated BillTag
saeloun/miru-web pull request #654
Opened 2022-09-12 23:03 UTC by prasanthchaduvula

## Notion card
notion://www.notion.so/saeloun/Bugs-in-update-timesheet-entry-719807ecfcce41d99860f66c04159422

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-09-20 19:43 UTC, prasanthchaduvula commented
@apoorv1316 Flaky test on cypress https://github.com/saeloun/miru-web/actions/runs/3092832700/jobs/5004546339
I am not sure about it. Please have a look

Please test the PR app regarding the bug fix.

2022-09-21 18:48 UTC, swaathi approved these changes

2022-09-21 19:07 UTC, prasanthchaduvula commented
@akhilgkrishnan I created Badge reusable styled component. I want to update `alias.js` file and I tried but config not working. As of now everything working fine but it's better if we add it to `alias.js` file for better imports in future.

2022-09-23 08:27 UTC, supriya3105 commented
@akhilgkrishnan Can you review ?

2022-09-26 06:30 UTC, apoorv1316 approved these changes

2022-09-27 09:08 UTC, akhilgkrishnan requested changes
@prasanthchaduvula Added some changes. Rest LGTM 👍

2022-09-27 09:08 UTC, akhilgkrishnan commented on app/javascript/src/styledComponents/Badge.tsx
> +import PropTypes from "prop-types";
You don't need a proptype checking if you are using typescript, you can directly use the typescript one.

```suggestion
type Props = {
  color: string;
};
```

2022-09-27 09:08 UTC, akhilgkrishnan commented on app/javascript/src/styledComponents/Badge.tsx
> +}) => (
```suggestion
const Badge = ({
  text = null,
  color = "",
  bgColor = "",
  className = ""
}:  Props) => (
```

2022-09-28 02:49 UTC, akhilgkrishnan approved these changes
LGTM

2022-09-28 09:06 UTC, merged