Fix invoices new line item entries
saeloun/miru-web pull request #660
Opened 2022-09-15 23:43 UTC by prasanthchaduvula

## Notion card
https://www.notion.so/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=2d3b4e5e8abe4bd8b4b6e3acfc77e977&pm=s

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-09-19 12:25 UTC, prasanthchaduvula commented
@apoorv1316 Please create issue on notion icebox - Extract the NewLineItemTable, Invoice Table, Invoice Total and Manual Entry components to invoice common components. As of now I only created  NewLineItemTable Header component to reuse it. It's better to create a new issue to work on these components. Everything is repeating in the above components and they are present in both generate & edit invoice. To implement any feature at present we have to write the codebase in both the places instead of writing at one place. Once we extract these components we can just call these components wherever needed and we can simply update the prop value passed to these components.

cc: @keshavbiswa @akhilgkrishnan @supriya3105

2022-09-20 05:02 UTC, apoorv1316 requested changes
@prasanthchaduvula Please see the loom https://www.loom.com/share/55cdb4c8285946488a99b3ad5704a2fa

2022-09-20 10:00 UTC, swaathi approved these changes

2022-09-20 10:30 UTC, prasanthchaduvula commented
@apoorv1316 Please test it again regarding the load more item on edit invoice

2022-09-20 13:36 UTC, apoorv1316 approved these changes

2022-09-20 13:36 UTC, merged