Stripe Payment Entry
saeloun/miru-web pull request #680
Opened 2022-09-27 10:08 UTC by shalapatil

## Notion card

## Summary
https://www.notion.so/saeloun/Add-entry-to-payments-when-the-user-pays-for-an-invoice-through-Stripe-1d92b138e95e4e83a89b29ca1d714555

I started work off https://github.com/saeloun/miru-web/pull/508

Webhook for listening to stripe events as per the [docs](https://stripe.com/docs/payments/checkout/fulfill-orders)

If webhook event is as expected then we create payment entry and also updates the invoice as paid

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-06 11:33 UTC, swaathi requested changes

2022-10-06 11:33 UTC, swaathi commented on app/controllers/webhooks_controller.rb
> +  def fulfill_stripe_checkout
This must be handled in a lib class. This is too much logic for the controller. Please refactor.

2022-10-06 11:33 UTC, swaathi commented on app/services/invoice_payment/stripe_checkout_fulfillment.rb
> +      data_object.payment_status == "paid"
Please add two separate methods for `complete?` and `paid?` so that we can use it elsewhere. Also rename the function to `is_valid_event?`.

2022-10-06 11:33 UTC, swaathi commented on app/services/invoice_payment/stripe_checkout_fulfillment.rb
> +        note: "Stripe_Payment_success"
Only success is in lowercase S. Any specific reason? Or is this a bug?

2022-10-06 11:33 UTC, swaathi commented on app/services/invoice_payment/stripe_payment_intent.rb
>      Rails.logger.error error.backtrace.join("\n")
Please remove all logger images.

2022-10-06 11:33 UTC, swaathi commented on config/routes.rb
> +  post "webhooks/stripe/checkout/fulfillment", to: "webhooks#fulfill_stripe_checkout"
Can you have a namespace called "webhooks" and organize everything under that?

2022-10-06 11:33 UTC, swaathi commented on config/routes.rb
> +  post "webhooks/stripe/checkout/fulfillment", to: "webhooks#fulfill_stripe_checkout"
Similarly, organize the controller structure.

2022-10-07 09:10 UTC, apoorv1316 approved these changes
Tested it on Shalaka's machine. There was some error with my API keys. Will have to configure webhooks for staging and test it on staging.

2022-10-07 09:17 UTC, shalapatil commented on config/routes.rb
> +  post "webhooks/stripe/checkout/fulfillment", to: "webhooks#fulfill_stripe_checkout"
> Can you have a namespace called "webhooks" and organize everything under that?

Can you please explain this more?

2022-10-07 09:36 UTC, shalapatil commented on app/services/invoice_payment/stripe_checkout_fulfillment.rb
> +        note: "Stripe_Payment_success"
This was a bug

2022-10-07 09:36 UTC, shalapatil commented on app/services/invoice_payment/stripe_payment_intent.rb
>      Rails.logger.error error.backtrace.join("\n")
replacing it with puts, is this correct?

2022-10-07 13:48 UTC, akhilgkrishnan reviewed
@shalapatil I've commented  couple of my doubts and concerns. Also, I noticed that there are some places we are using puts for logging. We have to change that to rails logger. https://guides.rubyonrails.org/debugging_rails_applications.html#the-logger. So it will be easier for us to debug the logs.

2022-10-07 13:48 UTC, akhilgkrishnan commented on app/controllers/webhooks/stripe_controller.rb
> +  skip_after_action :verify_authorized
How we are authenticating the webhook request.

2022-10-07 13:48 UTC, akhilgkrishnan commented on app/services/invoice_payment/stripe_checkout_fulfillment.rb
> +    @invoice = Invoice.find(event.data.object.metadata.invoice_id)
can you add a rescue on this block

2022-10-10 05:04 UTC, shalapatil commented on Gemfile
> +  gem "hash_dot"
We get event data in following formats
event.class =  Stripe::Event
event.data.objec.tclass Stripe::Customer
and data is accessible via dots methods

In order to do so, converting mocked data using hash_dot gem to same format

2022-10-10 05:05 UTC, shalapatil commented on app/services/invoice_payment/stripe_payment_intent.rb
> +    nil
previously it was rails logger only. @swaathi asked to remove that. but I am not sure if puts was the correct format. I had asked her in the comments.

2022-10-10 05:06 UTC, shalapatil commented on app/controllers/webhooks/stripe_controller.rb
> +  skip_after_action :verify_authorized
we are authenticating that in the code using webhook secret.

2022-10-10 05:07 UTC, shalapatil commented on app/services/invoice_payment/stripe_checkout_fulfillment.rb
> +    end
we return 400 saying that is invalid payload which happens in the caller class

2022-10-10 09:38 UTC, swaathi commented on app/services/invoice_payment/stripe_payment_intent.rb
> +    nil
I've asked to remove all comments (irrespective of puts or Rails logger) since it is essentially code smell. If we need to read debug info from the codebase, I would suggest to log it elsewhere.

2022-10-10 09:50 UTC, swaathi commented on app/services/invoice_payment/stripe_payment_intent.rb
>      Rails.logger.error error.backtrace.join("\n")
Replied in another comment.

2022-10-10 09:50 UTC, swaathi commented on config/routes.rb
> +  post "webhooks/stripe/checkout/fulfillment", to: "webhooks#fulfill_stripe_checkout"
Explained over Slack, resolving this thread.

2022-10-10 09:51 UTC, swaathi approved these changes

2022-10-10 12:38 UTC, akhilgkrishnan approved these changes
LGTM

2022-10-12 08:35 UTC, merged