Autosize timesheet notes textarea only on focus to avoid incorrect height and scroll issue
saeloun/miru-web pull request #695
Opened 2022-10-01 21:42 UTC by aaj013

## Summary
Closes #689

Ref: https://www.jacklmoore.com/autosize/#faq-hidden

## Preview
[miru-textarea-autosize-fix.webm](https://user-images.githubusercontent.com/5847582/193429373-ade0524c-a535-4bd0-8e5c-edf9f13f2353.webm)

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

### Checklist:
- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-03 16:09 UTC, prasanthchaduvula requested changes

2022-10-03 17:32 UTC, aaj013 commented on app/javascript/src/components/time-tracking/AddEntry.tsx
> +    });
Sure. Will do

2022-10-04 07:51 UTC, supriya3105 commented
@prasanthchaduvula Can you look at this again. Seems there was another deployment after your review yesterday. 
@apoorv1316 Please test this and merge once approved by Prasanth.

2022-10-04 07:59 UTC, prasanthchaduvula approved these changes
LGTM

2022-10-05 06:30 UTC, aaj013 commented
> @aaj013 Please resolve the conflicts

Hi, I am out of town for one week and internet access is very difficult here. It would be great if someone can help with resolving conflicts. Actually, there were no conflicts when I pushed my last commit. Don't know how it happened!

2022-10-05 16:13 UTC, apoorv1316 approved these changes

2022-10-05 16:13 UTC, merged