Update viewed state invoices to overdue
saeloun/miru-web pull request #699
Opened 2022-10-03 17:21 UTC by shalapatil

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-04 06:39 UTC, supriya3105 commented
@apoorv1316 Can you test this by running it on local.

2022-10-07 03:50 UTC, akhilgkrishnan requested changes
@shalapatil Requested one change

2022-10-07 03:50 UTC, akhilgkrishnan commented on app/services/update_invoice_status_to_overdue_service.rb
> +      .update_all(status: "overdue")
```suggestion
    Invoice
      .where(status: ["viewed", "sent"], due_date: ...Date.current)
      .update_all(status: "overdue")
```

2022-10-07 03:57 UTC, apoorv1316 approved these changes

2022-10-07 09:43 UTC, apoorv1316 commented
> @apoorv1316 Can you test this by running it on local.

@supriya3105 tested on local.

2022-10-07 09:51 UTC, akhilgkrishnan approved these changes
LGTM

2022-10-07 13:30 UTC, merged