renamed time-tracking and updated imports
saeloun/miru-web pull request #712
Opened 2022-10-06 09:36 UTC by camperjett

fixes #706 
## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-06 09:37 UTC, camperjett commented
@akhilgkrishnan PTAL

2022-10-06 09:47 UTC, akhilgkrishnan commented
@prasanthchaduvula can you review this?

2022-10-06 09:56 UTC, prasanthchaduvula requested changes

2022-10-06 09:56 UTC, prasanthchaduvula commented on app/javascript/src/constants/routes.ts
> +import TimeTracking from "../components/TimeTracking/Index";
@camperjett No need of giving `Index`. Rename `Index` file to `index` inside `TimeTracking` folder and update `import TimeTracking from "../components/TimeTracking/Index" ` to import TimeTracking from "../components/TimeTracking";;

2022-10-06 11:36 UTC, prasanthchaduvula approved these changes

2022-10-07 04:05 UTC, apoorv1316 approved these changes

2022-10-07 04:34 UTC, supriya3105 commented
@camperjett Can you check the CI tests that are failing with this PR ?

2022-10-13 08:13 UTC, apoorv1316 commented
@camperjett Thanks for contributing to miru.

2022-10-13 08:13 UTC, merged