Invoice list page updated
saeloun/miru-web pull request #715
Opened 2022-10-07 07:48 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Invoice-Page-UI-Issues-Updated-Invoice-Page-Designs-db0e720abda04294a739af8c04182d48

## Summary

- Invoice list page updated designs
-  Static data (No API integration)

## Preview

https://www.loom.com/share/6e26d057d42a48fe9467813c49952611

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-10-07 07:57 UTC, onkar-saeloun requested changes
@Shruti-Apte some minor changes.

2022-10-07 07:57 UTC, onkar-saeloun commented on app/javascript/src/common/CustomCheckbox.tsx
> +  <div className="">
we don't need empty className

2022-10-07 07:57 UTC, onkar-saeloun commented on app/javascript/src/components/Invoices/List/MoreOptions.tsx
> +    onMouseLeave={() => setIsMenuOpen(false)}
an event like onMouseLeave can cause performance issues. You can use debouncing inside them which will increase performance. Maybe you can create a separate task for this.

2022-10-07 07:57 UTC, onkar-saeloun commented on app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
> +      <h3 className="text-xs font-semibold text-miru-dark-purple-400">20.02.2020</h3>
Do we need hard coded values?

2022-10-07 07:57 UTC, onkar-saeloun commented on app/javascript/src/components/Invoices/List/Table/index.tsx
> +            deselectInvoices={deselectInvoices} setShowDeleteDialog={setShowDeleteDialog} setInvoiceToDelete={setInvoiceToDelete} />
You can take new line for individual prop.

2022-10-07 10:40 UTC, Shruti-Apte commented on app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
> +      <h3 className="text-xs font-semibold text-miru-dark-purple-400">20.02.2020</h3>
Values will be replaced when API is ready

2022-10-10 04:30 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/MoreOptions.tsx
> +    onMouseLeave={() => setIsMenuOpen(false)}
@Shruti-Apte There is already a useDebounce helper function. Please use it.

2022-10-10 04:51 UTC, prasanthchaduvula requested changes

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/CustomAvatar.tsx
> +const CustomAvatar = ({ url="", initials="" }) => (
@Shruti-Apte Add `classnames` support to allow developers to customise the avatar. Ref Badge component

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/CustomAvatar.tsx
> +    : initials ? <span className="inline-flex h-14 w-14 items-center justify-center rounded-full bg-gray-500">
@Shruti-Apte Coming to initials, how we are asking the other components to share these values. For example we should ask for the complete full name like `Shurthi Apte` & we have to split here and make the avatar. We should not ask developer to share `SA` as prop values to be shared. Please fix it.

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Tooltip.tsx
> +const Tooltip = (props) => {
@Shruti-Apte Please destructure the props. As developers while using this component they will pass the values to required props & it helps in better documentation & better reusability.

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Tooltip.tsx
> +    }, props.delay || 400);
@Shruti-Apte After destructuring use `delay` instead of `props.delay`
and updated the values across the component wherever `props.` used

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Tooltip.tsx
> +const Tooltip = (props) => {
@Shruti-Apte Please add classnames support to allow developers to customise the component & to override the styling.

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomCheckbox.tsx
> +  <div className="">
@Shruti-Apte If there is no styles provided please remove the `className=""` from the above `div`

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/InvoiceStatus.tsx
> +      <span className={`${getStatusCssClass(invoice.status)} uppercase`}>
Use `<Badge />` component here.

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
> +    <span className={getStatusCssClass("Draft") + " uppercase mt-2"}>
Use <Badge /> component here

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/Table/TableRow.tsx
>          <span className={getStatusCssClass(invoice.status) + " uppercase"}>
@Shruti-Apte use `<Badge />` component

2022-10-10 04:51 UTC, prasanthchaduvula commented on app/javascript/stylesheets/application.scss
> +
@Shruti-Apte Move `Tooltip` styling to the `Tooltip` StyledComponent

2022-10-10 06:14 UTC, apoorv1316 requested changes
@Shruti-Apte Some changes that need to be done
1. Use "StyledComponenets" instead of "styledComponents" in imports
2. On the recently updated card there is no space between the invoice number and date.
<img width="191" alt="Screenshot 2022-10-10 at 11 38 47 AM" src="https://user-images.githubusercontent.com/18750194/194806911-dce8aedb-e0e0-4746-98db-36094a5e42a2.png">
3. Send To tooltip is still visible sometimes even after the send invoice modal is opened
<img width="1792" alt="Screenshot 2022-10-10 at 11 40 09 AM" src="https://user-images.githubusercontent.com/18750194/194807024-568dab78-25b3-4e92-8e40-2cf2d0e1dc72.png">
4. Cursor pointer on the below list items
<img width="195" alt="Screenshot 2022-10-10 at 11 41 10 AM" src="https://user-images.githubusercontent.com/18750194/194807114-aeac329d-93d6-4b20-a9d0-e3b20a1ecabc.png">
5. CSS on balances section breaking on iPad
<img width="1792" alt="Screenshot 2022-10-10 at 11 43 01 AM" src="https://user-images.githubusercontent.com/18750194/194807262-5391bb29-8a72-4e87-9266-312f15fec7fd.png">

2022-10-11 04:18 UTC, prasanthchaduvula requested changes

2022-10-11 04:18 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/CustomAvatar.tsx
> +const CustomAvatar = ({ url="", initials="" }) => (
@Shruti-Apte Instead of `CustomAvatar` Please rename it to `Avatar` as we are already storing it inside the StyledComponents

2022-10-11 04:18 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/Table/TableRow.tsx
> +import CustomAvatar from "../../../../styledComponents/CustomAvatar";
@Shruti-Apte it should be imported as
`import {Avatar} from "StyledComponents";`

2022-10-11 04:18 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/Table/TableRow.tsx
> +import Tooltip from "../../../../styledComponents/Tooltip";
@Shruti-Apte it should be imported as
import {Tooltip} from "StyledComponents";

2022-10-11 04:58 UTC, Shruti-Apte commented on app/javascript/stylesheets/application.scss
> +
You mean in the StyledComponent folder  or should I create a different file naming StyledComponent.scss ?

2022-10-11 05:34 UTC, prasanthchaduvula commented on app/javascript/stylesheets/application.scss
> +
@Shruti-Apte Inside the `Tootip` component itself and all these are tailwindcss classes, so please make them inline

2022-10-11 06:21 UTC, onkar-saeloun approved these changes
LGTM Just one comment

2022-10-11 06:21 UTC, onkar-saeloun commented on app/javascript/src/StyledComponents/Tooltip.tsx
> +        <div className={classnames(`before:h-0 before:w-0 before:absolute before:pointer-events-none before:border-4 before:mr-4 before:content-none before:left-1/2 absolute left-1/2 z-10 rounded-md
can we break this to multiple lines?

2022-10-11 09:37 UTC, prasanthchaduvula requested changes

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Avatar.tsx
> +const Avatar = ({ url = "", name = "" }) => {
@Shruti-Apte Please add `className` prop to customise & override the Avatar styling. Refer Badge component

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Avatar.tsx
> +      let initials = "";
@Shruti-Apte In the code we are getting the name if it present. Then we are splitting but no need of running a for loop below.

we can write 
```
var str = "Shruthi Apte";
var matches = str.match(/\b(\w)/g); // ['S','A']
var acronym = matches.join(''); 
```
or we can also write
```
const fullName = nameString.split(' ');
const initials = fullName.shift().charAt(0) + fullName.pop().charAt(0); // last name adding should be conditional
initials.toUpperCase();
```

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Avatar.tsx
> +  useEffect(() => getInitials(), [initials]);
@Shruti-Apte Why Initials is in dependent array. We will get them on the component mount and we never do component update for Avatar right?

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Avatar.tsx
> +  return url ? (
@Shruti-Apte Instead of writing three conditions try to fix it in useEffect itself then return avatar with the image or name. If there is a default avatar if both the values not provided then by default it will be in image condition itself

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Avatar.tsx
> +
@Shruti-Apte Please add prop type validations

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/Tooltip.tsx
> +  delay = 400,
@Shruti-Apte It's not supporting the custom styles or not allowing developers to override it. Please use the `className` prop to allow it.
Refer Badge component

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/index.tsx
> +  Tooltip,
@Shruti-Apte Make this exporting in Alphabet wise for consistency.
```
export {
  Avatar
  Badge,
  Tooltip,
  }
```

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/InvoiceStatus.tsx
> +        className={getStatusCssClass(invoice.status) + " uppercase"}
@Shruti-Apte Please write this in the below format to allow others to add any styles in feature without making a concatination.
``className={`${getStatusCssClass(invoice.status)} uppercase`}``

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
> +      className={getStatusCssClass("Draft") + " uppercase mt-2"}
@Shruti-Apte Please write this in the below format to allow others to add any styles in feature without making a concatination.
className={`${getStatusCssClass("Draft"} uppercase mt-2`}

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
> +import getStatusCssClass from "utils/getStatusTag";
@Shruti-Apte Please change the `getStatusTag` file name to `getBadgeStatus`

2022-10-11 09:37 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/Table/TableRow.tsx
> +import { Avatar, Tooltip, Badge } from "StyledComponents";
@Shruti-Apte Always import them in the alphabet format.
`import { Avatar, Badge, Tooltip } from "StyledComponents";`

2022-10-12 06:39 UTC, prasanthchaduvula requested changes

2022-10-12 06:39 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/Filters/index.tsx
> +import getStatusCssClass from "../../../utils/getBadgeStatus";
@Shruti-Apte It should be `import getStatusCssClass from "utils/getBadgeStatus";`

2022-10-12 07:36 UTC, prasanthchaduvula approved these changes

2022-10-12 09:57 UTC, apoorv1316 approved these changes

2022-10-12 09:59 UTC, merged