Remove complex queries from client.rb and project.rb
saeloun/miru-web pull request #723
Opened 2022-10-10 06:56 UTC by mohinid

## Notion card
https://www.notion.so/saeloun/Move-Complex-Query-to-ES-bf5f01173ca045bb94c9bca6aa82e2fd

## Summary
- Remove "new_line_item_entries" method from client.rb and use generate_invoice controller to fetch line items.
- Remove "search_all_projects_by_name" method from project
- Rewrite internal_api/v1/project/search_controller.rb using searchkick to fetch searched projects(with string matching project name or client name)
- Additional Front End changes related to API calls.

## Preview
<img width="1792" alt="Screenshot 2022-10-10 at 12 24 47 PM" src="https://user-images.githubusercontent.com/5313625/194812007-93c45cbe-dbe7-4bf3-9937-92512e08436e.png">
<img width="1792" alt="Screenshot 2022-10-10 at 12 25 02 PM" src="https://user-images.githubusercontent.com/5313625/194812018-93733c58-4309-46c6-9764-11d91deb2903.png">

## Type of change
Please delete options that are not relevant.
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Via Postman, Local and Rspec

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-10 06:58 UTC, mohinid commented
@akhilgkrishnan It's giving this error while accessing the project path. Please suggest.
<img width="1792" alt="Screenshot 2022-10-10 at 12 27 46 PM" src="https://user-images.githubusercontent.com/5313625/194812375-718ae6f3-c8d1-4904-9dc5-8f105abbe845.png">

2022-10-10 07:02 UTC, mohinid commented
@prasanthchaduvula  As we have removed new_line_item_entries" method from client.rb, can you please check this file - 
Issue in edit invoice from frontend file- miru-web/app/javascript/src/components/Invoices/Edit/index.tsx

It's giving 404 after successfully loading the edit invoice page.

`// if (selectedClient.value != 0) {
    //   fetchNewLineItems(navigate, selectedClient.value, setSelectedClient, setLineItems);
    // }`

2022-10-12 17:13 UTC, mohinid commented
@apoorv1316  please review.

2022-10-14 04:57 UTC, apoorv1316 requested changes
@mohinid Project search is not working and throwing an error. Please check https://www.loom.com/share/b760c47313f94ea59a33c03929ad9259

2022-10-14 04:59 UTC, mohinid commented
> @mohinid Project search is not working and throwing an error. Please check https://www.loom.com/share/b760c47313f94ea59a33c03929ad9259

@apoorv1316  please do Project.reindex on your console before running tests. or do db reset.

2022-10-14 07:43 UTC, supriya3105 commented
@prasanthchaduvula Can you review and approve as well.

2022-10-14 08:39 UTC, shalapatil requested changes

2022-10-14 08:39 UTC, shalapatil commented on app/controllers/internal_api/v1/projects/search_controller.rb
> +      @_client_list ||= Company.find(current_company.id).clients.pluck(:id).uniq
current_company.clients.pluck(:id).uniq

2022-10-14 08:39 UTC, shalapatil commented on app/models/company.rb
> +          client_name_array.push(project.project_client_name)
why this change?

2022-10-14 08:39 UTC, shalapatil commented on app/models/project.rb
> +    }
you need to reindex project when client data changes. Add that code to client model

2022-10-14 08:42 UTC, mohinid commented on app/models/company.rb
> +          client_name_array.push(project.project_client_name)
hi this change was required as the client project list was failing. Akhil made this name change to resolve conflict.

2022-10-14 08:42 UTC, mohinid commented on app/models/project.rb
> +    }
sure

2022-10-14 08:43 UTC, mohinid commented on app/controllers/internal_api/v1/projects/search_controller.rb
> +        includes: [:client]
yes, no need of username as user is not displayed on the projects tab.

2022-10-14 08:44 UTC, mohinid commented on app/controllers/internal_api/v1/projects/search_controller.rb
> +      @_client_list ||= Company.find(current_company.id).clients.pluck(:id).uniq
added

2022-10-14 09:27 UTC, mohinid commented
@shalapatil  thanks for your comments! Updated the code accordingly. Please review it now.

2022-10-17 03:13 UTC, shalapatil requested changes

2022-10-17 03:13 UTC, shalapatil commented on app/controllers/internal_api/v1/projects/search_controller.rb
> +      total_searched_projects: searched_projects.total_count
as you are calling searched_projects twice, please either store it against var here or adding caching to the function

2022-10-17 03:13 UTC, shalapatil commented on app/models/client.rb
> +    Project.reindex
projects.reindex

2022-10-17 03:13 UTC, shalapatil commented on app/models/project.rb
> +  searchkick text_middle: [:name, :client_name]
if we are specifying text_middle here, then do we really need to speicify it while doing the actual search query?

2022-10-17 05:51 UTC, mohinid commented on app/models/project.rb
> +  searchkick text_middle: [:name, :client_name]
yes, it's not working without explicitly mentioning it in both places. can show you from the console.

2022-10-18 05:09 UTC, apoorv1316 approved these changes

2022-10-19 09:14 UTC, shalapatil approved these changes

2022-10-20 08:19 UTC, merged