Api integration recently updated invoices
saeloun/miru-web pull request #727
Opened 2022-10-12 11:34 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Integration-for-recently-updated-invoice-on-invoice-list-page-c06c5cd930ba4cd49875e6c7ce63de8c
## Summary

- API Integration for recently updated invoices. 
## Preview

<img width="1792" alt="Screenshot 2022-10-12 at 4 59 36 PM" src="https://user-images.githubusercontent.com/72149587/195331716-0684b66f-9148-424f-9d1b-da085ac07a3e.png">

<img width="1792" alt="Screenshot 2022-10-12 at 4 57 45 PM" src="https://user-images.githubusercontent.com/72149587/195331748-cc5a8d47-b4b9-47d3-a13b-26e347cf29f9.png">

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-10-12 14:18 UTC, prasanthchaduvula requested changes

2022-10-12 14:18 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
> +  <div key={index} className="p-4 mx-2 w-40 h-52 border-miru-gray-200 border-2 rounded-xl text-center">
@Shruti-Apte here instead of passing the array index and using it as key value, please use invoice.id or invoice.invoiceNumber or some unique field from invoice object

2022-10-12 14:18 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/container.tsx
> +              recentlyUpdatedInvoices.map((invoice, index) => <RecentlyUpdated invoice={invoice} index={index}/>)
@Shruti-Apte As mentioned above there is no need of having index here as we are not going to use as key value

2022-10-13 06:57 UTC, apoorv1316 approved these changes

2022-10-13 11:22 UTC, prasanthchaduvula approved these changes

2022-10-14 07:46 UTC, merged