Limit projects clients access for employees
saeloun/miru-web pull request #733
Opened 2022-10-14 03:28 UTC by shalapatil

## Notion card
https://www.notion.so/saeloun/Backend-Frontend-User-should-be-able-to-view-the-client-and-projects-where-they-have-been-added--594676f86be447dbb5ea88c405e96221

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-18 05:20 UTC, apoorv1316 approved these changes

2022-10-18 06:31 UTC, mohinid requested changes
Should only show projects for owner/admin if they are added to that project on timesheet entry.

2022-10-19 05:42 UTC, shalapatil commented
@mohinid 
@supriya3105 will comment on the expected behavior

2022-10-19 07:31 UTC, prasanthchaduvula requested changes

2022-10-22 05:31 UTC, shalapatil commented on app/controllers/internal_api/v1/time_tracking_controller.rb
> +    clients = get_clients(is_admin)
done

2022-10-22 05:33 UTC, shalapatil commented on app/controllers/internal_api/v1/time_tracking_controller.rb
> +          .includes(:projects).distinct
because we are getting clients here via projects associations which can return same clients multiple times. 
and that is not the case for getting clients for company, where there is direct association

2022-10-22 05:33 UTC, shalapatil commented on app/controllers/internal_api/v1/time_tracking_controller.rb
> +      projects = {}
this is existing format where we want client-name => client details

2022-10-28 10:14 UTC, mohinid approved these changes

2022-10-31 08:34 UTC, shalapatil commented on app/policies/time_tracking_policy.rb
> +    user_employee_role? || user_owner_role? || user_admin_role?
checking for user's company doesn't make any sense because we internally figure out the current company and that is not passed as part of the request.

2022-11-02 07:47 UTC, supriya3105 commented on app/policies/time_tracking_policy.rb
> +    user_employee_role? || user_owner_role? || user_admin_role?
@prasanthchaduvula Do you agree with Shalaka's response to your question ? If no, is this PR approved ?

2022-11-02 08:42 UTC, prasanthchaduvula approved these changes

2022-11-02 11:52 UTC, merged