Update reset email links
saeloun/miru-web pull request #735
Opened 2022-10-14 11:20 UTC by shalapatil

## Notion card
https://www.notion.so/saeloun/New-Domain-Mapping-related-fixes-required-e82990c301994a2c99d781425ff01ee6

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-21 05:43 UTC, apoorv1316 commented
@shalapatil We also need to update the website link on the invoice email footer. Can you also do that please?
<img width="1792" alt="Screenshot 2022-10-21 at 11 12 20 AM" src="https://user-images.githubusercontent.com/18750194/197121287-0b7242b7-6cf7-421c-9f70-45925e8448ed.png">

2022-10-28 06:33 UTC, apoorv1316 approved these changes

2022-10-31 05:53 UTC, JijoBose requested changes

2022-10-31 05:53 UTC, JijoBose commented on app/views/mailers/invoice_mailer/invoice.html.erb
>                style="color:#FFFFFF; vertical-align: middle; margin-bottom: 3px"
please add changes to the link text to "https://miru.so"

line: 125

2022-10-31 11:04 UTC, JijoBose approved these changes

2022-11-01 04:58 UTC, apoorv1316 commented
Weekly reminder to update timesheet to be tested on staging env.

2022-11-02 05:36 UTC, merged