Set invoice status to sent only if applicable
saeloun/miru-web pull request #743
Opened 2022-10-19 05:37 UTC by shalapatil

## Notion card
https://www.notion.so/saeloun/Invoice-status-to-be-paid-one-irrespective-whether-it-is-viewed-or-sent-for-paid-one-147f72805dd9470e93d4b38863142018

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-28 06:25 UTC, apoorv1316 commented
@shalapatil @prasanthchaduvula Why the amount paid is 0 even after paying the invoice also the amount due should be zero. Is it not fixed yet?
<img width="1792" alt="Screenshot 2022-10-28 at 11 53 58 AM" src="https://user-images.githubusercontent.com/18750194/198517786-db6fa28b-63c1-4398-ad6a-66b181cab258.png">

2022-10-31 00:51 UTC, prasanthchaduvula requested changes

2022-10-31 00:51 UTC, prasanthchaduvula commented on app/mailers/invoice_mailer.rb
> +  after_action -> { @invoice.sent! if @invoice.draft? || @invoice.viewed? || @invoice.declined? }
@shalapatil What about `overdue` one? Please confirm this with Supriya. If overdue also there then we can use `unless @invoice.paid? || @invoice.sent?`

2022-11-02 07:47 UTC, supriya3105 commented
@apoorv1316 Can you test this again and share your test results?

2022-11-02 08:24 UTC, apoorv1316 approved these changes

2022-11-02 12:14 UTC, merged