Invoice filter UI update
saeloun/miru-web pull request #745
Opened 2022-10-19 08:05 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Refactor-Filter-option-on-Invoice-list-page-as-per-new-design-fe8ad6f314884eeabca33059e2bd4bb5

## Summary

- Updated UI for filter panel
- Outsideclick functionality added
- Applied filters visible on invoice list page
- Few bug fixes
- sidepanel and button (reusable) component added

## Preview

https://www.loom.com/share/0747f23e787c40f4b809dea955f2ef09

https://www.loom.com/share/e467397751314d98b2783bbc3717c11d

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-10-19 10:25 UTC, prasanthchaduvula requested changes

2022-10-19 10:25 UTC, prasanthchaduvula commented on app/javascript/src/StyledComponents/SidePanel.tsx
> +      {restprops.children}
@Shruti-Apte Instead of passing `restprops` Please 
The component should be used in this way to make it more flexible. Above one is not allowing to customize the header and footer
Below one is just an example. We have to allow developer to add and customize the footer as well
```
<SidePanel isOpen={isOpen} onClose={onClose} >
     <SidePanel.Header>
             // This where the developer will write the header component
      </SidePanel.Header>
       <SidePanel.Body>
             // This where the developer will write the body component
         </SidePanel.Body>
         <SidePanel.Footer>
             // This where the developer will write the footer component
         </SidePanel.Footer>
   </SidePanel>
```

2022-10-19 10:25 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomCheckbox.tsx
> +      <label htmlFor={name} className={classnames("select-none",labelClassName)}>
@Shruti-Apte Why above text is changed to type object, if we are using the string value to appear in label name

2022-10-19 10:25 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
> +    if (selectedValue[0].label === "custom") {
@Shruti-Apte This whole function checking is wrong. What is the label is having upper case text or with some other text along with it. We should always check value which is standard and also here with these changes we are not handling all type of filters. Earlier one is good one to handle all sort of data types either it's an array or object.

2022-10-19 10:25 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
> +  const handleCheck = (event) => {
@Shruti-Apte Can we handle everything in `handleSelectFilter` instead of writing for clients and status separately. Try to make it generic as it will also be useful when we work on reports filter.

2022-10-19 10:25 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
>      return <div>Loading....</div>;
Here instead of writing loading try to show `miru-logo`. It is useful in production.

2022-10-19 10:25 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
> +      handleCancel={handleReset}
@Shruti-Apte Please change the sidepanel props by having header props first, then body props followed by footer props

2022-10-19 10:25 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/container.tsx
> +}) => {
@Shruti-Apte Please can you post a video explaining why this code is here and what it is for on app.

2022-10-19 10:25 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/index.tsx
> +    dateRange: [{ label: "All", value: "all", from: "", to: "" }],
@Shruti-Apte Can I know why dateRange is changed to array.

2022-10-20 06:25 UTC, Shruti-Apte commented on app/javascript/src/common/CustomCheckbox.tsx
> +      <label htmlFor={name} className={classnames("select-none",labelClassName)}>
Passing badge component as a text for status filter, that's why changed type to object

2022-10-21 06:09 UTC, apoorv1316 requested changes
@Shruti-Apte After selecting a client in the filter and applying it if we open filters again the checkbox for that client is not showing checked. Can you check that? Also, the overdue status is missing from the status filter options.
https://www.loom.com/share/7ee3fd7a268c43d3a726a8ec6ddeb83b

2022-11-08 07:34 UTC, prasanthchaduvula requested changes

2022-11-08 07:34 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomCheckbox.tsx
> +        <svg
@Shruti-Apte instead of svg is it possible to phosphor icons ?

2022-11-08 07:34 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
> +      setFilteredClientList(clientArr.sort(sortClients));
@Shruti-Apte Is individual stateful client list for this component` setFilteredClientList` required ? can't we use the original  client list itself

2022-11-08 08:20 UTC, Shruti-Apte commented on app/javascript/src/common/CustomCheckbox.tsx
> +        <svg
checkbox is customised with tick to match with the designs. It will take some extra efforts to figure out the same thing with phosphor icons.. I can work on it  if that is a priority !

2022-11-08 08:25 UTC, Shruti-Apte commented on app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
> +      setFilteredClientList(clientArr.sort(sortClients));
I added  `setFilteredClientList` because we need to set the clientlist to original state if no search query is written or clientlist is empty ! So if we use just the clientList state we need to call backend everytime when the query is empty to avoid backend calls I used different state. 
We can connect regarding this !

2022-11-08 12:44 UTC, prasanthchaduvula approved these changes

2022-11-09 14:25 UTC, apoorv1316 approved these changes

2022-11-11 05:21 UTC, merged