Reference input added to invoice generate
saeloun/miru-web pull request #748
Opened 2022-10-19 20:48 UTC by abinashpa

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-21 06:26 UTC, apoorv1316 requested changes
@abinashpa Reference is not there on the invoice email and edit invoice page. Also, as per ticket reference no. can't be longer than 12 characters but that implementation is missing(see image 3)
<img width="1792" alt="Screenshot 2022-10-21 at 11 45 01 AM" src="https://user-images.githubusercontent.com/18750194/197125530-8e470651-3c96-49b3-9867-f4c5443f280f.png">
<img width="1792" alt="Screenshot 2022-10-21 at 11 49 22 AM" src="https://user-images.githubusercontent.com/18750194/197126259-31bbd9f1-eaff-4534-8277-1ee27486f448.png">
<img width="1792" alt="Screenshot 2022-10-21 at 11 53 06 AM" src="https://user-images.githubusercontent.com/18750194/197126864-0ac7fb97-70c6-4feb-9acc-94c058369918.png">

2022-10-28 05:36 UTC, apoorv1316 commented
@abinashpa Reference is still missing on the invoice email 
<img width="1792" alt="Screenshot 2022-10-28 at 11 06 33 AM" src="https://user-images.githubusercontent.com/18750194/198510975-519fa633-98b6-48d4-9cc5-125ac5a38d03.png">

2022-10-31 00:42 UTC, prasanthchaduvula requested changes
@abinashpa Please add some test cases and If the user has added a reference number while generating the invoice then, it should be visible to the client on the invoice email and invoice PDF.  For this you have to pdf generation file and pdf view

2022-11-01 06:41 UTC, apoorv1316 commented
> @abinashpa Reference is still missing on the invoice email <img alt="Screenshot 2022-10-28 at 11 06 33 AM" width="1792" src="https://user-images.githubusercontent.com/18750194/198510975-519fa633-98b6-48d4-9cc5-125ac5a38d03.png">

@abinashpa Is this fixed?

2022-11-01 08:03 UTC, abinashpa commented
> > @abinashpa Reference is still missing on the invoice email <img alt="Screenshot 2022-10-28 at 11 06 33 AM" width="1792" src="https://user-images.githubusercontent.com/18750194/198510975-519fa633-98b6-48d4-9cc5-125ac5a38d03.png">
> 
> @abinashpa Is this fixed?

Not yet, I have an issue with elastic-search in my local.

2022-11-02 18:53 UTC, abinashpa commented
@apoorv1316  Reference added mailer.
<img width="653" alt="Screenshot 2022-11-03 at 12 22 51 AM" src="https://user-images.githubusercontent.com/33005890/199576994-c4373519-0e71-4885-b437-a7c4c2ac4ba5.png">

2022-11-03 05:17 UTC, prasanthchaduvula requested changes
@abinashpa Please add test cases for reference like allowing invoice with or without reference, max length allowed for invoice sort of conditions

2022-11-03 05:17 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/common/InvoiceDetails/index.tsx
> +          <input type="text" value={reference} onChange={(e) => setReference(e.target.value)} className="px-2 w-3/5"/>
@abinashpa Please make the indentation more readable and scalable
```
<input 
  type="text" 
  value={reference} 
  onChange={(e) => setReference(e.target.value)} 
  className="px-2 w-3/5"
  />
```

2022-11-03 08:27 UTC, apoorv1316 approved these changes

2022-11-03 09:38 UTC, abinashpa commented
@prasanthchaduvula Tests have been incorporated.

2022-11-03 09:56 UTC, prasanthchaduvula approved these changes

2022-11-04 13:38 UTC, merged