Fix: use badge components across the app
saeloun/miru-web pull request #750
Opened 2022-10-20 08:32 UTC by mayankagnihotri7

Fixes #708 
## Notion card

## Summary

- Used badge components across the app, wherever it was not being used.

## Preview

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-31 00:33 UTC, prasanthchaduvula requested changes

2022-10-31 00:33 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/Details/index.tsx
> +              <Badge text="BILLABLE"
@mayankagnihotri7 Instead of writing `text="BILLABLE"` make it into smallcase `text="billable"` and add `uppercase` to className

You can also use `getStatusCssClass`
Below is an example
```
import { Badge } from "StyledComponents";
import getStatusCssClass from "utils/getBadgeStatus";
<Badge
          text={invoice.status}
          className={`${getStatusCssClass(invoice.status)} uppercase`}
        />
```

2022-10-31 00:33 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/List/project.tsx
> +          <Badge text="Billable"
@mayankagnihotri7 Instead of writing `text="Billable"` make it into smallcase `text="billable"` and add `capitalize` to className. Also verify whether we need to be full uppercase or not.

You can also use `getStatusCssClass`
Below is example
```
import { Badge } from "StyledComponents";
import getStatusCssClass from "utils/getBadgeStatus";
<Badge
          text={invoice.status}
          className={`${getStatusCssClass(invoice.status)} uppercase`}
        />
```

2022-11-01 05:14 UTC, apoorv1316 approved these changes

2022-11-03 07:54 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2022-11-03 08:40 UTC, prasanthchaduvula approved these changes

2022-11-04 13:35 UTC, merged