[WIP] Added logic to only update non billed time entries
saeloun/miru-web pull request #755
Opened 2022-10-26 17:58 UTC by sudeeptarlekar

Signed-off-by: sudeeptarlekar <sudeeptarlekar@gmail.com>

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-10-31 00:59 UTC, prasanthchaduvula requested changes

2022-10-31 00:59 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/EntryCard.tsx
> +      { showUpdateAction(bill_status, id, setEditEntryId) }
@sudeeptarlekar Instead of defining view functions why can't we use 
```
billStatus != "billed" && 
<button onClick={() => handleDeleteEntry(id)} className="mr-10">
        <img
          src={deleteIcon}
          alt="delete"
          className="icon-hover fill-blue text-miru-han-purple-1000 hover:text-miru-han-purple-1000 w-4 h-4"
        />
      </button>
```

2022-10-31 00:59 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/EntryCard.tsx
> +      { showUpdateAction(bill_status, id, setEditEntryId) }
@sudeeptarlekar Here we also have to check The admin and owner role should still be able to edit and delete those entries.

2022-10-31 00:59 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/EntryCard.tsx
> +      { showDeleteAction(bill_status, id, handleDeleteEntry) }
@sudeeptarlekar Here also why can't we use 
```
billStatus != "billed" && 
<button onClick={() => handleDeleteEntry(id)} className="mr-10">
        <img
          src={deleteIcon}
          alt="delete"
          className="icon-hover fill-blue text-miru-han-purple-1000 hover:text-miru-han-purple-1000 w-4 h-4"
        />
      </button>
```
Here we also have to check The admin and owner role should still be able to edit and delete those entries.

2022-10-31 04:04 UTC, sudeeptarlekar commented on app/javascript/src/components/TimeTracking/EntryCard.tsx
> +      { showUpdateAction(bill_status, id, setEditEntryId) }
We can, but imo its better to keep render function as sleek as possible. Adding suggested code will hamper readability.
Thoughts?

2022-10-31 04:07 UTC, sudeeptarlekar commented on app/javascript/src/components/TimeTracking/EntryCard.tsx
> +      { showUpdateAction(bill_status, id, setEditEntryId) }
Also if time entry is non editable we have to render empty div to keep UI consistent.

2022-10-31 05:37 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/EntryCard.tsx
> +      { showUpdateAction(bill_status, id, setEditEntryId) }
@sudeeptarlekar Can't we fix the div UI as it is not needed and regarding the render function please add these checks The admin and owner role should still be able to edit and delete those entries.

2022-10-31 08:16 UTC, sudeeptarlekar commented on app/javascript/src/components/TimeTracking/EntryCard.tsx
> +      { showUpdateAction(bill_status, id, setEditEntryId) }
But from where admin/owner can change time entries of employees? And M not sure which div UI is not needed

2022-10-31 14:07 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/EntryCard.tsx
> +      { showUpdateAction(bill_status, id, setEditEntryId) }
@sudeeptarlekar The <div> in else condition of the ternary.

2022-10-31 14:08 UTC, sudeeptarlekar commented on app/javascript/src/components/TimeTracking/EntryCard.tsx
> +      { showUpdateAction(bill_status, id, setEditEntryId) }
That is needed div

2022-11-01 05:09 UTC, apoorv1316 requested changes
@sudeeptarlekar As per the card description, the admin and owner should still be able to delete and edit the billed entries but the edit and delete icons are missing for the owner and admin roles. https://www.loom.com/share/da2da1f1b4f7424d8965336918c9fbf8

2022-11-02 07:50 UTC, supriya3105 commented
@apoorv1316 Please test this and @prasanthchaduvula please review again.

2022-11-02 08:42 UTC, apoorv1316 approved these changes

2022-11-03 05:31 UTC, prasanthchaduvula requested changes

2022-11-03 05:31 UTC, prasanthchaduvula commented on app/controllers/application_controller.rb
> +  include SetCurrentDetails
@sudeeptarlekar Can we rename it to `SetCurrentUserDetails`

2022-11-03 05:31 UTC, prasanthchaduvula commented on app/controllers/application_controller.rb
> +  include SetCurrentDetails
@sudeeptarlekar Can I know what is the reason for `SetCurrentDetails` as we already have the access to `current user, current company and user roles`

2022-11-03 05:31 UTC, prasanthchaduvula commented on app/models/current.rb
> +class Current < ActiveSupport::CurrentAttributes
@sudeeptarlekar No need of this model. You can check it from the controller before updating or deleting the timesheet entry.

2022-11-03 05:31 UTC, prasanthchaduvula commented on app/policies/timesheet_entry_policy.rb
> +    (record.user_id == user.id && !record.billed?) ||
@sudeeptarlekar Here any admin or owner from the other companies can hamper our data as we are only checking the user role.

Here is an example
```
def update?
    authorize_current_user
  end

private
def authorize_current_user
    unless user.current_workspace_id == record.company_id
      @error_message_key = :different_workspace
      return false
    end

    user_owner_role? || user_admin_role?
  end
```

2022-11-03 06:04 UTC, sudeeptarlekar commented on app/controllers/application_controller.rb
> +  include SetCurrentDetails
You only have access to these objects in conteollers

2022-11-03 06:47 UTC, prasanthchaduvula commented on app/controllers/application_controller.rb
> +  include SetCurrentDetails
@sudeeptarlekar if you need `current_user` and `current_company` I don't think you need this `SetCurrentDetails`. They are already available to controllers

2022-11-03 06:48 UTC, prasanthchaduvula commented on app/controllers/application_controller.rb
> +  include SetCurrentDetails
@sudeeptarlekar Can you write what we are going to get with this `SetCurrentDetails`

2022-11-03 07:41 UTC, sudeeptarlekar commented on app/controllers/application_controller.rb
> +  include SetCurrentDetails
We need current_user in model which is not available, this module will make it available in models as well!!!

2022-11-03 07:42 UTC, sudeeptarlekar commented on app/controllers/application_controller.rb
> +  include SetCurrentDetails
Instead of writing I would like you to try it on local, and if you have better solution that this, please enlighten me

2022-11-03 07:45 UTC, sudeeptarlekar commented on app/policies/timesheet_entry_policy.rb
> +    (record.user_id == user.id && !record.billed?) ||
Are you crazy?? we are checking if user has a role for company or not

2022-11-03 07:49 UTC, sudeeptarlekar commented on app/policies/timesheet_entry_policy.rb
> +    (record.user_id == user.id && !record.billed?) ||
FYI, we have test cases for same as well
PLEASE check it [here](https://github.com/saeloun/miru-web/blob/711-user-should-not-be-able-to-update-billed-entries/spec/policies/timesheet_entry_policy_spec.rb#L98)

2022-11-03 09:53 UTC, prasanthchaduvula commented on app/controllers/application_controller.rb
> +  include SetCurrentDetails
@sudeeptarlekar https://www.loom.com/share/a7e0c79b44704f98bb39ebc364a6ea48

2022-11-07 05:06 UTC, sudeeptarlekar commented on app/controllers/application_controller.rb
> +  include SetCurrentDetails
What you are suggesting is not best practice either, but here I will ask team to take a call.

2022-11-07 09:36 UTC, prasanthchaduvula approved these changes

2022-11-07 12:41 UTC, merged