Invoice list page fix bugs
saeloun/miru-web pull request #760
Opened 2022-11-03 07:08 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Bugs-and-CR-s-for-recently-updated-invoices-section-on-invoice-list-page-9920d158186945b1842f3888be73542e

## Summary

- Fixed the mentioned bugs 

## Preview

<img width="1792" alt="Screenshot 2022-11-03 at 12 34 42 PM" src="https://user-images.githubusercontent.com/72149587/199663951-f5c947b8-559b-4b09-8ecb-f343bceb2af5.png">

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-11-03 08:47 UTC, prasanthchaduvula approved these changes

2022-11-03 08:47 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
> +import { useNavigate } from "react-router-dom";
@Shruti-Apte package import should be on top of local imports
```

import { useNavigate } from "react-router-dom";
import { currencyFormat } from "helpers";
```

2022-11-04 04:56 UTC, apoorv1316 commented
@supriya3105 @Shruti-Apte Please check how the amount of more than 1 lakh is shown. Is it a requirement?
<img width="1792" alt="Screenshot 2022-11-04 at 10 23 46 AM" src="https://user-images.githubusercontent.com/18750194/199890996-2cdafee0-9c16-4985-84d7-f180fb0b6a09.png">

2022-11-04 06:39 UTC, Shruti-Apte commented
> @supriya3105 @Shruti-Apte Please check how the amount of more than 1 lakh is shown. Is it a requirement? <img alt="Screenshot 2022-11-04 at 10 23 46 AM" width="1792" src="https://user-images.githubusercontent.com/18750194/199890996-2cdafee0-9c16-4985-84d7-f180fb0b6a09.png">

@apoorv1316 Yes !! Amount greater than 99999 should be displayed with suffix(according to currency L/M) with 2 decimal points ! This is what I discussed with sonam and supriya !  @supriya3105 can you check if this is right ?

2022-11-04 08:21 UTC, apoorv1316 approved these changes

2022-11-04 13:42 UTC, supriya3105 commented
@Shruti-Apte " On clicking an invoice from recently updated section, the admin/owner should be able to view the invoice. "  

Is this fixed in this PR ?

2022-11-07 05:09 UTC, Shruti-Apte commented
> @Shruti-Apte " On clicking an invoice from recently updated section, the admin/owner should be able to view the invoice. "
> 
> Is this fixed in this PR ?

Yes!

2022-11-07 09:32 UTC, supriya3105 commented
@Shruti-Apte I will approve this PR after the short numbers issue is fixed after discussion with Sonam. @sonamvg

2022-11-08 06:23 UTC, prasanthchaduvula requested changes
@Shruti-Apte Please add the key to map on recently updated invoices list to avoid the console warnings.

2022-11-08 06:23 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/RecentlyUpdated/index.tsx
> +import { useNavigate } from "react-router-dom";
@Shruti-Apte `useNavigate` should be imported before helpers. Always first priority of importing goes to packages then to local files.

2022-11-08 06:44 UTC, prasanthchaduvula approved these changes

2022-11-09 07:23 UTC, merged