Bulk invoice download
saeloun/miru-web pull request #769
Opened 2022-11-08 08:41 UTC by shalapatil

## Notion card
https://www.notion.so/saeloun/Backend-Bulk-Invoice-download-da485b6db7d64df1b4fefeb88740e3e0

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-11-15 14:28 UTC, swaathi requested changes

2022-11-15 14:28 UTC, swaathi commented on app/controllers/internal_api/v1/invoices_controller.rb
> +      root_url)
Move this `)` to the next line. This is very pedantic, please install a cop that can monitor this.

2022-11-15 14:28 UTC, swaathi commented on app/services/bulk_invoice_download_service.rb
> +    def get_zipped_invoices_data
This functions and all below this are doing multiple things. Each function must do only one specific action. Please split up the responsibility and refactor.

For example, constructing a ZIP name here is tedious. Better to move it off into a lib module dedicated to creating and managing zip files.

2022-11-15 14:28 UTC, swaathi commented on config/routes/internal_api.rb
> +      end
Please follow REST.

2022-11-16 09:11 UTC, shalapatil commented on config/routes/internal_api.rb
> +      end
could you please explain for how can make this more in the REST format?

2022-11-16 11:33 UTC, swaathi commented on config/routes/internal_api.rb
> +      end
RESTful routes are those that strictly use the routes provided by `resources` (index, show, create, etc.). Currently the route for this actions is something like `/invoices/bulk_download` which does not fit into the RESTful requirement. So you can either create a BulkDownloadsController under the InvoicesController or create a BulkDownloadsController separately and accept `ids`, `resource` and any other parameter into the `create` action of either controller.

2022-11-18 09:28 UTC, supriya3105 commented
@swaathi Can you review this PR again ?

2022-11-18 09:41 UTC, swaathi requested changes
Please let me know if you need help with RESTful routing.

2022-11-18 09:41 UTC, swaathi commented on lib/zip_utilities.rb
> +end
This would be better implemented using a class. Instead of passing `zip_file` everywhere, you can define it as an attribute.

This way you would be able to do things like,

```
zipfile = Zipfile.new
zipfile.name
zipfile.add_files(files)
zipfile.read
```

This is easier to understand and extend if required later.

2022-11-18 09:41 UTC, swaathi commented on lib/zip_utilities.rb
> +end
In the other file you've called,

```
zip_file = Tempfile.new(uniq_zip_file_name)
```

which is unnecessary if you move it inside this class. You can create an attribute called `file` that returns this. So outside you can call `zipfile.file`.

2022-11-22 07:47 UTC, swaathi requested changes

2022-11-22 07:47 UTC, swaathi commented on config/routes/internal_api.rb
> +      resources :bulk_download, only: [:create]
Download and search actions are usually GET since no data is being modified. You can use :index instead of :create for this.

2022-11-24 05:06 UTC, shalapatil commented
> Can you please address the refactor of the lib module?

which changes you are talking about? I have moved lib functionality to class as you had asked.

2022-11-24 05:15 UTC, swaathi commented
Please have a look at the open conversations here. Once you've addressed them click on the "Resolve Conversation". 

I gave you additional feedback for the lib comment [here](https://github.com/saeloun/miru-web/pull/769#discussion_r1026217040). Let me know if you need more info, happy to get on call!

2022-11-24 05:17 UTC, swaathi commented
NVM. I see that you've made the change. Give me some time will review. And meanwhile please mark conversations resolved if you have addressed them!

2022-11-24 19:30 UTC, vipulnsward commented
Can the branch be made green before PR review?

2022-11-27 09:29 UTC, swaathi commented
> Can the branch be made green before PR review?

Yes this branch was originally green. We were discussing over Slack about refactors that could be made (this discussion was long and wasn't easy to be done over the Github review system). We were both aware that the CI would fail during these refactors. Going forward will either mark this PR as WIP or avoid this altogether.

2022-11-27 09:31 UTC, swaathi approved these changes

2022-11-29 04:17 UTC, vipulnsward requested changes
Added some comments, will go over rest soon

2022-11-29 04:17 UTC, vipulnsward commented on app/controllers/internal_api/v1/invoices/bulk_download_controller.rb
> +    authorize :index, policy_class: Invoices::BulkDownloadPolicy
```suggestion
    authorize :index, policy_class: Invoices::BulkDownloadPolicy

```

2022-11-29 04:17 UTC, vipulnsward commented on app/controllers/internal_api/v1/invoices/bulk_download_controller.rb
> +    )
```suggestion
    )

```

2022-11-29 04:17 UTC, vipulnsward commented on app/controllers/internal_api/v1/invoices/bulk_download_controller.rb
> +      params.require(:bulk_invoices).permit(:download_id, invoice_ids: [])
When resources are nested like this- 

Invoice -> Bulk download, the param name should still be restful, params[:invoice][:bulk_dowload...

We can discuss this in refactoring call tomorrow

2022-11-29 04:17 UTC, vipulnsward commented on app/jobs/bulk_invoice_download_job.rb
> +    zip_content = BulkInvoiceDownloadService.new(invoice_ids, company_logo, root_url).process
```suggestion
    zip_content = BulkInvoiceDownloadService.new(invoice_ids, company_logo, root_url).process

```

2022-11-29 04:17 UTC, vipulnsward commented on lib/temp_pdf.rb
> +      file.write(utf_8_encoded_content)
Do we need to flush the file too?

2022-11-29 04:17 UTC, vipulnsward commented on config/routes/internal_api.rb
> +    namespace :invoices do
I see the confusion now. Instead of namespace can you try nesting under resources?

Then download controller needs a "create" method and only that should be called to create a virtual "download" 

I will explain more on call if not clear

2022-11-29 05:21 UTC, shalapatil commented on lib/temp_pdf.rb
> +      file.write(utf_8_encoded_content)
Yes, we are flushing it while cleaning up the zip.

2022-11-29 12:04 UTC, shalapatil commented on config/routes/internal_api.rb
> +    namespace :invoices do
but download is not for specific invoice, it is bulk download. If we make nested resources then it will need to pass invoice_id. Is my understanding correct?

2022-12-07 12:02 UTC, supriya3105 commented
@shalapatil Please update the branch .

2022-12-09 14:14 UTC, shalapatil commented on app/controllers/internal_api/v1/invoices/bulk_download_controller.rb
> +      params.require(:bulk_invoices).permit(:download_id, invoice_ids: [])
this is correct as I am using namespace and not resource. can you please confirm?

2022-12-09 17:27 UTC, shalapatil commented on app/channels/bulk_invoice_download_channel.rb
> +  end
This stream will be used to publish the data of created zip

2022-12-09 17:29 UTC, shalapatil commented on app/jobs/bulk_invoice_download_job.rb
> +      "bulk_invoice_download_channel_#{download_id}",
channel will be created when there is request from the frontend for specific download id.
 Frontend will send the bulk download request as well as the create channel request at the same time. 
So, when zip will be ready, that will be broadcasted to the channel with given download id.

2022-12-09 17:30 UTC, shalapatil commented on app/models/invoice.rb
> +  def pdf_content(company_logo, root_url)
this will generate the pdf contents

2022-12-09 17:31 UTC, shalapatil commented on app/models/invoice.rb
> +  def temp_pdf(company_logo, root_url)
this will generate a temporary pdf file of the invoice.

2022-12-09 17:32 UTC, shalapatil commented on app/services/bulk_invoice_download_service.rb
> +      zipper = Zipper.new(invoices_temp_pdf_data)
here we generate temporary pdf of all the asked invoice ids and call the zipper class to generate the zip.

2022-12-09 17:34 UTC, shalapatil commented on lib/temp_pdf.rb
> +class TempPdf
this is generic class to handle temporary file creation given  contents and the name

2022-12-09 17:35 UTC, shalapatil commented on lib/zipper.rb
> +class Zipper
this is generic class to handle zip related functionalities like
- adding files to zip
- reading zip file content
- cleaning up all the zip contents

2022-12-19 10:06 UTC, vipulnsward commented
Shalaka make this branch green, get it QA tested and merged. Then once its done we can do post review. 

For some PRs we get stuck, coder and reviewer both, its better psychologically to merge first if everything is working.

Then sene PRs for refactoring.

2022-12-21 08:15 UTC, supriya3105 commented
Manmeet is looking into why Github CI is failing .

2023-01-06 16:14 UTC, vipulnsward commented
Create new PR with these changes

2023-01-09 06:58 UTC, closed without merging