Admin & owner should be able to upload client logo when adding a new client
saeloun/miru-web pull request #775
Opened 2022-11-10 12:44 UTC by mayankagnihotri7

## Notion card

## Summary

[Notion card](https://www.notion.so/saeloun/Backend-Admin-owner-should-be-able-to-upload-client-logo-when-adding-a-new-client-501c5bed09464de0b9b1bbd967dc4838)

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-11-15 02:32 UTC, prasanthchaduvula requested changes

2022-11-15 02:32 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/EditClient.tsx
> +/* eslint-disable @typescript-eslint/no-var-requires */
@mayankagnihotri7 Create `ClientForm` which will have the common code of both `NewClient` & `EditClient` form.

2022-11-15 02:50 UTC, prasanthchaduvula requested changes

2022-11-15 02:50 UTC, prasanthchaduvula commented on app/controllers/internal_api/v1/purge_client_logo_controller.rb
> +
@mayankagnihotri7 Instead of handling it in separate controller try to handle it on update action itself.

2022-11-15 06:03 UTC, apoorv1316 approved these changes

2022-11-15 08:34 UTC, mayankagnihotri7 commented on app/javascript/src/components/Clients/Modals/EditClient.tsx
> +  const [clientLogo, setClientLogo] = useState("");
If I set the file type to this state then I won't be able to empty that state.

2022-11-15 13:34 UTC, mayankagnihotri7 commented on app/javascript/src/components/Clients/List/index.tsx
> +      col1: (
There are no console warnings in the browser.

2022-11-15 13:47 UTC, mayankagnihotri7 commented on app/controllers/internal_api/v1/purge_client_logo_controller.rb
> +
If I handle it inside the update action then it'd involve some extra code and the update purpose of the action would be lost. I added a separate controller here because I just need to delete the image since there is possibility of only deleting the image without sending the update request for the whole client.

2022-11-16 01:31 UTC, prasanthchaduvula commented on app/controllers/internal_api/v1/purge_client_logo_controller.rb
> +
@mayankagnihotri7 imagine when the admin or owner opened the edit client modal on the app and clicked on the delete icon of the client pic. There is an option on the edit modal at the bottom to save changes. But they realised after clicking on the delete they didn't want to save changes but we already deleted the image. Either you update the action or send one request to a separate action but the backend needs to handle the same number of requests.
Instead, when the admin or owner opens the client modal and edits the name and deleted the image we can send only one request with one click of the button which will handle everything.

2022-11-16 05:09 UTC, mayankagnihotri7 commented on app/controllers/internal_api/v1/purge_client_logo_controller.rb
> +
@prasanthchaduvula We need to implement the deletion of image just like we do for organisation settings. Let's have a call regarding this?

2022-11-16 13:52 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2022-11-16 14:05 UTC, prasanthchaduvula requested changes

2022-11-16 14:05 UTC, prasanthchaduvula commented on app/controllers/internal_api/v1/clients_controller.rb
> +    client.client_logo.destroy if client_params.key?(:client_logo) && client_params[:client_logo].blank?
@mayankagnihotri7 Handle it in a private method `client.client_logo.destroy if client_params.key?(:client_logo) && client_params[:client_logo].blank?`

Keep the actions clean

2022-11-16 14:05 UTC, prasanthchaduvula commented on app/controllers/internal_api/v1/clients_controller.rb
> +    def update_client_params
@mayankagnihotri7 make this `update_client_params` to a private method. If possible completely avoid it and handle the logic in the `client_params` method or call `update_client_params` inside client params to handle the logic part and try to call client params directly in update action if possible

2022-11-16 14:57 UTC, mayankagnihotri7 commented on app/controllers/internal_api/v1/clients_controller.rb
> +    def update_client_params
@prasanthchaduvula  `update_client_params` is already a private method. If I call the `update_client_params` in the `client_params`, it'd mean one and the same thing because then I'd need to create a new variable for storing these params in the `update_client_params` method -
```
params.require(:client).permit(
        policy(Client).permitted_attributes
      ).tap do |client_params|
        client_params[:company_id] = current_company.id
      end
```
and then use that to check the executable condition which would create a complex looking code. Even if I manage to move the condition to `client_params` it'd still create a mess over there as I would still need to do the same i.e; creating a variable to store and all.

2022-11-17 01:19 UTC, prasanthchaduvula requested changes

2022-11-17 01:19 UTC, prasanthchaduvula commented on app/javascript/src/apis/clients.ts
> +const removeLogo = (id) => axios.delete(`${path}/${id}/purge_logo`);
@mayankagnihotri7 Everything looks good. Now we are handling the deletion of the logo in the update action itself. So we can r`emoveLogo` API function, right?

2022-11-17 04:33 UTC, mayankagnihotri7 commented on app/javascript/src/apis/clients.ts
> +const removeLogo = (id) => axios.delete(`${path}/${id}/purge_logo`);
Oh alright! My bad. I totally forgot about that.

2022-11-17 04:54 UTC, mayankagnihotri7 commented
@prasanthchaduvula I've made the requested changes. Please review.

2022-11-17 08:31 UTC, prasanthchaduvula approved these changes

2022-11-21 06:22 UTC, apoorv1316 commented
@mayankagnihotri7 If we use a long co. name the initials logo CSS is breaking. Also, I can add an a.mp4 file for the logo and it doesn't throw an error. @supriya3105 Please decide on the image formats and also the size limitations.
<img width="1478" alt="Screenshot 2022-11-21 at 11 46 52 AM" src="https://user-images.githubusercontent.com/18750194/202978741-f2ea44b7-c6e5-4d95-8a99-7b35995eb2b9.png">

2022-11-23 08:59 UTC, supriya3105 commented
@apoorv1316 @mayankagnihotri7 
- The user can upload an image of type .PNG, .JPEG(JPG). If the user uploads an image of any other file type, display an error message “Incorrect file format. Please upload an image of type PNG or JPG "  in red font below the logo icon.
- The user can upload an image of size not more than 10 KB. if the user upload a file size more than 10KB display an error message below the client logo in red font color "File size exceeded the max limit of 10KB."

2022-11-29 18:09 UTC, vipulnsward commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +  return (
Can this be broken to new form component partial?

2022-11-29 18:14 UTC, vipulnsward commented on app/models/client.rb
> +  has_one_attached :client_logo
The model is already called client, so we can just call this logo, no name repetitions.

2022-11-29 18:14 UTC, vipulnsward commented on app/models/client.rb
> +      client_logo: client_logo.attached? ? Rails.application.routes.url_helpers.polymorphic_url(
Can we replace with just logo.url?

2022-11-29 18:16 UTC, vipulnsward commented on app/views/internal_api/v1/partial/_client_list.json.jbuilder
> +json.client_logo client[:client_logo] ? polymorphic_url(client[:client_logo]) : ""
Where are we fetching this from, can the url be passed here directly instead of url building logic?

2022-11-29 18:16 UTC, vipulnsward requested changes
@mayankagnihotri7 added some comments

2022-11-30 01:40 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +const deleteImage = require("../../../../../assets/images/delete.svg");
@vipulnsward Already `miruIcons` work is going on. Currently, we added the required npm package icons to `miruIcons`. @abinashpa will move the SVG files from the assets to miruIcons as the next step. 

cc: @supriya3105

2022-12-13 11:16 UTC, mayankagnihotri7 commented on app/models/client.rb
> +      client_logo: client_logo.attached? ? Rails.application.routes.url_helpers.polymorphic_url(
It does not work. I tried it. It does not generate a URL and throws a 500 error.

2022-12-14 05:29 UTC, mayankagnihotri7 commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +  return (
This already is a new and common component having the common code for the form from the new client modal and edit client modal.

2022-12-19 16:40 UTC, prasanthchaduvula approved these changes

2022-12-22 08:08 UTC, vipulnsward requested changes
@mayankagnihotri7

2022-12-22 08:08 UTC, vipulnsward commented on app/controllers/internal_api/v1/clients_controller.rb
> +      phone: client.phone, logo: client.logo.attached? ? url_for(client.logo) : ""
Make this a model concern no double dots

2022-12-22 08:08 UTC, vipulnsward commented on app/controllers/internal_api/v1/clients_controller.rb
> +        client.logo.destroy
Is this async?

2022-12-22 08:08 UTC, vipulnsward commented on app/javascript/src/components/Clients/List/index.tsx
> +      col1: (
Change method name we are not actually creating stuff here

2022-12-22 08:08 UTC, vipulnsward commented on app/javascript/src/components/Clients/List/index.tsx
> +                    createInitials(client).length > 3 ? "" : "text-lg"
Extract to helper

2022-12-22 08:08 UTC, vipulnsward commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +          "Incorrect file format. Please upload an image of type PNG or JPG. Max size (10kb)"
Lets start using i18n-js

2022-12-22 08:08 UTC, vipulnsward commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +                {clientData.name
Please extract method, no complex logic like this

2022-12-22 08:08 UTC, vipulnsward commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +  return (
Please don't mark things resolved if some other reviewer has posted comment and needs to very. cc @supriya3105

2022-12-22 08:08 UTC, vipulnsward commented on app/javascript/src/components/Clients/Modals/EditClient.tsx
> +    formData.append("client[name]", values.name);
Extract formatting to new method

2022-12-22 08:08 UTC, vipulnsward commented on app/javascript/src/components/Clients/Modals/NewClient.tsx
> +    formData.append("client[name]", values.name);
Ditto

2022-12-22 08:08 UTC, vipulnsward commented on app/javascript/src/components/Clients/Modals/NewClient.tsx
> +      document.location.reload();
No reloading here. Can it be on page update?

2022-12-22 08:08 UTC, vipulnsward commented on app/models/client.rb
>        address:,
Isn't this available as helper on logo object?

2022-12-22 08:08 UTC, vipulnsward commented on app/policies/client_policy.rb
> +    user_owner_role? || user_admin_role?
Add a test

2022-12-22 10:48 UTC, mayankagnihotri7 commented on app/models/client.rb
>        address:,
It is but it generates `Cannot generate URL for 12duvr4h5ry91.jpg using Disk service, please set ActiveStorage::Current.url_options.` error if we use `logo.url` directly.

2022-12-22 10:54 UTC, mayankagnihotri7 commented on app/policies/client_policy.rb
> +    user_owner_role? || user_admin_role?
This is redundant code. I'll remove it since it is nowhere being used.

2022-12-26 04:59 UTC, mayankagnihotri7 commented on app/javascript/src/components/Clients/Modals/NewClient.tsx
> +      document.location.reload();
we need to reload the page for the changes to take effect, be visible on the page, and let `useEffect` pull in the latest changes from the backend.

2022-12-26 05:25 UTC, mayankagnihotri7 commented on app/controllers/internal_api/v1/clients_controller.rb
> +        client.logo.destroy
No. It is being used for deleting the uploaded image from the frontend if the user removes it using the delete icon, makes some changes and then clicks on the save changes button. We are destroying client logo here in this so as to avoid sending in an additional destroy request to the backend just for deleting the logo.

2022-12-26 05:28 UTC, mayankagnihotri7 commented
@vipulnsward I've made the requested changes. Please review.

2022-12-26 15:36 UTC, mayankagnihotri7 commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +  return (
Yes, it can be broken into a new form component partial.

2023-01-06 15:26 UTC, supriya3105 commented
@mayankagnihotri7 Had messaged you today to resolve the conflicts and assign to Vipul for review.

2023-01-06 15:29 UTC, vipulnsward commented
I l review, fix and merge today, was busy

2023-01-06 15:52 UTC, mayankagnihotri7 commented
> @mayankagnihotri7 Had messaged you today to resolve the conflicts and assign to Vipul for review.

Apologies for the delay. I was working on the reviews on the PR for the client. I've resolved the conflicts.

2023-01-06 16:38 UTC, gowsik-ragunath commented on app/javascript/src/components/Clients/Modals/NewClient.tsx
> +      document.location.reload();
Seems like we are still reloading the page here

2023-01-06 16:38 UTC, gowsik-ragunath commented on app/javascript/src/components/Clients/Modals/ClientForm.tsx
> +  return (
Could you move the form component to a partial?

2023-01-06 16:38 UTC, gowsik-ragunath commented on app/models/client.rb
>        address:,
You can include `Rails.application.routes.url_helpers` in the model and use `url_for` instead.

2023-01-06 16:41 UTC, gowsik-ragunath commented
@mayankagnihotri7 Please merge the PR. CC: @vipulnsward

2023-01-06 17:10 UTC, mayankagnihotri7 commented on app/models/client.rb
>        address:,
That's what I am using.

2023-01-09 05:03 UTC, mayankagnihotri7 commented
> @mayankagnihotri7 Please merge the PR. CC: @vipulnsward

@gowsik-ragunath You might need to approve it as well as @vipulnsward for this to be merged.

2023-01-09 05:06 UTC, gowsik-ragunath approved these changes

2023-01-11 13:01 UTC, supriya3105 commented
@mayankagnihotri7 Lets close this PR and raise another one . Assign to Swaathi for review.

2023-01-11 13:17 UTC, mayankagnihotri7 commented
> @mayankagnihotri7 Lets close this PR and raise another one . Assign to Swaathi for review.

Sure.

2023-01-11 13:17 UTC, closed without merging