Invoice summury click actions
saeloun/miru-web pull request #776
Opened 2022-11-11 07:00 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/clicking-on-oustanding-overdue-and-draft-amount-section-the-respective-invoices-should-be-displaye-a95e2e433aab41859721be01aaf542d3
## Summary

- The invoices are getting filtered as per the selected invoice status on clicking invoice summary dashboard.
## Preview

https://www.loom.com/share/fca1af602e734ea9a83994906e883b27
## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-11-11 10:07 UTC, prasanthchaduvula requested changes

2022-11-11 10:07 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/InvoiceSummary/index.tsx
> +              ...filterParams,
@Shruti-Apte Extract the below type setFilterParams logic to function and used to set with OnClick action which is getting used across the page
```
setFilterParams({
              ...filterParams,
              ["status"]: [
                { value: "sent", label: "SENT" },
                { value: "viewed", label: "VIEWED" },
                { value: "overdue", label: "OVERDUE" }
              ]
            })
          }
```

2022-11-11 12:08 UTC, apoorv1316 approved these changes

2022-11-15 02:51 UTC, prasanthchaduvula approved these changes

2022-11-15 03:33 UTC, apoorv1316 commented
@supriya3105 Can merge this

2022-11-15 08:56 UTC, merged