Single invoice download
saeloun/miru-web pull request #780
Opened 2022-11-15 05:28 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Add-Download-button-to-Invoices-List-page-API-Integration-eda269189b9e437ba2feada30448e86a
## Summary

- API integration for single invoice download
## Preview

https://www.loom.com/share/0fb454d34faf4048b64855f7f1e4f2fa
## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-11-15 08:38 UTC, prasanthchaduvula requested changes

2022-11-16 11:11 UTC, Shruti-Apte commented on Gemfile.lock
> -  bcrypt (~> 3.1.7)
Fixed it!

2022-11-16 14:16 UTC, prasanthchaduvula requested changes

2022-11-16 14:16 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Invoice/index.tsx
> +      const response = await invoicesApi.downloadInvoice(invoice.id);
@Shruti-Apte can we name variable `response `to `res`

2022-11-16 14:16 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/common/MoreOptions.tsx
> +    {downloadInvoice != null && <li
@Shruti-Apte Boolean value of `null` is false. Can't we write `dowloadInvoice && `

2022-11-16 14:16 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/Table/TableRow.tsx
> +      const response = await invoicesApi.downloadInvoice(id);
@Shruti-Apte can we name the variable `response` to `res`. I think this `handleDownload` is getting used in different components. Can we re-use it? If not possible let's leave it like this.

2022-11-16 14:50 UTC, Shruti-Apte commented on app/javascript/src/components/Invoices/common/MoreOptions.tsx
> +    {downloadInvoice != null && <li
`dowloadInvoice` is a function. We are not using download functionality on edit invoice page (may use it in future), 
but that component is common that's why the condition `downloadInvoice != null &&`

2022-11-17 07:08 UTC, apoorv1316 commented
@Shruti-Apte We are getting the option to download the draft invoice on the invoice/id page.
<img width="1792" alt="Screenshot 2022-11-17 at 12 36 44 PM" src="https://user-images.githubusercontent.com/18750194/202379298-86a15e4e-f64c-4e84-bc0c-008cd8d8a542.png">

2022-11-17 08:35 UTC, prasanthchaduvula approved these changes

2022-11-18 08:32 UTC, apoorv1316 approved these changes

2022-11-18 09:28 UTC, merged