Refactor generate invoice controller view
saeloun/miru-web pull request #802
Opened 2022-11-25 05:16 UTC by shalapatil

## Notion card
https://www.notion.so/Analysis-Refactored-complex-queries-0bc12fa6584249a29ef38d8952a7c354

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-11-25 05:53 UTC, mohinid commented on app/services/generate_invoice/new_line_items_service.rb
> +        projects.each { |projectt| projects_members_rates[projectt.id] = project_members_rate(projectt) }
hi, can you fix the typo here.

2022-11-25 05:53 UTC, mohinid commented on app/services/generate_invoice/new_line_items_service.rb
> +        projects.each { |projectt| projects_members_rates[projectt.id] = project_members_rate(projectt) }
in "projectt"

2022-11-25 05:55 UTC, mohinid approved these changes
LGTM. Just test it thoroughly.

2022-11-25 06:00 UTC, mohinid commented on app/views/internal_api/v1/generate_invoice/index.json.jbuilder
>    # TODO:-Temporarily sending data for all unbilled timesheet entries even if user is not a part of the project.
Please check this TODO and fix if required.

2022-11-25 06:01 UTC, mohinid requested changes
Please check the comments. The refactoring looks ok.

2022-12-05 08:13 UTC, shalapatil commented on app/services/generate_invoice/new_line_items_service.rb
> +        params[:selected_entries].to_a | invoice_line_item_timesheet_entry_ids
no need for uniq?

2022-12-06 00:43 UTC, shalapatil commented on app/services/generate_invoice/new_line_items_service.rb
> +      end
yes, this is not being used anywhere.

2022-12-08 10:16 UTC, shalapatil commented on app/views/internal_api/v1/generate_invoice/index.json.jbuilder
>    # TODO:-Temporarily sending data for all unbilled timesheet entries even if user is not a part of the project.
what is the expected behaviour here? should we send such entries or nor?

2022-12-09 09:35 UTC, mohinid commented on app/views/internal_api/v1/generate_invoice/index.json.jbuilder
>    # TODO:-Temporarily sending data for all unbilled timesheet entries even if user is not a part of the project.
@shalapatil  @swaathi  I checked the code. This comment was added to avoid sending entries for users who are not a part of the project via generate invoice controller but later decided this should be handled in the time tracking controller.

I think it was already fixed in this pr - https://github.com/saeloun/miru-web/pull/733 
You can close this from my side, just remove the TODO comment.

2022-12-09 09:42 UTC, shalapatil commented on app/views/internal_api/v1/generate_invoice/index.json.jbuilder
>    # TODO:-Temporarily sending data for all unbilled timesheet entries even if user is not a part of the project.
Okay

2022-12-09 10:44 UTC, shalapatil commented on app/services/generate_invoice/new_line_items_service.rb
> +      end
Using presenters or not is not finalised by Vipul yet. Will make this change in the separate PR if we are good to go for presenters

2022-12-09 17:20 UTC, shalapatil commented on app/services/generate_invoice/new_line_items_service.rb
> +      end
Added presenter for the above functions

2022-12-09 17:24 UTC, shalapatil commented on app/presenters/project_members_presenter.rb
> +  def project_to_member_hourly_rate
structures data in the following format
{ project-id1: { member-id1: rate1, member-id2: rate2...}
project-id2: ......}

2022-12-12 06:11 UTC, mohinid approved these changes

2022-12-12 06:12 UTC, mohinid commented
> @mohinid please approve this. Github isn't allowing me to merge until that.

Done!

2022-12-13 08:53 UTC, shalapatil commented
@apoorv1316 Can we please test this PR?

2022-12-16 05:47 UTC, apoorv1316 commented
@shalapatil Looks good to me also!

2022-12-19 08:50 UTC, merged