Generate invoice page updates
saeloun/miru-web pull request #806
Opened 2022-11-29 08:25 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Update-Generate-Invoice-Page-as-per-the-new-design-da180f36927f4748a94cdf131f70cc48
## Summary

- New design implemented
- Search functionality added

## Preview

https://www.loom.com/share/b7e41a5507a14aac91e1cb3b0679e959

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

## How Has This Been Tested?

- The whole Generate invoice flow
- Manual entry 
- Edit invoice

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-12-02 01:52 UTC, prasanthchaduvula requested changes

2022-12-02 01:52 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/common/NewLineItemTable/Header.tsx
>      {/* Commented the search box as it is intended for next release */}
The revamped design doesn't have a search box, right? if yes, please remove the code related to it instead of commenting on it.

2022-12-02 04:32 UTC, apoorv1316 requested changes
@Shruti-Apte @supriya3105 Lots of changes need to be done here. I will post couple of videos for feedback https://www.loom.com/share/8b7aa58d8a284f5c816dee51c448f23a

2022-12-06 08:00 UTC, supriya3105 approved these changes
@apoorv1316 The functionality is as per expected. We can take further feedback based on user experience once this is deployed.

2022-12-13 05:12 UTC, apoorv1316 approved these changes

2022-12-13 09:19 UTC, prasanthchaduvula requested changes

2022-12-13 09:19 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/common/InvoiceTable/index.tsx
> +      item =>
@Shruti-Apte calculate the selected line items logic inside the single `useEffect` instead of having two **useEffects** to calculate the same.

2022-12-20 15:41 UTC, prasanthchaduvula approved these changes

2022-12-20 16:06 UTC, merged