Resolved date and day mistmatch issue
saeloun/miru-web pull request #821
Opened 2022-12-02 11:35 UTC by sudeeptarlekar

PR #818 has few bugs that when you click on any date in the month, date will not get set correctly. Reverted few changes in old PR and hard coded the days for month.

### Preview
https://user-images.githubusercontent.com/23317691/205284081-63643a6f-ffd1-4d6e-b1c1-68a19965ba5d.mp4

2022-12-02 12:32 UTC, prasanthchaduvula requested changes

2022-12-02 12:32 UTC, prasanthchaduvula commented on app/javascript/src/components/TimeTracking/MonthCalender.tsx
> +          {["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((d, index) => (
@sudeeptarlekar if `dayInfo ` is an unused prop & is not used anymore, please remove it even from the time-tracking module as well. One more thing is `dayinfo` is getting used to show the days information in the week view and in the day view as well. Instead of hardcoding the complete day names, it's better to reuse them.

2022-12-07 12:01 UTC, supriya3105 commented
@sudeeptarlekar Please resolve the failing tests on this PR so that we can merge it.

2022-12-08 16:11 UTC, sudeeptarlekar commented
@supriya3105 fixed specs

2022-12-14 02:23 UTC, sudeeptarlekar commented on app/javascript/src/components/TimeTracking/MonthCalender.tsx
> +          {["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((d, index) => (
`dayInfo` is using weekDay for calculating the days in the month, but month view imo should not change days displayed on top based on present day, so using `dayInfo` for rendering days is not ideal, In case of week's display it does make sense as we are only showing the week and it does not matter from which day week is starting in week view. If we want to show week from Monday irrespective of current day then we should hardcode days in week view as well.

2022-12-14 10:06 UTC, apoorv1316 commented
> Specs still failing? Can you please recheck?

Shalaka has opened a PR for fixing this spec. It's failing on multiple PR's

2022-12-21 08:40 UTC, prasanthchaduvula approved these changes

2022-12-21 08:41 UTC, merged