Fixed the space between radio buttons on create client
saeloun/miru-web pull request #825
Opened 2022-12-06 06:01 UTC by abinashpa

## Notion card
https://www.notion.so/saeloun/Spacing-between-radio-button-options-on-add-project-modal-c330e996057e4bd6b06c3f0b7f7497fe

## Summary
- Fixed the space between radio buttons on create project component

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

2022-12-07 12:00 UTC, supriya3105 commented
@abinashpa Why is this PR still in draft? . Also , please add the before and after screenshot to the PR.

2022-12-07 12:11 UTC, abinashpa commented
> @abinashpa Why is this PR still in draft? . Also , please add the before and after screenshot to the PR. 

I have webpacker issue. Will update it shortly.

2022-12-13 04:48 UTC, apoorv1316 commented
@abinashpa Please fix the spacing on this page too. @prasanthchaduvula Are we not using a common component for adding a new project modal?
<img width="1792" alt="Screenshot 2022-12-13 at 10 16 38 AM" src="https://user-images.githubusercontent.com/18750194/207229002-7bb796c1-fa7d-4dcf-9b63-acb9f89e2cf8.png">

2022-12-13 08:12 UTC, abinashpa commented
@apoorv1316 Fixed on the client page also.
<img width="1440" alt="Screenshot 2022-12-13 at 1 41 49 PM" src="https://user-images.githubusercontent.com/33005890/207261368-5f806d71-1ab2-42bc-a3c8-e66eb9534da8.png">

2022-12-13 08:16 UTC, prasanthchaduvula approved these changes

2022-12-13 08:18 UTC, prasanthchaduvula requested changes

2022-12-13 08:18 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Modals/AddProject.tsx
>                        <input
@abinashpa use common `CustomRadioButton` instead of input radio.

2022-12-13 08:18 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/Modals/AddEditProject.tsx
>                          <input
@abinashpa use common CustomRadioButton instead of input radio.

2022-12-14 05:45 UTC, apoorv1316 approved these changes

2022-12-14 05:47 UTC, apoorv1316 commented
@abinashpa Resolve conflicts

2022-12-19 16:42 UTC, prasanthchaduvula approved these changes

2022-12-21 08:44 UTC, merged