Mobile responsive navigation menu
saeloun/miru-web pull request #827
Opened 2022-12-06 08:23 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Mobile-Responsive-Navigation-Menu-54d119c402ad4d57a01b918b3530a18e
## Summary

 - Designed Mobile responsive navigation menu.
 - Created components for each section in navigation menu.
 - More options section's design is approved by sonam, Akash needs to create design for that section.
## Preview

<img width="351" alt="Screenshot 2022-12-06 at 1 46 01 PM" src="https://user-images.githubusercontent.com/72149587/205857109-bee2ced7-119b-4377-acf4-3764fda36e6c.png">

<img width="359" alt="Screenshot 2022-12-06 at 1 52 16 PM" src="https://user-images.githubusercontent.com/72149587/205858444-6702641f-d9b4-4303-8a70-747562c042f7.png">

## Type of change

- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

2022-12-07 05:12 UTC, apoorv1316 approved these changes

2022-12-07 11:59 UTC, supriya3105 commented
@prasanthchaduvula Please review this PR.

2022-12-07 12:27 UTC, prasanthchaduvula requested changes

2022-12-07 12:27 UTC, prasanthchaduvula commented on app/javascript/src/components/Navbar/Header.tsx
> +const miruLogo = require("../../../../assets/images/PurpleMiruLogoWithText.svg"); //eslint-disable-line
Any reason why eslint is disabled for this svg import

2022-12-07 12:27 UTC, prasanthchaduvula commented on app/javascript/src/components/Navbar/Mobile/Header.tsx
> +const miruLogo = require("../../../../../assets/images/logo.jpg"); //eslint-disable-line
eslint is disabled for this svg import as well. No need to disble this from checks

2022-12-07 12:27 UTC, prasanthchaduvula commented on app/javascript/src/components/Navbar/utils.tsx
> +    <li className="items-center hover:bg-miru-gray-100" key={index}>
Here, the complete `<li>` block is common for both employee and admin options. Please extract the `<li> `to render function and use it inside the employee and admin options

2022-12-07 12:27 UTC, prasanthchaduvula commented on app/javascript/src/components/Navbar/Mobile/Navigation.tsx
> +              <li
Here, the complete `<li>` block is common for both employee and admin options. Please extract the `<li> `to render function and use it inside the employee and admin options

2022-12-07 12:27 UTC, prasanthchaduvula commented on app/javascript/src/components/Navbar/Mobile/MoreOptions.tsx
> +                <li
Here, the complete `<li>` block is common for both employee and admin options. Please extract the `<li> `to render function and use it inside the employee and admin options

2022-12-07 12:27 UTC, prasanthchaduvula commented on app/javascript/src/components/Navbar/Mobile/MoreOptions.tsx
> +        {isAdminUser
I think the complete `{isAdminUser}` is common for both `MoreOptions` and `Navigation` components. Extract the logic to another component and reuse it in these both components

2022-12-13 08:48 UTC, prasanthchaduvula requested changes

2022-12-13 08:48 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/MoreOptions.tsx
> +import { Link } from "react-router-dom";
@Shruti-Apte Import packages on top
```
import { Link } from "react-router-dom";
```

2022-12-13 08:48 UTC, prasanthchaduvula commented on app/javascript/src/components/App.tsx
> +  window.addEventListener("resize", () =>
@Shruti-Apte extract the whole view logic to the `DisplayView ` component and make the `App` component clean.

2022-12-13 08:48 UTC, prasanthchaduvula commented on app/javascript/src/components/App.tsx
> +        {getView()}
@Shruti-Apte Call `<DisplayView /> ` here

2022-12-16 02:26 UTC, prasanthchaduvula approved these changes

2022-12-20 05:22 UTC, Shruti-Apte commented
@apoorv1316 Can you fix the CI tests!

2022-12-20 09:15 UTC, merged