Fixes radio button label not visible in add team member
saeloun/miru-web pull request #844
Opened 2022-12-12 20:35 UTC by abinashpa

## Notion card
https://www.notion.so/saeloun/Radio-buttons-are-not-visible-on-add-edit-team-member-modal-4737d81da4af46508ca0f9be3e6739ed

## Summary
- Made the radio button label visible.
- Fix the indentation between the radio button and the label.

## Preview
Before:
<img width="451" alt="Screenshot 2022-12-13 at 2 04 31 AM" src="https://user-images.githubusercontent.com/33005890/207148785-7b5ae39c-d160-4fbc-9437-a41e24d08bdc.png">

After:
<img width="451" alt="Screenshot 2022-12-13 at 2 04 49 AM" src="https://user-images.githubusercontent.com/33005890/207148828-6ac1bf8f-e6e0-46ef-8193-4177a1584d21.png">

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2022-12-13 04:53 UTC, apoorv1316 approved these changes

2022-12-13 08:10 UTC, prasanthchaduvula requested changes

2022-12-13 08:10 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/modals/AddEditMember.tsx
> +                            <div className="flex items-center justify-between">
Instead of rewriting the same logic for each radio button please map over them and use the `CustomRadioButton` common component.

2022-12-20 08:19 UTC, abinashpa commented on app/javascript/src/components/Team/modals/AddEditMember.tsx
> +                            <div className="flex items-center justify-between">
Every radio button has a different spacing so making it a common one is not feasible.

2022-12-20 08:21 UTC, abinashpa commented
@apoorv1316  Cypress tests are failing.

2022-12-21 08:49 UTC, supriya3105 commented
@abinashpa Please resolve conflicts on this PR.

2022-12-22 07:55 UTC, prasanthchaduvula approved these changes

2022-12-22 08:13 UTC, merged