Projects cypress specs
saeloun/miru-web pull request #850
Opened 2022-12-14 08:21 UTC by apoorv1316

## Notion card

## Summary
Cypress specs for projects

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2022-12-16 08:00 UTC, mohinid reviewed
Hi you have written test only for admin, is it intentional or you will be adding for other roles as well?

2022-12-16 08:11 UTC, apoorv1316 commented
> Hi you have written test only for admin, is it intentional or you will be adding for other roles as well?

Ahh forgot to commit those. Will ping you when it's ready for review.

2022-12-20 07:18 UTC, apoorv1316 commented
@mohinid Please review it now.

2022-12-22 11:37 UTC, mohinid reviewed
@apoorv1316  please add description to the pr

2022-12-22 11:38 UTC, mohinid requested changes
Please add tests and description in the pr.

2022-12-26 06:04 UTC, apoorv1316 commented
@mohinid Updated the description and added tests to it.

2022-12-28 13:52 UTC, mohinid requested changes

2022-12-28 13:52 UTC, mohinid commented on cypress/e2e/projects/admin.spec.js
> +    cy.get('select').select(1);
why are we using select 1? cant use the exact locator?

2023-01-12 10:00 UTC, mohinid approved these changes

2023-01-12 10:35 UTC, merged