Mark as paid with in invoice
saeloun/miru-web pull request #854
Opened 2022-12-15 08:12 UTC by abinashpa

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2022-12-20 09:34 UTC, prasanthchaduvula requested changes

2022-12-20 09:34 UTC, prasanthchaduvula commented on app/controllers/internal_api/v1/invoices_controller.rb
> +      params.require(:invoice).permit(InvoicePolicy.permitted_attributes)
Revert this change as the whole app follows this standard way `params.require(:invoice).permit(policy(Invoice).permitted_attributes)`

2022-12-22 07:47 UTC, prasanthchaduvula approved these changes

2022-12-26 04:29 UTC, apoorv1316 requested changes
@abinashpa Please check loom video https://www.loom.com/share/52de773e56d64da1ab26392f6ee7e537

2022-12-26 15:58 UTC, abinashpa commented
@apoorv1316 The 3 dot option is not available on new invoice.
<img width="1440" alt="Screenshot 2022-12-26 at 9 28 16 PM" src="https://user-images.githubusercontent.com/33005890/209565722-d4ba77c3-43f2-43c7-ad4b-6475bea0489d.png">

2023-01-02 07:02 UTC, apoorv1316 commented
@abinashpa As per the ticket "mark invoice as paid" option should be there for the overdue invoice which is currently missing. Can you please check?
<img width="1792" alt="Screenshot 2023-01-02 at 12 31 22 PM" src="https://user-images.githubusercontent.com/18750194/210202306-b6fcd284-4016-449c-8f66-0537028cdc67.png">

2023-01-02 07:15 UTC, abinashpa commented
@apoorv1316 fixed. 
<img width="1440" alt="Screenshot 2023-01-02 at 12 45 20 PM" src="https://user-images.githubusercontent.com/33005890/210203075-79f97b9e-e052-4ac0-8534-2f5aaba18f80.png">

2023-01-02 07:58 UTC, apoorv1316 approved these changes

2023-01-02 08:41 UTC, merged