Sent Invoice button
saeloun/miru-web pull request #858
Opened 2022-12-16 06:53 UTC by harshaanNihal

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2022-12-19 16:35 UTC, prasanthchaduvula requested changes

2022-12-19 16:35 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/index.tsx
> +      return;
Please use `Logger.error` to catch the error and change` //pooling` to `//polling`

2022-12-20 04:15 UTC, apoorv1316 approved these changes

2022-12-20 08:04 UTC, apoorv1316 commented
test

2022-12-20 08:25 UTC, prasanthchaduvula approved these changes

2022-12-20 09:41 UTC, merged