Accounts Aging reports UI and API integration
saeloun/miru-web pull request #867
Opened 2022-12-20 08:26 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Create-the-frontend-designs-for-Accounts-Aging-report-09c39ab08a7244edbb5503aad9a30c10
## Summary

- Accounts aging report section added.
- Table with alphabetical order, Filter with search, table row with total and summary dashboard  added.
## Preview

<img width="1792" alt="Screenshot 2022-12-20 at 1 56 09 PM" src="https://user-images.githubusercontent.com/72149587/208619072-360aafaa-a0c5-477b-a88d-15025942d403.png">

<img width="1792" alt="Screenshot 2022-12-20 at 1 55 04 PM" src="https://user-images.githubusercontent.com/72149587/208618827-c81d88ce-deb7-491b-a0ce-2d264cce3492.png">

<img width="1792" alt="Screenshot 2022-12-20 at 1 55 16 PM" src="https://user-images.githubusercontent.com/72149587/208618882-e374eb5f-9aba-4cef-bc15-931c2138cb2d.png">

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer

2022-12-26 04:16 UTC, apoorv1316 requested changes
@Shruti-Apte Please see the loom video https://www.loom.com/share/cdaa331d7cc443bc958ad5e3c8da1901?focus_title=1&muted=1&from_recorder=1

2022-12-27 15:48 UTC, prasanthchaduvula requested changes

2022-12-27 15:48 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/accountsAging/Filters/index.tsx
> +  const handleReset = () => {}; //eslint-disable-line
@Shruti-Apte Please remove `handleReset` if it is not needed

2022-12-27 15:48 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/accountsAging/Filters/index.tsx
> +const FilterSideBar = ({
@Shruti-Apte Component name and folder name should be the same if the file is `index.tsx` for better-naming conventions
eg: 
`app/javascript/src/components/Reports/accountsAging/Filters/index.tsx`

then component name `Filters`

2022-12-27 15:48 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/accountsAging/index.tsx
> +import React, { useState, useEffect } from "react";
@Shruti-Apte Here folder name should be `AccountsAging`

2022-12-27 15:48 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/api/accountsAging.ts
> +    setClientList(res.data.report.clients);
@Shruti-Apte Destructure the response, assign it to variables and use them.
Remove the unnecessary commented code.

2022-12-27 15:48 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/reportList/index.tsx
>  const ReportsList = () => (
@Shruti-Apte Here the folder name should be List

2022-12-27 15:48 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/outstandingInvoices/index.tsx
>  import TimeEntryReportContext from "../context/TimeEntryReportContext";
@Shruti-Apte Here the folder name and component should be same.

2022-12-27 15:48 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/revenueByClient/index.tsx
>  import TimeEntryReportContext from "../context/TimeEntryReportContext";
@Shruti-Apte Here folder name and component should be same for `RevenueByClientReport`

2022-12-27 15:48 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/timeEntry/index.tsx
> +import AccountsAgingReportContext from "../context/AccountsAgingReportContext";
@Shruti-Apte Here Folder name and component should be the same `TimeEntryReports` or make it `TimeEntry` for the folder name and keep component`TimeEntryReports`

2023-01-02 07:17 UTC, apoorv1316 commented
@Shruti-Apte App is breaking. Please fix
<img width="1792" alt="Screenshot 2023-01-02 at 12 46 36 PM" src="https://user-images.githubusercontent.com/18750194/210203149-527e0aca-6a3b-41f6-a18b-1298b88eab63.png">

2023-01-02 16:17 UTC, prasanthchaduvula requested changes

2023-01-03 07:25 UTC, supriya3105 commented
@Shruti-Apte Lets close the review comments from Apoorv and Prasanth on this PR today.

2023-01-03 07:59 UTC, Shruti-Apte commented on app/javascript/src/StyledComponents/SummaryDashboard.tsx
> +const formattedAmount = (amount, baseCurrency) =>
can we create a different refactor ticket for this ?? currencyFormat function is used in so many files @prasanthchaduvula @supriya3105

2023-01-04 07:07 UTC, supriya3105 commented on app/javascript/src/StyledComponents/SummaryDashboard.tsx
> +const formattedAmount = (amount, baseCurrency) =>
@prasanthchaduvula I have created a new ticket for this. Please approve this PR is all other review comments have been addressed.

2023-01-04 07:42 UTC, prasanthchaduvula approved these changes

2023-01-05 09:32 UTC, apoorv1316 requested changes
@Shruti-Apte Something is wrong with the aging reports. Not able to see clients and their data.
<img width="1792" alt="Screenshot 2023-01-05 at 3 02 16 PM" src="https://user-images.githubusercontent.com/18750194/210747597-b8d85d52-44db-4705-b6f3-2de4d004349d.png">

2023-01-05 09:37 UTC, Shruti-Apte commented
> @Shruti-Apte Something is wrong with the aging reports. Not able to see clients and their data. <img alt="Screenshot 2023-01-05 at 3 02 16 PM" width="1792" src="https://user-images.githubusercontent.com/18750194/210747597-b8d85d52-44db-4705-b6f3-2de4d004349d.png">

Fixed!

2023-01-05 09:43 UTC, apoorv1316 approved these changes

2023-01-05 09:48 UTC, merged