Retained applied filters on invoice even on refresh or page loads
saeloun/miru-web pull request #873
Opened 2022-12-23 03:30 UTC by prasanthchaduvula

## Notion card
https://www.notion.so/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=0a212842d8e34ed0891d978ee1bc93f8&pm=s
## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2022-12-28 09:25 UTC, harshaanNihal requested changes
Added a comment 

Rest look good 💯

2022-12-28 09:25 UTC, harshaanNihal commented on app/javascript/src/components/Invoices/List/FilterSideBar/index.tsx
> +    window.localStorage.removeItem("filters");
Move the localstorage key (i.e -> "filters") to a Constant variable.

2023-01-02 07:24 UTC, apoorv1316 approved these changes

2023-01-02 15:48 UTC, harshaanNihal approved these changes

2023-01-02 17:09 UTC, merged