New invoice from project details page
saeloun/miru-web pull request #874
Opened 2022-12-23 06:05 UTC by abinashpa

## Notion card

## Summary

## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2022-12-26 05:58 UTC, apoorv1316 approved these changes

2022-12-27 14:41 UTC, prasanthchaduvula requested changes

2022-12-27 14:41 UTC, prasanthchaduvula commented on app/javascript/src/components/Projects/Details/index.tsx
> +    navigate(`/invoices/generate/${project?.client?.id}`);
@abinashpa use client_id as query params on generate invoice instead of making the generate invoice route to `/invoices/generate/id`

2023-01-02 15:40 UTC, prasanthchaduvula requested changes

2023-01-02 15:40 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/Generate/index.tsx
> +  const clientId = new URLSearchParams(window.location.search).get("clientId");
Use `useSearchParams` To find the client id from query params.

2023-01-04 07:32 UTC, supriya3105 commented
@abinashpa Please update the branch.

2023-01-13 07:28 UTC, prasanthchaduvula approved these changes

2023-01-13 08:34 UTC, merged