loading message and invoice tab changed
saeloun/miru-web pull request #899
Opened 2023-01-02 12:57 UTC by Shruti-Apte

## Notion card
NA
## Summary

- Added loading message 
- Shifted invoice tab to first place
## Preview

<img width="285" alt="Screenshot 2023-01-02 at 6 21 01 PM" src="https://user-images.githubusercontent.com/72149587/210234169-e0d36525-a044-42ae-97db-9c44fb622955.png">

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Tested working for loading message
- Invoice tab is shifted to first place
### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2023-01-02 15:33 UTC, prasanthchaduvula requested changes

2023-01-02 15:33 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/container.tsx
> +  const [loading, setLoading] = useState<boolean>(false);
Use `true` as default value for loading in the useState

2023-01-02 15:33 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/container.tsx
> +  useEffect(() => setLoading(true), []);
This not required any more after making this change 
`Use true as default value for loading in the useState`

2023-01-04 07:29 UTC, supriya3105 commented
@apoorv1316 @prasanthchaduvula Please test and review this PR today. @Shruti-Apte Please update the branch.

2023-01-04 07:34 UTC, prasanthchaduvula requested changes

2023-01-04 07:34 UTC, prasanthchaduvula commented on app/javascript/src/components/Invoices/List/container.tsx
> +    if (invoices.length > 0) setLoading(false);
@Shruti-Apte What if invoice length is 0 then loading will be always true right? Instead its better to show no invoices found

2023-01-04 07:43 UTC, apoorv1316 commented
> @apoorv1316 @prasanthchaduvula Please test and review this PR today. @Shruti-Apte Please update the branch.

@supriya3105 Rpsec failing and page breaking because of a file name change. @Shruti-Apte is working on it. Will approve once it is fixed.

2023-01-05 08:15 UTC, prasanthchaduvula approved these changes

2023-01-05 09:36 UTC, apoorv1316 requested changes
@Shruti-Apte Please see loom https://www.loom.com/share/1d9b1ad557d844699223f9df85d9a064

2023-01-05 10:36 UTC, apoorv1316 approved these changes

2023-01-05 10:49 UTC, merged