invoice page UI changes and repost page icon, UI changes
saeloun/miru-web pull request #905
Opened 2023-01-03 14:07 UTC by Ankita012

## Notion card
https://www.notion.so/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=c87dbabdf1374c5a9c3b7372f3af5a38&pm=s
https://www.notion.so/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=d964a31b05f74812905554d6ef6316b3&pm=s

## Summary

- UI changes in invoice list page
- Fix Icons for Reports

## Preview
<img width="1792" alt="Screenshot 2023-01-03 at 7 19 05 PM" src="https://user-images.githubusercontent.com/22776061/210372838-5edc1f20-1534-4160-a5dc-6f86499fb7e3.png">
<img width="1792" alt="Screenshot 2023-01-03 at 7 21 29 PM" src="https://user-images.githubusercontent.com/22776061/210372845-1db89f1d-7412-4711-a53d-6709b9bb5171.png">
<img width="1787" alt="Screenshot 2023-01-03 at 7 21 39 PM" src="https://user-images.githubusercontent.com/22776061/210372848-9a57dcce-4d33-4741-a4b9-93bb6c163a30.png">

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Check for UI changes in the invoice list page.
- Check for icons and UI on report page

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2023-01-04 06:23 UTC, apoorv1316 requested changes
@Ankita012 Please change the font size to 40 px on the amount. It is 36px currently. Also, there has to be a hover effect on the reports icon. You can see the effect from here https://www.figma.com/proto/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?page-id=6785%3A69221&node-id=9248%3A102629&viewport=63%2C-7180%2C0.4&scaling=min-zoom
<img width="1334" alt="Screenshot 2023-01-04 at 11 51 49 AM" src="https://user-images.githubusercontent.com/18750194/210495934-c5f2ef2e-0ef5-4272-9c55-a446cf05ad61.png">

2023-01-04 07:45 UTC, prasanthchaduvula requested changes

2023-01-04 07:45 UTC, prasanthchaduvula commented on app/javascript/images/Revenue.svg
> +<svg width="77" height="71" viewBox="0 0 77 71" fill="none" xmlns="http://www.w3.org/2000/svg">
@Ankita012 Please move these svg icons used in this PR to miruicons

2023-01-04 14:39 UTC, prasanthchaduvula requested changes

2023-01-04 14:39 UTC, prasanthchaduvula commented on app/javascript/src/components/Reports/reportList/index.tsx
> +const calendarHover = require("../../../miruIcons/CalendarHover.svg");
@Ankita012 Please change the imports to this below format ```
import {
 CalendarHoverIcon,
  HoursIcon,
  HoursHoverIcon,
  OverdueOutstandingIcon,
  OverdueOutstandingHoverIcon.
  RevenueIcon,
  RevenueHoverIcon

} from "miruIcons";
```

2023-01-05 07:51 UTC, supriya3105 commented
@Ankita012 Please update the branch.

2023-01-05 09:39 UTC, prasanthchaduvula requested changes

2023-01-05 09:39 UTC, prasanthchaduvula commented on app/javascript/src/miruIcons/index.ts
> +const revenueHoverIcon = require(".../../../assets/images/RevenueHover.svg");
@Ankita012 Create a folder inside miruIcons to store the SVG files and import them inside miruIcons and use them. Delete the SVG files that got added to assets in this PR.

2023-01-05 10:33 UTC, Ankita012 commented on app/javascript/src/miruIcons/index.ts
> +const revenueHoverIcon = require(".../../../assets/images/RevenueHover.svg");
Done

2023-01-06 13:35 UTC, merged