Bulk download invoices
saeloun/miru-web pull request #910
Opened 2023-01-06 08:27 UTC by Shruti-Apte

## Notion card
https://www.notion.so/saeloun/Frontend-Bulk-Invoice-download-dc97201519554ec8a9e4698a7b3cb865
## Summary

- Bulk download functionality UI and Integration.
## Preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- Checked bulk download functionality.
- Need to test all other workflows like single download.
- -Backend Pr is not yet merged for this nor reviewd.
### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2023-01-09 07:46 UTC, apoorv1316 requested changes
@Shruti-Apte Couple of fixes we need to make. Please seem the loom video https://www.loom.com/share/171f20c67b9d411e9813f618d1e905bf cc @supriya3105

2023-01-11 09:21 UTC, shalapatil commented on app/services/bulk_invoice_download_service.rb
> +      file_uploader = FileUploader.new(zipper.file, "Invoices_" + Time.now.to_i.to_s + ".zip")
done

2023-01-11 09:21 UTC, shalapatil commented on lib/file_uploader.rb
> +class FileUploader
done

2023-01-12 05:48 UTC, apoorv1316 approved these changes

2023-01-12 09:01 UTC, prasanthchaduvula approved these changes

2023-01-12 09:40 UTC, shalapatil commented on spec/lib/file_uploader_spec.rb
> +    it "check if DeleteActiveStorageBlobJob job is queued" do
will do this in separate PR

2023-01-12 10:29 UTC, merged