updated mapped import to absolute path in all files
saeloun/miru-web pull request #938
Opened 2023-01-13 03:28 UTC by onkar-saeloun

## Notion card

## Summary

Added absolute import to mapper files

## Preview

No preview

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
Tested on local machine

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2023-01-13 08:19 UTC, prasanthchaduvula requested changes

2023-01-13 08:19 UTC, prasanthchaduvula commented on app/javascript/src/components/Clients/Details/index.tsx
> +import { unmapClientDetails } from "mapper/client.mapper";
Please add index.ts to the mapper and do the import & export from there. Please refer `StyledComponents` or `helpers`

2023-01-16 06:00 UTC, onkar-saeloun commented on app/javascript/src/components/Clients/Details/index.tsx
> +import { unmapClientDetails } from "mapper/client.mapper";
Done

2023-01-17 05:43 UTC, prasanthchaduvula approved these changes

2023-01-17 05:43 UTC, merged