Frontend -  Add PTO/Holidays [Admin]
saeloun/miru-web pull request #944
Opened 2023-01-16 08:54 UTC by onkar-saeloun

## Notion card
https://www.notion.so/saeloun/Frontend-Automated-PTO-Calculation-Admin-users-should-be-add-company-PTO-s-and-other-users-shou-92251ebc60854ae9b88f3a5ccb264485

## Summary
Added frontend- Holiday/PTO for admin.
Admin can add/delete the PTO and can view it on calendar.

## Preview

https://www.loom.com/share/5a810e9433e6409aa9e2864d875672d6

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
Tested Manually on Local Machine.

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2023-01-16 08:59 UTC, onkar-saeloun reviewed
We can't see this feature on UI until we do backend integration. The tab is disabled for now.

2023-01-16 08:59 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/LeavesAndHolidays/Details.tsx
> +  const optionalRepetitionType = "per_year";
This is static data and will be removed after integration so kindly ignore this

2023-01-16 08:59 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/SubNav.tsx
> +        {/* <NavLink
Disabled Nav till backend integration

2023-01-16 08:59 UTC, onkar-saeloun commented on app/javascript/stylesheets/pto.scss
> +// .react-calendar button:enabled:hover {
kept this class for future usecase if needed we can uncomment it and apply

2023-01-18 04:37 UTC, prasanthchaduvula requested changes

2023-01-18 04:37 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/LeavesAndHolidays/HolidaysModal.tsx
> +            {quarter_two.map(
Please loop on all the quarters in one shot instead of repeating the same logic for all quarter's DRY rule.
```
<div className="flex flex-row justify-around pt-4">
            {quarter_three.map(
              (
                month,
                  key //eslint-disable-line
              ) => (
                <CalendarComponent
                  id={month.id}
                  key={key}
                  name={month.name}
                  tileContent={tileContent}
                  year="2023"
                />
              )
            )}
          </div>
```

2023-01-18 04:37 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/Organization/LeavesAndHolidays/index.tsx
> +  const handleTotalChange = (e, index) => {
Here `handleRepetitionTypeChange`, `handleCountTypeChange`, `handleTotalChange`, `handleLeaveTypeChange` and `handleCarryForwardCountChange` are almost the same. Extract the logic to common` handleCountChange` which will handle all the above-mentioned logic with help of some extra props to serve it.

2023-01-18 05:14 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/LeavesAndHolidays/HolidaysModal.tsx
> +            {quarter_two.map(
Oh yes done it.

2023-01-18 05:14 UTC, onkar-saeloun commented on app/javascript/src/components/Profile/Organization/LeavesAndHolidays/index.tsx
> +  const handleTotalChange = (e, index) => {
Yup done

2023-01-18 07:43 UTC, prasanthchaduvula approved these changes

2023-01-20 05:37 UTC, apoorv1316 approved these changes

2023-01-20 05:55 UTC, merged