Employee to view PTO - Frontend
saeloun/miru-web pull request #955
Opened 2023-01-18 04:20 UTC by onkar-saeloun

## Notion card
https://www.notion.so/saeloun/Frontend-Each-Miru-user-should-be-able-to-view-their-PTO-balance-at-any-point-of-time-075ebfa98b5b4ca99742055f4d756c53

## Summary

This feature adds ability for employee to view their PTO balance

## Preview

https://www.loom.com/share/a6b6b380c55144449613132a05cf7d14

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested on local machine

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2023-01-18 04:21 UTC, onkar-saeloun commented
Keeping the PR in draft as this PR has dependency over https://github.com/saeloun/miru-web/pull/944

2023-01-20 05:09 UTC, supriya3105 commented
@onkar-saeloun Why is this PR still in draft ?

2023-01-20 05:10 UTC, supriya3105 commented
@onkar-saeloun Also since the backend is not ready for this, lets merge this onto a different branch instead of develop. The backend engineer can pull the changes from this branch

2023-01-20 05:20 UTC, onkar-saeloun commented
> @onkar-saeloun Why is this PR still in draft ?

@supriya3105 will raise it only once the Admin PTO PR got merged.

2023-01-20 05:23 UTC, onkar-saeloun commented
> @onkar-saeloun Also since the backend is not ready for this, lets merge this onto a different branch instead of develop. The backend engineer can pull the changes from this branch

@supriya3105 I think we can merge this to develop after admin PR gets merged. I won't cause any issues as we will not show anything on frontend till we merge backend.
Merging in other PR may cause lot of conflicts while we raise that PR.

2023-01-20 15:17 UTC, prasanthchaduvula requested changes

2023-01-20 15:17 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/LeaveBalance/index.tsx
> +      (result = holiday.find(o => o.date === dayjs(date).format("DD-MM-YYYY")))
Please move this else-if logic to switch case and move the conditions inside it to functions where we can call them

2023-01-25 07:41 UTC, apoorv1316 approved these changes

2023-01-25 08:27 UTC, supriya3105 commented
@onkar-saeloun Once you resolve the comments can you reply back with a done and request review again. The reviewer will then mark the conversation as resolved.

2023-01-25 08:59 UTC, onkar-saeloun commented
> @onkar-saeloun Once you resolve the comments can you reply back with a done and request review again. The reviewer will then mark the conversation as resolved.

Yes will do it.

2023-02-01 07:00 UTC, prasanthchaduvula requested changes

2023-02-06 05:27 UTC, supriya3105 commented
@onkar-saeloun Please reply to the review comment as done so that the reviewer knows about it. Also please update the branch.

2023-02-07 04:46 UTC, onkar-saeloun commented
> @onkar-saeloun Please reply to the review comment as done so that the reviewer knows about it. Also please update the branch.

Yes @supriya3105, I have replied to the comments and asked @prasanthchaduvula to review it.

2023-02-07 07:21 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/LeaveBalance/index.tsx
> +  const tileContent = ({ date }) => {
@onkar-saeloun Please make the above requested changes

2023-02-08 07:39 UTC, prasanthchaduvula approved these changes

2023-02-08 07:43 UTC, merged