Time tracking specs cypress
saeloun/miru-web pull request #968
Opened 2023-01-24 05:29 UTC by apoorv1316

## Summary
Cypress specs for time tracking

2023-01-30 07:39 UTC, supriya3105 commented
@apoorv1316 Can you add the list of time tracking cypress specs that are part of this PR.

2023-02-03 16:10 UTC, mohinid commented on cypress/e2e/timetracking/admin.spec.js
> +  it("should select a date and add entry", function () {
hey, we are writing the same steps for both admin and employee . Can you please check if there is a way it can be refactored?

2023-02-03 16:10 UTC, mohinid requested changes
Let's discuss on monday for refactoring.

2023-02-06 05:28 UTC, supriya3105 commented
@apoorv1316 Closing this as per Vipul's feedback to move the cypress specs in another repository. 
 https://saeloun.slack.com/archives/C03U02LUKSP/p1675611122594079

2023-02-06 05:28 UTC, closed without merging