Api integration personal details
saeloun/miru-web pull request #994
Opened 2023-02-03 14:30 UTC by onkar-saeloun

## Notion card
https://www.notion.so/saeloun/Integration-of-Personal-details-API-1fbe0517c2094a7b9ef0a3d03ae71659

## Summary

Added API integration of Personal Details Page under teams section

## Preview

https://www.loom.com/share/8964b2f1fb0c43c1beed9ffab6d6057f

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested manually in my local machine

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

2023-02-03 14:41 UTC, onkar-saeloun commented
PR should not be merged before updating backend for phone number field

2023-02-09 11:45 UTC, onkar-saeloun commented
@prasanthchaduvula can you please review this PR

2023-02-10 14:28 UTC, vipulnsward commented
@onkar-saeloun please rebase

2023-02-13 09:23 UTC, prasanthchaduvula commented
@onkar-saeloun Please resolve the conflicts

2023-02-14 05:58 UTC, onkar-saeloun commented
> @onkar-saeloun Please resolve the conflicts

@prasanthchaduvula can you please review.

2023-02-15 06:02 UTC, onkar-saeloun commented
@prasanthchaduvula can you please review the PR?

2023-02-15 06:57 UTC, prasanthchaduvula requested changes

2023-02-15 06:57 UTC, prasanthchaduvula commented on app/javascript/src/apis/teams.ts
> +import axios from "axios";
Here import axios from "apis"

2023-02-15 06:57 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/TeamsRouteConfig.tsx
> +    <Route element={<List />} path="*">
Please write this in `<Route element={<List />} path="*" />`

2023-02-15 10:44 UTC, onkar-saeloun commented on app/javascript/src/components/Team/TeamsRouteConfig.tsx
> +    <Route element={<List />} path="*">
done

2023-02-16 09:04 UTC, prasanthchaduvula approved these changes

2023-02-21 05:16 UTC, onkar-saeloun commented
@supriya3105 @shalapatil we need to send date format and formatted date from the backend. That is the only thing remaining in this PR.

2023-02-22 09:51 UTC, onkar-saeloun commented
@shalapatil, @prasanthchaduvula can you please review this PR?

2023-02-23 08:21 UTC, onkar-saeloun commented
@prasanthchaduvula can you please review this PR now?

2023-02-23 09:31 UTC, vipulnsward approved these changes
Please fix date formatting and merge on green. 
Then get it reviewed by Apoorv

2023-02-23 09:34 UTC, prasanthchaduvula requested changes

2023-02-23 09:34 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomAsyncSelect/index.tsx
> +import { customErrStyles } from "common/CustomReactSelect/CustomErrStyle";
it's better if we import 
import { customErrStyles } from "common/CustomReactSelect";

2023-02-23 09:34 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomAsyncSelect/index.tsx
> +import { customStyles } from "common/CustomReactSelect/CustomStyle";
it's better if we import 
import { customStyles } from "common/CustomReactSelect";

2023-02-23 09:34 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomAsyncSelect/index.tsx
import {import { CustomValueContainer } from "common/CustomReactSelect";

2023-02-23 09:34 UTC, prasanthchaduvula commented on app/javascript/src/components/Profile/LeaveBalance/QuarterlyCalendar.tsx
> +        key //eslint-disable-line
instead of disabling it, remove the key and use `month.id` as value key={month.id}

2023-02-23 09:34 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/Details/Layout/SideNav.tsx
> +  // {
What is the reason this code is commented out

2023-02-23 09:34 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/Details/Layout/SideNav.tsx
> +            content={`${personalDetails.first_name} ${personalDetails.last_name}`}
Destracture `personalDetails` and use them

2023-02-23 09:34 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/Details/Layout/SideNav.tsx
> +            {/* SENIOR SOFTWARE DEVELOPER */}
Remove this commented code

2023-02-23 09:34 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/Details/PersonalDetails/Edit/StaticPage.tsx
>              <CustomInputText
Both `CustomInputText` fields for first name and last name are the same. Can we use an array and call them once to follow DRY. If possible please do it for the remaining inputs in this file other wise leave it

2023-02-23 09:34 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/Details/PersonalDetails/Edit/index.tsx
> +      await schema.validate(
Instead of validating it inside submit please do it formik itself with validate.

2023-02-23 10:08 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomAsyncSelect/index.tsx
@onkar-saeloun Please fix them in another PR

2023-02-23 10:09 UTC, prasanthchaduvula commented on app/javascript/src/common/CustomAsyncSelect/index.tsx
> +import { customStyles } from "common/CustomReactSelect/CustomStyle";
@onkar-saeloun Please fix these in another PR

2023-02-23 10:10 UTC, prasanthchaduvula commented on app/javascript/src/components/Team/Details/PersonalDetails/Edit/index.tsx
> +      await schema.validate(
@onkar-saeloun Please fix these in another PR

2023-02-23 10:13 UTC, prasanthchaduvula approved these changes

2023-02-23 12:30 UTC, merged